### ISSUE TITLE
Upgrading Wand through purchasing all available spells lose some spells

### ISSUE THREAD

**Issue by PikachuEXE** [elBukkit/MagicPlugin#10]
# Environment
- Spigot 1.8.8
- Magic 5.4 (latest!)
- Some spells are disabled

`config.yml`
```yaml
welcome_wand:
load_default_crafting: false
enable_combining: false
enable_binding: true
enable_keeping: false
keep_wands_on_death: true
allow_spell_dropping: true
default_wand_mode: "chest"
regenerate_while_inactive: false
worth_base: 1
worth_sp: 5
sp_enabled: true
sp_display: "none"
```

# Steps
- `/wand`
- `/mage configure sp 10000`
- Keep buying Spells
- Buy the last spell, wand upgraded

## Expected
- Upgraded wand keeps all existing spells

## Actual
- Upgraded wand claims to have all existing spells, but some spells are missing in spell selection screen

### Default wand before upgrade to student
![default_wand_before_upgrade](https://cloud.githubusercontent.com/assets/1018543/11688021/e091b79a-9ec4-11e5-9763-cf69bb04f4e7.png)

### Default wand after upgrade to student
![student_wand_by_upgrade](https://cloud.githubusercontent.com/assets/1018543/11688042/07975598-9ec5-11e5-9ca8-9e89219285f4.png)

### Student wand get by command
![student_wand_by_command](https://cloud.githubusercontent.com/assets/1018543/11688051/141dcb6c-9ec5-11e5-8b25-f0ead5813774.png)

**Comment by NathanWolf** [comment]
Thanks!

The student, apprentice, master etc wands are just examples.. I honestly don't keep them up to date as I shift spells around in the enchanting paths. And I have recently been moving stuff around a lot for rebalancing.

So I think this is is probably all good- according to the web site:

http://mine.elmakers.com/#enchanting

A Student wand should have 21 spells, I think maybe you are missing one? I tried leveling a wand myself to Student and got to 21. Can you tell which spell was missing using that list?

![Beginner Wand](http://i.imgur.com/rm1LYrO.png)

**Comment by PikachuEXE** [comment]
I have disabled `collapse` spell
But the point is even it shows that it has 20 spells (which is fine for me since I disabled some spells)
There are less than 20 spells in selection.

**Comment by NathanWolf** [comment]
If you have the latest build I've moved the "2 hotbar" upgrade to the Student level. Is that maybe where your missing spells have gone?

The wand should print a message in chat when this happens, something like:

Your $wand's hotbar has been upgraded! &r&bPress Q while your $wand is active

**Comment by PikachuEXE** [comment]
There is no such message when I upgrade. (just tested now)
Pressing Q does not have anything (maybe I got custom key bindings)

**Comment by NathanWolf** [comment]
It's the "drop item" button

**Comment by NathanWolf** [comment]
And I see now that all the wand upgrade messages/instructions are broken :(

That'll be fixed in the next dev build- sorry!

**Comment by PikachuEXE** [comment]
I have tried "drop item" button, but it does not show anything. (message or UI)

**Comment by NathanWolf** [comment]
You have pressed that button while your wand inventory is open (spells are visible?) It should cycle the spell hotbar that is visible.

If this is too confusing, try doing "/wand configure hotbar_count 1". I can walk you through taking all of the extra hotbars out of your configs if need be. 

I am 90% sure this is the problem, it's a common issue with people who don't know about the extra hotbars thinking spells have "disappeared".

**Comment by PikachuEXE** [comment]
Yes I have changed the `hotbar_count` back to 1
And now all those things appears again
Should be included in change so that admins can inform players

I can see that `hotbar_count` was added in version 3.x, but I never have problem in 5.3.2 (even with fully upgraded wand).
This is a bit strange.
Could you kindly provide a link to somewhere that explains `hotbar_count`?

**Comment by NathanWolf** [comment]
There's no real link for it- but I'm certain it works. The messaging is fixed in latest dev build to notify players about it.

But if you can't figure it out, I guess your players probably won't either. If you'd like to turn it off, add the following to  your wands.yml:

```
student_upgrade:
    hotbar_count: 1
apprentice_upgrade:
    hotbar_count: 1
master_upgrade:
    hotbar_count: 1
```

**Comment by PikachuEXE** [comment]
Thanks, will try that out!

**Comment by PikachuEXE** [comment]
It works, thanks for your comment ;)

**Comment by NathanWolf** [comment]
You're welcome!
