### ISSUE TITLE
Texturepack Missing

### ISSUE THREAD

**Issue by mikk290** [elBukkit/MagicPlugin#1005]
When i first made the server everything worked fine. now i join again and the texturepack is missing. no gui's for the spells and i cant use anything. i get this error in my chat
There are errors in your Magic configs!
Please check your logs, fix the issue and restart the server
All magic items and features will be broken in the meantime.

when i check the logs it says something with legacy material support. do i need to download the texturpack. and where can i do that. if you can help me i would be very happy. thanks

**Comment by mikk290** [comment]
nvm i found it myself it was hidden for me

**Comment by mikk290** [comment]
i went to the page for the pack but i cant put in the command because it says an internal error occured while attempting to perform this command. i need to fix this quick otherwise i would have to close the smp

**Comment by killme** [comment]
AFAIK Bukkit recently broke ABI regarding configuration. So that is
probably what broke this. You can downgrade your server jar to work
around this for now.

Without logs thoug there is no way for me to be sure. Please include
those in future reports.

**Comment by mikk290** [comment]
i just made a new smp with other plugins and that turned fine. when the plugin gets fixed i will use it again but for now this also works.
