### ISSUE TITLE
Issues with Potter Configs

### ISSUE THREAD

**Issue by arialefairy** [elBukkit/MagicPlugin#1009]
first of all i had tested the war config and how to i get rid of the cars and npcs. second of all im using the harry potter config and when i use hagrid to go to hogwarts he says "sorry something went wrong" help please

**Comment by NathanWolf** [comment]
```
/mnpc select
/mnpc remove
```

In the future please try `/mhelp` first, it probably could've answered your first question.

"Something went wrong" is usually a hard error and there should be a stack trace in your logs when you do it, can you please check?
