### ISSUE TITLE
Default config disparition ; Spells icons bug

### ISSUE THREAD

**Issue by Elsopeen** [elBukkit/MagicPlugin#101]
Hello,
I have an issue with the spells icons in wand inventories, they are displayed as diamond axe with custom names and lores, so I thought it was something new in the config files, but I couldn't find the default ones. In the plugin repertory, there are all the modifiable config files (in those we create spells or wands or even items) but in the different folders (as wands, default, config) there is nothing. Could you please tell me where are the default config file gone ? And if the diamond axe bug is a functionality or a bug also ?
Best regards,
Elsopeen

Little update : I found how to restore default confgis thanks to the changelogs but the config.default.yml file still missing.

**Comment by NathanWolf** [comment]
You need to use the resource pack now, or change your configs. There is info in the ResourcePack section of the wiki here to help you out.
