### ISSUE TITLE
Not Booting Up

### ISSUE THREAD

**Issue by Culgor** [elBukkit/MagicPlugin#1011]
Hello, Just recently i hopped on my server and realized that magic isnt even booting up now. there are no errors in the logs and i dont want to reinstall because that wiped everyones progress last time.

**Comment by NathanWolf** [comment]
Guessing you updated Spigot but not the plugin. There was a breaking change recently in the 1.18.1 Spigot branch,  you need to update Magic to latest.

**Comment by Culgor** [comment]
No I did, i was the one who submitted that ticket. Now Its just not loading up but im not getting any error messages.

**Comment by NathanWolf** [comment]
Can you pastebin your full logs? If there's literally nothing from the plugin then I really don't know what could be going wrong other than you accidentally deleted the jar. Even a corrupt jar should have some kind of error from Spigot when trying to load it.

**Comment by Culgor** [comment]
yeah im just wondering if its something in the configs, but even if it was, i would always get an error message.
