### ISSUE TITLE
Is there any way to configure the learning of some spells through purchase so that it requires a specific level on a wand?

### ISSUE THREAD

**Issue by Lesanse** [elBukkit/MagicPlugin#1013]
Title. I'm clarifying because I re-read the title and it's not as clear as I'd like it to be.

I want players on my server to be able to learn, let's say, 40 spells through levels (like the plugin already does, just a different and custom path for a different progression).

What I want as well is for players to be able to buy certain spells at shops, which the plugin also allows. BUT I don't want them to be able to buy certain spells until X wand level. So, for instance, if I want them to be able to purchase "SuperHeal", I don't want them learning it via progression (enchanting table) but purchasing it in a certain place and ONLY if they are above a certain wand level.

Is there a way to do that? To restrict spell purchases until a specific wand level has been reached?

Thanks in advance! :)

**Comment by NathanWolf** [comment]
Yes, you can set up a custom shop (like the extraspells shop) but put `path: student` on the spells you want to be limited. Let me know if you need more help with that!

**Comment by Lesanse** [comment]
In my server I've only used the plugin "Essential" for setting up signs that act as shops (in which players on my server can buy or sell things). For the wands I didn't know how to do it so I ran a "CommandSign" sign in order for the players to acquire a wand with an specific path.

I do know there is shop options included in your Magic plugin but I've definitely no idea on how they materialize in game nor how to use them... So yeah, any help would me much more than welcomed! :)

**Comment by NathanWolf** [comment]
What you want to do is going to be a little complicated, all told.

Magic doesn't use sign shops, it uses NPCs- I would suggest you start by following the instructions here to set up a simple spell shop NPC:

https://github.com/elBukkit/MagicPlugin/wiki/Shops

Then maybe try changing its shop to `extraspells`

If you get that far, you can `/meditor spell extraspells` to see how that shop works, and then hopefully duplicate it to add the spells you want.

You'll need to add `path: student` to the spell shop config, under the `parameters` section.

If you are taking spells from a progression path and you don't want them to be available in the normal spell shop (enchant table), you'll need to `/meditor path student` and remove those spells from the list.

That should be all the pieces, let me know how far you get. :)
