### ISSUE TITLE
Survival Enchanting Table rightclicking doesnt work

### ISSUE THREAD

**Issue by KlixStyle** [elBukkit/MagicPlugin#1018]
Rightclicking switches spells instead of opening the enchanting table and the upgrade menu for the wand

**Comment by NathanWolf** [comment]
Can you please paste what `/mexample list` says?

**Comment by NathanWolf** [comment]
I was hoping to see the command output specifically.

if survival is not the main example, the enchantment table does not work. The star wars example doesn't use the enchant table, so if that's your main then you need NPCs to learn spells.

Try `/mexample set survival stars`

**Comment by KlixStyle** [comment]
I already tried that even removing stars yet it still does not work.

**Comment by NathanWolf** [comment]
Try
```
/mconfig config enchant_click progressmenu
/mconfig config enchant_block enchantment_table
```

**Comment by h266579110** [comment]
I have this issue too, can't place enchant table.
![image](https://user-images.githubusercontent.com/14806222/157657250-98b7b9e8-1f52-494c-acbb-f3275e16806c.png)

**Comment by NathanWolf** [comment]
I do not recommend using the rpg example yet.

**Comment by h266579110** [comment]
> I do not recommend using the rpg example yet.

Removed and do a fresh reinstall with only survival example, still can't place.

**Comment by NathanWolf** [comment]
Can't place what? Is this related to the ticket you're commenting on? If not please open a new one.
