### ISSUE TITLE
A lot of error messages

### ISSUE THREAD

**Issue by TheRealSedulo** [elBukkit/MagicPlugin#1020]
I'm getting up to 12.000 error messages everytime the notification comes up. In my server console appears this message:  [12:01:43 WARN]: [Magic]  Error evaluating transform in Mage class jedi.cost_reduction: 'spells 0.5': Unknown function or variable 'spells' at pos 0 in expression 'spells 0.5'

It appeared after I tried to change the costs for spells, but can't find the right file to change it back. 
And I want to turn the magic.notify off, but can't find that either.

**Comment by TheRealSedulo** [comment]
i looked into the files, but am not sure, if that, what I'm looking for is in there. I attached the files to this
[files.zip](https://github.com/elBukkit/MagicPlugin/files/8072693/files.zip)
.

**Comment by NathanWolf** [comment]
Delete _customizations.yml or use `/mconfig reset class jedi`

**Comment by NathanWolf** [comment]
That's all I got, sorry. The files you sent would be causing the error you pasted. If deleting the files doesn't help, then your server is possessed.

**Comment by TheRealSedulo** [comment]
I don't know if that is important, but the error occurs only when I'm online. As soon as I disconnect, the error is not shown in the server console.

**Comment by TheRealSedulo** [comment]
I tested something. The error only appears when I#m online. Other players are not affected

**Comment by NathanWolf** [comment]
Anyone with the jedi class would cause the error. Deleting the files will fix it.

If you need to, just delete the entire Magic folder.

**Comment by TheRealSedulo** [comment]
is there a way to keep my stats, when I delete the whole folder?

**Comment by NathanWolf** [comment]
Yes, by just deleting the classes folder

**Comment by TheRealSedulo** [comment]
i deleted the classes folder. Didn't change

**Comment by NathanWolf** [comment]
Save `plugins/Magic/data`, then. Really I have no idea- you sent me the file that had the error in it.

If you need further help with this, please come to Discord.

**Comment by NathanWolf** [comment]
One more possibility I thought of, if you somehow configured that on yourself rather than configs - did you ever use something like `/mage configure ...` ?

If so you will need to undo whatever you configured, or else reset yourself.

**Comment by TheRealSedulo** [comment]
I deleted the whole Magics folder. After putting the data folder back, the error came back. (It didn't appear befor I put the data folder back)

**Comment by NathanWolf** [comment]
You have modified your own player data somehow. Try `/mage reset TheRealSedulo jedi` to just reset your jedi class. (use your IGN of course)

If that doesn't work and you don't remember what command you used to cause this, it's going to be hard to help and at this point you should just `/mage reset` yourself and give back whatever you lose.

**Comment by TheRealSedulo** [comment]
ok thank you

**Comment by TheRealSedulo** [comment]
well that worked.
