### ISSUE TITLE
Actionbar GUI must have rp

### ISSUE THREAD

**Issue by Desmordss** [elBukkit/MagicPlugin#1022]
I use an alternative plugin for the resource pack, but I can't use the actionbar spell gui to view the selected abilities. How can i use another plugin and enable this feature?
![image](https://user-images.githubusercontent.com/78231435/155230733-7bf13809-f75b-4d31-b836-7d99bcfc3c99.png)

**Comment by NathanWolf** [comment]
Use `/mhelp resourcepack` it will give you the command you need to use.
