### ISSUE TITLE
Materia System not Working

### ISSUE THREAD

**Issue by Yyyoooadrian** [elBukkit/MagicPlugin#1023]
Before 1.18, the brushes all showed a materia cost for different blocks/items, but now there's nothing, it says that I need to have the block on me to use the spell. Now I'm stuck with excess materia that isn't being used at all :(

**Comment by NathanWolf** [comment]
Sorry, I completely missed this issue- is it still a problem? As far as I know, the materia system is working.

**Comment by NathanWolf** [comment]
This seems like it got fixed, please let me know if you're still having issues.
