### ISSUE TITLE
MythicMobs API changes seem to break Magic?

### ISSUE THREAD

**Issue by mercurialmusic** [elBukkit/MagicPlugin#1026]
Hey Nathan! Not sure if this is a you or them thing, but it looks like the MythicMobs peeps have been redoing their API again as of MM build 4052 and Magic won't enable when it is installed, with the following error: https://gist.github.com/mercurialmusic/c43bb1ddfbc1e4edbc39175978d493a1

This happened to several plugins, which is annoying, and of course they decide to make these changes on the first builds that support 1.18.2, so all the more annoying. Updated API examples here if it's useful: https://github.com/xikage/MythicMobs-API-Examples

Thanks!

**Comment by NathanWolf** [comment]
Temptation to drop MythicMobs support increasing.

**Comment by mercurialmusic** [comment]
Yeah, I don't blame you tbh. That plugin is a hot mess at times. I imagine we'd still be able to use the castp in the command skill, which is all we've ever done with them at least.

**Comment by masonalexone** [comment]
Will it be dropped soon? I cant update my server because mythicmobs and magic don't have compatible 1.18.2 versions.

**Comment by mercurialmusic** [comment]
> Will it be dropped soon? I cant update my server because mythicmobs and magic don't have compatible 1.18.2 versions.

For now you can at least add the following to your config.yml to disable the hook, but it seems like this might have some unintended consequences with magic mobs being able to spawn through the worlds configs. I haven't figured that one out yet/not even sure if it's related.

```
# MythicMobs integration, allows using mythicmobs in magic commands and configs
mythicmobs:
  enabled: false
```

**Comment by NathanWolf** [comment]
Thank you, mercuriualmusic! That would be my recommendation, too. 

I still haven't 100% decided to ditch support versus upgrading, I was kind of just raging out about it.

But in the meantime, turning off the integration should fix any issues with Magic, at the cost of Magic not being able to apply modifiers to mythic mobs, a feature which I think very little people are using, and is the only thing really lost if the integration goes away.

I don't *expect* turning this off would cause any issues with magic mob spawning or anything else, so do please let me know if you find any evidence of that.

**Comment by mercurialmusic** [comment]
I haven't seen any issues with the build, everything starts up as it should at least. I know it was a tangential mention and might need a separate issue, but the magic mobs still are not replacing vanilla mob spawns as they should in our other side. I'm able to spawn magic mobs manually, but nothing is happening automatically anymore. Were there some changes I needed to make in the worlds configs that I missed/should have made?

Thanks!

**Comment by NathanWolf** [comment]
@TheDarthFather what version of MythicMobs are you using? I just downloaded the latest free version and I'm not getting any errors.  I don't have access to the MM dev builds.

**Comment by TheDarthFather** [comment]
> @TheDarthFather what version of MythicMobs are you using? I just downloaded the latest free version and I'm not getting any errors. I don't have access to the MM dev builds.

I used the last dev build ... 

I did not update yet .. been a while since I had time to look on the server :) ... it seems they change disquises as well :(
I will check again later in the week!

**Comment by mercurialmusic** [comment]
I think it's safe to close this. Haven't had any issues with the integrations at least. 

I believe the mob spawning issue I mentioned is separate but still unable to pinpoint. I was able to come up with workarounds to that by a combination of redoing my worlds configs (was still using the legacy ```worlds:``` stuffs) and using MythicMobs to handle most of the spawning/replacing with Magic mobs.

**Comment by TheDarthFather** [comment]
Indeed!
