### ISSUE TITLE
Cannot use Action Bar or Boss Bar GUI

### ISSUE THREAD

**Issue by Kuuchuu** [elBukkit/MagicPlugin#1028]
Hello! My server loves the plugin, thanks for your work on it.
We are unable to apply the action bar gui or the boss bar gui. We get the error message about needing the resource pack. The Magic resource pack is merged into our ItemsAdder resource pack which is applied at login, so everyone is using the resource pack. In the Magic config.yml I have this set:
```
default_resource_pack: ""
```
That got Magic to not worry about the RP when players join, but it seems to have left those options disabled. Should my config.yml be different? Thanks in advance!

**Comment by NathanWolf** [comment]
You can set `assume_resource_pack_downloaded: true` in config.yml if you know players will have the RP.

The GUI will look really weird and broken however if players don't use the pack.

Glad you are enjoying the plugin!

**Comment by Kuuchuu** [comment]
Thank you! I appreciate it!

**Comment by Kuuchuu** [comment]
@NathanWolf Is there a way to automatically turn on the Boss Bar GUI for everyone in the server in the config.yml?

**Comment by NathanWolf** [comment]
Try using `/mhelp` for these sorts of questions- for instance, `/mhelp boss bar` should get you the answer to your question. Let me know if it does not :)

**Comment by Kuuchuu** [comment]
Sorry about that! Thank you again for the plugin and for your help. I appreciate it!
