### ISSUE TITLE
/mage attribute health_max 23 (and other attribute) didn't work [Magic-10.7-SNAPSHOT.jar]

### ISSUE THREAD

**Issue by vajuvung** [elBukkit/MagicPlugin#1029]
change attribute with **/mage attribute health_max 23** didn't work
![2022-03-14_21 40 08](https://user-images.githubusercontent.com/40630698/158696230-250fb6ba-5f18-4d9a-aede-734bfc35272b.png)

**Comment by NathanWolf** [comment]
Builtin attributes are not writeable. They are just there to advertise values like health, mana, etc to spells.

I would not recommend changing your max health directly anyway, you should use attribute modifiers for that.

**Comment by vajuvung** [comment]
oh... then sorry for bad report :(

**Comment by NathanWolf** [comment]
That's ok!

It *might* be a nice feature for some sets of attributes ... but for max health I do think it's a bad idea to modify the vanilla attribute directly, versus putting a modifier on it.
