### ISSUE TITLE
Keep this version or upgrade?

### ISSUE THREAD

**Issue by darkatflash** [elBukkit/MagicPlugin#103]
Hi Nathan!
Flash here!
I have a quick question... the version of  your plugin in not the newest one but it is the one you suggested to me... I am receiving a prompt to upgrade thru serverminer. Should i ignore it or upgrade? I do not want to mess things up!
We are running 1.8 atm.
thanks!
Miss seeing you around! 

Kathy (darkatflash)  :)

**Comment by NathanWolf** [comment]
I am honestly not sure, might be safest to ignore it. I did make a new release on spigotmc, but not sure where your provider gets their versions from!

**Comment by NathanWolf** [comment]
Oh wait 1.8 - definitely ignore updates then!
