### ISSUE TITLE
How to target entities in a ring?

### ISSUE THREAD

**Issue by afoxxvi** [elBukkit/MagicPlugin#1035]
Hello.
I wonder is it possible to target all entities in a ring by using AreaOfEffectAction, in other words, entities between the specified min and max radius will be targeted, just like targeter @PlayersInRing{min=#;max=#} in MythicMobs.
Thank you!

**Comment by NathanWolf** [comment]
No, but it should be a pretty easy add.

**Comment by NathanWolf** [comment]
Available as `min-radius` in the next dev build.

**Comment by afoxxvi** [comment]
I see it, thanks very much!
