### ISSUE TITLE
Please help me disable SP Earn cooldown on ALL spells

### ISSUE THREAD

**Issue by bigguyjones** [elBukkit/MagicPlugin#1039]
I would like Players to earn SP each time they use a spell, I don't want the long cooldown. using the arena you earn about 25 SP right at the start by using each spell once, then no more SP gain for the rest of it since the cooldowns are too long.

I do not know the correct format or the right way to edit this in, i tired adding this to my modifiers.yml with:

cooldown_reduction:
(space here) cooldown_reduction: 1

but this didn't work, what would be the best way for me to make this change?

**Comment by NathanWolf** [comment]
`mconfig spell default earns_cooldown 0` will turn off the cooldown.

**Comment by bigguyjones** [comment]
Wow you are a legend! Thanks for the fast reply! That worked great! Love the plugin by the way!
