### ISSUE TITLE
How to make a wand :( there nothing in INVENTRY that is added new 

### ISSUE THREAD

**Issue by xXxKileRv69xXx** [elBukkit/MagicPlugin#1045]
How to make a wand pls tell

**Comment by TheKommandr** [comment]
You have to craft it with 2 emeralds, 1 diamond and a stick

**Comment by NathanWolf** [comment]
Thank you, TheKommadr that is correct

You should learn these recipes automatically when holding any of the ingredients.

If you're opped you can also just do `/mgive wand`
