### ISSUE TITLE
Citizens issue

### ISSUE THREAD

**Issue by Blamo27** [elBukkit/MagicPlugin#105]
Hello !

It seems that when we enable the "welcome wand" option so that new players receive their first wand, many NPCs with the trait Sentry also receive a wand, as if they were new players as well. Beside the fact that it makes the save.yml of citizen far heavier (because of the additionnal data of the wands), it's also an issue with the sentries who don't have any weapon equipped : instead of having their fist, they yield a wand, and when they fight they fight with the wand (but not by using spells, they just punch people with the wand).

Can you help us ?

Spigot Version : 1.8.8
Magic Version : 5.5.6-SNAPSHOT (CombatTagPlus fix)

Our CombatTagPlus is set to kill instantly players.

Thanks. :)

**Comment by NathanWolf** [comment]
That's extremely weird. Does a Sentry trigger a player join event??

**Comment by Blamo27** [comment]
I think yes, because I tried to give wands with a command when a new player join our server. (FirstCommandJoin)

And there is another bug :
> http://i.imgur.com/nRtVKgA.png

We are in 1.8, but we are allowing 1.9.2 - 1.9.4 players. (ViaVersion)

**Comment by Blamo27** [comment]
?

**Comment by NathanWolf** [comment]
No idea on the protocol-hack stuff, I cant' really support that.

I can probably put a quick check in for NPC's on the join event though.

**Comment by NathanWolf** [comment]
I added a check for NPCs in #1667 

http://jenkins.elmakers.com/job/MagicPlugin/1667/

They will no longer be considered players at all by the internal code. I'm hoping there aren't any weird side-effects.

Better answer for the invis cloak- in the 1.8 version of Magic it uses an item, which in 1.8 MC is invisible. In 1.9 MC the player can see it.

There's nothing I can do about that, in 1.9 Magic it's an actual item that is made invisible via the 1.9-specific RP.

**Comment by Blamo27** [comment]
Thanks :)

**Comment by Blamo27** [comment]
@NathanWolf But the version is 6.2 and I'm still on (1.8.8) :(

**Comment by NathanWolf** [comment]
Ah, of course :p

I'll back port it when I get the chance.

**Comment by NathanWolf** [comment]
Ok, fixed in the 1.8 build:

http://jenkins.elmakers.com/job/MagicPlugin-1.8/41/com.elmakers.mine.bukkit.plugins$Magic/
