### ISSUE TITLE
Website issue

### ISSUE THREAD

**Issue by Diamondhero777** [elBukkit/MagicPlugin#1055]
I believe that the editor website is having an issue right now.  As I tried to continue making spells and such but it had an error.  The error was something related to security of the website, and when I went to the website my browser said it wasn't secure.  It was secure before and working, so I believe the website is having a security issue or something.  Please fix.

**Comment by NathanWolf** [comment]
Cert updated.

**Comment by Diamondhero777** [comment]
Thank you NathanWolf you are a freaking chad legend.
