### ISSUE TITLE
Interesting Error with EcoEnchants

### ISSUE THREAD

**Issue by masonalexone** [elBukkit/MagicPlugin#1057]
When loading up Ecoenchants and magic at the same time, it can be seen in the console that Magic registers all of Ecoenchant's enchantments as custom attributes. When playing the game and checking /mage attribute, all ecoenchants are listed and a value 0 will be given when the command is run. However, If I hold an item with an ecoenchant enchantment, and run the mage attribute command with the corresponding ecoenchant as the attribute it is checking, the level of the enchantment will be output.

This has caused no obvious issues yet but I am checking to make sure it could not cause future incompatiblity

**Comment by NathanWolf** [comment]
I don't understand the question.

Enchantments are available as attributes so they can be used in spell or other configs (e.g. spell damage increases with sharpness).

Obviously the enchantments only show values when you're holding/wearing an item with that enchantment.

Sounds like this is all working as intended- am I misunderstanding?

**Comment by masonalexone** [comment]
It seems to be working as intended then, I just wanted to make sure having ~200 enchants from a plugin like EcoEnchants wont cause any issues with Lag/Ram/CPU when used with Magic aswell

**Comment by NathanWolf** [comment]
No, they are only looked up if you use them. Shouldn't be a problem, but let me know if you see anything odd in timings.
