### ISSUE TITLE
MojoFailureException

### ISSUE THREAD

**Issue by Mhilkos** [elBukkit/MagicPlugin#1073]
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project MagicAPI: Compilation failure.
This error happens when i try to compile the plugin.
edit: those two more errors were a mistake but this error is still weird.

**Comment by NathanWolf** [comment]
As far as I know those are all very common maven plugins available in Central. I don't know why you'd be having this issue.

**Comment by Mhilkos** [comment]
And there is no repo for com.garbagemule Mobarena. and the version provided there is old. I just wanted to hook MobArena into Magic but the problem is that the version is too old so it doesnt hook up and i cant compile your plugin (with the newer version of mobarena depency changed in the pom.xml) by myself because of the errors.

**Comment by Mhilkos** [comment]
The api is not compilable and the mobarena version is too old on the pom.xml of the Magic folder.
