### ISSUE TITLE
magic plugin not working on 1.19 update

### ISSUE THREAD

**Issue by GriffTime** [elBukkit/MagicPlugin#1079]
As the title states, the plugin is not working on the 1.19 update. Unfortunately I did not back up my world before updating to 1.19 and now I can’t use the plugin on the world I had hoped to continue using it on.

**Comment by NathanWolf** [comment]
What version of Magic are you on? The latest release works on 1.19, Magic 10.8

https://dev.bukkit.org/projects/magic

**Comment by GriffTime** [comment]
Oops I noticed that after
