### ISSUE TITLE
Wand GUI Hot Bar Issue

### ISSUE THREAD

**Issue by 0MrCrazy0** [elBukkit/MagicPlugin#1082]
hello did the wand hot bar GUI ever have a fix? cos iv tested it & still see this small white box issue.
![2022-06-10_21 27 18](https://user-images.githubusercontent.com/102135865/177456816-4a72791e-4ecc-4fdb-a6ea-9d9de7daf5a5.png)
.

**Comment by NathanWolf** [comment]
Yah you need to get rid of the space in the `message` property.

This is why it's always good to use the builtin configs when you can, and maybe just turn off what you don't need.

Perhaps I should move some of this base config stuff off into a separate example that survival inherits from.

**Comment by 0MrCrazy0** [comment]
thanks again, i got it working YAY! can close ticket
