### ISSUE TITLE
wizard armor textures failing

### ISSUE THREAD

**Issue by ohnight1** [elBukkit/MagicPlugin#1084]
i have the magic plugin installed, we have crafted the wizard robe and other armor but it shows as chainmail not the robe, we have to texturepack on, it also bugs out for the custom monsters, is there a known fix, also other textures still work like the wand and other things

**Comment by NathanWolf** [comment]
You need to enable the robes example, it uses a different resource pack. `/mexample add robes`

**Comment by ohnight1** [comment]
that worked thanks.
