### ISSUE TITLE
How to reset the plugin

### ISSUE THREAD

**Issue by ohnight1** [elBukkit/MagicPlugin#1086]
if I was to reinstall magic plugin, or update it, would I lose my progress and the rest of the server, i have a bug with my villagers where someone them kick you when you open there menu and im trying to find out which plugin is causing it

**Comment by ohnight1** [comment]
![image](https://user-images.githubusercontent.com/109130670/178905986-82318312-80e0-4272-b624-5f3796921c50.png)
this is what shows up, not sure if you know how to fix it, or if its even related to magic plugin

**Comment by ohnight1** [comment]
i figured out the problem, its with bungee cord but i still want to know if it loses progress if i delete magic plugin

**Comment by NathanWolf** [comment]
Reinstalling or updating is fine, but won’t really help or change much. You can delete `plugins/Magic` to reset all configs, but if you want to keep progress you should save the contents of `plugins/Magic/data`.

That error sounds like a bad item in an inventory GUI. I *think* someone on the Discord was having a similar issue but I’m not sure of the cause.

**Comment by ohnight1** [comment]
the cause of the error was bungee, but thanks for the info
