### ISSUE TITLE
dragons

### ISSUE THREAD

**Issue by ohnight1** [elBukkit/MagicPlugin#1088]
on the website it says theres dragons, the command doesn't work though

**Comment by NathanWolf** [comment]
What command are you trying to use and what are you expecting to happen?

**Comment by ohnight1** [comment]
/mmob spawn cyandragon not sure if i need an update or what

**Comment by NathanWolf** [comment]
Do you have LibsDisguises installed? It is required for dragons.

**Comment by ohnight1** [comment]
oh I forgot to do that sorry

**Comment by ohnight1** [comment]
does it automaticly add the dragons or do i need to add anything, and can it be any version

**Comment by NathanWolf** [comment]
You will need to add the spawnmobs example `/mexample add spawnmobs` if you want them (and other magic mobs) to spawn naturally. But once you have LibsDisguises you should be able to spawn them with the `mmob` command.
