### ISSUE TITLE
Compatibility between magic spells and model engine mythic mobs

### ISSUE THREAD

**Issue by ICEconchy** [elBukkit/MagicPlugin#1092]
When utalising magic missile (And probably others) Magic doesn't like it and throws errors.

https://mcpaste.io/c4b01644c285e0e1

**Comment by NathanWolf** [comment]
I don’t think LivingEntity.getEquipment is ever supposed to return null. It certainly doesn’t for normal mobs.

so this sounds like something weird MythicMobs is doing.

**Comment by ICEconchy** [comment]
![image](https://user-images.githubusercontent.com/20145992/182884989-c5ddac6c-87af-4901-9493-ab1f26fc40b0.png)
Apparently it is nullable
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html#getEquipment()

**Comment by NathanWolf** [comment]
Will be fixed in the next dev build.
