### ISSUE TITLE
Drop glowstone in nether when mine glowstone

### ISSUE THREAD

**Issue by andllillmon** [elBukkit/MagicPlugin#1096]
Glowstone dust don't drop. Drop glowstone in nether when I mine glowstone.

**Comment by NathanWolf** [comment]
The mine spell only works on ores, it should not affect glowstone at all.

Are you talking about just normal mining with a pick? If so that is not something this plugin would affect.

**Comment by andllillmon** [comment]
That plugin have affect on glowstone normal mining, he is change drop glowstone, you can check it. I use default configs

**Comment by NathanWolf** [comment]
It really doesn't unless you've configured it. 

Please remove the plugin if you think it's causing something like that.

**Comment by andllillmon** [comment]
Okey, i understand you. But check it when you will have time.

**Comment by NathanWolf** [comment]
![glowstone is fine](https://i.imgur.com/2IcOMDv.png)

Tried it just now on my dev server. Unless you have configured world drop rules, your problem lies elsewhere.
