### ISSUE TITLE
Editor Unavailable

### ISSUE THREAD

**Issue by NightScythe1** [elBukkit/MagicPlugin#1099]
Seems like the Editor's certificate has expired, and is no longer accessible, just a heads up!
![2022-08-07_04 20 23](https://user-images.githubusercontent.com/18646617/183273657-82f30346-6929-411f-a7ef-d848687ad695.png)
![editor](https://user-images.githubusercontent.com/18646617/183273659-219015e1-aaa3-4514-b1a4-d792bdb9e4e5.PNG)

**Comment by NathanWolf** [comment]
Oof, whoopsie. Thanks for the head’s up! I’ll get that fixed next time I’m at my computer.

**Comment by NathanWolf** [comment]
I *swore* had just renewed them recently- turns out I did, but forgot to restart Apache so the new cert didn't take effect :sob:

Should be all good now.

**Comment by NightScythe1** [comment]
awesome stuff, thank you!!
