### ISSUE TITLE
Netherside world not load 

### ISSUE THREAD

**Issue by xXxKileRv69xXx** [elBukkit/MagicPlugin#1106]
Hello I am kilerv69 from aternos server I have been having a major issue as when I add all examples and things to netherside and then restart my server so the nether side world doesn't load I mean when I creates it it works and when I restart my server it never loads and delete whole plugin and did the same thing again but still not works also 34 warning from it which I can't view as I am bedrock but I'm sure it says that the newly added biome doesn't have the replacements in netherside .pls fix the issues :(  I'm on 1.19.1

**Comment by NathanWolf** [comment]
I think you will just need to turn the netherside example off. Sorry!

**Comment by xXxKileRv69xXx** [comment]
Turned it off for always ??? 
Will it load world then also

**Comment by NathanWolf** [comment]
It is resource intensive. If your server can’t handle it, you would need to turn it off and can’t use it. 

You could try using a plugin like worldborder to pre generate, but if it won’t load in the first place there is nothing I can do.
