### ISSUE TITLE
Textures.

### ISSUE THREAD

**Issue by Azurzar** [elBukkit/MagicPlugin#1107]
I'm using the textures packs, and I have the problem that the chestmail armor is completely override by the magic skin, not adding but substituting.

**Comment by NathanWolf** [comment]
Turn off the robes example.

**Comment by Azurzar** [comment]
How??

**Comment by NathanWolf** [comment]
If you used `/mexample` to add the robes example, you use the same command to remove it: `/mexample remove robes`
