### ISSUE TITLE
Question on GUI

### ISSUE THREAD

**Issue by Geekonline** [elBukkit/MagicPlugin#1121]
I am looking to find where I can go in the config to change the Boss Bar GUI to the default
I can see it on the enchantment table as an option, is there a way to set this as the default for all players?
![BOSS GUI](https://user-images.githubusercontent.com/4981890/194881814-f36e45cc-bbd0-4c04-bd3a-8e093f28ce28.png)

**Comment by NathanWolf** [comment]
Try `/mhelp boss bar`

**Comment by Geekonline** [comment]
Thanks, I tried playing with this, but it quickly got over my head, I'll just direct the users to use an enchantment table to change the position of the Bar. 
Thanks anyway!

**Comment by NathanWolf** [comment]
The mhelp command should have given you an article on on the "Wand GUI" with the specific command you need to run to do exactly what you're asking

```
mconfig config wand_slots.gui.default_slotted gui_bossbar
```

**Comment by Geekonline** [comment]
Oh thank you, I didn't realize they were links in the chat window, Thank you again!
