### ISSUE TITLE
Forced resource pack handling conflicts with other plugins

### ISSUE THREAD

**Issue by marcelschoen** [elBukkit/MagicPlugin#1132]
The forced resource pack loading of Magic conflicts with plugins like ItemsAdder and others. There should be a switch to disable this and let me handle the resource pack completely on my own.

**Comment by NathanWolf** [comment]
`/mconfig config enable_resource_pack false`

In the future you can use the `/mhelp` command to answer basic questions about the plugin. `/mhelp disable resource pack` would have led you to the above command.
