### ISSUE TITLE
Broomstick doesn't work

### ISSUE THREAD

**Issue by Miclebrick** [elBukkit/MagicPlugin#115]
When you use a broomstick, it mounts it, but when you press spacebar, it does not move. I haven't been able to get it moving at all.

**Comment by NathanWolf** [comment]
Yes, sorry they broke in 1.10 and I don't know why yet.

**Comment by Miclebrick** [comment]
Ah, ok. Do you plan on fixing it soon?

**Comment by NathanWolf** [comment]
No time frame. I'm on hiatus right now but it's definitely at the very top of my list to fix.

**Comment by Miclebrick** [comment]
oh ok.

**Comment by Miclebrick** [comment]
Another broomstick plugin said that horses refused to work so they used armor stands I think, if that's any help. http://dev.bukkit.org/bukkit-plugins/broomsticks/

**Comment by NathanWolf** [comment]
Magic currently uses horses and armor stands but I think you are right and I need to take the horse out of the equation.

**Comment by iKezzaUK** [comment]
Any news on Broomsticks yet?

**Comment by NathanWolf** [comment]
Nooe

**Comment by NathanWolf** [comment]
*Nope. :)

Hoping soon. No guarantees, very busy IRL.

**Comment by iKezzaUK** [comment]
OK, do you know what Potterworld are doing about brooms? They are upgrading to 1.10. I thought you may have been supporting them with the upgrade

**Comment by NathanWolf** [comment]
They will be disabling them for now.

**Comment by iKezzaUK** [comment]
Ok

**Comment by NathanWolf** [comment]
Fixes in 6.1.2
