### ISSUE TITLE
General Issues Getting Plugin to Work

### ISSUE THREAD

**Issue by nagsmp** [elBukkit/MagicPlugin#1151]
it's not working with slimefun4 or i just can't do anything with it and cant craft a wand

**Comment by nagsmp** [comment]
nvm its just not working

**Comment by NathanWolf** [comment]
Have you checked your logs for startup errors?

The only known incompatibility with slimefun is that they both require a resource pack. There is a merged one you can use, but it sounds like you are having bigger problems.

**Comment by NathanWolf** [comment]
Have you tried `/mgive wand`?

**Comment by nagsmp** [comment]
nvm found some stuff but
![Screenshot 2022-12-13 11 13 09 AM](https://user-images.githubusercontent.com/120241251/207399602-ec6d1d01-f457-4d5f-b3d8-1bc5cb0b6819.png)
 idk what it means I'm on 1.19.3 and using the latest version i think

**Comment by NathanWolf** [comment]
There isn't a stable version yet that works on 1.19.3

https://jenkins.elmakers.com/job/MagicPlugin/4205/

You can try that dev build if you want. The resource pack needs updating. Wait for a release would be my recommendation.

**Comment by nagsmp** [comment]
so do i gotta go back to 1.19.2 on my server?

**Comment by NathanWolf** [comment]
You can

* Use the dev build I linked above
* Go download the 10.8.5 release from spigotmc
* Wait for the release on dev.bukkit.org (submitted, not yet approved)
* Wait for aternos to pick up 10.8.5

Once you've updated your server, you can't go back.

**Comment by nagsmp** [comment]
ok
