### ISSUE TITLE
i went into the data files and all the data was gone and it's not working anymore

### ISSUE THREAD

**Issue by nagsmp** [elBukkit/MagicPlugin#1153]
![image](https://user-images.githubusercontent.com/120241251/206864235-ea5aaaa7-845f-45b1-86ef-730555cee67b.png)
![Screenshot 2022-12-10 10 07 48 AM](https://user-images.githubusercontent.com/120241251/206864263-29f7351b-2595-474d-a1be-be9135150966.png)

**Comment by NathanWolf** [comment]
You'll need to check your startup logs, it seems like the plugin is not working.

I'm going to close this one as a duplicate, we can continue investigating in #1151

**Comment by nagsmp** [comment]
i did
