### ISSUE TITLE
Solve for making Resource Pack 1.19.3 Compatible (Example file included)

### ISSUE THREAD

**Issue by Remodactyl** [elBukkit/MagicPlugin#1154]
[atlases file.zip](https://github.com/elBukkit/MagicPlugin/files/10213732/atlases.file.zip)
In short, Minecraft updated to 1.19.3, causing incompatibility issues in a lot of Texture packs.

To solve this:
add a folder in  assets/minecraft/ named 'atlases'.
inside this folder, for whichever category of textures required, add a <>.json file.
For blocks and item textures, this will be 'blocks.json' (now located in assets/minecraft/atlases/blocks.json)
an example file of blocks.json is included in the attachments for this Github Issue.
this file includes the source references for several magic examples with textures using the hires-all resource pack.

The way this file works:
the file contains a list of entries for folders minecraft needs to scan for textures that will be used by the client. It used to do this automatically, but this is no longer the case.
Lets say we want minecraft to recognize the spell icons, we must add the blocks.json in the atlases file containing at least 1 entry.
It will look like this:
```
  {
    "sources": [
      {
        "type": "directory",
        "source": "icons",
        "prefix": "icons/"
      }
    ]
  }
```
This tells minecraft to scan directory icons for textures, and refer all urls using 'icons/...' to refer to this texture atlas.

**Comment by lionking1208** [comment]
I'm so confused. How do we get an assets file.

**Comment by NathanWolf** [comment]
There should be nothing for you to do here. The RP has been updated, you'll get it automatically as usual.

If you're having issues please open a new ticket.
