### ISSUE TITLE
1.19.3 compability

### ISSUE THREAD

**Issue by firefury1** [elBukkit/MagicPlugin#1155]
Hi! I'm trying to start server with paper 1.19.3 and Magic but getting error. Is there already support for 1.19.3?

**Comment by Remodactyl** [comment]
I posted an Issue right below this one about how to update the resource pack @NathanWolf
I tested this out for myself and all spells, icons, wands etc are working properly with it!

**Comment by NathanWolf** [comment]
I saw that, thank you! I'm hoping to get the RP updated as soon as I can, I really appreciate the help there.

**Comment by Remodactyl** [comment]
yw!

**Comment by NathanWolf** [comment]
@Remodactyl that was extremely helpful, you saved me a bunch of time figuring all that out and building the json file. I really appreciate it!

The RP's are all updated and look great to me. I've released 10.8.5 with official 1.19.3 support- not tested super well but things seem to be working OK.
