### ISSUE TITLE
Editor Unavailable (Certificate Expired)

### ISSUE THREAD

**Issue by NightScythe1** [elBukkit/MagicPlugin#1170]
Same issue as last time, [mentioned here.](https://github.com/elBukkit/MagicPlugin/issues/1099) Editor's certificate expired and cannot be accessed in-game.
<img width="841" alt="image" src="https://user-images.githubusercontent.com/18646617/215364173-6dd10c33-eccd-46f0-bcf3-2861b7fd92df.png">

**Comment by NathanWolf** [comment]
Sorry about that! Certs renewed, should be ok now.

**Comment by NightScythe1** [comment]
Thanks!
