### ISSUE TITLE
Circular dependencies issue on newest Paper prevent server startup

### ISSUE THREAD

**Issue by benklop** [elBukkit/MagicPlugin#1175]
According to an issue opened in the Paper issue tracker, an update is needed to this plugin to avoid loading issues:

> The Magic plugin has an invalid plugin.yml. They are both depending on and requiring loading before MobArena and Skript. A plugin can't load after and before a plugin at the same time. Report this to the Magic plugin.

https://github.com/PaperMC/Paper/issues/8867#issuecomment-1436134832

**Comment by NathanWolf** [comment]
This should be fixed in this dev build:

https://jenkins.elmakers.com/job/MagicPlugin/4210/

I will do some testing and make an official release when I can.

Thanks for letting me know about this issue!
