### ISSUE TITLE
spell carpet bombing will bomb self when aim far

### ISSUE THREAD

**Issue by NGGCGG2** [elBukkit/MagicPlugin#1188]

**Comment by NathanWolf** [comment]
What do you mean by "far"?

Aiming up into the sky, or at a very distant block or mob?

IIRC this spell just drops bombs all over the place, it's not meant to avoid hitting the caster.

**Comment by NGGCGG2** [comment]
https://user-images.githubusercontent.com/42895594/223507173-65c8d59f-aa89-4c71-828d-6cf7b67c232c.mp4

**Comment by NathanWolf** [comment]
Thank you for the video- that does look unintentional, I will take a look when I can.

**Comment by NGGCGG2** [comment]
> Thank you for the video- that does look unintentional, I will take a look when I can.

thank you very much!

**Comment by NGGCGG2** [comment]
> Thank you for the video- that does look unintentional, I will take a look when I can.

when

**Comment by NathanWolf** [comment]
Fixed in next dev build and 10.8.11 release.
