### ISSUE TITLE
Question regarding too many spells learned

### ISSUE THREAD

**Issue by Grinjr** [elBukkit/MagicPlugin#119]
Hey, I really love the plugin and what you have done with it, it is the best plugin I have seen in a long time just because of all the content it adds and the care put into it.
I have a question though, the wiki is a bit unclear on this, but in the demo video it looked like there was some form of spell book allowing you to store more spells than your inventory can hold. How do I get something like this? I was just testing around giving myself levels just to see what kind of spells players have access to, and I got to the point where I have so many spells learned that my inventory cannot hold all of them and I cannot use a lot of the spells I know just because of my inventory. I have tried doing a few things such as left clicking outside of my inventory to go to the next page, but that didn't work. I've looked for a spell book that I could craft but couldn't find anything, but I can't figure out how to access my other spells  that I have access to.
I guess my question is, how can I see all the spells I have access to? Is there a spell book that I can buy from a villager somewhere or craft?

**Comment by NathanWolf** [comment]
There is no spell book, the books in the video are just books that show all possible spells.

Clicking outside of the inventory is the way to change pages. If that's not working, that's most often a plugin conflict. If you are able to test it without other plugins that'd be great to know. Otherwise I think there is another way to change pages, or maybe a config option but I'm not sure offhand and am not looking at the code right now.

**Comment by Grinjr** [comment]
the plugin that might be conflicting might be... mcmmo... but I'll look through the configs and check later as to which plugin may be conflicting. Thanks

**Comment by NathanWolf** [comment]
Mcmmo usually is ok with Magic, UltraCosmetics I think has this problem and one other plugin I can't remember offhand was reported. Worse case I do have a workaround.

**Comment by Grinjr** [comment]
Yeah, mcMMO is ok for the most part other than that when you right click with the wand it says "You ready your hoe". It was UltraCosmetics, I was testing it out and that was the one causing the issues. 
Thanks for the help!

**Comment by NathanWolf** [comment]
Ah, yup! That plugin eats all "clicked on nothing" inventory events for some reason- kind of annoying!

There is an option in config.yml you can use to work around this:
```
# This will make hitting the drop button over a wand while open change pages instead of
# cycling the hotbar
drop_changes_pages: true
```

Set that to "true" and you can now hover over the wand and hit the Q button to cycle pages instead.
