### ISSUE TITLE
Numbers after dots

### ISSUE THREAD

**Issue by vajuvung** [elBukkit/MagicPlugin#1195]
is possible to uhm... idk how to call it but is possible to remove numbers after dots?
![obraz](https://user-images.githubusercontent.com/40630698/225035802-b7eeef6f-6a61-4a99-9217-d15a232ab031.png)

**Comment by NathanWolf** [comment]
You should be able to use floor() or ceil() for that. Like try
```
floor(x * 10) / 10
```

**Comment by vajuvung** [comment]
Thanks!
