### ISSUE TITLE
(Request) Difficulty attribute or variable/requirement

### ISSUE THREAD

**Issue by NightScythe1** [elBukkit/MagicPlugin#1197]
Was wondering if it would be possible to add a 'Difficulty' attribute/requirement? This could perhaps either be a numerical attribute from 0 for peaceful to 3 for hard, or a string variable/requirement for spells with CheckRequirements? Currently making some spells designed to scale with game difficulty, which this would be very handy for!

**Comment by NathanWolf** [comment]
I like this idea, should be an easy add for the next release.

**Comment by NightScythe1** [comment]
Thanks, much appreciated!!

**Comment by NathanWolf** [comment]
This was added in 10.8.7
