### ISSUE TITLE
Suggestion - Essentials warps integration

### ISSUE THREAD

**Issue by Elsopeen** [elBukkit/MagicPlugin#12]
Hello,
I write this issue to suggest to the creator and the team an integration of Essentials warps.
I tried to have Essentials and commandBook at the same time on my server but Essentials always has the priority on the commands, so the command "/setwarp <warp-name>" cannot be run with commandBook, even with the well configured permissions (Essentials' one prohibited and commandBook's one allowed). So, with the trouble of the incompatibility between two plugins doing the same stuff, I cannot set the Magic "Recall" marks to help my sorcerers on my server. So, I ask your help by creating an Essentials warps integration to your great plugin for helping those who use Essentials instead of commandBook.
I cannot obviously simply change Essentials to commandBook because all portals and permissions are set, and the server's running all day long, so this little add to Magic would be a very useful one.
Thank you for reading this little message, and early thanks for considering my ask,
best regards
Elsopeen

**Comment by NathanWolf** [comment]
Oh, I actually have essentials warp integration - but I think the commandbook warps are taking precedent. I can add an option to disable the commandbook warps, that should fix you up.

I have to admit, though, I've never heard of anyone using both commandbook and essentials! Can I ask why?

**Comment by Elsopeen** [comment]
I used both especially to set the Recall marks but it didn't worked at all unfortunately. Thanks for answering so quickly. I've just read that Essentials warps were effectively supported, but I've created a warp with Essentials for testing if Recall would be able to display it but it didn't, so I believe I did something wrong.
Thanks again for your answer,
best regards,
Elsopeen

**Comment by NathanWolf** [comment]
Oh! Well it ought to just work if you remove CommandBook then :)

I'm using this on a few live servers with Essentials warps, it works great. You do need to customize Recall for warps to show up though!

See my example configs here: https://github.com/elBukkit/MagicPlugin/blob/master/src/examples/elworld/spells.yml#L71

**Comment by Elsopeen** [comment]
Thanks a lot, now Sorcerers will can teleport themself to the school without any tech portal.
