### ISSUE TITLE
Many spells produce fire particles when they shouldn't

### ISSUE THREAD

**Issue by Aresiel** [elBukkit/MagicPlugin#1207]
Many spells, such as boon and kill, most notably kill produce fire particles instead of the particles they should, as if the fire particle was default somehow.

Picture to demonstrate:
![image](https://user-images.githubusercontent.com/25839246/229356946-85164b15-1227-49ba-b468-d3769a9abc8f.png)

This is on Paper 1.19.4 with Magic 10.8.7.

**Comment by Aresiel** [comment]
Upon running fxdemo, it looks to me like the default particle became fire and that the proper particle isn't specified in the spells.

**Comment by NathanWolf** [comment]
The default particles should be fixed in the next dev build- sorry about that! Crazy how that went unnoticed (or at least unreported here) for a year or so.
