### ISSUE TITLE
/meditor doesn't work

### ISSUE THREAD

**Issue by 44wrw44** [elBukkit/MagicPlugin#1208]
![image](https://user-images.githubusercontent.com/73754757/230763306-6a94c123-a8c5-431c-8fb7-b2397c07eaba.png)

**Comment by NathanWolf** [comment]
Seems ok now, are you having consistent connection issues?

Try going there manually in your browser:

https://editor.elmakers.com

If that works but it still doesn't work on your server, there may be some firewall or other network issue on your side.

**Comment by 44wrw44** [comment]
Ok, Thanks.
