### ISSUE TITLE
Request new override option to disable sp gain on wands

### ISSUE THREAD

**Issue by Vritra22189** [elBukkit/MagicPlugin#122]
sometimes in SMP, we may want to experiment with spells using admin wands.
but during that time, spells cast may gain additional sp, 
which some server may want to revert that, but this have to be done manually.

if an override option exist to prevent sp gain using that wand, it will be more convenient.
this will also allow servers to have non-sp-impacting events simply using admin-provided overridden-wands.

**Comment by NathanWolf** [comment]
This is a great idea, by the way- sorry I haven't gotten to it. I'd like to put it in when I can.

**Comment by NathanWolf** [comment]
You can now add this to a wand to disable SP earning for it (in latest dev build, will be in 6.9)
```
sp_multiplier: 0
```
