### ISSUE TITLE
Wand to use for Conduit for Flash only :)

### ISSUE THREAD

**Issue by darkatflash** [elBukkit/MagicPlugin#123]
Hi Nathan!
I hope your work trip is going well!! We sure do miss you!!

Anyway, I have a very simple and quick question regarding wands on my survival server... spock and I are still using only your magic plugin .. can you please give me the command again for the "nathan" wand so that I may level up to "conduit"?

Thank you !!

Also... when you are back in town, let's talk! I have really good news!!

:)

Sincerely,

DarkatFlash aka Kathy (Kleinerman)

**Comment by NathanWolf** [comment]
Hi Flash! So you need some special permissions - Magic.wand.use.protected and Magic.wand.use.powered ... Those will let you use the Wolf staff and any other OP wand.

I hope that helps! I'd love to come on your server sometime when I'm less busy.
