### ISSUE TITLE
I wanted to disable the cooldown on certain spells like for example the 'fling' spell, how can I do that ?

### ISSUE THREAD

**Issue by MasterDiamond2k** [elBukkit/MagicPlugin#1234]

**Comment by NathanWolf** [comment]
`/mconfig spell fling parameters.cooldown 0`

This gets complicated with spells that level up though- fling's cooldown decreases as you level it. 
So if you want to turn all that off and just make it OP without having to level it, you probably want to turn off the cooldown for all of the levels as well.

```
/mconfig spell fling|2 parameters.cooldown 0
/mconfig spell fling|3 parameters.cooldown 0
/mconfig spell fling|4 parameters.cooldown 0
```
