### ISSUE TITLE
How to create Ollivander

### ISSUE THREAD

**Issue by WasdCat** [elBukkit/MagicPlugin#125]
Hello, I activate the example of harry potter, The server give me the ticket but I don't find how to create the npc of Ollivander to change the ticket for a wand.

![pic](http://image.prntscr.com/image/915a440ca7604dd3b9a7bb986f8609ac.png)

Thanks and sorry for my bad english.

**Comment by NathanWolf** [comment]
With a Citizens NPC selected, perform the following commands:

'''
/trait magic
/mtrait ollivander
'''

**Comment by WasdCat** [comment]
Thanks, you're nice
