### ISSUE TITLE
The Chop spell is unable to work with the Cherry trees.

### ISSUE THREAD

**Issue by Wind0220** [elBukkit/MagicPlugin#1251]
Hello, the Chop spell cannot cut down the new cherry wood. Could you please add the new  cherry wood to the cutting down list?
![QQ截图20230729015614](https://github.com/elBukkit/MagicPlugin/assets/96609471/5e44da4f-59ec-4d94-9af7-235c859ca698)

**Comment by NathanWolf** [comment]
This will be fixed in the next dev build.
