### ISSUE TITLE
Resourcepack colors not working in 1.20.1

### ISSUE THREAD

**Issue by Kalleball** [elBukkit/MagicPlugin#1255]
When I load the resourcepack all colors are black and purple. Any ideas on what to do? I downloaded the pack from a youtube description.

**Comment by NathanWolf** [comment]
There are different versions of the resource pack for each server version. It's best to let the plugin provide the right link.

If you don't want to use the automatic RP feature, use the `/getrp url` command to get the right URL and download it from there.

**Comment by Kalleball** [comment]
Here I am again. Thanks for your quick answer! How do I use the automatic RP function though?

**Comment by Kalleball** [comment]
Its a minehut server and I tried using the /getrp url command, but it tells me the command is disabled because another texture pack is configured in server.properties. I think thats some kind of automatic minehut thing. I'm gonna try the thing I saw in the link you sent.

**Comment by NathanWolf** [comment]
You should be able to remove the RP setting in your Minehut console.

**Comment by Kalleball** [comment]
Okay, thanks! I'll try. Sorry for my lack of experience with this stuff.

**Comment by NathanWolf** [comment]
The current RP link (for 1.19 and up) is just http://rp.elmakers.com/Magic-RP-1.19.zip if you want to try that.

**Comment by NathanWolf** [comment]
No worries :)

**Comment by Kalleball** [comment]
Well I did as you told me to with the RP file and the server broke. It somehow fails to load the entire server.properties file upon restart, 30 lines or so are left out which makes it impossible to join.

**Comment by Kalleball** [comment]
![image](https://github.com/elBukkit/MagicPlugin/assets/141743233/db4318ee-2514-4f7f-b321-d2c9f7dc8796)
In total there should be amost 60 lines :/

**Comment by NathanWolf** [comment]
Oof, sorry, I don't know why that would've happened. You can find all the defaults here, but maybe Minehut has a way to reset it?

https://minecraft.fandom.com/wiki/Server.properties

I think you could've used their console to change the RP rather than editing the properties file :(

**Comment by Kalleball** [comment]
![image](https://github.com/elBukkit/MagicPlugin/assets/141743233/fd479815-da81-4ce0-96b0-0d7fc18eb329)
Here is the entire server.properties. The red one is the line I tried editing. I don't know what the yellow one is though? 

I will try the manual install too!

**Comment by Kalleball** [comment]
ITS WORKING, OH MY JESUS.
