### ISSUE TITLE
Mount Spell Broken in Magic 10.8.9+

### ISSUE THREAD

**Issue by mercurialmusic** [elBukkit/MagicPlugin#1256]
Heya! The mount spell seems to be broken in Magic 10.8.9 (release), with the following error in console: https://gist.github.com/mercurialmusic/dddceca9de2c3669f455512cd3a60772

I don't think this is directly related to #1044 but maybe? The player was trying to cast on a vanilla zombie (we have Model Engine (Model-Engine-R3.1.8) installed but NO mobs from it are active. We were able to reliably reproduce the behavior -- simply nothing happens when mount is cast. Not sure if other spells are affected.

Tried updating to Magic 10.8.10 b4232 but had the same result. 

Running on git-Paper-108 (MC: 1.20.1).

Thanks!

**Comment by NathanWolf** [comment]
You can turn off model engine integration to fix this error. `/mconfig configure model_engine.enabled false` should do it.

They keep changing their API, last I checked there were no real docs or control over it, and now they've teamed up with MythicMobs so I'm considering just removing this integration entirely.

For now I am going to disable it by default int he next dev build.

**Comment by mercurialmusic** [comment]
Ah, cool cool. Thanks!
