### ISSUE TITLE
How to set custom currency 

### ISSUE THREAD

**Issue by vajuvung** [elBukkit/MagicPlugin#1261]
Hello i need support

i need to know how to set currency in ``class: ModifyCurrency```

If i try set ``value: 5`` it add to value, ``NOT`` set. I need help how to configure it

**Comment by NathanWolf** [comment]
Hm I don't think there is a parameter to change it from a modify to a set, but you could try `value: 5-$currency` to set it to 5?

**Comment by vajuvung** [comment]
oh it work so nevermind. thx!
