### ISSUE TITLE
Some damage types are invalid

### ISSUE THREAD

**Issue by Clexus** [elBukkit/MagicPlugin#1265]
I mean this https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html#BLOCK_EXPLOSION
should be the cause of the "explosion" damage type, but in fact it's https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html#MAGIC
The death message is "xxx is killed by magic"
Some damage types like lava, fire worked well, but types like explosion, overall etc. Not
For example, the damage type OUT_OF_WORLD deals void damage to the player. And yes, it did deal the void damage, the death message is "xxx fell out of world". And explosion damage type should deal explosion damage to the target, the death message should be "xxx is killed by explosion"(or whatever i forgot), but in fact it didn't, the damage cause is magic, and death message is "xxx is killed by magic"

**Comment by NathanWolf** [comment]
Unfortunately I don't think there is anything I can do about this- some vanilla damage types are not useable directly.

I think there may be a tradeoff where you can use explosion damage but not have it be from the caster, and so it would bypass pvp or other checks. I'm not sure if there is a flag implemented to allow that switch, though- I will check.
