### ISSUE TITLE
You are not trained to use Wand. phrase

### ISSUE THREAD

**Issue by Koss809** [elBukkit/MagicPlugin#1267]
I wanted to disable every class in magic plugin bcs I thought that, people will use this classes. but when i seen in minecraft (You are not trained to use Wand.) i wanted to enable classes back. but its still spaming me with that phrase. Can someon help me?
![2023-09-01_18 45 27](https://github.com/elBukkit/MagicPlugin/assets/143830880/d97e9b45-9c44-4ed1-8479-ec9e57f24952)

**Comment by NathanWolf** [comment]
There are no classes in the default configs, I don't know what you have done, sorry.

You may need to just delete the `plugins/Magic` folder and start fresh.

**Comment by Koss809** [comment]
> There are no classes in the default configs, I don't know what you have done, sorry.
> 
> You may need to just delete the `plugins/Magic` folder and start fresh.

I did but still its showing me this

**Comment by Koss809** [comment]
> If you deleted the entire plugin folder with the server shut down, then restarted and you're still seeing this message, I can't help you, sorry. That resets the entire plugin.

I can send some screenshots from config if that help

**Comment by NathanWolf** [comment]
There shouldn't be any configs if you've deleted them all.

**Comment by Koss809** [comment]
> There shouldn't be any configs if you've deleted them all.

I know but when i restart the server some config shows up bcs in there are informations. After deleting magic file

**Comment by NathanWolf** [comment]
They should all be empty.

**Comment by NathanWolf** [comment]
You would also need to create new wand items after this reset- have you done that or are you trying to use ones from when the config was messed up?

**Comment by Koss809** [comment]
> You would also need to create new wand items after this reset- have you done that or are you trying to use ones from when the config was messed up?

when i restart the server with new config file i use /mgive wand command

**Comment by NathanWolf** [comment]
To be really clear, the server needs to be shut down completely when you do this delete since player data is also stored in memory. You can also `/mage reset` yourself to see if that fixes it, if it does you probably weren't shut down.

All of those files should be empty. If you open one up you will see nothing but comments.

**Comment by Koss809** [comment]
Okay i try reset myself

**Comment by Koss809** [comment]
Its works 😂 so only thing to do is reset myself... im big idiot Really 😄

**Comment by NathanWolf** [comment]
Whew- ok well if you have other players and you don't want to have to reset them all manually, you will need to

1. shut down server completely
2. Delete `plugins/Magic/` folder
3. Start server back up

All that reset command does is delete your player data file for you :)

**Comment by Koss809** [comment]
> Whew- ok well if you have other players and you don't want to have to reset them all manually, you will need to
> 
> 1. shut down server completely
> 2. Delete `plugins/Magic/` folder
> 3. Start server back up
> 
> All that reset command does is delete your player data file for you :)

my server is on maintenance so only 4 people was on server.. Thank you very much again <3
