### ISSUE TITLE
The function select(v,x,y,z) problem

### ISSUE THREAD

**Issue by Clexus** [elBukkit/MagicPlugin#1268]
select(v,x,y,z): If v < -1, return x, if v = 0 return y, if v > 0 return z
are you sure it's not "if v <0" but "if v < -1"?

**Comment by NathanWolf** [comment]
It is "if < 0" - where do you see "< -1", do I have it wrong in the docs somewhere?

https://github.com/elBukkit/EffectLib/blob/d112c9bc09c0bff5db0945bd8770d3444dbd00ba/src/main/java/de/slikey/effectlib/math/EquationTransform.java#L99

```
                    if (args[0] < 0) return args[1];
                    else if (args[0] == 0) return args[2];
                    return args[3];
```

**Comment by Clexus** [comment]
https://github.com/elBukkit/MagicPlugin/wiki/Equations#:~:text=select(v%2Cx%2Cy%2Cz)%3A%20If%20v%20%3C%20%2D1%2C%20return%20x%2C%20if%20v%20%3D%200%20return%20y%2C%20if%20v%20%3E%200%20return%20z

**Comment by NathanWolf** [comment]
Thank you, I fixed the wiki :)
