### ISSUE TITLE
keep_wands_on_death: false

### ISSUE THREAD

**Issue by sorandno** [elBukkit/MagicPlugin#1272]
keep_wands_on_death: false doesn't work.
Even if you set it for all wands in config and wand settings, it will remain in your inventory when you die.

Paper1.20.1

**Comment by FinnDemonCat** [comment]
That it's bound parameter. Set it to false.

**Comment by sorandno** [comment]
Whether true or false, the wand remains in the inventory.
keep_wands_on_death is not working.
I don't want to leave it in my inventory.

**Comment by sorandno** [comment]
/mconfig configure wand override keep false
/mconfig configure wand override keep_wands_on_death false

I executed the above command, but it didn't work.

**Comment by NathanWolf** [comment]
What wand(s) are you using? Just the default craftable survival wand?

**Comment by sorandno** [comment]
Wand.
It is the default survival wand.

**Comment by sorandno** [comment]
I heard this on Discord, but it seems like it may be affected by version 1.20.1.

**Comment by sorandno** [comment]
It worked fine!
thank you very much!
