### ISSUE TITLE
Problem 1.19.4 PureBDcraft resource pack

### ISSUE THREAD

**Issue by Cry667** [elBukkit/MagicPlugin#1275]
There are texture problems with the resource pack PureBDcraft that the texture of the totem is broken, torches, Glock etc. are compared are displayed twice, that some objects become vanilla textures like lanterns etc. Please would it be possible to make compatibility with PureBDcraft resource packs in 1.19.x?

Here is a screenshot of the textures https://postimg.cc/TpYTffHg

**Comment by NathanWolf** [comment]
You could try combining the two resource packs

http://merge.elmakers.com

If that doesn't work then you'd have to pick one of the two to use.
