### ISSUE TITLE
ModifyWalkSpeed does not see variables and attributes

### ISSUE THREAD

**Issue by neYaANK** [elBukkit/MagicPlugin#1276]
When setting `speed` field for `ModifyWalkSpeed` it does not recognize neither variables nor attributes. For variables it gives the warning, that variable is unknown and for attributes (I've used `movement_speed` attribute) it just disables movement.

**Comment by NathanWolf** [comment]
It looks like this action was not reading its parameters in the right place.

I've pushed a fix, can you please try the latest dev build and let me know if it's better?

https://jenkins.elmakers.com/job/MagicPlugin/4243/

**Comment by neYaANK** [comment]
Yeah, everything is working now!

**Comment by NathanWolf** [comment]
Great, thank you for letting me know!
