### ISSUE TITLE
Maven repository missing updated versions of plugins

### ISSUE THREAD

**Issue by danieli1818** [elBukkit/MagicPlugin#1277]
Hey! :D
how are you?
I have noticed a problem when I tried to work on the plugin on my own computer that it doesn't find some plugins in the maven repositories.
I think that it can be solved easily by adding the new versions on your maven repository.
Another thing is the updated maven shade plugin which its snapshot no longer exists which should be changed to 3.3.0.
Thanks in advance

**Comment by danieli1818** [comment]
[new_maven_debug_log.txt](https://github.com/elBukkit/MagicPlugin/files/13260642/new_maven_debug_log.txt)
attaching a log file

**Comment by NathanWolf** [comment]
The only dependency update I've done in _years_ was Multiverse, and it does look like I neglected to upload that to the elmakers repo.

http://maven.elmakers.com/repository/com/onarandombox/multiversecore/

I just fixed that, can you try again?

If it's still not working can you tell me what plugins are missing? That debug log is very difficult to follow.

**Comment by danieli1818** [comment]
still doesn't work here is the list of plugins it doesn't find:
![image](https://github.com/elBukkit/MagicPlugin/assets/46127670/80b47c83-86ef-4d74-9e1b-10c558cbcbbe)

**Comment by danieli1818** [comment]
btw what is the JDK version you use?

**Comment by NathanWolf** [comment]
Hm- wondering now if you're the first person to try to build this since moving the Maven repo off my build server 😪

I've uploaded all of those, thank you that log was very helpful. Can you try yet again and let me know if anything is still missing?

My build server is using `java-16-oracle`

**Comment by danieli1818** [comment]
Np, it works now thx! :D
