### ISSUE TITLE
Recent Errors with Some Spells

### ISSUE THREAD

**Issue by mercurialmusic** [elBukkit/MagicPlugin#1282]
Heya,

Getting a couple errors from the recent builds with some spells, so far only noted on Chop and Air Scooter, with the "Something went wrong!" feedback in game:

Error on wand use (chop):
https://gist.github.com/mercurialmusic/a72d03da8185ae5fe1d3d2f704d7db36

Error on command use (chop):
https://gist.github.com/mercurialmusic/b1c32f2db60835ad31af8ac2410312ea

Error on command use (airscooter):
https://gist.github.com/mercurialmusic/61c44f25989d91ababeb72a07c20d9b5

Using Magic 10.8.12-SNAPSHOT-b4250 on git-Paper-318 (MC: 1.20.2). Thanks!

**Comment by NathanWolf** [comment]
This seems to be due to a CraftBukkit change they made for 1.20.4 and made somewhere in the middle of 1.20.2 ... but now I guess have reverted?

I'm trying to figure out what happened, but I think the fix will be reverting the corresponding change in Magic's 1.20.2 layer.

I really wish I had time to make an API-only version of Magic, relying on internal functions like this is so problematic :(

**Comment by NathanWolf** [comment]
I'm actually not sure what to do about this for now. When I build Spigot, I get the new method signature. But Paper seems to not have it for some reason.

I'm not sure what's going on but I may have to do something more drastic, I'll take a closer look, hopefully tomorrow.

**Comment by mercurialmusic** [comment]
Paper rather frustratingly still hasn't released yet for 1.20.4 (which is why I'm still on 1.20.2 despite most plugins being updated long ago and now 1.20.5 looming!), so perhaps that's part of it. I'm not in a rush, and it's the holiday, so don't fret about it.

**Comment by mercurialmusic** [comment]
I'm guessing this one is also related, but getting this error when trying to spawn a magic mob: https://gist.github.com/mercurialmusic/1fa83df5253d0eb4a5bb1eb2c0047d30

**Comment by NathanWolf** [comment]
The error is unfortunately in the code that spawns entities, so any entity (mob, invisible armor stand, etc) will cause the error.

I’m hoping that Paper updates after the holidays to match Spigot internals and this error goes away.

If not, I’ll need to think of some way to be compatible with both.

**Comment by NathanWolf** [comment]
This seems ok now on latest Paper

**Comment by mercurialmusic** [comment]
Yes, I think we're good too, and thank you. On 1.20.4 now and have been able to successfully summon the entities at least. I haven't had a chance to test the spells, but I imagine they're fine. Will try tonight and will report if there's still anything weird, but will close this one.

Thanks again!
