### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by WasdCat** [elBukkit/MagicPlugin#129]
I want to translate the plugin but this links don't work:

https://github.com/elBukkit/MagicPlugin/wiki/Customization

Thanks.

UPDATE:
This link: https://github.com/elBukkit/MagicPlugin/tree/master/src/main/resources/defaults/messages

**Comment by NathanWolf** [comment]
Here are some example localizations:

https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/examples/localizations

And here are the defaults:

https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/main/resources/defaults/messages
