### ISSUE TITLE
Dupe bug. Magic and mythic crucible custom blocks have conflicting behavior.

### ISSUE THREAD

**Issue by PaintsplattersMC** [elBukkit/MagicPlugin#1290]
Mythic crucible blocks take damage from say cast grenade (or any spell that breaks blocks, regenning doesn't matter) and drop themself. the problem is, they shouldn't be. they should be disappearing and regenerating.
 
 So, they then regenerate and now players have the dropped copy and the regenerated copy.
 
Im using note block custom blocks for this btw
paper 1.20.2
Magic 10.8.12 SNAPSHOT 4f766c8 (edited)
MythicCrucibel lastest dev 2.0.0
it also bypasses region checks if a player can build or not, the blocks will drop a copy, but not break/regen.

**Comment by NathanWolf** [comment]
This plugin is basically in maintenance mode, I don't forsee adding any new plugin integration so unfortunately I think you will have to remove it if it's having compatibility issues like this with some other plugin.

Sorry!

**Comment by PaintsplattersMC** [comment]
no can do,. mythic crucible is a major feature of my server.

**Comment by NathanWolf** [comment]
I was suggesting you remove Magic.

**Comment by PaintsplattersMC** [comment]
how can i remove the explosion effect from the grenade and such?

**Comment by PaintsplattersMC** [comment]
also, has this plugin been abandoned?

will you return in the future?

**Comment by NathanWolf** [comment]
It hasn't been abandoned, but I don't have time to service feature requests or plugin integration issues. The specific issue you're mentioning will probably never get fixed.

I will continue to make updates for bugs within the plugin itself and for compatibility with future versions of Minecraft.

You can turn off all block-breaking with `/mexample add safe`, so you could try that before resorting to removing the (Magic) plugin.

**Comment by PaintsplattersMC** [comment]
now i cant cast grenade at all

**Comment by NathanWolf** [comment]
That will disable all block-breaking and creating spells. Most of them won't really do anything if you don't let them break blocks, there's no point in leaving them on. Who's going to use Grenade to just deal AOE damage to entities?

`/mexample remove safe` to turn that back off.

You could try making all blocks indestructible, I think that's `/mconfig configure material indestructible *`  but a lot of spells are going to feel underwhelming or downright useless.

Really just remove Magic, the entire point of like 75% of the builtin "survival" spells is breaking or creating blocks.

Your other option is to go for a fully custom config that does not revolve around block-breaking, but that's going to be a lot of work and something like Heroes or MagicSpells may be a better fit for your server out of the box at that point.

**Comment by PaintsplattersMC** [comment]
I use te bomb for AOE indeed.

**Comment by NathanWolf** [comment]
Hey sorry I should've thought of this earlier, but there is one other thing you could try if you're not wanting to remove or nerf the Magic plugin.

There's a feature that will pass block break events to other plugins when breaking blocks with spells- maybe that will help?

The command would be something like `/mconfig configure generic_protection MythicMobs`

Or if Crucible is a separate plugin (I think it's a MM add-on? Not sure...) instead of "MythicMobs" put "Crucible" or "MythicCrucible" whatever the name of the plugin is.

Also, again sorry, I missed this part in your original issue:

> it also bypasses region checks if a player can build or not, the blocks will drop a copy, but not break/regen.

That is honestly very strange- can I ask what region plugin you're using?

**Comment by PaintsplattersMC** [comment]
worldguard

**Comment by PaintsplattersMC** [comment]
/mconfig configure attribute generic_protection block MythicCrucible
/mconfig configure attribute generic_protection block MythicMobs

the exact command /mconfig configure generic_protection MythicMobs

![Screenshot from 2024-01-04 00-24-57](https://github.com/elBukkit/MagicPlugin/assets/83564809/5dc5b819-682c-4897-a591-1deca8f47438)


preventing the user from casting it altogether fixes the block breaking issue at spawn

but here are screenshots of the problem:
1: initial placement of the block ![2024-01-04_00 19 57](https://github.com/elBukkit/MagicPlugin/assets/83564809/dc21240b-fb5b-4eb4-afa2-5e8dc0981f08)

2: cast a spell that breaks blocks ![2024-01-04_00 20 05](https://github.com/elBukkit/MagicPlugin/assets/83564809/5d41d61b-4527-4448-b1ef-75ba4dc9d0a2)

3: THe block breaks dropping an item from crucible, ![2024-01-04_00 20 11](https://github.com/elBukkit/MagicPlugin/assets/83564809/419c7a9b-41b9-4e65-83e2-7f0e6f48c3a9)

4: the area regens. original block returns alongside dropped one ![2024-01-04_00 20 33](https://github.com/elBukkit/MagicPlugin/assets/83564809/20ee667b-b354-4a0b-998e-f1730e17ea21)

Potential fix would be an option to change the break block mechanic with "replace with air"

similar to how rubberize works with slime blocks. It does not cause blocks to drop themself

**Comment by NathanWolf** [comment]
The block break mechanic for most spells *does* just replace with air.

Is the grenade spell (and possibly boom) the only issue?

If so, then this is starting to make some sense, those are different in that they use vanilla explosions. Maybe just disable those two spells. If you are very attached to Grenade it could probably be re-written so the primed TNT entity is just visual and block-breaking is handled similarly to the Blast spell.

**Comment by PaintsplattersMC** [comment]
powerstone does it too

bomb rain, etc

**Comment by PaintsplattersMC** [comment]
I personally use the grenade for aoe. its part of Rogue class.


they way I have to configured, its actually useful

**Comment by NathanWolf** [comment]
Idk what powerstone is, but yeah the carpet bomb one makes sense, anything that uses TNT or explosions. Sounds like Crucible is catching those explosion events and force-dropping blocks.

I would disable any of the ones you don't care about. You could try editing grenade `/meditor spell grenade`, add `size: 0` to parameters and the TNT won't explode (I think)

Then you could look at some other spells, maybe blast, to see how to deal AOE damage and optionally break blocks (without an explosion), just copy+paste some of the actions and parameters.

**Comment by PaintsplattersMC** [comment]
Ok thanks. i removed the explosion effects
