### ISSUE TITLE
Disguised Magic Mobs force arm swing animation upon cast

### ISSUE THREAD

**Issue by NightScythe1** [elBukkit/MagicPlugin#1293]
Magic mobs which are disguised will cause an arm swing animation for all spell casts. Mentioned [by Remo on Discord](https://discord.com/channels/580099743875727363/862759829928280104/1038113334442086461) as well, and [here's a video](https://youtu.be/1hiV7KlsoQs) showcasing the issue. This is jarring for certain magic mobs who may have passive spells or interval spells which don't necessarily have any visual component, so it just looks like they are swinging their arms repeatedly. It is also a bit of an issue for mobs such as dragons, as they appear to have a janky-looking wing punch whenever any interval or triggered spells occur.

**Comment by NathanWolf** [comment]
Can you try putting `swing_arm: false` in the mob trigger?

If that's the problem I could also add a way to turn that off by default.

**Comment by NightScythe1** [comment]
Unfortunately this doesn't seem to work, at least where I tried to place it:
<img width="161" alt="image" src="https://github.com/elBukkit/MagicPlugin/assets/18646617/312f2517-b41f-4544-957e-5dae0c641c2e">
Neither of these positions in the config stop the behaviour, unless it should be somewhere else?

**Comment by NathanWolf** [comment]
That looks like the right place- is it *only* disguised mobs?

I don't have a setup right now that can work with LibsDisguises (it hasn't been updated) so it's kind of hard for me to test.

But testing with an undisguised mob, it seems to work:

```
noswing:
  type: zombie
  health: 50
  interval: 1000
  triggers:
    interval:
      swing_arm: false
      cast:
        missile: 100
        none: 100
```

I don't do anything special to trigger animations for disguised mobs, and I can't see how LibsDisguises would "know" a spell cast is going on- but you *could* try adding `animations: false` to the disguise config. I honestly don't know what that does, it refers to `setAddEntityAnimations` in the Disguise API.

**Comment by NightScythe1** [comment]
Complete oversight on my part, sorry! :sweat_smile:  I misread the initial message, and was trying with `arm_swing` instead of `swing_arm` like you suggested. `swing_arm: false` works perfectly and prevents the animation, thank you!
