### ISSUE TITLE
Suggestion - Teaming function

### ISSUE THREAD

**Issue by wintermaples** [elBukkit/MagicPlugin#13]
Hello there.
I use this plugin to play PvP, but this plugin seems not to have a teaming function.
So, using scoreboard, I created teams that friendly fire is disabled.

As a result, a magic can't damage players belonging to a team I belong, but a magic action affects them.
For example, even if players belong to the team, "homing" magic targets them.

I think a magic action shouldn't affect players belonging to the team.

**Comment by NathanWolf** [comment]
I like this idea! I'll see about adding it as an option, though I'd want it off by default since a lot of servers use/abuse teams just to give players colored names :)

**Comment by wintermaples** [comment]
Thank you. I'm looking forward to implementing this function :)

**Comment by NathanWolf** [comment]
I've added a config.yml option in the latest dev build (#1349 or higher)
```
use_scoreboard_teams: true
```

It is off by default.. and I don't have a great set up for testing it!

If you could try it out and let me know if it works, I'd appreciate it! With that turned on, players on the same scoreboard team should not be able to target or effect each other with spells, excepting those tagged as bypass_friendly_fire - usually healing spells.

**Comment by wintermaples** [comment]
Thank you for creating teaming function! I'm going to test this plugin today :)

**Comment by wintermaples** [comment]
Excuse me. Where can I find dev #1349 build?

**Comment by wintermaples** [comment]
Ah, sorry, I found it.

**Comment by NathanWolf** [comment]
Oops, I should've linked it! Glad you found it :)

**Comment by wintermaples** [comment]
Maybe, teaming function is moving without a problem, excepting following problem.
"healing magic" heals other team players.
Could you fix it?

**Comment by NathanWolf** [comment]
Hm- I would probably want to do that later as a separate feature, I think we would want a separate flag on spells that says "can only cast on team mates", there is currently nothing like that.

For now I guess I would tell your players to watch where they aim! ;)
