### ISSUE TITLE
1.10

### ISSUE THREAD

**Issue by iKezzaUK** [elBukkit/MagicPlugin#130]
When is magic 1.10 coming out? It works fine on my server, but the  RP doesnt :/ I keep being told internal server error when i join, and i figured out it is the RP, as i removed it and i was able to join my server

**Comment by NathanWolf** [comment]
Magic 1.10 has been out for a while. There are some known issues, mainly broomsticks don't work.

The RP didn't really need any changes, so I'm not sure what's going on there. It something says "internal server error" you should always check your server logs.

The RP generally doesn't affect the server at all, so this all sounds a little weird.
