### ISSUE TITLE
How to disable block regeneration for all in the world??

### ISSUE THREAD

**Issue by Krissssik** [elBukkit/MagicPlugin#1300]
Before this there was a similar post from 2021, but I wrote commands and it doesn’t work..

**Comment by NathanWolf** [comment]
`/mconfig spell override undo 0` 
is the way.

What command did you use?

**Comment by Krissssik** [comment]
i used that /mconfig spell default parameters.undo 0

**Comment by Krissssik** [comment]
by the way /mconfig spell override undo 0 doesnt work :(

**Comment by NathanWolf** [comment]
I had it a little wrong, it’s like a mix of the two.

`/mconfig spell override parameters.undo 0`

Should do it.

Where did you get the command with “default” in it? I’d like to fix it if it’s in a wiki or help somewhere.

**Comment by NathanWolf** [comment]
What do you mean?

did you try the command from my most recent comment?

**Comment by Krissssik** [comment]
I apologize, i meant that old wiki where u didn't fix the command. About `/mconfig spell override parameters.undo 0` its work, thank you so much!
