### ISSUE TITLE
SP points

### ISSUE THREAD

**Issue by WasdCat** [elBukkit/MagicPlugin#131]
How can my players get SP?
I don't find in the wiki nothing about it.

Thanks.

[img]http://image.prntscr.com/image/443659bd0e6a4dafb0bbae9a5c0b24f3.png[/img]

**Comment by NathanWolf** [comment]
https://github.com/elBukkit/MagicPlugin/wiki/SkillPoints

**Comment by WasdCat** [comment]
Thanks ;)
I've other problem, I put a Hermione to she learn the players the spell alohomora but doesn't work.
http://image.prntscr.com/image/c258cf7973444126a21f2e4072854fed.png

Thanks you're amazing :+1:

**Comment by WasdCat** [comment]
Thanks ;)
