### ISSUE TITLE
Bug with mana on a wand

### ISSUE THREAD

**Issue by Desmordss** [elBukkit/MagicPlugin#1317]
When I use spells, then put away the wand, and take them back in my hand, mana is restored. In some cases, this but did not exist, but now I don’t know how to fix it. What could be the reason?

https://github.com/elBukkit/MagicPlugin/assets/78231435/3e168332-ea46-4840-8a9e-5f19f771b1f8

**Comment by Desmordss** [comment]
fixed

**Comment by NathanWolf** [comment]
What was the problem and fix?

**Comment by Desmordss** [comment]
> What was the problem and fix?

![image](https://github.com/elBukkit/MagicPlugin/assets/78231435/cfb16769-c217-4fd7-912c-bea5dfcb24f4)
All mana returned if i took the wand out of hands. I removed this setting and the mana no longer returned instantly.
