### ISSUE TITLE
CheckInventory is checking for durability

### ISSUE THREAD

**Issue by Ferocimo** [elBukkit/MagicPlugin#1319]
Hello,

I'm trying to create some spells and passives which require the player to have specific weapons equipped.

It seems the CheckInventory action is checking if the player has the weapon equipped, but it only returns positive result IF and ONLY IF the weapon is in pristine condition. If it has lost one point of durability, then CheckInventory doesn't recognize it as the required item anymore and the sub-actions do not run.

This is an issue because one of the main use of CheckInventory could have been to check for durability-based items. I think an option should allow the spell creator to ignore item durability for this action.

Thank you for your time.

**Comment by NathanWolf** [comment]
Try adding `material_only: true`

https://reference.elmakers.com/#actions.check_inventory

**Comment by Ferocimo** [comment]
I was certain I already tried that before among other tests, but upon testing it again it actually worked. I guess I might have missed a "/magic load" command upon one of my testing...

Anyway thank you again and sorry for the useless question !
