### ISSUE TITLE
There is a small bug in the texture package

### ISSUE THREAD

**Issue by ChrisTVH** [elBukkit/MagicPlugin#1323]
## There should be no space in the name of that texture:
 **/assets/magic/textures/halloween/hsword_ grip.png**

Just in case, I checked if the texture path in the model file was correct, and it turned out to be the case, there is no a space there.
If you're wondering how I figured it out, I got this error when I put the texture pack in the itemadders plugin.

**Comment by NathanWolf** [comment]
Thanks! I fixed the filename. It'll only show up in the newest RP though, currently only used by the dev builds.

**Comment by ChrisTVH** [comment]
> Thanks! I fixed the filename. It'll only show up in the newest RP though, currently only used by the dev builds.

Great, at least it will be available for everyone in future versions, I corrected it in my own installation.
