### ISSUE TITLE
Citizens - Magic

### ISSUE THREAD

**Issue by LordAthos** [elBukkit/MagicPlugin#133]
I'm having an issue where magic doesn't seem to effect npc's  (Citizens 2). the particles pass right through them.The only spells capable of hitting them are once which involve a physical object (Arrows, wither head, fire, etc)
I don't suppose anyone could help me figure out why this is the case?
(feel free to ask any relevant info needed)

**Comment by NathanWolf** [comment]
That's intentional- NPC's aren't usually something you want spells to target.. I guess if you've got Sentry or something that's maybe not the case.

Try adding this to your spells.yml to change this behavior:
```
default:
  parameters:
     target_npc: true
```

**Comment by LordAthos** [comment]
Thank you, this has fixed the issue :+1:
