### ISSUE TITLE
Magic defense

### ISSUE THREAD

**Issue by Blamo27** [elBukkit/MagicPlugin#134]
Hello : )

I want to know how I should create an event which decrease damage.
CastEvent cannot get the TargetEntity :

> @EventHandler
	public void cast(CastEvent event)  {
		
		Bukkit.broadcastMessage(""+event.getSpellResult());
		
		if (event.getSpellResult().toString() == "CAST" ) {
			
			event.getSpell().getTargetEntity(); // Doesn't work
			Bukkit.broadcastMessage("getSpellResult() ==> CAST");
			
		}
       }

And use EntityDamageByEntityEvent event is buggy :/

**Comment by NathanWolf** [comment]
The vanilla damage events are the only way to do this, Magic doesn't fire any special events on damage since it is already handled by Spigot.

How is it buggy?

**Comment by Blamo27** [comment]
The event.getDamage() is very low (E-5) with the EntityDamageByEntityEvent

**Comment by NathanWolf** [comment]
That seems very strange to me.. if that were true I think a lot of plugins would break, including Magic's own damage protection.

I would suggest maybe adding some more logging- what type of entities are being damaged and what type of damage would all be very interesting to know.

**Comment by Blamo27** [comment]
How I can detect if the player has been targeted by a spell ?

**Comment by Blamo27** [comment]
> Yes, I will

**Comment by NathanWolf** [comment]
That part is trickier, there is not an API way but there is a hacky way- check CompatilbilityUtils.isDamaging

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/java/com/elmakers/mine/bukkit/utility/CompatibilityUtils.java#L82

Magic sets that static variable while it is damaging entities. This is used internally because the damage event will actually trigger a spell cast (when you whack something with a wand), and we need to prevent infinite recursion on damaging spells.

**Comment by Blamo27** [comment]
Is it a good way to check if the Caster have a wand in his hand ?

**Comment by NathanWolf** [comment]
That could maybe work, but I can think of some exceptions- like casting with a wand in the alt-hand, or throwing a potion with the alt-hand, thorns armor... there are probably more.

**Comment by Blamo27** [comment]
I'm still on 1.8.9

**Comment by NathanWolf** [comment]
Then thorns are maybe your only concern :)

**Comment by Blamo27** [comment]
Why thorns ?

**Comment by NathanWolf** [comment]
If you're wearing thorns armor and an entity hits you, they take damage. If you're just checking for player holding a wand, you'll count thorns damage as damage from the wand.

You can just check the damage type to skip that case... thoughhhhh for weird reasons wands apply thorns damage to the ender dragon (it won't take damage otherwise, bug in Spigot/MC)

**Comment by Blamo27** [comment]
Okey, so I'll not check if a player is holding a wand.
But I don't understood, how I use CompatilbilityUtils.isDamaging ?

**Comment by NathanWolf** [comment]
if (CompatibilityUtils.isDamaging) { .. this damage came from a Magic spell ... }

**Comment by Blamo27** [comment]
How I import CompatibilityUtils ?

**Comment by NathanWolf** [comment]
You'll need to build against the Magic jar. Easy with Maven:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/pom.xml#L6

Otherwise just add Magic.jar to your build path.

**Comment by Blamo27** [comment]
Yes, thanks .. ^^'

**Comment by Blamo27** [comment]
So the damage are negative sometimes :/

**Comment by NathanWolf** [comment]
Is there any chance you have some plugins doing weird stuff with damage? I don't think that should ever be true, damage events don't fire for healing as far as I know.

**Comment by Blamo27** [comment]
it's when a player equip his armor again
> http://pastebin.com/sCqg76fF

**Comment by NathanWolf** [comment]
I'm not sure what you mean- equipping armor is triggering a damage event? And that first debug print prints a negative number?

None of that makes much sense to me, sorry :(

**Comment by Blamo27** [comment]
http://i.imgur.com/RgqmOjG.png

**Comment by Blamo27** [comment]
This is a magic missile

**Comment by NathanWolf** [comment]
Can you reproduce this with no other plugins present? 

I honestly don't know, feels like it has to be something like mcmmo or some other damage-preventing type of plugin.

**Comment by Blamo27** [comment]
Citizens, Essentials, PermissionsEx, TimeLock, EssentialsSpawn, WorldGuard, WorldEdit, Sentry, Lores, HolographicDisplays and my plugins :/

**Comment by Blamo27** [comment]
The event is also multiplied
