### ISSUE TITLE
Ban Appeal 

### ISSUE THREAD

**Issue by Youn84** [elBukkit/MagicPlugin#1351]
Hello sorry for post here, but i was banned from the discord like 2 year ago, i'm sorry for the thing i did ( I don't remember. ) but is possible to get a last chance to come to your discord ? Thank you and my apologize my name is Younara thank you.

**Comment by NathanWolf** [comment]
Well I guess there isn't a better place to discuss this. It was *years* ago so I had to go look up what happened.

It seems that you

1. Backed out of a commission and asked for a refund, which I think in itself isn't a problem
2. But then got mad and started a brigade from some of your other server(s), having a bunch of people come and harrass and spam on our server, which is not super great and was a big headache for my mods

I'm not on the server much anymore so I will need to talk to the people who had to deal with all that and see what they think.

I do appreciate the apology, I'll let you know what they say.

**Comment by NathanWolf** [comment]
Well staff was ok with it, so I lifted the ban. We will probably put a "probation" role on you and disallow commissions for some period.

Thanks again for the apology.
