### ISSUE TITLE
1.21 Dev Build Testing

### ISSUE THREAD

**Issue by NightScythe1** [elBukkit/MagicPlugin#1356]
Here's just a compendium of things I found (so far) while testing Magic's 1.21 dev build:

🟢 Positive:
- Spells seem to work fine so far. This includes most types of basic actions such as damage, velocity, modify block, damage block, undo.
- Wands work *functionally*, i.e. they can store spells or read spells from your class, affect your stats, cast spells, etc.
- Classes work, they can store magic data, affect your player stats, etc.
- The resource pack works to an extent, but the custom GUI for spells, mana, etc especially seems to have survived the best.

🔴 Negative:
- Certain key spells like the spell shop or progress menu don't work at all. The menu can be accessed via enchantment table, but selecting these options does nothing.
- Some effect particles need to be renamed in spells in order to work (very minor)
- Wands themselves don't seem to use their custom textures, and default to their base item texture
- Spells don't use their custom textures, and instead seem to default to the skulls(?) example icons
- Lastly the *really* weird one, Magic seems to break all CustomModelData items. Currently, giving yourself any *non-wand* item that uses CustomModelData, whether through `/mgive` or even just vanilla `/give`, and then holding this item, will instantly turn it into a Broomstick Handle, *rename* that item to a Broomstick Handle, and set its CustomModelData to *exactly* 18047, giving it the texture of a Broomstick Handle.

If you'd like any pictures or videos to help with any of this, let me know and I'll hop back on. I'll also keep this thread updated with any further finds relating to the 1.21 dev build.

**Comment by NathanWolf** [comment]
Yikes, thanks! Some of those are pretty major. I'll try and take a look this week.

Thanks for testing!

**Comment by NathanWolf** [comment]
Sorry this is taking so long :(

I pushed fixes for the "all items turn into broomstick handles" problem, as well as wands and spells not using custom model data items.
All of that basically revolved around internal changes to how Minecraft handles CMD.

Still not working are enchantment table menus. 

Also not working but not mentioned in your report, the "drop" button is not working on wands. This makes the default wand not very usable since you can't open the wand inventory.

**Comment by NathanWolf** [comment]
Ok I got the GUIs fixed as well as the drop key.

I'm still testing but I'm hoping this is almost ready to release- thanks for all your help!

**Comment by Its-Austin** [comment]
So the snapshot that was made today has a few of the same issues, the wand itself wont let me open the spell menu. The wand tweaks out on my screen, I am now able to learn new spells via the enchanting table. The minecraft vanilla recipe book thats green that helps you craft is no longer working properly with the plugin. and Ill report anything else i notice

**Comment by NathanWolf** [comment]
Thank you for testing!

The wand not opening *should* be fixed, though. Assuming you're using the default wands that open/close with the "drop" button. There was an issue with detecting the drop button but the fix was part of that dev build.

Can you please share the full output of `/version` and `/magic`, and also let me know if you're using custom wands or configs?

I will need to take a look at the Knowledge Book, but that does actually use the Spigot API so if something is broken there it may be out of my control.

Thanks again :)

**Comment by Its-Austin** [comment]
Broom sticks are working
But when pushing Q while flying/usage they drop the handle 
Broom booster is craftable but unsure how to use

Custom model data so far is working

Magic bow is working and its GUI is as well when you push Q

Magic sword like the magic wand in the clip is glitching out and it wont let me open the GUI when pushing Q
(I'm assuming its either the plugins im using or those two GUI's are just having issues)

Spell book is working with its GUI and casting

Auto crafting/auto helper for the recipes are working properly, 
Missing the basic wand recipe
Missing the broomstick recipe

Wizard armor:
Scarf
Robes
Pants
Boots
Custom model is not working and is glitching like the clip with the wands Though the actual usage of the clothing seems to work|

These tools that are "bounded" to user doesnt seem to specify that they are and who they are bounded too like before.
Broom glider is craftable

Camera is not craftable even when configed enabled

Diving helmet works and is craftable

Emerald sword is craftable and works

Flash boots are craftable once enabled and is usable

Night vison goggles are craftable and usable 

Invisiability cloak is not craftable even when configed enabledd
Rabbit boots are working but the crafting recipe is not working

Rocket boots are working but it is uncraftable

Saddles are craftable and obviously works but the auto recipe is not

Smelting Zombie flesh into Leather works

Name tags are craftable but the auto recipes do not
The enchanting table GUI usage is not working
learning new spells
Checking progress
Apperance

Everthying for that is not working in the enchanting table 
It wont let me learn new spells even when opening up the learn spell menu saying "I already learned that"

**Comment by Its-Austin** [comment]
Also the glitching I had where the wand and a few items were tweaking out were due to another plugin, I shared it in the magic discord in the feedback channel

**Comment by NathanWolf** [comment]
The enchantment table, learning spells, and the magic sword should all be fixed in the latest dev build.

I don't know what's up with the knowledge book or auto crafting- those things actually use the Spigot API so should be working.

**Comment by Its-Austin** [comment]
Honestly most of the plugin seems to be running just fine for 1.21, for the magic plugin. The enchantment table and learning spells and magic sword is all fixed. Other than this error from /magic logs.. from my untrained/skilled eye the plugin is usable! :D
![Magic](https://github.com/user-attachments/assets/6afc5b7b-a080-40a8-b51a-99b0ac42009d)
![MagicLogs](https://github.com/user-attachments/assets/fd6add0f-8e8d-4bbb-8e8c-baeca63ff74c)

**Comment by NathanWolf** [comment]
Thank you! That's good to hear.

I just pushed a fix for that EntityFallingBlock issue, and also 1.21.1 support.

Maybe I could actually release this soon ... longest version-in-progress ever! 😅

**Comment by NathanWolf** [comment]
Thanks for all of your help!
I'm closing this now, hoping the issues are few enough that we can open individual tickets.

(I just fixed all item lore being broken, something we somehow completely missed..)
