### ISSUE TITLE
The plugin doesn't read the spell.yml

### ISSUE THREAD

**Issue by WasdCat** [elBukkit/MagicPlugin#136]
I put the prices of the spells but it doesn't work

ERROR IN LOG: http://pastebin.com/JSzMFWx8

 blink:
   worth: 1000
 deprimo:
   worth: 1000
 nox:
   worth: 500
 vermillious:
   worth: 500
 lumos:
   worth: 500
 patronus
   worth: 1500
 piertotum
   worth: 3000
 reducto
   worth: 500
 avis
   worth: 500
 fourpoint
   worth: 500
 duro
   worth: 2000
 araniaexumai
   worth: 2000
 finiteincantatem
   worth: 2500
 fumos
   worth: 2500
 diffindo
   worth: 500
 snowball
   worth: 2000
 colorvaria
   worth: 1000
 accio
   worth: 2700
 obscuro
   worth: 500
 alohomora
   worth: 5000
 locomotomortus
   worth: 3000
 bombarda
   worth: 2000
 flipendo
   worth: 600
 glacius
   worth: 500
 periculum
   worth: 500
 rictusempra
   worth: 4000
 firestorm
   worth: 4500
 expelliarmus
   worth: 4500
 bogies
   worth: 4500
 petrificustotalus
   worth: 4000
 orchideous
   worth: 200
 rennervate
   worth: 2000
 bubblehead
   worth: 2500
 protego
   worth: 3000
 episkey
   worth: 4000
 aguamenti
   worth: 1000
 aguamenti
   worth: 1000
 evanesco
   worth: 1000
 lacarnum
   worth: 1500
 ferula
   worth: 6000
 stupefy
   worth: 1500
 immobulus
   worth: 2000
 confringo
   worth: 3000
 incendio
   worth: 3000
 engorgio
   worth: 1000
 ventus
   worth: 1500
 vulnera
   worth: 3000
 meteo
   worth: 10000
 disillusion
   worth: 2000
 atmos
   worth: 10000
 arrow
   worth: 500
 confundus
   worth: 2000
 conjuntivitis
   worth: 2000
 incarcerous
   worth: 5000

When I use "/wand" http://image.prntscr.com/image/02ee42ffceb44990982952871c155ec7.png

**Comment by NathanWolf** [comment]
The logs are telling:
```
 in 'string', line 74, column 2:
     patronus
     ^
could not find expected ':'
 in 'string', line 75, column 9:
       worth: 1500
```

You are missing a colon after all of the spell names starting with patronus

Also make sure there are at least two spaces before every "worth", it's hard to tell from here if that's wrong if the formatting just got lost when you pasted it.

**Comment by WasdCat** [comment]
Thanks, I see it after write the message thanks the color.

http://image.prntscr.com/image/b99fe705259c4e83b121ac38dc0a5727.png
