### ISSUE TITLE
Ressource pack 1.20.4 build missing some textures o not rendering them

### ISSUE THREAD

**Issue by AbdelwahedTahri** [elBukkit/MagicPlugin#1365]
1.20.4:
![Capture d’écran du 2024-07-27 22-35-23](https://github.com/user-attachments/assets/4415f2fc-cf10-45ba-be72-aae6771e2155)

1.20:
![Capture d’écran du 2024-07-27 22-35-09](https://github.com/user-attachments/assets/4a06fd2b-4376-43d8-9557-dcf92e5bcc08)

**Comment by alekso56** [comment]
Isnt this a resource pack issue? [maybe open the issue here](https://github.com/elBukkit/Magic-RP)

**Comment by AbdelwahedTahri** [comment]
ok thx
