### ISSUE TITLE
Item lore broken in 1.20.5 and up

### ISSUE THREAD

**Issue by arkent112** [elBukkit/MagicPlugin#1367]
It is not explain the items, for example when i am put the mouse on the talisman it is only show "luck of the sea 1" and not the thing it sould do.

**Comment by NathanWolf** [comment]
Do the items actually work?
What are your spigot server and Magic plugin versions?
```
/version
/magic
```

**Comment by arkent112** [comment]
the items are working but as i say the instead of what the talisman does it is say "luck of the sea 1".
I am using the latest version of magic and version 1.21.1

**Comment by NathanWolf** [comment]
Thank you for reporting this, I can't believe I didn't notice that all lore was completely broken :(

I have it fixed now, you can get the latest dev build or wait for me to make a new release, which I will probably do pretty soon.

https://jenkins.elmakers.com/job/MagicPlugin/4295/

**Comment by arkent112** [comment]
Are you going to uploade it to spigot when it is done?
I love this plugin so much and i am using it in my aternos server.

**Comment by NathanWolf** [comment]
I just released it to spigot and dev.bukkit.org as 10.9.2
