### ISSUE TITLE
Upgrade spells

### ISSUE THREAD

**Issue by WasdCat** [elBukkit/MagicPlugin#138]
I can't found what is the command to upgrade a enchant, can you please tell me what is it? thanks :)

(I'm using the potter pack)

**Comment by NathanWolf** [comment]
As in you want to level up a spell, add more spells to a wand, or rank up a wand?

**Comment by WasdCat** [comment]
level up a spell, thanks for your help :)

**Comment by NathanWolf** [comment]
Leveled up spells are unique spells on their own. So you simply add them to a wand, they will replace any lower-levelled versions already on the wand.

They have special "key names", so like "/wand add apparate|2" will add apparate level 2. The character there is a pipe, normally shift+backspace.

**Comment by WasdCat** [comment]
Thanks :)
