### ISSUE TITLE
The capture action does not keep mob's nbt data anymore

### ISSUE THREAD

**Issue by KingofAnomaly** [elBukkit/MagicPlugin#1382]
API: Paper 1.20.6-149
Magic: 10.9.2

In previous versions the capture action would keep the nbt data of the mob it was used on but now it seems to give spawn eggs with random nbt data.

**Comment by NathanWolf** [comment]
Thanks for the report!

This is fixed in the latest dev build here: https://jenkins.elmakers.com/job/MagicPlugin/4302/
