### ISSUE TITLE
Maven repository private?

### ISSUE THREAD

**Issue by knokko** [elBukkit/MagicPlugin#1384]
One of my plugins is using the MagicAPI as dependency, but my builds started failing somewhere the past week because it can't download the dependency from https://maven.elmakers.com/repository/com/elmakers/mine/bukkit/MagicAPI/7.5/MagicAPI-7.5.pom

When I visit this in my browser, I get
```
Forbidden

You don't have permission to access this resource.
```

If it has been moved, could you please point me to the new location?

**Comment by NathanWolf** [comment]
Oops, sorry about that!

I was consolidating storage on my web server to save some money and I forgot to fix the symlink to point to the new repository location.

It's working now, please let me know if you have any more trouble.

**Comment by knokko** [comment]
Yes, it works again. Thanks for the very quick response!
