### ISSUE TITLE
Inventory conflict

### ISSUE THREAD

**Issue by Elsopeen** [elBukkit/MagicPlugin#14]
Hi,
I know, that's the second ticket I open in two days, but I think that the website doesn't say in a good way how to configure easily this whole universe of items and spells.
I write this because there is a conflict between Multiverse-Inventories and Magic. When someone changes world, the server writes that it couldn't load the player's inventory through its .json file. And unfortunately, this conflict usually destroys the player's inventory and his bound enderchest. That's pretty annoying, especially when there is a huge number of sorcerers having the same problem.
Could you please try to make a compatibility between Magic and Multverse-Inventories ? That would help us a lot, and make that we don't have to give to players their stuff back anymore. And if you can, could you create any documentation about the plugin, more precise and easier to find than in a github please ?
Thanks for reading this post, and probably answering it,
best regards,
Elsopeen

**Comment by wintermaples** [comment]
Hi, elBukkit team.
I thought causes of this problem and found it.


See following code.
```json
{
    "SURVIVAL": {
        "inventoryContents": {
            "1": {
                "==": "org.bukkit.inventory.ItemStack",
                "type": "WOOD_HOE",
                "meta": {
                    "==": "ItemMeta",
                    "meta-type": "UNSPECIFIC",
                    "display-name": "§6Magic Missile§f (§3Wand§f)",
                    "lore": [
                        "§o§aBeginner Magic Wand",
                        "Fire a bolt of pure magic",
                        "§eCooldown: §6A Moment",
                        "§eCosts 15 Mana",
                        "§7§9Range: §624 §9meters",
                        "§2Earns up to §65 §eSP",
                        "§o§3Bound to wintermaples",
                        "§d§oMana: 50",
                        "§r§dMana Regeneration: 5/s"
                    ],
                    "Unbreakable": true,
                    "ItemFlags": [
                        HIDE_PLACED_ON,
                        HIDE_UNBREAKABLE,
                        HIDE_POTION_EFFECTS,
                        HIDE_ATTRIBUTES,
                        HIDE_DESTROYS
                    ],
                    "internal": "H4sIAAAAAAAAAG2QzW7bMBCEN6mdCEn6c+o5h6CnKCAt0pIeoucehRW5tIlKIktRtR+/ayUNeuiFwJLL+WbmDuAONiecbAFFpjEOmAluLTlchlzANpwmSvBw8lOmNGIcaC7g5hy7Ec9wrUUBn3lIdCDew+zDBFe6gK/kHJncRUzZm4G64NxMGT6Il4pJq2rnLTw5qSsSO1EqoXRZyVqWjW6wbK3SjVCipT1b2/ZhmSxsclqogI03jClOIdjuGOg/tITWL/OFtivg3tJsko+ruS9PEfPx8TsevHn8seb+5CfeYGmTfT/QX8oD8vybujnSMMDt6OfZDxf6RQCKng5+4hS8yAVkP7IEjhE+SqVFXdXNXu9Uza9v3kwYQoJv2JAwbd23fD6Ta7SstcW6Fc9630pZmUrt9siUn0TxPfCEI/t6tXt95nstXrj67a/Fc6lXkm/XMh3Wrpa6VDtnStVWbdkgNaXtdeWUxAaNYUfHkHtM7GiZXj/frBnnf0Lec90pxIjvhQD8AdwAv7QsAgAA"
                }
            }
        },
        "potions": "[]",
        "enderChestContents": {},
        "armorContents": {},
        "stats": {
            "ex": "2.0085025",
            "ma": "300",
            "fl": "20",
            "el": "0",
            "hp": "20",
            "xp": "0.5283001",
            "txp": "0",
            "sa": "5.0",
            "fd": "0.0999915",
            "ft": "-20",
            "ra": "-14"
        }
    }
}
```


Maybe, this error is caused because itemFlags elements aren't String(aren't surrounded "").
itemFlags' elements should be String.


I think itemFlags' elements are EnumType.
You should convert EnumType into String.


I hope It helps elBukkit team fix this bug.

**Comment by NathanWolf** [comment]
If that's the case, I think you can fix this with some config changes in Magic!

Try adding this to your config.yml:
```
wand_hide_flags: 0
```

That will prevent wands from using the "hide lore" flags, and maybe make MVInv happy.

MV Inventories does have a history of wiping wand data, though- not sure if that's better now, but something to keep an eye on. This at least may prevent the player's inventory from getting completely lost though!

**Comment by NathanWolf** [comment]
I'm going to close this, please re-open if there's still an issue!
