### ISSUE TITLE
Mobs

### ISSUE THREAD

**Issue by LordAthos** [elBukkit/MagicPlugin#140]
I'm having an issue where if the Magic Mobs go into unloaded-chunks their disguise dis-apears.
Not only that but the game no-longer reconizes them to be that mob 
For example:
if i summon a Dark Wizard, i could remove it using /mmob clear Dark_Wizard.
However if i summon the Dark wizard and than run far away or relog, the skin has vanished (Showing the actual mob - Zombie Pigman.) But more importantly i am unable to get rid of the mob using commands (important since i am using command blocks to manage this)

i was wondering if there was a way to either set it so that the mobs despawn all together, or another work-around of sorts?

-PS- This plug-in is amazing, adds a whole unique aspect to a server.

**Comment by NathanWolf** [comment]
I don't think there will be a work-around for this, it would be a LibsDisguise issue. Magic is also unable to track them across unloads.

Generally I am working towards making sure Magic Mobs despawn completely when they unload, though so far that does not look possible.
