### ISSUE TITLE
Issue regarding Magic/Heroes/MythicMobs

### ISSUE THREAD

**Issue by PABerwen** [elBukkit/MagicPlugin#141]
Console Log : http://pastebin.com/80G1pZ9d
These lines in particular
[13:56:17] [Server thread/WARN]: [Magic] Heroes found, but failed to integrate!
[13:56:17] [Server thread/WARN]: [Magic] CharacterManager is null
[13:56:17] [Server thread/WARN]: [Magic] SkillManager is null

The plugins Heroes and Magic work fine until MythicMobs is added to the server, resulting in Magic not integrating with Heroes properly. Of course this may be an issue with either of the other plugins or on my end, please feel free to point me in the right direction.

Also, please note that I've tried using Spigot 1.9.4 and appropriate plugin versions with the same results.

Thanks for your time.

**Comment by NathanWolf** [comment]
This is fixed in the latest build of Magic, which should work in 1.9.4 - grab it from spigotmc or by build server.
