### ISSUE TITLE
Error in console when i use broomstick on the latest version

### ISSUE THREAD

**Issue by VolanDeVovan** [elBukkit/MagicPlugin#142]
I updated the plugin to the latest version(6.2.1)  and the error is not gone.

old ticket
https://github.com/elBukkit/MagicPlugin/issues/139

**Comment by VolanDeVovan** [comment]
please fix it

**Comment by NathanWolf** [comment]
Are you still running 1.9? It may be you need to downgrade Magic if that's the case, though it should be backwards compatible. I'm certain the issue was fixed in 1.10.

Can you please provide your server version and the exception you're getting now?

**Comment by VolanDeVovan** [comment]
Spigot version: CraftBukkit version git-Spigot-798f32d-0cd0397 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
Plugin version: latest.
Crash report there in the old ticket

**Comment by NathanWolf** [comment]
Fixed in Magic 6.2.2, tested in 1.9.4
