### ISSUE TITLE
Resource pack

### ISSUE THREAD

**Issue by iKezzaUK** [elBukkit/MagicPlugin#144]
Hi Nathan,
Really odd problem here. I have your texture pack, and its installed on the server. On the inventory and hot bar its ok. But when I open my wand, the spells are all diamond Axes, with the names etc in their desc. when I hover over. It never used to do this :/ I have reloaded the server, redownloaded the RP and replaced the link,and still the same problem. Any insight to this problem?
Thanks,
Kieran

**Comment by NathanWolf** [comment]
That does sound really odd- actually sounds like some other plugin might be messing with your inventory when opened? Do you have a backpack plugin, dtlTraders, anything like that?

Sorry for the late response, let me know if you're still having issues.

**Comment by iKezzaUK** [comment]
The problem fixed itself :) thanks for replying though
