### ISSUE TITLE
Spell casting velocity issue [MAGIC 6.2.2]

### ISSUE THREAD

**Issue by alekso56** [elBukkit/MagicPlugin#148]
http://pastebin.com/raw/mQEWAqdq

**Comment by NathanWolf** [comment]
Do you know what spell is causing this? Push, Pull or something else?

May be fixable with some config changes to the offending spell, I assume entity velocity checks have gotten more strict, though I have not seen these errors myself.

**Comment by alekso56** [comment]
This was caused by repeatedly spamming fling above the height limit, or just general spam .

**Comment by NathanWolf** [comment]
I never could get this to happen, and this message does not appear anywhere in Spigot/CraftBukkit code.

Was this paper spigot or something?
