### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JustHamster** [elBukkit/MagicPlugin#153]
How can I switch the configuration to Harry Potter or Avatar? Thanks 😄 

PS: I love your plugin 😄 keep up the good work, also I play on Potterworld, and I only just found out this plugin runs on it! Amazing!

**Comment by NathanWolf** [comment]
You just turn them on in config.yml via "example: potter" or "example: bending"

See here: https://github.com/elBukkit/MagicPlugin/wiki/Examples

**Comment by JustHamster** [comment]
Thanks!

Also, does the game of Life work on this? I know what it is, but how do you do it in-game, I am struggling to get it working. I saw your video on it, messing around, and it looks fun!
