### ISSUE TITLE
Having Issues with Getting Certain Spells to Work?

### ISSUE THREAD

**Issue by SweetHABIT** [elBukkit/MagicPlugin#154]
Hi there! I'm using this plugin for an RP server and I was having problems getting certain spells to work.
I'm using this plugin to give each character 'powers', so they can only use certain ones. I've made some progress with this by making it impossible to cast just about every spell, and the re-added permissions for individual spells, but some of the spells just won't cast.
So far I've found that Lightning, Blessing, Chain Lightning, Flamethrower and probably others, when added to a wand, show up with a '0' beside them and you can't cast them. I'm not sure if it's  a problem with mana levels or what, but how do I make these spells available for the common player?
Being opped does allow you to use them, but I can't let everyone run around with op permissions so that's out.

Any help?

**Comment by NathanWolf** [comment]
It should be pretty easy to tell if it's a mana issue- open your inventory and look at the tooltips for the spell and wand. The wand will say how much mana it has, the spell will say how much is required to cast.

It may also be region related, if you are using Factions, WorldGuard, Towny or a number of other plugins, spells may be blocked for PvP or build permission reasons. You can use the command

```
/mage debug <playername>
```

While the player is holding a wand with a spell active to tell why they can't cast it.
