### ISSUE TITLE
[Question] How do you do the missile effect?

### ISSUE THREAD

**Issue by IsS127** [elBukkit/MagicPlugin#155]
Hey,
Ive been looking allover the files to see how you do the missile effect with effectlib, but i didnt really find out how you do it.
So how do you really create it?

This is how i do it but its really slow..
http://hastebin.com/sanojucari.java

**Comment by NathanWolf** [comment]
That's more or less how it's done, just plays an effect at every step. That part really has nothing to do with effectlib.

There is also a ConeEffect overlaid on that, if I remember correctly.

Never use distance() for things like this, favor distanceSquared (you'd be comparing against 1.5 * 1.5 in this case). Not sure if by "slow" you meant inefficient, or if it's really just moving slowly through the world.

**Comment by IsS127** [comment]
Ok.
With slow i mean this
![effect](https://cloud.githubusercontent.com/assets/8834158/19239663/6ce59364-8f07-11e6-855f-3d665e69451f.gif)

**Comment by NathanWolf** [comment]
That is completely a matter of how quickly you move your point:
```
double x = t*dir.getX() + 0.005;
```

That means you are moving 0.005 meters per tick, which is going to be pretty slow.

**Comment by IsS127** [comment]
Oh ye that does make it slower..
But it also changes possition of where it spawns.

**Comment by NathanWolf** [comment]
The CustomProjectile class plays multiple particles per tick, which is why the speed of the projectile doesn't change the frequency of particles.

So if you move the projectile 1 meter per tick, you might play 10 particles per tick, each stepping 1/10 of a meter.

**Comment by IsS127** [comment]
Ok i made my effect/particle work, i found a code and i modified it a little bit
But could u help me with a tiny thing?
I want to change color of my SPELL_MOB_AMBIENT
I use this code
`try{
				        	ParticleEffect.SPELL_MOB_AMBIENT.display(l, 40.0D);
				        }
				        catch (Exception ex) {
				          ParticleEffect.SPELL_MOB_AMBIENT.display(0.0F, 0.0F, 0.0F, 0.0F, 1, l, 40.0D);
				        }
				        
				        if ((i > 5)){
				          block = start.getWorld().getBlockAt(l);
				          if (block.getType().isSolid()) {
				           // l.getWorld().createExplosion(l.getX(), l.getY(), l.getZ(), 1.0F, false, false); 
				            break;
				          }
				        }`

Thank you.

**Comment by NathanWolf** [comment]
Assuming that's the EffectLib ParticleEffect class, you can use this display call:

```
    public void display(ParticleData data, Location center, Color color, double range, float offsetX, float offsetY, float offsetZ, float speed, int amount) {
```

"data" can be null, so long as you're not using block_crack, icon_crack or one of the other particle types that needs data.

**Comment by IsS127** [comment]
Ty!
