### ISSUE TITLE
Wand Template

### ISSUE THREAD

**Issue by Fancepants** [elBukkit/MagicPlugin#156]
I cant seem to figure out the command to save a wand template in game. I take a normal wand add the spells I want but I can't get it to save. Is there a special command?

**Comment by NathanWolf** [comment]
It's just "/wand save somewandname". This is a newer command, I think added sometime after Magic 6.0, so you may not have it if you're still on 1.8 or something.

**Comment by Fancepants** [comment]
So this is what I am do
/wand
/wand add boomstown
/wand add fire
/wand add missle
/wand save test
Then is should save the wand so I do 
/wand test also tried /mgive Fancepants test
it gives the wand but only with the last spell added 

Its not saving all the spells I have loaded

**Comment by NathanWolf** [comment]
That would be pretty weird. What version of Magic?

Can you open up the file and take a look at it? It would be in plugins/Magic/wands/test.yml - there should be a list of spells, maybe it's not saving properly.

**Comment by Fancepants** [comment]
Version 6.2.3 
I found the issue. The wand auto saves as 
test:
  spells:
  - boomstown
  - fire
  - missile
  hotbar_count: 1
  active_spell: missile
  name: Wand
  description: $path Magic Wand
  mana: 50.0
  mana_regeneration: 5
  mana_max: 50
  mana_timestamp: 1476200419129
  effect_color: 766fa6beed67,8cbc4213716a,ef955a20377b
  effect_particle_radius: 0.2
  effect_particle_offset: 0.3
  quiet: 1
  keep: true
  bound: true
  indestructible: true
  undroppable: true
  left_click: CAST
  right_click: NONE
  drop: TOGGLE
  swap: CYCLE_HOTBAR
  icon: wood_hoe:1
  path: beginner
  creator_id: f8f08f01-7ee6-4e0d-8859-a325d6802491
  creator: Fancepants


The hotbar_count is set to 1 automatically . I changed this to 21 to test and it Works!

**Comment by NathanWolf** [comment]
Huh- that sounds kinda weird, I mean hotbar_count should probably be 1, but that wouldn't prevent spells from showing up. Well glad you got it resolved, though!
