### ISSUE TITLE
Issue with the ressources pack and Heroes

### ISSUE THREAD

**Issue by themaxou** [elBukkit/MagicPlugin#157]
Hi everybody !
First, sorry for my bad english, then
I recently buy Heroes RPG plugin to make a server to play with friends, so i wanted to add Magic to make skills shortcuts in hotbar, it's working ! except one thing, on the /mskills command to have the heroes skills, the texture pack don't match. How to have icon instead of stick in the inventory ?

**Comment by NathanWolf** [comment]
There's a little bit about this on the integration page:

https://github.com/elBukkit/MagicPlugin/wiki/Integration#heroes-integration

Basically this:

> In order to get icons for your skills, you will need to edit your skills.yml. Put an "icon: blaze_rod" line in to use an item for an icon, or "icon-url: http://some_skin_url" to use a custom player head icon.

**Comment by themaxou** [comment]
Thanks you very much ! that's working ! But how do the "icon-url:" does work ? My goal is to set custom icon on the skills shortcut, is icon-url the solution ?

**Comment by NathanWolf** [comment]
You can either use a resource pack for that, I have a good tutorial on how to set this up in 1.9 and above here:

https://www.spigotmc.org/wiki/custom-item-models-in-1-9-and-up/

Or use icon-url. This will only work with player skin textures, you can't put just any URL in there or it will get blocked by the client. (That is if you are in 1.8.6 and up).

I have a library of icons you can use here:

http://mine.elmakers.com/#textures

**Comment by NathanWolf** [comment]
Note that with the resource pack approach you can make high-res (up to 64x64, I think) icons. The player skin texture icons will be limited to 8x8.

**Comment by themaxou** [comment]
thanks you so much ! you're awsome ! :D

**Comment by themaxou** [comment]
how and last thing, i often have error like "you're not trained to use blaz-rod", it's because of heroes ?

**Comment by NathanWolf** [comment]
Yup. There's probably some way to turn that off, but I'm far from a Heroes expert.
