### ISSUE TITLE
Moving to a newer java version?

### ISSUE THREAD

**Issue by killme** [elBukkit/MagicPlugin#159]
Are there still good reasons to stick with java 6 or could we move to 7 or 8?
Newer versions don't really provide any shocking new features, it's mostly just nicer syntax, but I don't see any reason not to move on.
It looks like jenkins is on 7 already (`[MagicPlugin] $ /Library/Java/JavaVirtualMachines/jdk1.7.0_55.jdk/`) so that would at least get us to 7.
Are there any major users still on outdated java versions or other reasons that would make this unfeasible?

**Comment by killme** [comment]
I would like to finally be able to write a `try-with-resources` in a lambda using a diamond operator. ;)

**Comment by NathanWolf** [comment]
The only real reason I've held out is the possibility of servers still on Java 6, but according to mcstats there aren't any of those left. It does look like we'd need to keep support for Java 7 though.

http://mcstats.org/plugin/Magic

And yeah I'm so out of date my other fear is maybe not understanding my own code anymore once you get ahold of it XD   .. I guess I should really get up to speed on JDK7+ features :P

So yeah I'd be fine with moving up to Java 7.

**Comment by killme** [comment]
I imagined we were staying on 6 for that, but good to see we won't have to disappoint anyone with switching to 7.

I hope I'm not pushing my perfectionism too far. If you have any remarks or questions on why I am doing things, you know how to contact me on IRC I guess.

I'll push a commit to start targeting java 1.7 in a bit.

(PS: Some of the stats might have been wrong before this 2df8d80ec7 (Or is it just called delta as a surprise for unknowing devs? :P))

**Comment by killme** [comment]
c78b3657d8b6dcc105241ab7121638648a2a7679
