### ISSUE TITLE
Bank Plugin -https://www.spigotmc.org/resources/bank.3556/

### ISSUE THREAD

**Issue by cricketcricketcricket** [elBukkit/MagicPlugin#16]
when u have a wand selected and go to deposit xp - u can just endlessly deposit xp.

**Comment by NathanWolf** [comment]
Yes, sorry- any other plugin that directly interacts with XP is going to have compatibility issues with Magic. 

To fix this, turn off the SP and Mana displays by putting this in your plugins/Magic/config.yml:
```
mana_display: none
sp_display: none
```
