### ISSUE TITLE
Mob Arena

### ISSUE THREAD

**Issue by iKezzaUK** [elBukkit/MagicPlugin#160]
Is there any support or upcoming support for MobArena plugin?

**Comment by NathanWolf** [comment]
No, very doubtful. Not something I would personally be working on since I have my own arenas plugin.

What sort of support do you have in mind?

**Comment by iKezzaUK** [comment]
I was wanting to use a wand with classes, and maybe have set spells for
certain classes

**Comment by NathanWolf** [comment]
I would say that's very unlikely to happen.

If MobArena can give kits, then you could put a wand item in a kit. Probably the closest thing you're going to get.
