### ISSUE TITLE
CombatTag not working with magic item

### ISSUE THREAD

**Issue by Blamo27** [elBukkit/MagicPlugin#163]
Hello,

My server has this version of magic :
-> https://github.com/elBukkit/MagicPlugin/issues/152
-> http://jenkins.elmakers.com/job/MagicPlugin-1.8/42/com.elmakers.mine.bukkit.plugins%24Magic/

But this version don't include the fix of this version :
-> https://github.com/elBukkit/MagicPlugin/issues/94 (CombatTag)
-> http://jenkins.elmakers.com/job/MagicPlugin-1.8/37/com.elmakers.mine.bukkit.plugins%24Magic/artifact/com.elmakers.mine.bukkit.plugins/Magic/5.5.6-SNAPSHOT/Magic-5.5.6-SNAPSHOT.jar

Could you upload a correct version please ?

Thank you.

**Comment by NathanWolf** [comment]
Are you sure? I mean reading that issue it sounds like I backported it for you, so it should be there since build #37 (and you have #42).

Is Magic suddenly not working with CombatTagPlus anymore? Was it ever?

**Comment by Blamo27** [comment]
Yes it was working and now it isn't.

**Comment by NathanWolf** [comment]
Did you do anything besides update Magic? There's no real reason why that fix would just stop working :\

**Comment by Blamo27** [comment]
Okey sorry, it was my plugin ... 😞

``` Java
@EventHandler(priority=EventPriority.LOWEST)
	public void PlayerLogin(PlayerJoinEvent event) throws SQLException {

		if (event.getPlayer() != null) {

			Player p = (Player) event.getPlayer();
                        p.setHealth(p.getMaxHealth()); <----- Very very bad idea .. :/

	         }

	}
```
