### ISSUE TITLE
Error on Gather spell in Spigot 1.11

### ISSUE THREAD

**Issue by jlwitt** [elBukkit/MagicPlugin#170]
First, thank you for this plugin.  My users all love it.  I've run into two issues though.  I have MagicWorlds-1.4 and Magic-6.3 loaded with just the default settings.  I'm running in survival mode on Spigot 1.11.  I do run several other plugins, but I've tried with just these two also.  I've tried as OP and as a normal user.  The results are the same.  If you need any additional info, I'll do the best I can.  Any help would be appreciated.  Thank you.

First - When trying to cast the spell Gather:

I get the following console message in debugging:
[18:43:48 INFO]: Cast Gather from -222,68,234: cast (true)

The user gets the message:
Unknown command.  Type "/help" for help.

The particle effects take place, but the nothing else happens.

Second - I've found dozens of chests near spawners, in mines, and in strongholds.  I haven't had a single message about items in chests nor have I found a single magic item.  With the same config on my 1.9 server I had messages and items all of the time.  When I upgraded to 1.10 they stopped.  1.11 is the same, I haven't had a single message.

**Comment by NathanWolf** [comment]
Gather relies on there being some plugin available to handle the /tpa command.

MagicWorlds only puts items in newly generated chests- do you know if you have new chunks being generated, or was the world mostly populated before you added the plugin?

**Comment by jlwitt** [comment]
I added a teleport plugin and it worked great!  Thanks for the help.

For the servers, I made a brand new world with both 1.10 and with 1.11.  Also created a new server with just the Magic worlds and Magic plugins, on the same seed I'm using so I could go straight to known chests.  They were all there, no magic items though.

**Comment by NathanWolf** [comment]
Oh.. hm so .. sorry about this, I forgot that I made the chest populator optional at some point.

If you drop this file into the MagicWorlds plugin folder it will enable the chest populator- and you can configure it how you like from there:

https://github.com/elBukkit/MagicWorlds/blob/master/src/main/resources/examples/mixins/chest_populators.yml

The command "/magicw populate" can be used to populate existing chests in the world, make sure to only run this once or items will double up.

**Comment by jlwitt** [comment]
The YML works as did the command.  Thanks for the help again.  Will that be included in the next update of the plugin?

**Comment by NathanWolf** [comment]
I think I intentionally took it out for .. reasons. MagicWorlds can do a lot of things now, and I was thinking people might not want to install it and automatically have the chest populator. So I made all the configs optional - I probably just need to write some better documentation or something. Honestly I didn't know anyone was really using it anymore :)
