### ISSUE TITLE
[Issue update 6.3.1]

### ISSUE THREAD

**Issue by Svennieboy777** [elBukkit/MagicPlugin#171]
Hello there,

lately we have updated the plugin from 5.3.3 to 6.3.1. For a reason I cannot right click the wand to change of spell. All 3 the modes do not work. 

If you got a solution to this issue would be useful.

Thank  you

**Comment by NathanWolf** [comment]
Firstly make sure you're on a server version that support 6.3.1 - it needs to be 1.9.2 or above.

In Magic 6 the right-click button was changed to the drop button by default, to support dual-wielding. 

You can change this back, but it sounds like you've already tried the upgrade items (e.g. /mgive mode_rightclick) to change it?

**Comment by Svennieboy777** [comment]
Is there a way to make it set for everyone to right click?

**Comment by Svennieboy777** [comment]
Also, it doesn't seems to work by the default wands

**Comment by NathanWolf** [comment]
I'm not sure what you mean by that second bit, but yes you can customize the wand template configs. Wands all inherit from the base_wand template, which defines what the buttons do:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/defaults/wands/base.yml#L5

So to override this behavior, you could put something like this in your plugins/Magic/wands.yml file:

```
base_wand:
    drop: cycle_hotbar
    left_click: cast
    right_click: toggle
    swap: none
```

I think that is more like the pre-1.9 behavior, it uses right-click to open the wand inventory, drop to cycle hotbars, and doesn't use the item swap button at all.

**Comment by Svennieboy777** [comment]
I tried what you said, but it still doesn't seems to work. I cannot switch of spells with a wand by right-clicking, I cant change of spell using the drop button. This applies for all wands beside the wolf, that one seems to work correctly.

**Comment by NathanWolf** [comment]
The only thing special about the Wolf is that it's set to inventory mode no matter what the main config has the defaults set to.

So you could try /wand configure mode inventory

Failing that, check the wolf with /wand describe and see what's different.

The wolf is not set to right click, though, nothing is anymore - so I might be losing sight of what you're asking.

**Comment by Svennieboy777** [comment]
It seems to work, but I want to set it as default for everyone, I dont want everyone to execute /wand configure mode inventory before it works. Is there a way to set that? I tried what you said above with
```
base_wand:
       drop: cycle_hotbar
       left_click: cast
       right_click: toggle
       swap: none
```

**Comment by NathanWolf** [comment]
Try adding "mode: inventory" then, maybe. No idea why you'd have to do that but if it works for you in-game then it should work via config. The configs and configure command do the same thing.

**Comment by NathanWolf** [comment]
Also since I don't know what version you're on and base_wand is pretty new, try just "wand:" in the configs.

Or use "/wand describe" on whatever wand you're giving players and check the "template" tag to know where it came from.

Finally, make sure you're editing plugins/Magic/wands.yml - it kind of sounds like none of your changes are doing anything, which is a common symptom of trying to edit the default files.

**Comment by Svennieboy777** [comment]
> Try adding "mode: inventory" then, maybe. No idea why you'd have to do that but if it works for you in-game then it should work via config. The configs and configure command do the same thing.

This seems to work.
