### ISSUE TITLE
Wand appearance and Hat selector

### ISSUE THREAD

**Issue by meneertimmy** [elBukkit/MagicPlugin#173]
I don't know if this has something to do with your plugin but in the PotterWorldMc server they do have a wand and hat selector. You type /hats to see a list with the hats you've bought and if you type /wands you can choose through wand appearances, effects and guardians. Did they make that with your plugin or with another one. And if it is another one do you know a plugin wich does the same thing?

**Comment by NathanWolf** [comment]
That is a custom plugin of their own.

You could implement both pretty easily with Magic shops though. One shop that has upgrade items to change wand appearance, one that casts spells to put hats on the player.

**Comment by meneertimmy** [comment]
okay, but I want that players can buy the hats and wand upgrades once and than can switch between them

**Comment by NathanWolf** [comment]
You'll need to write you own plugin for that, I'm afraid. I have no plans on adding a feature like that, at least not anytime soon. Sorry!
