### ISSUE TITLE
Spells dropping on death then other player picking them up and getting them permanently

### ISSUE THREAD

**Issue by ICHIGOunserscore** [elBukkit/MagicPlugin#176]
title says everything help

**Comment by NathanWolf** [comment]
This sounds like it would be due to some other plugin, possibly a "binding" plugin or something else that is modifying a player's inventory on death and dropping items. May not be anything I can do about that on my end.

**Comment by ICHIGOunserscore** [comment]
there is no such plugin on the server

**Comment by NathanWolf** [comment]
I'll double check but I'm 99% sure this doesn't happen on a clean server with just Magic.

What server and plugin version do you have?

**Comment by NathanWolf** [comment]
I've never heard of that happening before, but I guess check /tps and make sure the server isn't lagging tremendously. If possible, see if you can reproduce this on a dev server without any other plugins.

**Comment by NathanWolf** [comment]
Any update on this? Did it get fixed somehow? Never seen this before.
