### ISSUE TITLE
1.11.2 wand item isn't upgrading (stays at wooden hoe) and all spell icons are diamond axes

### ISSUE THREAD

**Issue by eloijasper** [elBukkit/MagicPlugin#177]
yes i have the resource pack. At first everything worked but then someone did /stop on the server to stop tnt in their base from blowing up and once i started the server again, the issue arose

**Comment by Mutim** [comment]
did you try /magic reload ?

**Comment by NathanWolf** [comment]
That all makes very little sense, unfortunately. Are there any errors in your server logs? 

The resource pack is a client-side thing, someone using /stop making it not work sounds very odd.

**Comment by eloijasper** [comment]
i fixed it by going to a backup of the server but i still have no idea what
happened
