### ISSUE TITLE
Wands broke when the server restarts 

### ISSUE THREAD

**Issue by Aquamoles** [elBukkit/MagicPlugin#179]
Hi, I'm Aquamoles and I have a server with my friends and we installed the plugin Magic.

I have an issue from this plugin that when I have a wand and it brokes after a restart of the server, in addition we have too the multi-verse plugin and also the multi-inventories.

I hope I get a reply for answer my issue :)

PD: How can I add the 3d hats?

**Comment by NathanWolf** [comment]
Magic is not compatible with MV Inv, it will discard wand data. I don't think there is going to be a fix for this, that plugin hasn't been updated (as far as I know) in quite a long while.

There are no "hats" built into Magic. There are night vision goggles and an invisibility cloak that you wear on your head, but no purely cosmetic items. It would be up to you to add those yourself using 3D models you have the rights to use.
