### ISSUE TITLE
Magic 1.11.2(latest) Arrow spell bug?

### ISSUE THREAD

**Issue by GreatRaceofGithub** [elBukkit/MagicPlugin#180]
thanks.

The spelling of Arrow is not cast accurately.
I am using the latest spigot.

http://pastebin.com/r5ZvvZ7U

**Comment by NathanWolf** [comment]
What version of Magic is this from?

**Comment by NathanWolf** [comment]
I think I've forgotten what the problem was here and the pastebin has been removed. If this is still an issue, can you please remind me what it was?
