### ISSUE TITLE
Changing Cost Of Sp

### ISSUE THREAD

**Issue by Cornelwallace** [elBukkit/MagicPlugin#182]
Hello, I was wondering if there was a way to change the cost of spells with sp, for instance say a spell cost 200 sp and you wanted to change it to 1 sp

**Comment by NathanWolf** [comment]
Yes, that is the "worth" property of spells. So add something like this to spells.yml
```
blink:
  worth: 2
```

**Comment by Cornelwallace** [comment]
If a spell was inherited would I have to go back to the original?
accio:
  worth: 5
    category: charms
    inherit: pull

**Comment by NathanWolf** [comment]
No, anything you add to accio will always override whatever is in push.
