### ISSUE TITLE
Recall Particles 

### ISSUE THREAD

**Issue by Cornelwallace** [elBukkit/MagicPlugin#183]
Im having a issue with configuring the recall spell particles to look like blinks, with this I mean the dome like shape it produces. Everytime I try to edit it, the plugin crashes. is possible to do this?

**Comment by NathanWolf** [comment]
Plugin should never crash - do you have an error log?

**Comment by Cornelwallace** [comment]
If I can recall it said there was a issue and it said the plugin is disabled whilst trying to set differant particles for the recall spell

**Comment by Cornelwallace** [comment]
but i would like to know how to set the particles up the way i want them
