### ISSUE TITLE
Villager Profession Magic Mobs

### ISSUE THREAD

**Issue by meneertimmy** [elBukkit/MagicPlugin#184]
Hello,
I made a mob (deatheater) and in my resourcepack it's a blackmith villager
but how can i change the profession? I tried different things like
''villager_type: blacksmith''
''prof: blacksmith''
''profession:blacksmith''
but nothing worked

**Comment by NathanWolf** [comment]
Sorry for the late response and that this isn't better documented!

"villager_profession: blacksmith" should work.

**Comment by meneertimmy** [comment]
thank you

**Comment by meneertimmy** [comment]
is this also possible as disguise?

**Comment by NathanWolf** [comment]
I'm not sure, honestly- whatever you put in "disguise" gets passed to LibsDisguise, so if there's a way to do it with a command then you should be able to do it with configs too.
