### ISSUE TITLE
Russian Localization trouble.

### ISSUE THREAD

**Issue by IamLocalHero** [elBukkit/MagicPlugin#185]
Hello my friend!
I  got messages.yml file translated to russian, moreover, I mad my own. But every time I try to use it - plugin don't work. Spigot 1.8.8
(tried almost any verison of ur plugin)
log part:

[latest.txt](https://github.com/elBukkit/MagicPlugin/files/712030/latest.txt)

**Comment by NathanWolf** [comment]
Hello!
If you can upload the messages.yml file, I can take a look. A couple of things to note:

1. You generally don't want to edit the keys, the parts of the YAML to the left of the : - it looks like from your error message that you have done that, though I'm not sure.
2. You may need to put double-quotes around anything with special characters- I'm not sure about that, but definitely if you've broken rule #1 the key will have to have quotes.

**Comment by IamLocalHero** [comment]
Well, there is 3 different types of translation:
1st(90kb) - my own zapp.su based translation
2nd(73kb) - zapp.su 1.9+
3d (84kb) - zapp.su 1.8+
It was fine to zapp.su. I tried to do my best, cheked every spaces and
quotes.
Maybe double quotes..maybe my dubmness, maybe whothellknows :)

What about assisting me with configuration and some litte resouce-pack
changes? For a fee. I want to make a cool rpg-based MC server, we have
nothing substantial in Russia. You as a creator of such massive plugin are
the best perfomer of magicrpg part.
Nontheless, if you are not interested, I hope I'll find a way just to
translate and make it work for 1.8.8 (it's very popular in Russia
1.88+viaversion)


2017-01-18 4:04 GMT+03:00 Nathan Wolf <notifications@github.com>:

**Comment by NathanWolf** [comment]
I don't generally do private work and haven't really had time lately in any case- but I can definitely help get the translations working, it's hopefully just a matter of quoting things. 

The 1.9 ones should work on 1.8, though some of the keys and instructions may have changed- you can stick with the 1.8 one if that one's more working. Anyway, if you can link to whichever file you'd like to get working, I can take a look when I have some time!

**Comment by IamLocalHero** [comment]
I'll be great.
my spigot: https://getbukkit.org/spigot I took 1.8.8
And tried any verison of your plugin :) from 4xx to 6xx. If 5.5.5 will work
with my translation(1st(90kb) - my own zapp.su based translation) I sent
you - it will be awesome (it 95% done). Im sorry for poor language and
circumstances arising from that.

2017-01-18 4:22 GMT+03:00 Nathan Wolf <notifications@github.com>:

**Comment by IamLocalHero** [comment]
And how should I change visualisation of spell items? Like on video. On my
server (even if I use resource pack) it looks like heads with url-pic, but
not panels.

2017-01-18 4:32 GMT+03:00 Сережа Прянский <makeyoubelievein@gmail.com>:

**Comment by IamLocalHero** [comment]
Please, provide me any information. I really need that localization.

2017-01-18 4:38 GMT+03:00 Сережа Прянский <makeyoubelievein@gmail.com>:

**Comment by NathanWolf** [comment]
Sorry, for the localizations I was waiting for you to link to the files. I can't really tell what's wrong unless I can see them- can you put what you're currently working with up on hastebin or something, please?

For your visualization question, you need to use the Magic resource pack (or make your own) for the spell icons to show up properly.

This is the RP you want for 5.x : 

https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-RP-5.zip

**Comment by IamLocalHero** [comment]
I have ur resource pack and works fine but icons are head not glass panels
(the still have need visualisation, but on heads).
damn, I've attached my files, but it was blocked by github. hastebin link:
https://hastebin.com/suholujabi.pl  - my translation,  original -
https://hastebin.com/ajeyujucan.vbs

2017-01-21 1:18 GMT+03:00 Nathan Wolf <notifications@github.com>:

**Comment by NathanWolf** [comment]
You need an older version of the RP, try the one I linked to. Spell icons in Magic 5.x are skulls, in 6.x they are items.

For the skulls, you need a special file in the RP to make them look flat, this is not in the latest Magic RPs.

**Comment by IamLocalHero** [comment]
sorry the original file - https://hastebin.com/rasorucimi.vbs  (5.5.5 im
using, translated file - same version)
it's for 5.3 default - https://hastebin.com/ajeyujucan.vbs

**Comment by IamLocalHero** [comment]
I got it, I saw flat items on video - its 4.2?

2017-01-21 4:52 GMT+03:00 Сережа Прянский <makeyoubelievein@gmail.com>:

> sorry the original file - https://hastebin.com/rasorucimi.vbs  (5.5.5 im
> using, translated file - same version)
> it's for 5.3 default - https://hastebin.com/ajeyujucan.vbs
>

**Comment by NathanWolf** [comment]
Icons for 4.x are skulls, too. They had been skulls for a while, until MC 1.9 allowed me to use retextured RP items instead.

You'll need the older RP if you want them to look flat in Magic 5.x

**Comment by IamLocalHero** [comment]
Okay I got it. Sorry, I have +12time, it's a real trial to concentrate :)

2017-01-21 4:54 GMT+03:00 Nathan Wolf <notifications@github.com>:

**Comment by IamLocalHero** [comment]
I tried to change encoding to UTF-8, changed double quotes to single ones.
Still don't work

2017-01-21 4:56 GMT+03:00 Сережа Прянский <makeyoubelievein@gmail.com>:

**Comment by NathanWolf** [comment]
Ok, I finally got to try this out myself and I think the problem is what I said earlier- you have to put any special characters inside of double quotes. For example, your original "general" section won't load, but this will:

```
general:
    no_spells: "Вы не знаете никаких заклинаний."
    no_spells_in_category: "Вы не знаете заклинания, которые относятся к категории: $category"
    spell_list_page: "Вы знаете $count заклинаний.[Страница $page из $pages]"
    spell_list: "Вы знаете $count заклинаний"
    locked_chest: "Этот сундук закрыт, вы не можете его разбить."
```

If you put everything inside of double-quotes like that, it should work.

**Comment by IamLocalHero** [comment]
Well, I guess I'm on right way. Keep trying :), it's quite big.

2017-01-23 2:27 GMT+03:00 Nathan Wolf <notifications@github.com>:

**Comment by IamLocalHero** [comment]
Yeah man, I did it. Thanks.

2017-01-23 4:13 GMT+03:00 Сережа Прянский <makeyoubelievein@gmail.com>:
