### ISSUE TITLE
texture pack

### ISSUE THREAD

**Issue by Cornelwallace** [elBukkit/MagicPlugin#186]
im having a issue trying to change the default magic texture pack to another, if possible can you tell me if i can?

**Comment by NathanWolf** [comment]
Just put it in your server.properties. Or in Magic's config if you want Magic to manage the SHA for your RP.

https://github.com/elBukkit/MagicPlugin/wiki/ResourcePack

**Comment by Cornelwallace** [comment]
so i could set it up like this?

default_resource_pack: "https://dl.dropboxusercontent.com/u/75066972/Tiny%20Pixels%20-%2025th%20October.zip"

**Comment by NathanWolf** [comment]
Assuming that is a direct download link (DB links often are not) then yes.

**Comment by Cornelwallace** [comment]
thanks so much it worked!
