### ISSUE TITLE
Wand box 

### ISSUE THREAD

**Issue by Cornelwallace** [elBukkit/MagicPlugin#187]
The issue im having is with the wand damage, when ever I want to add damage to a item to change its texture, it stays the same texture and same damage it was originally 
Example:

icon: diamond_hoe:2

**Comment by NathanWolf** [comment]
The wand box is special:
```
wandbox:
    icon: wood_hoe,gold_axe,gold_pickaxe
    randomize_icon: wood_step
```

The "icon" property in this case should be a list of icons, a random one of which gets chosen when the box is opened and becomes a wand.

To change the appearance of the box itself, you need to change "randomize_icon" instead.
