### ISSUE TITLE
Learning with wands

### ISSUE THREAD

**Issue by Cornelwallace** [elBukkit/MagicPlugin#188]
Im having a issue with wands being able to learn at all, for example when holding the wand that does not allow you to learn and you use a enchantment table it says "you can not learn with that wand" is there a way to bipass this

**Comment by NathanWolf** [comment]
Find that message in the messages.defaults.yml file and then add it to your messages.yml file as ""

That will make the message go away if that's what you want.

**Comment by Cornelwallace** [comment]
I'm looking to make it so I can learn with the wand I want if possible

**Comment by NathanWolf** [comment]
What wand is this? Customized configs?

**Comment by Cornelwallace** [comment]
yes customized, it won't let me learn with it, and thats all i want it to let me do 

cornel:
    icon: diamond_hoe:59
    active_spell: Flipendo
    path: year1
    locked: true
    keep: false
    path: year1
    quick_cast: true
    mode: inventory
    undroppable: true
    quiet: 1
    xp_max: 50
    xp: 50
    xp_regeneration: 6
    effect_color: random
    bound: true
    undroppable: true
    indestructible: true
    hotbar_count: 2
    spells:
    - Flipendo

**Comment by NathanWolf** [comment]
Do you have a path called "year1" in your enchanting.yml?

Take a look at the built in potter configs (or just use them directly)

**Comment by Cornelwallace** [comment]
i do have a path as year1, i set the spells and everything for it

**Comment by NathanWolf** [comment]
Hm well that is weird then. Any chance you can link to all of your configs? Or at least wands, spells and enchanting?

**Comment by Cornelwallace** [comment]
wandboxy:
    icon: diamond_hoe:59
    active_spell: Flipendo
    path: year1
    locked: true
    keep: false
    path: year1
    quick_cast: true
    mode: inventory
    undroppable: true
    quiet: 1
    xp_max: 50
    xp: 50
    xp_regeneration: 6
    effect_color: random
    bound: true
    undroppable: true
    indestructible: true
    hotbar_count: 2
    spells:
    - Flipendo

year1:
    icon: wood_hoe:1
    migrate_icon: wood_hoe
    upgrade: year2
    upgrade_item: student_upgrade
    inherit: default
    property_count:
      0: 100, 20, 10
      1: 25,  50,  200
    max_protection: 0.2
    protection:
      0^1: 100, 100, 90
      0^2: 0,   5,   10
    max_protection_falling: 0.4
    protection_falling:
      0^1: 100, 100, 90
      0^2: 1,   10,  20
    max_protection_physical: 0.4
    protection_physical:
      0^1: 100, 100, 90
      0^2: 1,   10,  20
    max_mana_regeneration: 10
    mana_regeneration:
      1: 100, 30, 5
      2: 20,  30, 40
    max_mana: 100
    mana_max:
      2: 100, 10,  0
      5: 20,  30, 50
    spell_count:
      1: 100, 5,   1
      2: 0,   50,  40
      3: 0,   10,  90
    extra_spells:
      flare: 110,80,60
    spells:
      missile: 100,90,80
      arrow: 0,20,10
      blind: 0,1,5
      poison: 5,10,20
      fire: 50,70,60
      frost: 80,70,50

year2:
    icon: wood_hoe:2
    migrate_icon: wood_hoe
    upgrade: year3
    upgrade_item: apprentice_upgrade
    inherit: year1
    property_count:
      0: 100, 20, 10
      1: 50,  50, 30
      2: 0,   10, 100
    max_protection: 0.4
    protection:
      0^1: 100, 100, 90
      0^2: 0,   5,   10
      0^3: 0 ,  1,   5
    max_protection_falling: 0.5
    protection_falling:
      0^1: 100, 100, 90
      0^2: 1,   10,  20
      0^3: 0 ,  15,  15
    max_protection_physical: 0.5
    protection_physical:
      0^1: 100, 100, 90
      0^2: 1,   10,  20
      0^3: 0 ,  15,  15
    max_protection_fire: 0.3
    protection_fire:
      0^1: 100, 100, 90
      0^2: 1,   10,  20
      0^3: 0 ,  15,  15
    max_protection_explosions: 0.3
    protection_explosions:
      0^1: 100, 100, 90
      0^2: 1,   10,  20
      0^3: 0 ,  15,  15
    max_mana_regeneration: 30
    mana_regeneration:
      1: 100, 30, 5
      2: 20, 30, 40
      3: 0 , 10, 10
    max_mana: 150
    mana_max:
      5:  100,10,  0
      7: 20, 30, 50
      10: 5 , 20, 30
    spell_count:
      1: 100, 10,  1
      2: 0,   70,  40
      3: 0,   1,   90
    extra_spells:
      disarm: 0,0,0
      stun: 4,4,5
    spells:
      lightning: 40,50,30
      admission: 12,10,6
      petrify: 10,10,10
      whip: 1,10,20
      Flipendo: 4,3,3

**Comment by Cornelwallace** [comment]
speaking of wands why is the icon not damaged

wandboxyy:
  spells:
  - Flipendo
  hotbar_count: 2
  active_spell: Flipendo
  name: Wand
  mana: 50.0
  mana_regeneration: 6
  mana_max: 50
  mana_timestamp: 1484969691150
  effect_color: random
  effect_particle_radius: 0.2
  effect_particle_offset: 0.3
  quiet: 1
  keep: true
  bound: true
  undroppable: true
  left_click: CAST
  right_click: TOGGLE
  drop: CYCLE_HOTBAR
  swap: NONE
  icon: diamond_hoe:59
  path: year1
  creator_id: e6ebe748-d2eb-4d2e-bafe-7a4a0bfb597f
  creator: iCornelBear

**Comment by NathanWolf** [comment]
Wands are unbreakable by default, unless you add "indestructible: false"

I'll see what I can do with these configs, a code block or hastebin would be better since they've lost all the indentation.

**Comment by Cornelwallace** [comment]
Any chance I can learn with the wand?

**Comment by NathanWolf** [comment]
I don't know what's wrong with your configs, I will need to try them out. It would help a lot if you'd put them in a code block or on hastebin.
