### ISSUE TITLE
Magic Image Maps doesn't work

### ISSUE THREAD

**Issue by meneertimmy** [elBukkit/MagicPlugin#189]
Hello, I've got a problem with the /mmap load command. If I try to load a image from the internet by using /mmap load [url] it doesn't work. I just get a blank map. How can i fix this?

**Comment by NathanWolf** [comment]
I just tried it on my dev server and it appeared to work.

Can you please check your server logs for errors? The image is downloaded server-side, so if you have a firewall there blocking outgoing connections (unusual, but possible) that might get in the way.

It's also possible it's something with the specific image you're trying, so if you want to let me know the URL I can try it myself.

**Comment by NathanWolf** [comment]
I had a weird issue yesterday where I map I had previously loaded looked blank. Later, after a server restart maybe, it came back.

Just noting that here. Did you ever get it working?
