### ISSUE TITLE
Players can fly with NoCheatPlus & Magic

### ISSUE THREAD

**Issue by Blamo27** [elBukkit/MagicPlugin#193]
Hello,

We found an incompatibility with NoCheatPlus : using a jump potion allows you to completely bypass SurvivalFly anticheat from NoCheatPlus. It's only the case when both Magic and NCP are loaded on a server, and it's the case on every Minecraft and plugin versions we've tested.

**Comment by NathanWolf** [comment]
Try putting "ncp_enabled: false" in Magic's config.yml to disable NCP integration.

**Comment by Blamo27** [comment]
That worked, thanks !
