### ISSUE TITLE
Arrow spells bug

### ISSUE THREAD

**Issue by Blamo27** [elBukkit/MagicPlugin#194]
Hello again,

Since updating to 1.11, we noticed that every "arrow" spells we had on 1.8 no longer work. They always fail. Do you know why, and how could we fix it ? If you want, I'll provide the configuration of one of the arrow spell.

Thanks.

**Comment by NathanWolf** [comment]
Did you also update to latest Magic? Are there any startup errors? The default arrow spells definitely work, but did require some NMS updates in 1.11.

**Comment by Blamo27** [comment]
Yes we have latest version, no there wasn't any startup error... Here is the configuration of the arrow spell, we modified it a little bit long ago, maybe that is what caused the issue in the new version.
http://pastebin.com/Ft8KaZRU

**Comment by NathanWolf** [comment]
I don't see anything useful in there but I can try it out myself when I get a chance - please remind me if you don't hear back in a few days.

There are no errors on cast either?

**Comment by Blamo27** [comment]
Actually there is, I forgot to check that. Here is the error : http://pastebin.com/6SnW1DYa

**Comment by NathanWolf** [comment]
Thanks, that's somewhat helpful - and is this Spigot 1.11 or is it Craftbukkit, paper or something else?

**Comment by Blamo27** [comment]
Spigot 1.11.

**Comment by NathanWolf** [comment]
Huh- that is very weird, I didn't think anything had really changed there. It doesn't look like I've had to touch any of the projectile-spawning code in almost a year!

I just added some more detailed logging for the case when this fails- do you think you could try out this dev build, please?

http://jenkins.elmakers.com/job/MagicPlugin/1792/com.elmakers.mine.bukkit.plugins$Magic/

**Comment by Blamo27** [comment]
Here is the error now : http://pastebin.com/L5r2QeZi

**Comment by NathanWolf** [comment]
I'm sorry to say I still don't have an answer here. I double-checked to make sure that it's calling the right constructor for EntityArrow, and it seems like it should be. Nothing's really changed there in 1.11

Can you please post your spell code again so I can take another look? And have you been able to check the builtin Arrow spell to see if it does the same thing?

**Comment by Blamo27** [comment]
So, I tried with the new Arrow spell from the spells.default.yml, and it indeed worked. I then compared our arrow spell to the new one, and noticed a small, but crucial difference : projectile is no longer marked as "Arrow", but "TippedArrow". That was it, nothing more... Sorry for having bothered you with this issue, I simply forgot to compare the two.
Anyway, thanks, it works now.
