### ISSUE TITLE
3rd Spell

### ISSUE THREAD

**Issue by DillPickle613** [elBukkit/MagicPlugin#195]
Hi,

I'm using this plugin on a server with some of my friends. Everyone has encountered an issue where when you get your 3rd spell, you no longer gain SP. We have tried getting different wands, readjusting the timer, using different spells but nothing seems to be working. So, we are limited to only 3 spells per person. We don't know how to fix this. We are trying to prevent using money to buy spells, but we will if we have to. Hope you can fix this. Thanks!!

**Comment by NathanWolf** [comment]
That sounds very weird. You're aware of the SP cooldowns, right?

https://github.com/elBukkit/MagicPlugin/wiki/SkillPoints#sp-cooldowns

There's nothing special or specific about how many spells you have or what spells you have that would affect earning SP. I'm afraid I wouldn't really know where to start with this if it's a problem :(

Are you able to play long enough on my dev server (mine.elmakers.com) to see if it's a problem there too? I haven't ever seen this happen myself.

**Comment by DillPickle613** [comment]
Thank you very much for responding! Yes, I am aware of skill cooldown. I will try to join your server sometime tonight or tomorrow. It happens once you get the 3rd skill. Even if you get a new wand the issue still occurs. I will join your server to see if the issue persists. Thanks!

**Comment by NathanWolf** [comment]
Ok- that's really very weird! Please also check your server logs for errors, just in case. I can't imagine what could cause that, but I'll give it some thought.

**Comment by DillPickle613** [comment]
Thanks a bunch for letting me on the server. I'm pretty sure it's just the server I'm trying it on. I went on yours and the issue didn't occur. I will check to see if we have the right version. (It's a 1.10 server).

**Comment by NathanWolf** [comment]
Did you ever figure anything out here? I'm still really confused by this.

**Comment by DillPickle613** [comment]
not yet. Still working on it. we are going to put the spells in the shop for now. Thanks for your help
