### ISSUE TITLE
Permissions Not Working

### ISSUE THREAD

**Issue by koalaleader** [elBukkit/MagicPlugin#197]
I've added the /wand permission to a rank and when I try to execute the command it just doesn't go anything. It doesn't even display the "You do not have access to this command." It just plain and simple doesn't work. It works when I'm in OP, but not with PEX ranks.

**Comment by NathanWolf** [comment]
What permissions have you given?

Magic.commands.wand
and
Magic.commands.wand.*

Are needed to access all of the /wand commands. (This is not a good idea to give out except maybe to very trusted admins). More fine-grained control is available, but basically just "Magic.commands.wand" doesn't do anything in itself.

**Comment by koalaleader** [comment]
I have only given .wand and .wand.wand.<wandname>
I don't want regular players to have admin priveleges though.

**Comment by NathanWolf** [comment]
Are you trying to give them permission for "/wand name"? I think you also need Magic.commands.wand.name then (no double .wand)

**Comment by koalaleader** [comment]
No. I was giving them permissions for a wand from a template.

**Comment by NathanWolf** [comment]
Ah, they need Magic.commands.wand.create to be able to create wands with commands.

Then, hopefully finally, if you've done Magic.commands.wand.wand.name (and the wand you want them to be able to create is called "name") it should work.

**Comment by koalaleader** [comment]
I don't want them to be able to create wands, I want them to spawn in a  certain wand. I've already done Magic.commands.wand.wand.name and it still hasn't worked.

**Comment by NathanWolf** [comment]
By create I mean spawn into the game.

You are trying to let them execute the command "/wand name" (which, consequently won't work- but let's assume your wand has a better name than "name") ... right?

**Comment by koalaleader** [comment]
Thank you so much! It works now.

**Comment by koalaleader** [comment]
Also, after using the /wand OP command, it won't let me switch the spell using Q. It will let me cast the that was on the wand before a /wand saved it.

**Comment by NathanWolf** [comment]
Oh good! You're welcome.

For the new problem- you're saying you "/wand save"'d a wand to a file and then tried to load it and it has no spells? Sorry, I may have that wrong, not sure I'm following.

**Comment by koalaleader** [comment]
Yes.

**Comment by NathanWolf** [comment]
Hm well now I think you've found a bug. After saving the wand, try "/magic load" - I think it should work after that.

Not supposed to be necessary though, I'm taking a closer look now.

**Comment by koalaleader** [comment]
It still doesn't work. The one pre save has 32 spells in the description of the item, but the post save on has no line indicating it has any spells.

**Comment by NathanWolf** [comment]
/wand save testwand
/magic load
/wand testwand

That much worked for me. But there is definitely a bug there so if you can hold out for a fix that may be easier.

**Comment by koalaleader** [comment]
Okay, thanks, it works. Buut... when I try to cast a spell, it just has a noteblock sound, and it isn't the cooldown. Spells like boom work but not superkill. Any thoughts?

**Comment by NathanWolf** [comment]
Probably not enough mana to cast- SuperKill requires 300. Check the lore of each spell and compare with lore on wand- did you give the wand like a ton of mana?

**Comment by koalaleader** [comment]
How would I do that?

**Comment by NathanWolf** [comment]
I mean in-game, like just look at the spells on the wand and the wand itself, the tooltips say mana requirements for spells and max mana for wands.

**Comment by koalaleader** [comment]
How would I give the wand mana?

**Comment by NathanWolf** [comment]
Oh- 
/wand configure mana_max 500
/wand configure mana_regeneration 50

**Comment by NathanWolf** [comment]
Judging by what you're doing you also may wan to add

sp_enabled: false
enable_enchanting: false
enable_crafting: false
enable_automatic_spell_upgrades: false

To plugins/Magic/config.yml

So players can't progress, upgrade or craft wands.

**Comment by NathanWolf** [comment]
That bug with needing to /magic load is fixed now, it's in 6.4 which I just released.

**Comment by koalaleader** [comment]
:D

**Comment by NathanWolf** [comment]
To be on the safe side, I'm thinking you may also want to add this: "-Magic.commands.wand.wand.*", with the -, as a negated permission, to your base permission class.

I'm not sure it's necessary, but it sounded like it might be in #198
