### ISSUE TITLE
elmakers domain is inaccessible

### ISSUE THREAD

**Issue by modom3** [elBukkit/MagicPlugin#2]
Connection to the elmakers TDL and subdomains keep timing out.

**Comment by NathanWolf** [comment]
Sorry, had a fire and a power outage! Should be fixed now- I'll leave this open for now, but if I don't hear from you I'll assume all is well :)

**Comment by modom3** [comment]
Yep. Everything looks back up and operational. Thanks!

On Thu, Sep 3, 2015 at 12:17 PM, Nathan Wolf <notifications@github.com>
wrote:

> Sorry, had a fire and a power outage! Should be fixed now- I'll leave this
> open for now, but if I don't hear from you I'll assume all is well :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elBukkit/MagicPlugin/issues/2#issuecomment-137500169>.
>



-- 

*Markus Odom*Software Engineer
Mobile: 803.257.3593
Email: markusodom11@gmail.com
