### ISSUE TITLE
More like a question... Not really an issue...

### ISSUE THREAD

**Issue by EziodeDragon** [elBukkit/MagicPlugin#20]
Is it possible that I can make an empty hand act like a wand? I want to have it so when you shift+right click with an empty hand it will turn on particles around you and have it so when you right click after that, it opens the spell inv; then you shift+ right click again with an empty hand to turn off the particles and you can't access the spell inventory anymore until you activate it again. Just wondering if this is possible without coding... If it does require coding, how would I do it myself (if possible)?

Edit: I want this to be for me only- Not added to the plugin for everyone unless it already technically is through default configuration without coding

**Comment by NathanWolf** [comment]
No, sorry- Magic is an item-based plugin.

The closest you could do is make an item look "invisible" via a resource pack.
