### ISSUE TITLE
Enchant System. Please help me.

### ISSUE THREAD

**Issue by DanielTenebris** [elBukkit/MagicPlugin#200]
Hello, i need your help. :( 

I need to make improvement sticks only skill points (spellshop), but i dont understand what I'm doing wrong. :(

Spellshop upgrade wand ignore required_spells !.. 
it must improve and give new spells for purchase in spellshop 
He should stick to improve only when the desired spell bought

My Configs:

wands: http://pastebin.com/QfbA0yNP
enchanting: http://pastebin.com/sHtyWn4f

please help :(
version minecraft -- 1.8

**Comment by NathanWolf** [comment]
Have you tried to put your configurations in http://yamllint.com ?

Are there errors in the server logs at startup?

It looks like you have some indentation problems, I suspect these configs aren't loading:

```
    required_spells:
     - missile
      - arrow
      - grenade
      - poison
      - fire
      - wither
```

**Comment by DanielTenebris** [comment]
All configs are valid, 
When I use spellshop it immediately brings me to the new patch, even not allowing to buy spells for the current. I do not understand what is wrong.

It should give the player to buy spells, and then, when he buys all, go to the next wand. And it just improves the parameters of the wand.

Expectation:
Buy All Spell ==> Level UP
Reality:
Click on Npc-spellhop ==> Add stats for wand. This all. :(


It would be great if you could explain to me what I do wrong.

**Comment by NathanWolf** [comment]
You should put the spells you want to show up in the spell shop in "spells" in your paths in enchanting.yml

Same with required_spells- though you may not want that. Those are spells that don't show in the spell shop but are required for leveling up. That does nothing on a wand though.

**Comment by DanielTenebris** [comment]
Thank you, Nathan. This work, but something is not working..
I had a novice wand. I buy 1 spell (grenade) AND wand UPGRADED! Why? 
I use required_spells(in wands.yml)
      - missile
      - arrow
      - grenade 
      - poison
      - fire
      - wither

My wand have 1 spell. (missile) I buy grenade spell and wand upgrade (novice>adept), but not all conditions are met. (spells in required dont learn)

It should be improved only when the player will explore all spell their paths.

**Comment by NathanWolf** [comment]
Hm, I agree - could you please share your updated spell and wand configs?

**Comment by DanielTenebris** [comment]
Okay, thank you.
wands: http://pastebin.com/e73u1ZCt
enchanting: http://pastebin.com/PwyvkfEZ

I use the default configuration of spells. Later I redid spells config, add their own spells. With this I have experience. :)

**Comment by NathanWolf** [comment]
The main issue I see here is the "migrate_to" line on novice, please remove that. That will make a novice wand turn into the default wand, which only has one spell.

Otherwise this seems to work as expected but I do need to clear up some confusion:

1. "spells" on wands mean that wand starts with all of those spells. This is why the novice wand will immediately upgrade, it starts with all of the spells on the "novice" path already.

2. "required_spells" goes on a path, not on a wand. This will make it so you can't advance on that path until you collect some spells, which are not available in the spell shop. My guess is you don't really want that, and you can remove "required_spells" from all of your wand configs.

**Comment by DanielTenebris** [comment]
It seems that it should work, but ..

Wand have only missile.
I buy grenade and wand go to next patch. While still need to buy poison, arrow and more..

I remove migrate_to and required_spells. 

It continues to flip to the next path after the first purchase.

**Comment by NathanWolf** [comment]
When I removed "migrate_to" the issue was fixed for me, the novice wand came with a bunch of spells.

If it's still not working, please share your configs again.

**Comment by DanielTenebris** [comment]
Sorry, it's my fault, I have in the default path of improvement in the novice. I have corrected and it seems to be working as it should :)

Thank you for your help.

**Comment by NathanWolf** [comment]
You're welcome, glad you got it working!
