### ISSUE TITLE
Brooms making 'thud' sound when in flight

### ISSUE THREAD

**Issue by Curtis73** [elBukkit/MagicPlugin#202]
Hey,
Regarding the broom 'flight FX', whenever I am flying a broom I can hear a soft thudding/banging sound in the background - but when I dismount or do /playsound, the sound effects are smooth without anything in the background. Is this just a problem on my side or is anyone else hearing it?

**Comment by NathanWolf** [comment]
That's about the best I can do, you're welcome to take a crack at it if you want. I need a sound engineer :)

The main problem is that sounds are locational when played by the server. If you tried /playsound while flying around you'd notice you only hear it for a moment and then it's gone.

**Comment by Curtis73** [comment]
Okay - I've found that
`        sound: magic.flying
        sound_max_volume: 20000
        sound_min_volume: 1000
        sound_max_pitch: 2
        sound_min_pitch: 0.5`
Pretty much masks the sound

**Comment by NathanWolf** [comment]
That seems like an insane volume level... but glad you found something you're happy with!

**Comment by Curtis73** [comment]
Thanks!
One more thing, though... Whenever I go to the wand enchant NPC and select the level 2 broom - the GUI just closes and doesn't say anything.

**Comment by NathanWolf** [comment]
Er, there shouldn't be a level 2 room in the enchant NPC ... does that pop up when you use your broom with it?

Brooms upgrade on use, there's no GUI or enchanting for that. Or shouldn't be.

**Comment by Curtis73** [comment]
Yeah, pops up whilst holding broom.

**Comment by NathanWolf** [comment]
I'm not seeing that in the default or potter configs- do you have spellshop overridden to show_upgrades or anything like that?

**Comment by Curtis73** [comment]
I have auto_upgrade: true in my spellshop?

**Comment by NathanWolf** [comment]
No, it's no that- it'd be "show_upgrades: true" but I've never actually used it myself, I think @dumptruckman  added it.

Do you see that for wands, like does Stupefy Level 2, 3, etc show up there?

**Comment by NathanWolf** [comment]
Do you maybe have the old broom path in your enchanting.yml? 

Not sure that'd do it either but interested to figure this out.

**Comment by Curtis73** [comment]
I don't see any broom enchanting paths in my enchanting.yml
There's not a show_upgrades value

Only one spell upgrade shows at the same time (if that makes sense)

**Comment by NathanWolf** [comment]
Hm, well I did just notice I accidentally left in the old Power progression to brooms in the potter configs.

But that still shouldn't (and doesn't seem to, when I test it) make the spellshop GUI show up. 

Very mysterious - well if you want and are able to share your wand, path and spell configs I can try it out myself. Otherwise I'm really not sure what's up with this.

**Comment by Curtis73** [comment]
hmm...
I don't think it really matters that much as I don't see it causing very much damage ~ Still, Thanks for your help on everything!
