### ISSUE TITLE
No broom levels in Potter Configs?

### ISSUE THREAD

**Issue by Curtis73** [elBukkit/MagicPlugin#203]
Hey there,
I've just noticed that the broom levels aren't working on the potter configs. On default, there is broom|2, broom|3 etc. Is there a reason or should I just

broom|2:
            enabled:true
?

Thanks!

**Comment by NathanWolf** [comment]
Oops, I forgot levels don't auto-inherit :(

yes, enable the extra levels- I'll do it in my configs too. Wish I had noticed before 6.6 sorry!

**Comment by Curtis73** [comment]
Okay - Thanks!
