### ISSUE TITLE
I am looking for a 1.11.2 compatible shopping plugin for selling spells

### ISSUE THREAD

**Issue by dragonesque7** [elBukkit/MagicPlugin#204]
Hi,
Could you please help? :) How can I sell spells on my Minecraft 1.11.2 Spigot server?
Best Regards,
Sylwia

**Comment by NathanWolf** [comment]
You can use Citizens to set up magic shops:

https://github.com/elBukkit/MagicPlugin/wiki/NPC

Or just use the built in spell shop which offers ranked progression. You can easily change it to use currency instead of spell points if you want.

**Comment by dragonesque7** [comment]
Thank you very much for fast and helpful reply! 👍
