### ISSUE TITLE
Dementors

### ISSUE THREAD

**Issue by iKezzaUK** [elBukkit/MagicPlugin#205]
Hey Nathan!
I have configured magic for harry potter, But i was wondering how I would make a dementor?
Any Ideas?

**Comment by NathanWolf** [comment]
Hm I thought I had one in the configs but I guess not.

You could make a magic mob wither that casts spells... I'll add one when I get a chance.

**Comment by iKezzaUK** [comment]
OK thanks, Magic mob is one of your plugins?

**Comment by iKezzaUK** [comment]
How do I make it so it can cast spells?

**Comment by NathanWolf** [comment]
Check on the warlock in the default configs

**Comment by NathanWolf** [comment]
There is now a basic dementor mob in the potter configs.
