### ISSUE TITLE
Ocarina Duplication Bug

### ISSUE THREAD

**Issue by Curtis73** [elBukkit/MagicPlugin#206]
Hey,
One of my players noticed that if you hold an ocarina, open the spell inventory and press Q or F it throws out an extra ocarina.

**Comment by NathanWolf** [comment]
Whoops, thanks I'll take a look at that!

I think I meant for the ocarina to be a droppable, but this sounds like a general issue I need to look at.

**Comment by NathanWolf** [comment]
Fixed in latest dev build, targeted for 6.7

Thanks for the head's up!

**Comment by Curtis73** [comment]
You're welcome :)
