### ISSUE TITLE
Suggestion about dual-wielding

### ISSUE THREAD

**Issue by Blamo27** [elBukkit/MagicPlugin#210]
Hello !

As you may know, we have a 1.8 server running Magic for quite some time now. We are planning on updating, however there is a feature that completely breaks down the PvP and PvE as we want it : the dual wielding of wands !

It's a cool feature without doubt, however we don't want it to work that way on our server : we want the wand to be a real weapon like the sword, and having two at the same time is simply too overpowered (especially since the mana is not shared between the wands, which means the player can fire twice as much spells as before, but in the same time). 

Considering this, it would be really nice if we had something in the config.yml to disable completely wands in off hand (they can't fire spells, for instance). Or at least something so only the mana of the first wand is used, or something that divides the mana of both wands.

**Comment by NathanWolf** [comment]
You can set "allow_offhand_casting: false" in config.yml :)

In 7.0 there will be a shared mana pool, but I can't really say when that's going to be ready.

**Comment by Blamo27** [comment]
Oh you're right, sorry, I did check the config though, but I didn't see that option somehow. 
Thanks, that's all I needed for now, but I look forward 7.0 features on that matter !
