### ISSUE TITLE
Unable to Open Wand Inv

### ISSUE THREAD

**Issue by lBerZerKl** [elBukkit/MagicPlugin#212]
I am unable to open the wand inv on both the test server and my own server. Any advice?

**Comment by NathanWolf** [comment]
Test server, like mine.elmakers.com ? You are pressing the Q button, right?

If you mean your own servers and you have custom wand configs, there are some properties you may need to add, see MIGRATION.md for details.

**Comment by NathanWolf** [comment]
Specifically here, if it's a config issue:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/MIGRATION.md#65

**Comment by lBerZerKl** [comment]
Thanks! it works now
