### ISSUE TITLE
Wands stopped working after update

### ISSUE THREAD

**Issue by meneertimmy** [elBukkit/MagicPlugin#213]
I have fully configured the magic plugin but since I updated the plugin not any of the wands work. I don't know how this happened. I get these errors for every single spell. I hope someone could help me because I'm using the plugin quite a time but never had any issues like this

11.03 16:45:45 [Server] WARN Unknown or disabled spell prerequisite missile in path battle, ignoring
11.03 16:45:45 [Server] WARN Unknown or disabled spell prerequisite cure in path battle, ignoring
11.03 16:45:45 [Server] WARN Unknown or disabled spell prerequisite fireball in path battle, ignoring
11.03 16:45:45 [Server] WARN Unknown or disabled spell prerequisite push in path battle, ignoring
11.03 16:45:45 [Server] WARN Unknown or disabled spell prerequisite pull in path battle, ignoring
11.03 16:45:45 [Server] WARN Unknown or disabled spell prerequisite blind in path battle, ignoring
11.03 16:45:45 [Server] WARN Unknown or disabled spell prerequisite reflect in path battle, ignoring

**Comment by NathanWolf** [comment]
Could you please post the full server log via pastebin? I suspect there are errors before these?

Seeing your config.yml would help too.

It looks like it's failing to load configs, or else you have the default spells disabled?

**Comment by NathanWolf** [comment]
Hm if all there is are those warnings everything should still work, but I'm guessing you maybe missed this migration step?

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/MIGRATION.md#66

enchanting.yml changes to paths.yml

And if you have load_default_enchanting in config.yml you need to change it to load_default_paths

That's maybe not it, but definitely would cause those warnings- they are just warnings though, so unless something else is in your logs those shouldn't be causing problems.

**Comment by meneertimmy** [comment]
there are no other errors, but i removed the spells config and now the spells work but i couldn't open my spells inventory so i removed the other magic files and started it up but i still can use the spells on the wands but i can't open the spells inventory

**Comment by NathanWolf** [comment]
Read through that migration log, there are probably some things you need to add to your wand configs if they are completely custom- see the section on mode, left_click, etc

Very important to check the migration log when updating, I try not to change things but sometimes I have to.

**Comment by NathanWolf** [comment]
Please let me know if those config changes fix your problems, if not then something else may be wrong.

**Comment by meneertimmy** [comment]
I deleted all the configs and the plugin itself. Restarted the server but it didn't work. I tried an older version of the plugin too but that also didn't work. I can't find any other errors so I don't know what could have happened.

**Comment by NathanWolf** [comment]
That sounds really weird, this definitely looks like a config issue. Could you please hastebin your server logs here so I can take a look?

**Comment by meneertimmy** [comment]
http://pastebin.com/719cyj95

**Comment by NathanWolf** [comment]
Oh hm, so the errors are gone? But the plugin still isn't working? Does that include commands?

**Comment by meneertimmy** [comment]
No, everything works except for opening the wand inventory. So the spells work to but i can't scroll through the spells.

**Comment by NathanWolf** [comment]
And you definitely don't have anything in plugins/Magic/config.yml, no custom wands?

I'm pretty sure that build isn't broken (I could be wrong)- if you do /wand describe while holding a wand, does it show a "mode" and "drop" property in the wand template parameters?

And just to be 100% clear, you are using the drop (Q) button to open the wand inventory, right?

**Comment by meneertimmy** [comment]
Nope, I have always used right mouse click xD. This did always work last time i tried the Q button didn't do anything too so i think it was something in my configs. But thank you! Everything is working now i just have to use the Q butten xD I feel so stupid haha but thank you!

**Comment by NathanWolf** [comment]
Ah, whoops! That changed a long while ago, around 1.9, to support offhand items.

You can change it back in your configs pretty easily, it'd be like this:

```
base_wand:
  right_click: toggle
  drop: none
```

**Comment by meneertimmy** [comment]
Is it normal that the spell icons are changed? It doesn't have that easy look anymore

**Comment by NathanWolf** [comment]
Not sure what you mean. Unless you're using the potter configs the icons haven't really changed.

**Comment by meneertimmy** [comment]
I am using the potter configs. I think the new icons are not looking very clear.

**Comment by NathanWolf** [comment]
Oh- yeah they did change in the potter configs. Someone donated 32x32 high-res icons specifically made for those configs.

If you don't want them, you can just use the survival configs. Add this to your Magic/config.yml

```
default_resource_pack: "https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-RP-6-4.zip"
```
