### ISSUE TITLE
Cannot show wand inventory on 1.11.2

### ISSUE THREAD

**Issue by alexchandel** [elBukkit/MagicPlugin#214]
The only server plugins are WorldEdit, OpenInv, SuperVanish, ExtraHardMode, and Magic 6.8. There are no client plugins.

Right-clicking with a wand does nothing but lower the wand briefly the first time. No inventory is shown.

Is Magic incompatible with these plugins, or with 1.11.2?

Edit: Magic 6.8 is the latest version on https://dev.bukkit.org/projects/magic.
Edit 2: Testing build 2000 from the Jenkins server has the same problem.
Edit 3: Disabling every plugin but World Edit and Magic 7.0-snapshot (build 2000) has the same problem.

Is wand inventory broken? Am I doing something wrong? An example wand the inventory is failing for is a `Magic Missile (Wand)` at `Beginner Magic Wand` bound to 3 spells.

**Comment by NathanWolf** [comment]
The Q button opens the wand inventory, not right-click. The wand should tell you this in chat when you get your 2nd spell.

Let me know if that's not the problem.

**Comment by alexchandel** [comment]
@NathanWolf 

Aha. Actually, I couldn't find anywhere in the wiki documentation how to open the wand inventory, and [this documentation](https://dev.bukkit.org/projects/magic/pages/admin-instructions) actually says "right-click."

**Comment by NathanWolf** [comment]
I probably need to delete all of the dev.bukkit pages they are all outdated.

Wand mechanics are configurable though, it's easy to switch back to right click if you want. I changed to Q in 1.9 so wands would work with offhand items.
