### ISSUE TITLE
Troubles spawning wither skeletons

### ISSUE THREAD

**Issue by Blamo27** [elBukkit/MagicPlugin#215]
Hello,

Since we updated from 1.8 to 1.11 we can't seem to be able to spawn wither-skeleton via /mmob. We tried several changes in the configuration of the mob, but it just doesn't work, it spawns a regular skeleton and displays "an internal error occured while attempting to perform this command" in the chat. 
We found nothing new on this matter on the wiki. Could you please tell us how to spawn customized wither skeletons with /mmob ?

Thank you

**Comment by NathanWolf** [comment]
This was a spigot API / MC change. Wither skeletons are no longer variants of skeletons, they are their own entity type. Try type: wither_skeleton

**Comment by Blamo27** [comment]
That worked, thank you !
