### ISSUE TITLE
Can i change spell's color ?

### ISSUE THREAD

**Issue by odyszey** [elBukkit/MagicPlugin#216]
like that head,I don't know how to change the spell's color.Is that possible to change the spell's color ?

**Comment by NathanWolf** [comment]
Yeah, of course. It can be different for every spell, so you have to just look at the configs of whatever spell you want to change. If it's using redstone or mob_spell particles, there's usually a color parameter somewhere.

If it's using other particles then you can't change the color of those, but you can change what particle it uses, or change it to redstone/mob_spell and set a color.

**Comment by odyszey** [comment]
Thank you 👍
