### ISSUE TITLE
Broomstick duplication

### ISSUE THREAD

**Issue by downboy** [elBukkit/MagicPlugin#217]
when you have a wand in your main hand and a broomstick in you off hand. The moment when you active the broomstick your wand will be removed and when you dismount it you get a broomstick but not your wand. The broomstick in your off hand still be there.

**Comment by NathanWolf** [comment]
Eek, thanks for the report- I'll try and fix that ASAP.

**Comment by NathanWolf** [comment]
This is fixed in 6.9.2 (latest dev build)- thanks!
