### ISSUE TITLE
How to recovery wand (With Donaters)

### ISSUE THREAD

**Issue by DanielTenebris** [elBukkit/MagicPlugin#218]
How can you give donors the opportunity to restore their wand with full progress when it is lost?

**Comment by NathanWolf** [comment]
Why is their wand getting lost?

You can give the permission: Magic.commands.wand.restore

Then they can use /wand restore.

**Comment by DanielTenebris** [comment]
command /clear <name>

Thank.

**Comment by DanielTenebris** [comment]
How best to protect players from losing a wand?

**Comment by NathanWolf** [comment]
Well don't run /clear on them, I guess XD

Giving them /wand restore should work, then.
