### ISSUE TITLE
Possible to check if player has an spell?

### ISSUE THREAD

**Issue by ImranDoet** [elBukkit/MagicPlugin#219]
Title says it.

**Comment by NathanWolf** [comment]
Currently spells are stored by wands, not players. I'm aiming to change this in 7.0

For now you have to check a player's Wand, not the player. This can be done via the API, e.g. api.getMage().getActiveWand().hasSpell("blink");

**Comment by NathanWolf** [comment]
You can now use Mage.hasSpell
