### ISSUE TITLE
Changing the wands

### ISSUE THREAD

**Issue by RaulH22** [elBukkit/MagicPlugin#220]
Hi, is it possible for the player to have the same spells on any wand ??
Thanks!!!

**Comment by NathanWolf** [comment]
Not yet. This is the goal of 7.0, though.

**Comment by ShadyPaws** [comment]
Hey, So I think I found a way to fix this issue for you from my perspective. I was trying to do something like this for my server when I figured out
**/wandp ShadyCarpet configure icon wood_hoe:2**
What it's basically saying is to reconfigure your wand to that design or wand template

**Comment by NathanWolf** [comment]
Ah, yeah that's an easy way. They still can't have more than item share the same set of spells, but if you're happy with that for now that works for me :)
