### ISSUE TITLE
Changes in resourcepack?

### ISSUE THREAD

**Issue by PanCakev2** [elBukkit/MagicPlugin#223]
Hi, 
i'd like change a few icons, logo and description of official txt for this plugin - can I? And if i have a demo version, and i use this for medium server (20-50 players)  (if i will have a money for full version, i buy it - i promise!), will you be angry for me? This plugin is wonderful - i'm creating a polish version (translate).

**Comment by NathanWolf** [comment]
It's no problem at all - the plugin is free and open, there is no full version :)

If you'd like to share your Polish translation, I'd love to add it to the set of localizations I have, but that's entirely up to you.
