### ISSUE TITLE
Servercrash with spell

### ISSUE THREAD

**Issue by downboy** [elBukkit/MagicPlugin#225]
Hello,

When players do the spell "Air Scooter", they can fly but my server freeze and then crash after 20 seconds. there is no error in console. 
I have it disabled now, but can you look at it??

greetings

**Comment by NathanWolf** [comment]
Yikes, yes I'll look at that right away. Is this the air scooter from the default configs, or a custom one you've made?

**Comment by downboy** [comment]
its the air scooter from the default config. but will try the new magic 6.9.7

**Comment by NathanWolf** [comment]
Yes, I just release a fix- sorry meant to come tell you. 

Really sorry about that- it was applying infinite velocity on crash :(

Should be all good in latest release.
