### ISSUE TITLE
Vehicles able to climb one block high hills

### ISSUE THREAD

**Issue by Prowco** [elBukkit/MagicPlugin#226]
Please add more models, and make the cars can jump one block bc some cities have one block up in the streets and one question how i can spawn your mobs automatic in the world? for example polices?

**Comment by NathanWolf** [comment]
In case it's not 100% clear from the Model 3, my art skills are not really up to this task XD

The Ferrari was donated to me, though I still did not do a great job of importing it. Ideally players would sit inside the cars, but that didn't really work out.

So anyway this is not really up to me, we'll have to see if I come across any more cars.

This is what I use on my Chicago server to spawn cars randomly:

https://github.com/elBukkit/MagicWorlds/blob/master/src/main/resources/examples/mixins/war.yml

You'll need the MagicWorlds plugin.

**Comment by NathanWolf** [comment]
Oops, I meant to leave this open to try and get to this request one day:

> make the cars can jump one block bc some cities have one block up in the streets

**Comment by NathanWolf** [comment]
This will work in 7.5.1 when released, it is part of the current dev build. I may try to make it a little smoother before release, I'll leave this open until it's available in a released build.
