### ISSUE TITLE
Question regarding the "Breach" spell

### ISSUE THREAD

**Issue by Makverus** [elBukkit/MagicPlugin#228]
Hi! First of all - great mod, really enjoying it on my private server with friends. 
The question: I'm not sure how Breach works. Looks like it can breach some blocks, but can't others? For example, it's not breaching stone bricks for me. Is it a feature? Can it be customized?
Thanks in advance for the answer!)

**Comment by NathanWolf** [comment]
Cool, glad you figured it out!
