### ISSUE TITLE
Sentinel NPC Integration

### ISSUE THREAD

**Issue by jezzajacobs** [elBukkit/MagicPlugin#229]
Is there a way to make NPC's from the citizens plugin cast spells to attack, like using the sentinel trait but with magic instead of normal weapons?

**Comment by NathanWolf** [comment]
No, I'm afraid not. I can keep this open as a feature request if you like.

Your best bet in the meantime is to use Magic Mobs (see wiki) or MythicMobs, though the last time I tried that their command skill didn't seem to work anymore, so maybe not.

**Comment by jezzajacobs** [comment]
Yes that'd be good thank you :)

**Comment by NathanWolf** [comment]
Sentinel NPCs can cast spells in the current dev build, slated to be released as 7.5.3

.. Didn't quite make it in under a year, but better late then never, amirite?
