### ISSUE TITLE
Locking a wand at some progression level. 

### ISSUE THREAD

**Issue by Makverus** [elBukkit/MagicPlugin#230]
Hello! It's me again) Is there a way to create a wand with which a player **can** progress, but limit that progress, let's say, at student? So it basically becomes locked when all the student spells are learnt? 
And also - is there a way to make some spells admin-only?

Thank you!

**Comment by NathanWolf** [comment]
Hm, no there's no way to do that at a wand level, I guess you could copy the paths and rename them (like how the Master Sword works) but just stop it at student.

You can remove permissions for certain spells, give you default group "-Magic.cast.backup" then give your admin group "Magic.cast.backup", for instance.

**Comment by Makverus** [comment]
Thanks a lot! I'll look into that!

**Comment by NathanWolf** [comment]
Did that work out for you?

**Comment by Makverus** [comment]
I went the "WhoGivesADamn" path and let my friends do whatever they like to)) I decided that would be more fun than restricting them. But thanks for asking)

**Comment by NathanWolf** [comment]
Ha, ok then! :)
