### ISSUE TITLE
XP mana bar does not go down when the wand is put in your off-hand.

### ISSUE THREAD

**Issue by mibby** [elBukkit/MagicPlugin#234]
Instead, the xp bar goes up, then shoots back down when using a wand in your offhand slot.

**Comment by NathanWolf** [comment]
Correct. It briefly shows you mana when you cast, but otherwise shows XP.

This is by design.

**Comment by NathanWolf** [comment]
Well, I should say it's by design for now. Maybe in 7.0 once wands can share mana it'd make sense for the offhand wand to get full XP bar status, but for now I think it just gets confusing.
