### ISSUE TITLE
Not able to equip a magic hat.

### ISSUE THREAD

**Issue by mibby** [elBukkit/MagicPlugin#237]
https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/resource-pack/default/assets/minecraft/models/item/custom/magic_hat.json#L587

Are you suppose to be able to equip the magic hat? As right clicking it only produces a cloud of particles, not wearing it.

**Comment by NathanWolf** [comment]
Look up and right-click.

**Comment by mibby** [comment]
Oh! Thanks, didn't realize you had to look straight up to equip!
