### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ahrigumi** [elBukkit/MagicPlugin#238]
Hi ! ,
First sorry for my english, is not my primary language :)
1.
I have 2 question. I want to use this amazing plugin "magic" on my spanish server, so i was translating "message.yml" and I had the first problem. A few sentences are translated and others sentences not. For example.. 
![2](https://user-images.githubusercontent.com/29241452/26865360-98658ea6-4b5c-11e7-87c0-a422e28542cb.jpg)
![1](https://user-images.githubusercontent.com/29241452/26865365-9c54c61c-4b5c-11e7-86a8-8ea6504f668b.jpg)
How can i translate the plugin correctly?

2
I want to used AC to buy spells , but.. how can i get "Ac" with a command? , i want to include in my server "classes" and i need it jeje

Regards!

**Comment by NathanWolf** [comment]
Hi! If you have not already, you should start with these files:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/examples/localizations/messages.ES.yml

Or this one:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/examples/localizations/messages.ES2.yml

Neither are complete though. To see all of the messages available for translation, check **plugins/Magic/defaults/messages.defaults.yml**

Search for text in there you want to change, like "You must be holding". Then copy that into your plugins/Magic/messages.yml and change it. Or copy that whole file and start editing- it'll be a little hard to merge the two together, though- the files I have are very old and I'm sure not complete.

As for AC- Assuming you got the classes plugin from Kedric, you should ask him about that. Unfortunately what he did was release a plugin he made for another server, without having the actual AC system. AC is a feature of Potterworld's private core plugin. You can ask Kedric, but you're not the first person to come to me with this, and I feel like you may have gotten ripped off.

**Comment by Ahrigumi** [comment]
Hi! , thank you very much for the answer! 
I will use the messages from the complete file "messages.defaults.yml".

Unfortunately, I don't have the "classes plugin from Kedric", I have a very simple plugin about the classes.. but it's not enough :/

**Comment by NathanWolf** [comment]
Oh I see - well your classes plugin would need to integrate with magic to give SP (which you could rename to AC if you wanted)

That is assuming you want to be able to spend AC to buy spells

Otherwise I'm not sure what your classes plugin is doing - it gives AC already? What can players do with that AC?

**Comment by Ahrigumi** [comment]
I understand.
It's a very basic plugin, it is really made for the Role play , it has not incorporated a type of obtaining of points. 
I've tried modifying the code to implement it, but it's a little difficult for me.

**Comment by NathanWolf** [comment]
If you can have that plugin issue commands, then it's pretty easy. "/mgive <player> sp <amount>" will give players Magic spell points.

You can rename these in all in-game text to AC or whatever you want, and they can then be used with the builtin spellshop to learn new spells.

**Comment by Ahrigumi** [comment]
But with your method, I should enter in the "magic" code, not?

**Comment by NathanWolf** [comment]
Not if it can just run commands, if that's easier for you. Then you don't need to use the Magic API

**Comment by Ahrigumi** [comment]
Ah!, I understand you right now.
Then I can use SP as AC (renamed), right?

**Comment by NathanWolf** [comment]
That's right!

**Comment by Ahrigumi** [comment]
Thank you very much! to finish... where can i rename SP ?

**Comment by NathanWolf** [comment]
I think this would cover it, goes in messages.yml:

```
sp:
    name: "&e$amount &6Academic Credits"
    description: Will be absorbed by your wand

costs:
    sp_amount: $amount AC
    sp: Academic Credits
```

**Comment by Ahrigumi** [comment]
Thank you very much! I have translate 95% and Implemented AC (SP). but i have a little questions.. 
![asddd](https://user-images.githubusercontent.com/29241452/26924185-fa4f6388-4c44-11e7-8387-0d48e08545c9.jpg)
I have this error and i cant use commands in game, dont know what is happend..
![asd2](https://user-images.githubusercontent.com/29241452/26924201-10169114-4c45-11e7-9e56-6ed68f647a5d.jpg)
When i use the commad "/mgive sp" i can look the hotbar but not the chat message 
![asd](https://user-images.githubusercontent.com/29241452/26924226-34a75c66-4c45-11e7-8c29-ce7c790f5400.jpg)
and the last, i didnt see in "message.yml" ,"spells.yml and "wand.yml" how to translate "first year,etc" and the caterogies of spells.

**Comment by NathanWolf** [comment]
Most messages go to the action bar now, not chat- keeps things uncluttered. You can change that by changing the prefix used in config.yml if you want:

# A prefix to use for cast messages
# This and the above (and any message in messages.yml) support two special prefixes:
# a: send as an action bar message
# t: send as a title (with default fade in/out timing)
cast_message_prefix: "a:&5&o"

Just remove the "a:" to send it back to chat.

All of the Harry Potter specific messages will be in the harry potter configs, here:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/examples/potter/messages.yml

**Comment by Ahrigumi** [comment]
Perfect! Thanks a lot, I have translated all.
I tryed to disable wand upgrade by enchanting table with "enable_enchanting: false" in "config.ym" but nothing happens. How can i solve this?

**Comment by NathanWolf** [comment]
For that you'd want to put this in config.yml:

```
# Disable the enchantment table showing the spell shop or upgrades
enchant_block: ""
```

That is assuming you still want the SP system, spell shop and everything- just want to turn off the enchantment table functionality.

**Comment by Ahrigumi** [comment]
It works perfectly!! About the SP system, are available spells that when cast, you earn x sp, how can I disable this?

**Comment by NathanWolf** [comment]
That one would be `sp_earn_enabled: false` in config.yml

**Comment by Ahrigumi** [comment]
Thank you very much! , to finish..
Any link where I can find all the  variables for "config.yml" ?

**Comment by NathanWolf** [comment]
You can look on your server, in plugins/Magic/defaults/config.defaults.yml

Or this folder:

https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/main/resources/defaults/config

**Comment by Ahrigumi** [comment]
So nice! , Thank you very much Nathan for all :)

**Comment by NathanWolf** [comment]
You're welcome!
