### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Xemeriys** [elBukkit/MagicPlugin#239]
Hello I created this to add spell that gives the night vision effect, is it right?

```
lumosio:
    icon: diamond_axe
    icon_disabled: diamond_hoe
    icon_url: http://textures.minecraft.net/texture/4abfe52d50f710f4103bc650b5e972d49832ea419841d9fa24e16ce617c716
    actions:
        cast:
        -  class: PotionEffects
    parameters:
        target: self
        duration: 20000
        cooldown: 10000
		effect_nightvision

**Comment by NathanWolf** [comment]
effect_nightvision: 1

Needs the amplifier after a colon

Otherwise, assuming it's indented correctly (use the <> button above when posting code next time, please) I think that will work.

**Comment by Xemeriys** [comment]
Thanks so much and sorry
Last think, I set 20 seconds as duration, so will the night vision effect last 20 second?

**Comment by NathanWolf** [comment]
Yup, correct.

**Comment by NathanWolf** [comment]
If you want some effects on it you need to add an effects block- look at some of the other spells (like Boon) for examples

**Comment by Xemeriys** [comment]
Ok, thanks again! Your plugin is amazing? :)
