### ISSUE TITLE
Problem solved

### ISSUE THREAD

**Issue by Alakazamba03** [elBukkit/MagicPlugin#240]
Problem solved

**Comment by NathanWolf** [comment]
Can you paste the spell configs? You've checked the server log for parse errors or other errors, right?

**Comment by Xemeriys** [comment]
May I send you them by emails? I'd prefer to keep them private

**Comment by NathanWolf** [comment]
Sure, of course. nathan 4t elmakers d0t com

**Comment by Xemeriys** [comment]
Sorry? May you wirte it again,please?

**Comment by NathanWolf** [comment]
Do you have a spigotmc account? If so, please PM me there. 

https://www.spigotmc.org/

**Comment by Xemeriys** [comment]
Okie

**Comment by Xemeriys** [comment]
Done
