### ISSUE TITLE
How to disable crafting broomstick ?

### ISSUE THREAD

**Issue by Kuroyabumozu** [elBukkit/MagicPlugin#246]
as title , I can't set  "enabled: false" wiith BroomStick

here is what I set in crafting.yml
https://paste.ubuntu.com/24947116/

**Comment by NathanWolf** [comment]
That looks right to me. You have that in plugins/Magic/crafting.yml ?

**Comment by NathanWolf** [comment]
It also takes a full server restart for crafting changes to take effect.
