### ISSUE TITLE
Creating a spell that runs a command

### ISSUE THREAD

**Issue by khodgson2001** [elBukkit/MagicPlugin#247]
Hi Nathan - 
Could you leave a template in the comments for creating a spell that runs a command (i.e. one that does the command /reload (or something along those lines))
Thanks,
Kieran

**Comment by NathanWolf** [comment]
That kind of stuff is probably a better fit for the wiki. 

https://github.com/elBukkit/MagicPlugin/wiki/Command#examples

**Comment by khodgson2001** [comment]
Thank you :D Looked through the wiki and must of missed that
