### ISSUE TITLE
Wand Texture pack / Brooms on head?

### ISSUE THREAD

**Issue by BelleGoBelle** [elBukkit/MagicPlugin#249]
Hi! So I currently have the newest version of Magic and the newest version of the texture pack.

But I realized that rooms and wands are on / above player's heads.

![2017-07-18_14 37 46](https://user-images.githubusercontent.com/26444209/28334150-3ad3a9ee-6bc8-11e7-9bb6-4ed89be88bd1.png)

![2017-07-18_14 49 40](https://user-images.githubusercontent.com/26444209/28334198-6787c614-6bc8-11e7-981d-a456220ec107.png)

Is there a way to fix this?

**Comment by NathanWolf** [comment]
Are you sure you have the latest RP? That was fixed in the RP itself, which should be used automatically. If you have downloaded it or are linking to it yourself (as in not using Magic's built-in RP features) you may be out of date. 

This change was made quite a while ago.

**Comment by BelleGoBelle** [comment]
I looked on the original Magic Plugin spigot page, There was a link there for the resource pack.

I downloaded it, it wasn't the 1.8 version tho.

**Comment by NathanWolf** [comment]
You need to look at the configs of the plugin version you're using to get the right resource pack. Or just leave it all alone and let the server handle it, then you don't need to worry about updating.

If you really need to download it for some reason, check your plugins/Magic/defaults/config.defaults.yml file for the right URL, or look here:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/defaults/config/rp.yml

**Comment by BelleGoBelle** [comment]
Alright, Next time I'll check, Thank you!
