### ISSUE TITLE
Commands wont run/work

### ISSUE THREAD

**Issue by Triliton** [elBukkit/MagicPlugin#25]
Hello,

ive read an earlier post about commands showing, but not working.
I do however have the same. But i cant see anything in the log that has errors,
I have spigot 1.8 and Magic 5.4

Is there any compatibillity issue list?

**Comment by NathanWolf** [comment]
You will need Spigot 1.8.8 or higher, otherwise Magic 5.3.x or lower.

There should be some errors in your startup logs in any case, though. If the versions aren't the issue, please pastebin your logs here?

**Comment by Triliton** [comment]
Hello, thanx for answering me. I have now 5.3.3 installed, but still same problem. I cant craft anything either if i try blazerod pluss netherstar. Also command comes up /magic but nothing else happens.

Heres a log

0.01 21:16:43 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
30.01 21:16:43 [Server] WARN at com.dre.brewery.filedata.UpdateChecker.run(UpdateChecker.java:51)
30.01 21:16:43 [Server] WARN at com.dre.brewery.filedata.UpdateChecker.query(UpdateChecker.java:84)
30.01 21:16:43 [Server] WARN at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
30.01 21:16:43 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
30.01 21:16:43 [Server] WARN java.io.IOException: Server returned HTTP response code: 504 for URL: https://api.curseforge.com/servermods/files?projectIds=68006
30.01 21:16:43 [Server] INFO ERROR: Could not check for Updates. This error can probably be ignored
30.01 21:16:39 [Server] INFO Full render of map 'flat' of 'World' in progress - 41100 tiles rendered (100.14 msec/tile, 53.50 msec per render)
30.01 21:16:30 [Server] INFO Full render of map 'flat' of 'World' in progress - 41000 tiles rendered (100.16 msec/tile, 55.56 msec per render)
30.01 21:16:20 [Server] INFO Full render of map 'flat' of 'World' in progress - 40900 tiles rendered (100.17 msec/tile, 60.14 msec per render)
30.01 21:16:11 [Server] INFO Full render of map 'flat' of 'World' in progress - 40800 tiles rendered (100.19 msec/tile, 75.58 msec per render)
30.01 21:15:59 [Server] INFO Full render of map 'flat' of 'World' in progress - 40700 tiles rendered (100.15 msec/tile, 195.79 msec per render)
30.01 21:15:20 [Server] INFO Loading default resource pack
30.01 21:15:19 [Server] WARN Update at: http://dev.bukkit.org/server-mods/vault
30.01 21:15:19 [Server] WARN Stable Version: 1.5.6 is out! You are still running version: 1.5.3
30.01 21:15:19 [Server] INFO Checking for Updates ... 
30.01 21:15:19 [Server] INFO WorldGuard plugin detected on server.
30.01 21:15:19 [Server] INFO Loaded 230 NPCs.
30.01 21:15:18 [Server] WARN No permission groups found.  the GROUP target will not function.
30.01 21:15:18 [Server] INFO **********************************************************
30.01 21:15:18 [Server] INFO [HerobrineAI] No problems detected.
30.01 21:15:18 [Server] INFO **********************************************************
30.01 21:15:17 [Server] INFO Slimefun is up to date!
30.01 21:15:17 [Server] INFO CS-CoreLib is up to date!
30.01 21:15:17 [Server] INFO Failed to check for a update on spigot. Now checking bukkit..
30.01 21:15:16 [Server] INFO ExoticGarden is up to date!
30.01 21:15:16 [Server] INFO ##########################################################
30.01 21:15:16 [Server] INFO ( 332 Items from Slimefun, 215 Items from Addons )
30.01 21:15:16 [Server] INFO Successfully loaded 547 Items (152 Researches)
30.01 21:15:16 [Server] INFO ###################### - Slimefun - ######################
30.01 21:15:16 [Server] INFO This may take a while...
30.01 21:15:16 [Server] INFO Saving Blocks for World "world_herobrine_graveyard"
30.01 21:15:16 [Server] INFO This may take a while...
30.01 21:15:16 [Server] INFO Saving Blocks for World "Varlan"
30.01 21:15:16 [Server] INFO This may take a while...
30.01 21:15:16 [Server] INFO Saving Blocks for World "Twilight"
30.01 21:15:16 [Server] INFO This may take a while...
30.01 21:15:16 [Server] INFO Saving Blocks for World "Pyro"
30.01 21:15:16 [Server] INFO This may take a while...
30.01 21:15:16 [Server] INFO Saving Blocks for World "Phantasya"
30.01 21:15:16 [Server] INFO This may take a while...
30.01 21:15:16 [Server] INFO Saving Blocks for World "Phalon"
30.01 21:15:16 [Server] INFO This may take a while...
30.01 21:15:16 [Server] INFO Saving Blocks for World "Loroth"
30.01 21:15:16 [Server] INFO This may take a while...
30.01 21:15:16 [Server] INFO Saving Blocks for World "Lithos"
30.01 21:15:16 [Server] INFO This may take a while...
30.01 21:15:16 [Server] INFO Saving Blocks for World "Duune"
30.01 21:15:16 [Server] INFO This may take a while...
30.01 21:15:16 [Server] INFO Saving Blocks for World "World_the_end"
30.01 21:15:16 [Server] INFO This may take a while...
30.01 21:15:16 [Server] INFO Saving Blocks for World "World_nether"
30.01 21:15:16 [Server] INFO This may take a while...
30.01 21:15:16 [Server] INFO Saving Blocks for World "World"
30.01 21:15:16 [Server] INFO Auto-Saving Data... (Next Auto-Save: 10m)
30.01 21:15:16 [Server] Startup Done (30.376s)! For help, type "help" or "?"
30.01 21:15:16 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
30.01 21:15:16 [Server] INFO Enabling ExoticGarden v1.5
30.01 21:15:16 [Server] INFO Finished!
30.01 21:15:15 [Server] INFO Loaded a total of 0 Blocks for World "world_herobrine_graveyard"
30.01 21:15:15 [Server] INFO Loading Blocks... 100% (FINISHED - 0ms)
30.01 21:15:15 [Server] INFO This may take a long time...
30.01 21:15:15 [Server] INFO Loading Blocks for World "world_herobrine_graveyard"
30.01 21:15:15 [Server] INFO Avg: 0.019ms/Block
30.01 21:15:15 [Server] INFO Loaded a total of 1132 Blocks for World "Varlan"
30.01 21:15:15 [Server] INFO Loading Blocks... 100% (FINISHED - 21ms)
30.01 21:15:15 [Server] INFO Loading Blocks... 97% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 93% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 90% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 87% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 83% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 80% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 77% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 73% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 70% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 67% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 63% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 60% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 57% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 53% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 50% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 47% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 43% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 40% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 37% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 33% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 30% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 27% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 23% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 20% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 17% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 13% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 10% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 7% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 3% done ("Varlan")
30.01 21:15:15 [Server] INFO Loading Blocks... 0% done ("Varlan")
30.01 21:15:15 [Server] INFO This may take a long time...
30.01 21:15:15 [Server] INFO Loading Blocks for World "Varlan"
30.01 21:15:15 [Server] INFO Loaded a total of 0 Blocks for World "Twilight"
30.01 21:15:15 [Server] INFO Loading Blocks... 100% (FINISHED - 0ms)
30.01 21:15:15 [Server] INFO This may take a long time...
30.01 21:15:15 [Server] INFO Loading Blocks for World "Twilight"
30.01 21:15:15 [Server] INFO Loaded a total of 0 Blocks for World "Pyro"
30.01 21:15:15 [Server] INFO Loading Blocks... 100% (FINISHED - 0ms)
30.01 21:15:15 [Server] INFO This may take a long time...
30.01 21:15:15 [Server] INFO Loading Blocks for World "Pyro"
30.01 21:15:15 [Server] INFO Avg: 0.038ms/Block
30.01 21:15:15 [Server] INFO Loaded a total of 314 Blocks for World "Phantasya"
30.01 21:15:15 [Server] INFO Loading Blocks... 100% (FINISHED - 12ms)
30.01 21:15:15 [Server] INFO Loading Blocks... 96% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 92% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 88% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 85% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 81% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 77% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 73% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 69% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 65% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 62% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 58% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 54% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 50% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 46% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 42% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 38% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 35% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 31% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 27% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 23% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 19% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 15% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 12% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 8% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 4% done ("Phantasya")
30.01 21:15:15 [Server] INFO Loading Blocks... 0% done ("Phantasya")
30.01 21:15:15 [Server] INFO This may take a long time...
30.01 21:15:15 [Server] INFO Loading Blocks for World "Phantasya"
30.01 21:15:15 [Server] INFO Avg: 0.018ms/Block
30.01 21:15:15 [Server] INFO Loaded a total of 1305 Blocks for World "Phalon"
30.01 21:15:15 [Server] INFO Loading Blocks... 100% (FINISHED - 24ms)
30.01 21:15:15 [Server] INFO Loading Blocks... 97% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 94% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 91% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 88% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 85% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 82% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 79% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 76% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 74% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 71% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 68% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 65% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 62% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 59% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 56% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 53% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 50% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 47% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 44% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 41% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 38% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 35% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 32% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 29% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 26% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 24% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 21% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 18% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 15% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 12% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 9% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 6% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 3% done ("Phalon")
30.01 21:15:15 [Server] INFO Loading Blocks... 0% done ("Phalon")
30.01 21:15:15 [Server] INFO This may take a long time...
30.01 21:15:15 [Server] INFO Loading Blocks for World "Phalon"
30.01 21:15:15 [Server] INFO Avg: 0.5ms/Block
30.01 21:15:15 [Server] INFO Loaded a total of 2 Blocks for World "Loroth"
30.01 21:15:15 [Server] INFO Loading Blocks... 100% (FINISHED - 1ms)
30.01 21:15:15 [Server] INFO Loading Blocks... 50% done ("Loroth")
30.01 21:15:15 [Server] INFO Loading Blocks... 0% done ("Loroth")
30.01 21:15:15 [Server] INFO This may take a long time...
30.01 21:15:15 [Server] INFO Loading Blocks for World "Loroth"
30.01 21:15:15 [Server] INFO Avg: 0.083ms/Block
30.01 21:15:15 [Server] INFO Loaded a total of 12 Blocks for World "Lithos"
30.01 21:15:15 [Server] INFO Loading Blocks... 100% (FINISHED - 1ms)
30.01 21:15:15 [Server] INFO Loading Blocks... 67% done ("Lithos")
30.01 21:15:15 [Server] INFO Loading Blocks... 33% done ("Lithos")
30.01 21:15:15 [Server] INFO Loading Blocks... 0% done ("Lithos")
30.01 21:15:15 [Server] INFO This may take a long time...
30.01 21:15:15 [Server] INFO Loading Blocks for World "Lithos"
30.01 21:15:15 [Server] INFO Avg: 0.011ms/Block
30.01 21:15:15 [Server] INFO Loaded a total of 705 Blocks for World "Duune"
30.01 21:15:15 [Server] INFO Loading Blocks... 100% (FINISHED - 8ms)
30.01 21:15:15 [Server] INFO Loading Blocks... 50% done ("Duune")
30.01 21:15:15 [Server] INFO Loading Blocks... 0% done ("Duune")
30.01 21:15:15 [Server] INFO This may take a long time...
30.01 21:15:15 [Server] INFO Loading Blocks for World "Duune"

**Comment by NathanWolf** [comment]
Those are kind of some weird-looking logs :\ I mean nothing says what it's coming from - normally there would be some [Plugin] prefixes, I'd think.

That said, if you could actually paste the *full* logs once the server has completely started up, either in a code block here or via http://www.pastebin.com that would be helpful. As you can see there's not a single message from Magic, so I think we missed all the important stuff.

Offhand, I've heard reports that SlimeFun is not compatible with Magic. I still have no clue what that plugin is, but it seems very popular so I'll try it out for myself.

**Comment by NathanWolf** [comment]
Well I guess SlimeFun isn't necessarily the issue, I just tried it out and things seem fine.

Your server logs do look quite weird though- here is what it would normally look like, note the plugin names:

http://pastebin.com/wa1Sq9zY

If you can send me full logs I can try to help more.

**Comment by Triliton** [comment]
Ok,

Attached is a txt document with full log.



Med Vennlig Hilsen / Regards 
 
 
 
 Johan Fossum
 Tlf:: +47  980 19 443
 Email: johan.fossum@yahoo.com 

--------------------------------------------
On Sat, 1/30/16, Nathan Wolf <notifications@github.com> wrote:

 Subject: Re: [MagicPlugin] Commands wont run/work (#25)
 To: "elBukkit/MagicPlugin" <MagicPlugin@noreply.github.com>
 Cc: "Triliton" <johan.fossum@yahoo.com>
 Date: Saturday, January 30, 2016, 9:11 PM
 
 Those are kind of some
 weird-looking logs :\ I mean nothing says what it's
 coming from - normally there would be some [Plugin]
 prefixes, I'd think.
 
 That said, if you could actually paste the full
 logs once the server has completely started up, either in a
 code block here or via http://www.pastebin.com
 that would be helpful. As you can see there's not a
 single message from Magic, so I think we missed all the
 important stuff.
 
 Offhand, I've heard reports that SlimeFun is not
 compatible with Magic. I still have no clue what that plugin
 is, but it seems very popular so I'll try it out for
 myself.
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by NathanWolf** [comment]
I don't think you can attach files here - but if you go to pastebin via the link above you can paste it all in there and get a link so o can see it.

**Comment by NathanWolf** [comment]
You also may want to edit your email and phone number out of here since this is all public!

**Comment by Triliton** [comment]
How about this:

http://www.mediafire.com/download/3bax38346a9y8sp/latest.log

**Comment by NathanWolf** [comment]
```
[21:15:13] [Server thread/INFO]: [Magic] Enabling Magic v5.3.3
[21:15:14] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_8_R1.EntityArmorStand.n(boolean)
[21:15:14] [Server thread/WARN]: 	at java.lang.Class.getDeclaredMethod(Unknown Source)
[21:15:14] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.utility.NMSUtils.<clinit>(NMSUtils.java:344)
[21:15:14] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.magic.MagicPlugin.onEnable(MagicPlugin.java:155)
[21:15:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[21:15:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[21:15:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[21:15:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
[21:15:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
[21:15:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
[21:15:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
[21:15:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
[21:15:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
[21:15:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505)
[21:15:14] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:15:14] [Server thread/WARN]: [Magic] Something went wrong with some Deep Magic, plugin will not load.
[21:15:14] [Server thread/WARN]: [Magic] Please make sure you are running a compatible version of CraftBukkit or Spigot!
```

That's the relevant error message - that still looks like Magic 5.4 or higher trying to run on Spigot 1.8.7 or lower.

**Comment by Triliton** [comment]
Strange. I have deleted the jar and the folder. Now ive tried 5.3.1 and still it wont work.
Are you sure i can run 5.3.1 or even 5.3.3 ? Idk why it wont work...

**Comment by NathanWolf** [comment]
Oh, no- if you're on 1.8.1 then you're gonna need an older build.

Magic-5.3.3 is for 1.8.3 and up ..I think you have to go all the way back to 4.9.7 if you're still on 1.8.1. It'd be a really good idea to update your server though, pre-1.8.3 has some pretty serious security issues!

**Comment by Triliton** [comment]
Im gonna try 4.9.5. I cant update my server to 1.8.3. I need then to update all my other plugins, some of them arent even updated for more then 1.8......

**Comment by Triliton** [comment]
Magic works now :)
