### ISSUE TITLE
how can i combine wands on an anvil

### ISSUE THREAD

**Issue by rock211212** [elBukkit/MagicPlugin#250]
![2017-07-25_22 22 12](https://user-images.githubusercontent.com/25649691/28577290-f077f730-7188-11e7-92f6-443e140a042f.png)
![2017-07-25_22 22 48](https://user-images.githubusercontent.com/25649691/28577295-f43156e6-7188-11e7-9a89-ee2ca828e9c3.png)

**Comment by NathanWolf** [comment]
I don't think it really works anymore, and has been turned off by default for a while. It doesn't really make much sense now that wands rank up.

If you want to try it, add "enable_combining: true" to your plugins/Magic/config.yml
