### ISSUE TITLE
How to disable enchantment table?

### ISSUE THREAD

**Issue by BelleGoBelle** [elBukkit/MagicPlugin#251]
Hi, My players are able to get spells from an enchantment table, but is there a way to disable this
for the plugin?

Thanks :P

**Comment by NathanWolf** [comment]
Copy+paste this to plugins/Magic/config.yml

```
# Set this to empty to prevent the enchantment table from showing players the spell shop defined above
enchant_block: ""
```

In general it's good to search through default configs when you have a question, it's all well documented and a simple search for "enchant" would've found this.
