### ISSUE TITLE
API page is not loading for me

### ISSUE THREAD

**Issue by Devillion** [elBukkit/MagicPlugin#256]
My dev needs access to the api page, but the page for it is not loading: http://jenkins.elmakers.com/job/MagicAPI/doxygen/

**Comment by NathanWolf** [comment]
Build server HD died, hoping it'll be back up eventually.

**Comment by NathanWolf** [comment]
Hm, well I guess I could leave this open until it's back.

**Comment by Kuzzzmaz** [comment]
помогите как включить все крафты предметов

**Comment by NathanWolf** [comment]
It's in the FAQ: https://github.com/elBukkit/MagicPlugin/wiki/FAQ

**Comment by Kuzzzmaz** [comment]
помогите мне  куда   писать battle:                     и как
                                                    enabled: false

**Comment by NathanWolf** [comment]
plugins/Magic/crafting.yml

```
battle:
  enabled: false
```

**Comment by Kuzzzmaz** [comment]
не работает все равно крафты отключены

**Comment by NathanWolf** [comment]
If crafting is disabled then why are you asking about recipes?

**Comment by Kuzzzmaz** [comment]
я уже не знаю  помогите  мне включить  крафт предметов предметов таких как бластер и тд

**Comment by NathanWolf** [comment]
The blaster is part of the Star Wars configs and isn't craftable. The wiki explains how to turn on example configs, and you'd have to look at the crafting recipe configs to see how to set up new ones.

If crafting isn't working at all (like just for the basic wand) then something is broken or you've turned it off.

**Comment by NathanWolf** [comment]
Also, at this point this has strayed way past what this issue was supposed to be about. I'm not really providing support for this plugin at the moment, so if you can't figure it out I may not be able to help you, sorry!
