### ISSUE TITLE
Can not cast spells using Potter Config

### ISSUE THREAD

**Issue by RayleighDK** [elBukkit/MagicPlugin#260]
Hello!

I created a server to play with my friends and I love this plugin, it's really amazing.

The problem comes when I set the config to Potter, we can't use our wands anymore:
"You don't have permission to use that here"
I can select the spell but I can not cast it.

I tried using PermissionsEx and adding Magic.cast.* and Magic.wand.use, but still doesn't work.
It only works if I use Magic.* or if they in OP mode, but I want just to let them use their wands.

I don't know what I am doing wrong, I need help.

Thanks.

**Comment by NathanWolf** [comment]
Players should not need permissions for any spells or for wand use.

If you are using WorldGaurd or some other supported protection plugin, it may be build or PvP permission getting in the way. Use the "/mage check" command while holding a wand to see what your current spell requires.

That all said, there's nothing really different about the potter spells in this regard. If none of that helps you, let me know specifically which spells you are trying.

**Comment by RayleighDK** [comment]
Oh, PvP was disabled and Vermillious, the spell I was trying, needed PvP.

I'm sorry and thanks once again.
