### ISSUE TITLE
Appearance Shop - Can you just please help?

### ISSUE THREAD

**Issue by BelleGoBelle** [elBukkit/MagicPlugin#261]
Hello, Yes. This is like the 5th issue now, But I'm at that point in my server where I want to put the wand textures into a Donation Shop for players to purchase.

I have looked at GitHub for the last 3-4 hours and have found nothing about this.

What I mean by this is,

I would like to put the wand textures onto a Donation Shop where players can purchase the textures and it changes the wand texture.

I see that potterworld has the same plugin and is able for players to purchase the wands and then change the wands anytime in /wands. However, I'm not talking about the command.

Is there a permission or a command to where the wands change textures? Thank you for helping.

And yes, I am aware of the Appearance Shop. But that is ingame money. I'm talking about Enjin Donation Store permissions or console commands.

**Comment by NathanWolf** [comment]
You can use the /mgive command to give players the same items that are purchasable in the appearance shop. "/mgive BelleGoBelle appearance_master" for instance will give the master wand appearance.

You can set up an Enjin shop to run this command, which should work OK.

Magic has no built-in support for remembering which appearances players have "unlocked" or anything like that, though.

**Comment by BelleGoBelle** [comment]
Okay. Thank you, This helps a bunch.
