### ISSUE TITLE
Magic can break spawners and they don't return

### ISSUE THREAD

**Issue by TheZenKitteh** [elBukkit/MagicPlugin#262]
Is there a way to prevent this?

**Comment by NathanWolf** [comment]
Strange that they don't return, I'll keep this open to look at that when I can. It should put them back, unless some other plugin is interfering.

In the meantime, you can add mob_spawner to the indestructible list in materials.yml, like this:

```
indestructible:
- bedrock
- barrier
- ender_portal_frame
- mob_spawner
```

**Comment by NathanWolf** [comment]
I could not reproduce this. Placed spawned, cast Blast at it, waiting for blast to undo. Spawner came back and was functional (still had correct mob and data).

If you'd like to re-open this, please let me know what spell you were using, and if you have any other plugins that might be preventing spawners from working.
