### ISSUE TITLE
World Guard Breaks Magic

### ISSUE THREAD

**Issue by Mutim** [elBukkit/MagicPlugin#264]
Hello, Does anyone know why world guard would be breaking magic? I am using the most up to date versions of each WG 6.2.1, and Magic 6.9.17. I added magic to our new server first, and even added my custom modeled wands. Everything works with the resource pack, the models, everything. But then I added worldGuard, and all spells stopped working. I don't know what would make them stop, the only spells I have being blocked are construction, and master. Which shouldn't apply to OP's anyway. Please help if anyone knows anything about this. No error's in console, and wands are still active (meaning you can like switch spells, and all that) You just can't cast anything with WG active. Thank you everyone.

**Comment by NathanWolf** [comment]
Try the "/mage <player> check" command on a player while they're holding a wand. That should tell you why they can't cast spells. This shouldn't affect ops though.

If it's not build or PvP permissions, ops also can't cast, and you have no errors then I really don't know what could be wrong.
