### ISSUE TITLE
Trait "hat" disappears . 

### ISSUE THREAD

**Issue by Amaknajaja** [elBukkit/MagicPlugin#267]
Hello nathan ^^ . 
When I restart the server. NPC's with the trait "hat" , turns back to "Spell hat unknown" .
What can I do?

Regards!

**Comment by NathanWolf** [comment]
I just tried this myself to make sure it hasn't broken and it seems ok. You are trying to put a hat on an NPC, right- not give them the hat spell?

If so, then
```
/trait magic
/mtrait hat wool
```

Should do it, that'll put a wool block on their head. Is that what you were doing?

**Comment by Amaknajaja** [comment]
Yes, I use .
`/ trait magic
/mtrait hat wool
`
by the moment, dont have problems right now when I reboot. So.. maybe was an a bug .
Thank so much ^^
