### ISSUE TITLE
3D Models 

### ISSUE THREAD

**Issue by Amaknajaja** [elBukkit/MagicPlugin#271]
Hello nathan! , When I use this format in JSON wooden_hoe to add 3d models. In game, I cant get this modes with /mgive amakna wooden_hoe:1.2.3,etc..  This format of JSON works in 1,11,2?

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/resource-pack/default/assets/minecraft/models/item/wooden_hoe.json#L31

I looked at the json of other resourcepacks with models and this format was in a single line, it affects ?

**Comment by NathanWolf** [comment]
This RP is set up to only affect *unbreakable* items.  So if you want to see them in-game you have to do

```
/mgive wooden_hoe:1
/mitem add unbreakable
```

Then the custom icon should show up.

Having it all on one line is probably just to compact it or possibly make it less readable (obfuscated).

**Comment by Amaknajaja** [comment]
It's so strange, if I use my own JSON in one line, it works! , but with the format "https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/resource-pack/default/assets/minecraft/models/item/wooden_hoe.json#L31" not. Any suggestions? hhahahaha
