### ISSUE TITLE
HitEvent

### ISSUE THREAD

**Issue by christophe6** [elBukkit/MagicPlugin#274]
Hi

Could it be possible to add an HitEvent to magic?

**Comment by NathanWolf** [comment]
There is a CastEvent:

https://github.com/elBukkit/MagicPlugin/blob/master/MagicAPI/src/main/java/com/elmakers/mine/bukkit/api/event/CastEvent.java#L43

You can call getSpellResult, if the result is CAST it was a hit.

**Comment by christophe6** [comment]
How can I get the target?

**Comment by christophe6** [comment]
@NathanWolf

**Comment by NathanWolf** [comment]
Hm- try getSpell().getCurrentCast().getTargetedEntities() (there may be more than one target, such as for AOE spells)
