### ISSUE TITLE
Spells Duplication

### ISSUE THREAD

**Issue by archideous** [elBukkit/MagicPlugin#275]
I am messing around just with a friend and I try to fully upgrade my wand, i can't switch inventories between spells and one of the hotbars becomes the same as another.

**Comment by NathanWolf** [comment]
> I am messing around just with a friend and I try to fully upgrade my wand

Legit or via commands?

>  i can't switch inventories between spells 

Tried clicking outside the inventory?

> and one of the hotbars becomes the same as another.

Using creative mode?

**Comment by archideous** [comment]
I am using commands and in creative and yes i clicked outside

**Comment by NathanWolf** [comment]
Wands don't really work in creative mode.
