### ISSUE TITLE
Worldguard

### ISSUE THREAD

**Issue by Matthijs1002** [elBukkit/MagicPlugin#278]
Is there an option to enable magic and disable magic with a command (only 1 world) or with worldguard?

**Comment by NathanWolf** [comment]
There's not really an "enable disable the whole plugin" but you can use two flags to pretty much do that:

```
region flag __global__ -w world blocked-spells *
region flag __global__ -w world blocked-wands *
```

See: 
https://github.com/elBukkit/MagicPlugin/wiki/Regions

Examples:
https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/examples/elworld/regions.cmd
