### ISSUE TITLE
Breaking Tall Grass While Holding a Wand

### ISSUE THREAD

**Issue by MineStein** [elBukkit/MagicPlugin#279]
When breaking double grass while holding a wand item the double block is replaced with a floating peony.

**Comment by NathanWolf** [comment]
Unfortunately this seems to be an issues with Spigot, that arises from cancelling the interact event.

Probably the best way for me to fix this would be to find the core problem and submit a PR to Spigot. Not sure when I'd be able to do that, however.

In the meantime the only fix would be to add this to Magic's config:

```
cancel_interact_on_left_click: false
```

That will of course have side-effects, mainly that wands will be able to break blocks as normal (as if you were hitting the block with a hoe).

**Comment by NathanWolf** [comment]
So this is a known issue that Spigot calls "won't fix", and is apparently present in vanilla as well (when spawn protection is enabled)

It is a client glitch mostly, if you relog you'll see the tall grass is actually intact.

https://hub.spigotmc.org/jira/browse/SPIGOT-1805?jql=text%20~%20%22tall%20grass%22

So I don't think there's much I can do about it, unfortunately.
