### ISSUE TITLE
Cooldowns approximately 1 second shorter than configured.

### ISSUE THREAD

**Issue by dumptruckman** [elBukkit/MagicPlugin#28]
The cooldowns for all spells are approximately 1 second less than the configured amount. A spell with ``cooldown: 1000`` can be spammed as if it had no cooldown. A spell with ``cooldown: 2000`` can be cast approximately every 1 second. The cooldown display on the hotbar reflects the actual correct cooldown. That is to say, a spell with ``cooldown: 1000`` will show -1 on the spell icon yet still be castable.

**Comment by NathanWolf** [comment]
I'm so baffled by this, thanks for opening an issue to remind me- I will have to take a look.
