### ISSUE TITLE
Question - Are wands bound to the player's UUID or stuck on displayname?

### ISSUE THREAD

**Issue by mibby** [elBukkit/MagicPlugin#282]
```
    bound: true
```

When a wand is bound to a player, it seems to show their displayname on the wand lore. If a player changes their in-game nickname via ```/nick```, the wand still shows being tied to their old displayname.

Would it be possible to tie the wand to the player's playername instead of displayname so they can continue to use their wands? As well as remap to their UUID in case they one day change their account name?

**Comment by NathanWolf** [comment]
I think the lore will update eventually. If not, let me know.

Use of wands is not lore-based, it is UUID-based so name changes shouldn’t prevent anyone from using their wands.

**Comment by mibby** [comment]
Oops, sorry @NathanWolf Nathan. Didn't see that you had replied! 

Thanks, that is very good to know! I'm glad it is UUID based so nicks and actual name changes won't affect the wand. :) I don't recall whether or not lore updates when a player changes their name, but I'll let you know if I notice it doesn't.

---

Another concern I have. Do wands try to repair themselves when their damage value changes unintentionally? Such as if a player used ```/repair``` to reset all durability on everything in their inventory.

Using these settings on the wands to avoid changes and loss. I have certain damage values set on wands for custom textures.
```
    indestructible: true
    locked: true
    keep: true
    bound: true
```
