### ISSUE TITLE
Per item permissions?

### ISSUE THREAD

**Issue by Nonnisi** [elBukkit/MagicPlugin#283]
I'm a little confused about the permissions setup. I can see that you can do magic.cast.<spell> to limit spell casting, but id like to limit certain players from using/crafting certain items/wands. 

For example some players should not be allowed to use broomsticks.

Can this be accomplished?

**Comment by NathanWolf** [comment]
Yes, this was missing from the Permissions page on the wiki but I added it recently. Sorry for the delayed response:

> -Magic.use.<wandname> : Player may not use a specific wand or magic item
