### ISSUE TITLE
MythicMobs config

### ISSUE THREAD

**Issue by christophe6** [elBukkit/MagicPlugin#284]
Hi

The Mythic mobs config is broken. (Location: MagicPlugin/Magic/src/main/resources/examples/potter/MythicMobs-2.0/Skills/MagicPotterSkills.yml)
[https://img.christophe6.be/LTxaV.png](https://img.christophe6.be/LTxaV.png)
Does anyone know a fix?

**Comment by NathanWolf** [comment]
I don't support the MythicMobs configs anymore, sorry. Their config format has changed and I don't use the plugin anymore.

I don't think anyone else really looks at these issues so I'm going to close this out- sorry!

You'd probably have better luck taking the configs and getting support from MythicMobs devs or community.
