### ISSUE TITLE
MysticMob skill.yml file

### ISSUE THREAD

**Issue by God0fLight** [elBukkit/MagicPlugin#285]
https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/examples/potter/MythicMobs-2.0/Skills/MagicPotterSkills.yml I installed that file into the server but it keep saying this error: Cannot load plugins/MythicMobs/Skills/MagicPotterSkills.yml

**Comment by NathanWolf** [comment]
I'm not supporting my MythicMob configs anymore, sorry. The config format has changed since I made those, you'd have to re-work it yourself.
