### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by scarlord83** [elBukkit/MagicPlugin#290]
Hey Nathan, I know you are busy but I just had a quick question. One of my players requested for their  wand appearance to be changed to a diamond hoe instead of a golden hoe. What I want to know is it possible for me to change the appearance of their wand without giving them a whole new one?

**Comment by martdamp** [comment]
I don't know what your setup with wands is, but when I created a new one for myself I was able to change the look by using this command: ```/wand configure icon diamond_hoe```

**Comment by scarlord83** [comment]
well do you know a way to change other players wands without giving them a new one?

**Comment by NathanWolf** [comment]
Use the /wandp command, “/wandp <player> configure ...”

Another option is to give them upgrade items or access to an appearance shop. Use “/cast appearanceshop” to try this out.

**Comment by NathanWolf** [comment]
Sorry my command got mangled - should be 

/wandp [player] configure ...

**Comment by scarlord83** [comment]
thank you!
