### ISSUE TITLE
brooms on top of head 

### ISSUE THREAD

**Issue by pvpmaster16** [elBukkit/MagicPlugin#291]
Brooms are on top of head instead below where they should be is there anyway to fix this?

**Comment by NathanWolf** [comment]
Use current RP. If you have a custom one you’ll need to update the broom json.

**Comment by pvpmaster16** [comment]
oh how do I update the broom json?

**Comment by pvpmaster16** [comment]
and i used the the current rp for the plugin and i had the same problem

**Comment by NathanWolf** [comment]
The latest RP should work fine. Make sure you don't have an RP specified in your server properties and Magic will load it automatically.

Or update your broomstick.json, the important part is the vertical offset here:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/resource-pack/default/assets/minecraft/models/item/custom/broomstick.json#L429

**Comment by NathanWolf** [comment]
If this didn't work for you, please re-open and let me know.
