### ISSUE TITLE
Player Skull Wands Don't Work With Right-Click

### ISSUE THREAD

**Issue by NathanWolf** [elBukkit/MagicPlugin#298]
A wand based on a player skull (like a Hunter Heart) doesn't register right-click events, or at least won't respond to "right_click: cast"

Issue raised by millmilla on spigotmc

**Comment by killme** [comment]
Wasn't there a commit in which you fixed this?

**Comment by NathanWolf** [comment]
Yes, I just forgot to close this- thanks!

Fixed in 3e90ad5298448c395304ecc25c6eac4b238c16eb

**Comment by NathanWolf** [comment]
Though I'll note it was a bit of a hack, the main issue is that skulls are wearable and the plugin assumes right-clicking with a wearable item means wear it.

However, for whatever reason, right-clicking a skull doesn't (currently) wear it. If that ever changes, I'll want to remove this code and right-click with skull wands won't work again.
