### ISSUE TITLE
WorldGuard with block-place set to deny make blocks from explosive spells drop.

### ISSUE THREAD

**Issue by 4kz** [elBukkit/MagicPlugin#299]
Hello there,
just want to report that when I cast a spell that applies velocity to blocks (like Blast or tornado for example) and hit blocks that are in a worldguard region with the flag "block-place" set to deny, blocks from in the explosion area are being dropped.
This doesn't happen at all when I'm in a region without the flag.

**Comment by NathanWolf** [comment]
Yes, it's a known issue. Something weird that WorldGuard. Their response is to not use that flag, since just making a region is enough to prevent players (non-members) building. 

So if you remove that flag it should still prevent building, but the bug will go away.

**Comment by 4kz** [comment]
I've removed the flag but players still seem to be able to place blocks, here's a screenshot of the flags
If I set passthrough to deny then players won't be able to cast spells in the area.

[
![immagine](https://user-images.githubusercontent.com/35037484/35239409-b1d88cf4-ffb0-11e7-89bd-52dd63835bf4.png)
](url)

**Comment by NathanWolf** [comment]
Yeah, passthrough means people can build!

if you want them to be able to use destructive/building spells but not destroy/build by hand, remove passthrough as well but add "allowed-spells *".

**Comment by NathanWolf** [comment]
Hoping this helped, unfortunately there's not much I can do about the core WorldGuard issue, and their team does not seem interested in fixings it.
