### ISSUE TITLE
Magic mob not casting a spell

### ISSUE THREAD

**Issue by 4kz** [elBukkit/MagicPlugin#301]
(copypaste from a pm on spigotmc, I don't know if this is the right place to ask for help but seems a pretty strange issue)

 
Hello there, I'm having some troubles with a custom mob I made, it doesn't cast the spell I want him to.

here's the spell (working normally, with a wand)

> MFire:
>     actions:
>         cast:
>         - class: CustomProjectile
>           actions:
>           - class: Disc
>             actions:
>             - class: Cover
>               actions:
>               - class: Burn
>     parameters:
>         velocity: 80
>         target_type: LivingEntity
>         allow_max_range: true
>         range: 48
>         hitbox: true
>         fov: 0.03
>         radius: 0
>         vertical_range: 4
>         undo: 1000
>         target_breakables: 0
>         destructible: burnable

here's the mob (everything else behaves normally)

> roasty:
>   chestplate: ""
>   leggings: ""
>   helmet: ""
>   boots: ""
>   item: ""
>   name: "roasty"
>   type: husk
>   health: 8
>   default_drops: false
>   drops:
>   - exp_bottle@2
>   attributes:
>     generic_follow_range: 30
>   cast_interval: 1200
>   cast:
>     MFire: 1
>   potion_effects:
>   - type: fire_resistence
>     amplifier: 1
>   disguise:
>     type: blaze

**Comment by NathanWolf** [comment]
I just tried this out and it worked for me- the only issue being I had to go hit the husk before he'd attack. Magic mobs will only cast spells when they are aggressive, little odd this husk didn't get aggressive with me near but I think that's a vanilla thing.

If you walk up and hit the husk, does he then cast the spell ok?

**Comment by 4kz** [comment]
it doesn't cast any spell even if I hit him, but normal melee-attacks from him do work.
It should be disguised as a blaze...

**Comment by NathanWolf** [comment]
I don't have protocol lib or libsdisguises on my dev server, so it looked like a husk.

I copied your configs directly and it seemed to work. Not sure what else I can do, sorry! :(

**Comment by 4kz** [comment]
Wait, just tried it out in another world, seems to work fine in here, probably was a multiverse thing.
Thank you so much for the support, could you please respond to a question I asked on spigotmc? It is about
collateral damage from spells that you cast, Don't think I should open a ticket in here
