### ISSUE TITLE
Modify demage

### ISSUE THREAD

**Issue by Zeuscp1** [elBukkit/MagicPlugin#302]
Is there any way i can modify demage of magic missile?

**Comment by NathanWolf** [comment]
Check the FAQ, this is the very first question. Best to look over and understand the customization section before going down that route.

https://github.com/elBukkit/MagicPlugin/wiki/Customization

tl;dr it's complicated for several reasons:

 - Magic Missile damage levels up. 
 - It does different damage depending on player vs mob targets
 - It does different damage for headshots

For the first level it'd be like this to do 200 damage to a player and 100 to a mob:

```
missile:
 parameters:
  player_damage: 200
  entity_damage: 100
```

Look here for the various levels, you'd want to override each one:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/defaults/spells/missile.yml

Headshots are multipliers so will scale appropriately if you change the base damage. You can change the multiplier if you want, though, just look at the configs.

**Comment by Zeuscp1** [comment]
Last question, is there any way i can make it so that the spell lvl 1 doesnt lvl up?

**Comment by NathanWolf** [comment]
If you want to turn off spell levelling completely, use this in config.yml:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/defaults/config/defaults.yml#L69

```
enable_spell_upgrades: false
```

Or to disable just missile levelling, add "upgrade_required_casts: 0" to the missile spell

```
missile:
  upgrade_required_casts: 0
```
