### ISSUE TITLE
How can an NPC give a wand to a player, only once...

### ISSUE THREAD

**Issue by Zeuscp1** [elBukkit/MagicPlugin#304]
As the title says, is there a way to do that?

**Comment by Zeuscp1** [comment]
By the way im using the Quests plugin, i would like it to give it in the quest

**Comment by Zeuscp1** [comment]
Or is there any command that i can use to give certain player a wand?. must be with a placeholder

**Comment by NathanWolf** [comment]
You can give players a unique item on spawn that they can exchange for a wand. That's how the potter configs work.

The command to give a wand is

```
mgive @p wand
```

Or you can use the MagicQuests module to add wands as Quests rewards. Drop the jar in Quests/modules

http://jenkins.elmakers.com/job/MagicQuests/89/com.elmakers.mine.bukkit.plugins$MagicQuests/artifact/com.elmakers.mine.bukkit.plugins/MagicQuests/1.1-SNAPSHOT/MagicQuests-1.1-SNAPSHOT.jar
