### ISSUE TITLE
Broom - Fatal ERROR

### ISSUE THREAD

**Issue by paperrain** [elBukkit/MagicPlugin#305]
Hello, when I use the brooms I do right click to mount on them and shows me a FATAL ERROR on the console.

Edit: The error is when I dismount the broom. And the error only appears with the broom.

https://pastebin.com/raw/FpuKHUA1

Spigot: 1.12.2
Version: Magic 6.9.21

_I don't know if this would help..._
https://www.spigotmc.org/threads/error-executing-task-java-util-concurrent-executionexception-trap.282031/

Thanks!

**Comment by NathanWolf** [comment]
I can't seem to reproduce this one. Is it consistent for you, you see this every time you try to mount a broom?

It looks like from the thread you linked and your stack trace this should only happen when trying to place a block. Do you have broomsticks modified to use placeable blocks or anything like that? I did try that myself (dirt block broomsticks) and still couldn't get an error to happen.

**Comment by paperrain** [comment]
Sorry for the inconvenience, I found the bug. It was incompatible with the BetterChairs. 
https://www.spigotmc.org/resources/better-chairs.18705/

Thank you for your time and sorry to bother you.

**Comment by paperrain** [comment]
Do you know any Magic compatible plugins for sitting on slabs/stairs? 

Tested with this and same error:
https://www.spigotmc.org/resources/kittystairchairs.45141/
https://dev.bukkit.org/projects/chairstairs

Thanks!

**Comment by NathanWolf** [comment]
I don't really know why Magic would be incompatible with any chair plugins.

Have you tried any of those plugins without Magic?

**Comment by paperrain** [comment]
Edit my first message: The error is when I dismount the broom. And the error only appears with the broom.

**Comment by NathanWolf** [comment]
I guess they are reacting to the player dismounting from an armor stand. In their defense, that wouldn't normally happen in vanilla. But since we are writing plugins that run with other plugins they really should do a better job of playing nice with others.

Unfortunately I can't really help out, I don't have a chairs plugin. The ones I've used in the past have been custom and had no issues with brooms.

**Comment by NathanWolf** [comment]
I tried KittyStairChairs, seemed to work fine. Are you sure you removed the original plugin that was causing the error?

With that plugin, I can right-click a stairs and sit on it. I can mount and unmount my broom with no errors. The only thing I see is this:

```
NathanWolf moved wrongly!
```

Which the author warned about, and is a mostly benign warning.

**Comment by paperrain** [comment]
About ChairStairs; yes, it gives the same error and works perfectly. The problem is with the brooms that when you dismount it shows the error "TRAP". I'm trying to understand why it shows an error with a sitting plugin. There shouldn't be any incompatibility because they're not doing the same thing. One sits you in this case on an "arrow" and the other on an ArmorStand. And for example, the plugin "PetBlocks" works with ArmorStand and does not give that kind of error. I don't quite understand.

I will try again with the KittyStairChairs plugin. 

Thanks again for your time!

Translated with www.DeepL.com/Translator

**Comment by NathanWolf** [comment]
Please re-open if you're still having issues here.
