### ISSUE TITLE
Custom Wands

### ISSUE THREAD

**Issue by yotam1802** [elBukkit/MagicPlugin#306]
Is there a way to make a custom wand with custom lore?

**Comment by NathanWolf** [comment]
Completely custom lore is not currently possible. You can set a description, but the rest of the lore is autogenerated based on wand properties like spells, mana, etc.

**Comment by yotam1802** [comment]
How do you set descriptions? I read your custom wand article. Trying to make a Necromancer Staff for players.

**Comment by NathanWolf** [comment]
Easiest way is in the wand config, just add a "description" property.

```
necromancer:
  inherit: base_wand
  name: Necromancer Staff
  description: Raise the dead
  icon: wood_hoe:5
  spells:
  - monster
```

Something like that. Create upgradeable wands will be a little more work, you have to set up a path as well.

Everything in this plugin is best learned by looking at the default configs. Though in this case, the wand descriptions and names are all in a separate file for localization purposes.

**Comment by yotam1802** [comment]
Alright thanks a lot! Appreciate it.

**Comment by yotam1802** [comment]
I received this error when trying.

29.01 18:32:55 [Server] INFO ... 15 more
29.01 18:32:55 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.0-20170608a.jar:git-Spigot-ede465d-bb4ae3b]
29.01 18:32:55 [Server] INFO at com.elmakers.mine.bukkit.magic.command.WandCommandExecutor.onCommand(WandCommandExecutor.java:101) ~[?:?]
29.01 18:32:55 [Server] INFO at com.elmakers.mine.bukkit.magic.command.WandCommandExecutor.processWandCommand(WandCommandExecutor.java:518) ~[?:?]
29.01 18:32:55 [Server] INFO at com.elmakers.mine.bukkit.magic.command.WandCommandExecutor.onWand(WandCommandExecutor.java:1227) ~[?:?]
29.01 18:32:55 [Server] INFO at com.elmakers.mine.bukkit.magic.command.MagicTabExecutor.giveWand(MagicTabExecutor.java:95) ~[?:?]
29.01 18:32:55 [Server] INFO Caused by: java.lang.NullPointerException
29.01 18:32:55 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
29.01 18:32:55 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.0-20170608a.jar:git-Spigot-ede465d-bb4ae3b]
29.01 18:32:55 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.0-20170608a.jar:git-Spigot-ede465d-bb4ae3b]
29.01 18:32:55 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.0-20170608a.jar:git-Spigot-ede465d-bb4ae3b]
29.01 18:32:55 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.0-20170608a.jar:git-Spigot-ede465d-bb4ae3b]
29.01 18:32:55 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.0-20170608a.jar:git-Spigot-ede465d-bb4ae3b]
29.01 18:32:55 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
29.01 18:32:55 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
29.01 18:32:55 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.0-20170608a.jar:git-Spigot-ede465d-bb4ae3b]
29.01 18:32:55 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.0-20170608a.jar:git-Spigot-ede465d-bb4ae3b]
29.01 18:32:55 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.0-20170608a.jar:git-Spigot-ede465d-bb4ae3b]
29.01 18:32:55 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot-1.12.0-20170608a.jar:git-Spigot-ede465d-bb4ae3b]
29.01 18:32:55 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot-1.12.0-20170608a.jar:git-Spigot-ede465d-bb4ae3b]
29.01 18:32:55 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) ~[spigot-1.12.0-20170608a.jar:git-Spigot-ede465d-bb4ae3b]
29.01 18:32:55 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.0-20170608a.jar:git-Spigot-ede465d-bb4ae3b]
29.01 18:32:55 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.0-20170608a.jar:git-Spigot-ede465d-bb4ae3b]
29.01 18:32:55 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'wand' in plugin Magic v6.9.21
29.01 18:32:55 [Server] ERROR null
29.01 18:32:55 [Server] WARN Player data request for b7f95d2e-89a8-4c6f-8909-5b2c97292bd4 (LegallyYotam) failed, plugin not loaded yet

My config :   necromancer:
     inherit: base_wand
     name: &8Necromancer Staff
     description: &7Long lost in the depths of the dead, now found....
     icon: wood_hoe:5
     mana_max: 150
     mana_regeneration: 5
     spells:
     -monster
     -blind
     -curse
     -arrow

**Comment by NathanWolf** [comment]
There is probably an error further up in your logs saying the configs didn't load. And it's probably because you need quotes around the lines that start with &.

**Comment by NathanWolf** [comment]
Also Yaml lists need a space between the - and text. This is just yaml stuff, nothing specific to this plugin.

**Comment by yotam1802** [comment]
Oh alright.

**Comment by NathanWolf** [comment]
Can confirm this works:

```
necromancer:
  inherit: base_wand
  name: "&8Necromancer Staff"
  description: "&7Long lost in the depths of the dead, now found...."
  icon: wood_hoe:5
  mana_max: 50
  mana_regeneration: 5
  spells:
  - monster
  - blind
  - curse
  - arrow
```
