### ISSUE TITLE
LightAPI or similar

### ISSUE THREAD

**Issue by MineStein** [elBukkit/MagicPlugin#308]
Would it be possible to implement LightAPI or similar for fake light effects?

**Comment by NathanWolf** [comment]
Probably not unless they Mavenize it.

However, it'd be pretty easy to make your own plugin that adds a Magic action that interacts with LightAPI if you have a bit of dev know-how. 

I just can't really add anything to Magic that's not available via Maven or it makes things complicated. The other option would be to wrap it via reflection, but I'm not totally up for that myself.

I'll leave this open, though. It's something I've had in the past and would like to have again.

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/java/com/elmakers/mine/bukkit/spell/builtin/LightSpell.java

**Comment by NathanWolf** [comment]
Implemented Light action, targeted for 7.2

Requires LightAPI.
