### ISSUE TITLE
Custom Wand page

### ISSUE THREAD

**Issue by GrandpaDanik** [elBukkit/MagicPlugin#310]
Hello! I work at a Harry Potter server and this plugin is 11/10. However, the Custom Wand page on the documentation was trolled, so I can't learn how to make custom wands. :/

**Comment by NathanWolf** [comment]
After some inspection, I think that page never actually existed. He just added it with "nothing here", which is still kind of annoying.

This is the only real documentation on wand creation that exists:

https://github.com/elBukkit/MagicPlugin/wiki/WandParameters

I'm not sure exactly what you're looking for, it doesn't seem like an HP server would really need custom wands as in custom configs for wands?

If you're looking for modeling help that's not something I'll be able to provide.

**Comment by GrandpaDanik** [comment]
Ah, I was trying to find why my wand model goes to the diamond hoe texture instead of the damaged predicate. I mean by holding the damaged predicate wand and do /wand create, then it becomes to a diamond hoe texture. Why does that happen?

**Comment by NathanWolf** [comment]
You need to set up your predicates in a very specific way to work with unbreakable items.

There is some info here, including a helpful wiki article I wrote:

https://github.com/elBukkit/MagicPlugin/wiki/ResourcePack#customizing

But beyond that I don't really give help with RP creation, sorry- there's lots of info out there, the only real trick is the predicate stuff that I go over in great detail on the Spigot wiki.

**Comment by GrandpaDanik** [comment]
Ah, thanks! 

(Will let Lucy and Jay know that you helped me! ;))
