### ISSUE TITLE
Disappearing texture

### ISSUE THREAD

**Issue by GrandpaDanik** [elBukkit/MagicPlugin#311]
Hello! I have the damage predicates working out! I see the texture with me, whenever I do /wand create, it turns into a diamond hoe, is the plugin preventing it to staying true to the model?

**Comment by NathanWolf** [comment]
Wands make the item unbreakable. As I said before, there is some specific method to the predicates to make them work with unbreakable items, this is outlined in the Spigot wiki article I wrote.

**Comment by GrandpaDanik** [comment]
I see that your article explains how to get it into ingame, however my issue is with the plugin not how to get it ingame.

**Comment by NathanWolf** [comment]
The article is about how to set up a resource pack- did you read it?

Look at the section titled "Preserving the original items" - you need to do that part for it to work with Magic.

If you are spawning in an item and it is using your custom model, you have done it wrong. It should only change models when you make it unbreakable.

**Comment by NathanWolf** [comment]
To be clear I'm talking about this article: https://www.spigotmc.org/wiki/custom-item-models-in-1-9-and-up/

**Comment by GrandpaDanik** [comment]
Yes, thats the article I'm talking about :/

**Comment by NathanWolf** [comment]
Probably you should just copy the files from my RP and edit them...

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/resource-pack/default/assets/minecraft/models/item/wooden_hoe.json

**Comment by GrandpaDanik** [comment]
I could, I'm gonna check if It works!

**Comment by GrandpaDanik** [comment]
Nope, doesn't work. Messed up my respack.

**Comment by NathanWolf** [comment]
I'm not sure I can help out any more here, re-open if you think otherwise.
