### ISSUE TITLE
What is the name for Magic Missile.

### ISSUE THREAD

**Issue by yotam1802** [elBukkit/MagicPlugin#312]
Whenever I try to give a wand the spell Magic Missile it says it's invalid. Can you suggest what its called when I do /wand add (spell).

**Comment by NathanWolf** [comment]
missile

http://mine.elmakers.com/#spells

Has a list.

**Comment by yotam1802** [comment]
How do I allow magic missile to damage npcs?
Thanks for responding.

**Comment by NathanWolf** [comment]
To make all spells target npcs add to spells.yml

```
default:
  parameters:
     target_npc: true
```

If you just want magic missile, use “missile” instead of “default”.

**Comment by yotam1802** [comment]
Thanks

**Comment by yotam1802** [comment]
Did I do this correctly? 
https://gyazo.com/0eb8d96130f4ef845a770e87b1bad446

**Comment by yotam1802** [comment]
Closed on accident but
idk if I did this correctly. 
https://gyazo.com/0eb8d96130f4ef845a770e87b1bad446

**Comment by NathanWolf** [comment]
It looks indented, make sure that the “default” line has no space in front of it.

Otherwise that should be good.

**Comment by yotam1802** [comment]
Still cant damage the npcs with magic missile.

**Comment by yotam1802** [comment]
Also trying to change the cool down for the monster spell do you know how I can edit that?

**Comment by yotam1802** [comment]
Also would like to know if I can make the monster spell not attack other players

**Comment by yotam1802** [comment]
I met the default player

**Comment by NathanWolf** [comment]
plugins/Magic/spells.yml should look like this, no indentation:

https://i.imgur.com/A1hMJV0.png

If you do it like that, spells can hit NPCs. Otherwise they go right through them. I just tried it myself to be sure.

Change cooldowns in that same file like this:

```
monster:
  parameters:
    cooldown: 1000
```

Magic has no direct support for modded mobs, it just spawns vanilla mobs who will behave as normal.

**Comment by yotam1802** [comment]
Alright thanks
