### ISSUE TITLE
engineering spells?

### ISSUE THREAD

**Issue by sx34** [elBukkit/MagicPlugin#315]
1) Is there a way to gauge how many brushes or materials one has on a wand, or no?

2) How many times do I have to use Absorb to attain the amount of brushes required to use Bridge, or Toss, or Volley, etc.

**Comment by NathanWolf** [comment]
1. It tells you in your wand's lore: https://imgur.com/a/651eH

2. They are unrelated, you should be able to use those spells right away. They don't work with the erase brush, but should work with basically any. You get a handful (dirt, etc) when ranking up to engineer so the spells should be available immediately.

**Comment by NathanWolf** [comment]
Did that answer your question?
