### ISSUE TITLE
7.0 Wand Hot bar issues

### ISSUE THREAD

**Issue by Peculiarityy** [elBukkit/MagicPlugin#318]
I was messing around with wands today when I noticed that you cannot switch to wand hot bar. I've tried the default files and my own. You cannot switch over to the wand hot bar. I've tested this with Creative and Survival

**Comment by NathanWolf** [comment]
Also I guess I should ask, is the plugin working at all? Can you cast spells? Checked your logs for errors?

**Comment by Peculiarityy** [comment]
I've tested it on a couple of times on the Elmakers server. I've checked the logs for errors, and as for casting, I can only cast the set spell. Although I'm on 1.12 and it still doesn't seem to work.

**Comment by NathanWolf** [comment]
So are you saying right-click is not working for you on my dev server?

**Comment by Peculiarityy** [comment]
No, it was on my test server. Sorry for not clarifying this.

**Comment by NathanWolf** [comment]
So if it works on my server but not on yours, there are no errors and you’re on Spigot 1.12 - it sounds like probably a config issue.

Are you updating from an older version of Magic? Do you have completely custom wand configs?

If so there may be some migration steps you need to follow.

**Comment by NathanWolf** [comment]
https://github.com/elBukkit/MagicPlugin/blob/master/Magic/MIGRATION.md#65

**Comment by Peculiarityy** [comment]
I've tried the migration steps, and yeah I was updating from an older version with custom items.

**Comment by NathanWolf** [comment]
Please paste your wands.yml and other wand configs, and let me know which wand(s) you're using.

**Comment by Peculiarityy** [comment]
Hey, Sorry for never responding. But I was about to give you my wand configuration file and it appears to be empty all the sudden. I've tried the basic /wand and switching to the spell inventory in Survival and it doesn't seem to work.

**Comment by NathanWolf** [comment]
If you don't intentionally have any custom configs, try just deleting everything in your plugins/Magic folder

**Comment by Peculiarityy** [comment]
I ended up deleting all my configuration files, and I've just restarted. Thanks.
