### ISSUE TITLE
Configurable Magic Mob Spawners

### ISSUE THREAD

**Issue by Devillion** [elBukkit/MagicPlugin#319]
Would you be able to add a location option in the config for spawners that supports multiple locations?

Here's an example: https://pastebin.com/tnAinyPt

The reason for this is to keep spawners better organized and would be easier to keep track of spawners of the same type.

I tried to suggest something like this for mythicmobs over a year ago. It's just frustrating having to create so many spawners for the same mob type in multiple locations.

With all the features you have in place now with creating custom items, custom mobs, all the spawning options for magic mobs and having all the spells, etc I don't think I even need to use mythicmobs anymore.

**Comment by NathanWolf** [comment]
Magic doesn’t support spawners in the same way that mythic mobs works. The location is not part of the config.

These are configs for actual vanilla mob spawner blocks- you have to give them to yourself and then go place them in the world where you want mobs to spawn.

I don’t have any plans right now to implement mythic mobs style configured spawn locations.

**Comment by Devillion** [comment]
that sucks, but thanks for the quick reply.

**Comment by NathanWolf** [comment]
Re-opening this, after some experimentation with vanilla spawner oddities it seems worth making a custom spawner system.

I think I'd rather it be a custom spellcasting system, though. Something where you say

- At these locations
Optionally:
- Check every S seconds
- When players are within X
- When there are fewer than Y mobs around
- When day/night
- etc...

Cast spell Z

Then you can just make simple spells for spawning mobs, but you could also do all kinds of cool scripted event kinds of stuff, traps, secrets, etc.

**Comment by Devillion** [comment]
that sounds amazing

**Comment by NathanWolf** [comment]
This is now implemented as part of the /mauto command:

https://github.com/elBukkit/MagicPlugin/wiki/AutomaticBlocks

Available in recent builds.
