### ISSUE TITLE
build 2773 wand inventories don't seem to be opening

### ISSUE THREAD

**Issue by malonnnn** [elBukkit/MagicPlugin#322]
Also, undroppable wands are now droppable

edit: they are sometimes openable, but then not openable a 2nd time in a row

**Comment by NathanWolf** [comment]
This sounds very similar #318

It would be really helpful if you and @Peculiarityy could get on my dev server and let me know if you see the same issues there:

mine.elmakers.com

That would help rule out custom config issues. I haven’t seen any of these problems myself, and nothing has really changed in the area of wand controls in 7.0 so this all seems a little strange to me.

**Comment by malonnnn** [comment]
my plugins folder is a git repository, and I keep a copy on github, so you can find my config here, and i just pushed a copy for this post:

https://github.com/malonnnn/ServerConfig/tree/master/Magic

I cannot reproduce it on your server. I have upgraded to build #2274 with no success, it still acts very glitchy. 

I might be spitballin' here, but it seems to me that when the server 1st loads, I cannot right click to access spell inventory if my crosshair is pointed to air. But it works one time if I look at the ground and put a block in my crosshair. In this instance the inventory opens, and I can also close it again with right click, but I am unable to open it again no matter what i do. I will continue to test.

**Comment by NathanWolf** [comment]
The configs all look fine... the behavior your describing sounds super odd. Did this just start happening after you updated Magic? Did anything else change at the same time, like maybe you added some other plugins?

**Comment by malonnnn** [comment]
Honestly, I'm not really certain when it started happening. Magic isn't the main focus on my server and so I didn't notice the issue immediately. It may have occurred after updating to 7.0 or on a build after 7.0

**Comment by NathanWolf** [comment]
Ok, thanks for the info- it *feels* like something that would be do to some other plugin, maybe something like mcmmo, that would be blocking item use.

**Comment by malonnnn** [comment]
Got it fixed, it was all my fault. Nothing wrong with the plugin. Sorry to waste your time :(
