### ISSUE TITLE
startup error on magic 7.1

### ISSUE THREAD

**Issue by Devillion** [elBukkit/MagicPlugin#323]
I just did a fresh install on magic 7.1 and I'm getting this error on server startup:

https://pastebin.com/1sk4WbyY

**Comment by NathanWolf** [comment]
Oops, sorry! It looks like this would happen if you have SkillAPI but have its attribute system disabled. Does that sound right?

If so it's fixed in 7.1.1

http://jenkins.elmakers.com/job/MagicPlugin/2282/com.elmakers.mine.bukkit.plugins$Magic/

**Comment by Devillion** [comment]
yes, I was going to enable it, just hadn't done it yet.

**Comment by NathanWolf** [comment]
Great, thank you for confirming- that should be fixed, then.
