### ISSUE TITLE
Pvp restriction on every spell

### ISSUE THREAD

**Issue by GeMiniXCape** [elBukkit/MagicPlugin#329]
Today, my players found a problem. There is pvp restriction on every spell. Almost all of them are unusable. I don't know how this happened, but they are all this way. How do I fix this?

**Comment by NathanWolf** [comment]
Seems odd, did you enable a WorldGuard pvp flag for the whole work or something?  If you need to turn it off completely you can add this to your plugins/Magic/spells.yml

```
override:
  parameters:
     bypass_pvp: true
```

That will allow pvp with spells even in areas that disallow pvp.

I'd be curious to know what exactly happened, though.

**Comment by NathanWolf** [comment]
Did you figure out what was going on here? Did the pvp bypass fix it?
