### ISSUE TITLE
Wand has gone missing

### ISSUE THREAD

**Issue by iWessa** [elBukkit/MagicPlugin#330]
Hello! :)
First of all, I really LOVE this plugin. Okay, but now the issue.
When I create or just type /wand and use this wand it works fine, but when I want to switch from spells by hitting the right mouse button it opens up my inventory.  So the problem is when switching from spells is a hell. Continuously opening my inventory is not how it suppose to work I guess. The sword "Master Swords" in the other hand works great! When I press Q it just switches to my hotbar spells and it just works great!

[Command line interface message](http://prntscr.com/imv9b0)

I'm currently using the latest version of craftbukkit (from spigot) 1.12.2.
I also did download the latest version of Magic, but I thought maybe an earlier version would work, but it didn't. 

I hope you can help me <3

iWessa

**Comment by NathanWolf** [comment]
Do you have customized configs, especially config.yml or wands.yml? If so could you please put them in a pastebin and show me?

**Comment by iWessa** [comment]
Hi!
I have not edited any of the files. I also did delete the folder that it came with and reinstalled the plugin.
Here are the conifg and wands.yml in pastebin:
[config.yml](https://pastebin.com/VY6HXP5f)
[wands.yml](https://pastebin.com/Dc0he2UJ)

I do have other plugins installed. However I don't believe that's the case of not working properly.
[plugin list (I know, it's quite a lot)](http://prntscr.com/imybgq)

Hope to have informed you sufficiently :)

**Comment by NathanWolf** [comment]
Thank you! Clearly doesn’t seem to be config-related :)

That sounds like what happens in creative mode- is that it?

**Comment by iWessa** [comment]
Yes. The funny part is that it’s not only in creative mode. It’s like opening the gui store (for buying new spells)-inventory. 
I’m not ready for sending a picture of that. But it’s basically my hotbar + opening a kind of chest. (So it’s not the same as pressing E for opening the inventory).

**Comment by NathanWolf** [comment]
What you're describing is an intention mode of the wand called "chest". It should only engage if:

1. You've put your wand in chest mode. This can be done with a command or by using the tweak menu. "/wand describe mode" will tell you what mode you are in. "/wand configure mode inventory" will force the regular inventory mode.
2. You've put all wands in chest mode via configs, seems like that's not it.
3. You are in creative mode

So I guess it sounds like option 1 may have happened? Try checking your wand's mode with the describe command, but if that's not it then I am running out of ideas.

**Comment by iWessa** [comment]
Hi Nathan!
I'm back and now in-game. I checked everything. Made a new wand (in survival). The wand is in inventory mode and still. Right-click opens inventory and give me the [reflectionhelper] + [magic] error, like in the first message. This is what I see in-game:

[Output](http://prntscr.com/in8e0h) (The messages in-game is MCMMO. I sadly can't disable these messages).

I thought it was the "OldCombatMechanics" plugin, but it wasn't. 
I really really really hope you can help me further

**Comment by NathanWolf** [comment]
You please screenshot the output of these two commands?

`/magic`
`/wand describe`

The second one make sure you're holding the wand.

This is definitely a little weird, I can't see how another plugin would cause it.

**Comment by iWessa** [comment]
Alright here is the output of the commands you mentioned :)

[/wand](http://prntscr.com/in941y)

[/wand describe (1)](http://prntscr.com/in94sq)
[/wand describe (2)](http://prntscr.com/in9552)

Me neither, I can't see any of these plugins cause trouble

**Comment by NathanWolf** [comment]
Sorry, can you please do `/magic` so I can see what version you're on?

The wand configs look OK but they also don't look like the defaults from the current version.

**Comment by iWessa** [comment]
My current version is:
[Magic](http://prntscr.com/in9gh7)

from: https://www.spigotmc.org/resources/magic.1056/

**Comment by NathanWolf** [comment]
I just downloaded that specific version to make sure there wasn't anything weird.

So I'm at a bit of a loss, it must be due to some other plugin, but I can't imagine what. Have you had this problem since the first time you tried Magic, or did it ever work correctly?

Since you're saying the Master Sword works, it sounds like it's something specific to right-click, maybe? If so, try this in-game while holding your wand:

```
/wand configure right_click none
/wand configure drop toggle
```

That will make the Q button toggle the hotbar like how the sword works.

If that's OK by you and working well, you can make the change to your configs in wands.yml to make it affect all wands:
```
base_wand:
  right_click: none
  drop: toggle
```

**Comment by iWessa** [comment]
Yes. You're my hero! this works. It seems to be a plugin indeed. Maybe essentials/mcmmo I believe, however I can't find out how. Pressing Q works just like the Sword, awesome! I lost all my spells tho, you can make a shop to buy/unlock them, right?

**Comment by iWessa** [comment]
Oh I can finally right-click the enchantment table while holding the staff. Thanks Nathan!! <3

**Comment by NathanWolf** [comment]
If you update to the latest Magic, then spells get stored on the player and you won't lose them if something goes wrong with the wand item.

Otherwise you'd have you buy them again at the enchant table.

Glad I could help!

**Comment by iWessa** [comment]
One more question:
Can I just paste these rules in the wands.yml at the buttom? 
base_wand:
  right_click: none
  drop: toggle

**Comment by NathanWolf** [comment]
That's right, but make sure to preserve the indenting when you paste it.

**Comment by iWessa** [comment]
Nathan. Thank you very much for your help and time. I really appreciate it.
This is the final result:
[wands.yml](http://prntscr.com/inab73)

**Comment by NathanWolf** [comment]
That looks a little off- make sure there are no spaces in front of "wand:" at all. it should line up with the # comment character above it.

**Comment by iWessa** [comment]
[Like this? ](http://prntscr.com/inan6f)

**Comment by NathanWolf** [comment]
Looks right to me!

**Comment by iWessa** [comment]
Nathan. Thank you. I love you man 💃
