### ISSUE TITLE
Magnetic Leggings losing items

### ISSUE THREAD

**Issue by SullyTheUnusual** [elBukkit/MagicPlugin#332]
Sometimes when the magnetic leggings cast the Grab spell, items on the ground launch past the player and can get lost.

**Comment by NathanWolf** [comment]
I'll change grab to do a smaller velocity amount but repeat it several times with a delay- I think that'll make the items slowly gravitate towards you instead of flinging towards you wildly.

**Comment by NathanWolf** [comment]
I'm going to close this now, let me know if it's still an issue. I think the changes to the grab spell are working much better.

**Comment by SullyTheUnusual** [comment]
Yeah, items aren't flying past anymore.  My wife gave it a thumbs up.  👍
