### ISSUE TITLE
Master Sword main hotbar all spells stuck at 3 second cooldown

### ISSUE THREAD

**Issue by SullyTheUnusual** [elBukkit/MagicPlugin#333]
I don't know what triggers it, but sometimes my Master Sword gets stuck with all 8 spells on the main hotbar showing "3" and I can't cast.  Holding the normal wand and switching back seems to fix it.

**Comment by NathanWolf** [comment]
I haven't seen this myself but I will keep an eye out for it. Please let me know if you find some way to reproduce it!

**Comment by SullyTheUnusual** [comment]
Thanks, I'll try to find out a way to trigger it.

**Comment by NathanWolf** [comment]
Did you ever see this again?

**Comment by SullyTheUnusual** [comment]
A couple times, but I couldn't consistently reproduce.  When it does happen, switching active tool to a different wand, and then back to the sword causes the 3-second cooldown to count down normally.

**Comment by NathanWolf** [comment]
I *think* I found the issue with this looking into an unrelated bug, but I never could reproduce it so I'm not sure. If you don't see it again for a while (this fix should be in 7.3.1) I'll close this issue.

**Comment by NathanWolf** [comment]
I'm going to close this, but please re-open if you see it again on the latest build.
