### ISSUE TITLE
Mod Compatability Issue

### ISSUE THREAD

**Issue by tacticalskirt** [elBukkit/MagicPlugin#335]
i installed this death messages mod a bit ago
https://dev.bukkit.org/projects/completedeaths2
but when i installed the magic mod it stopped working completely, dunno whats up.

**Comment by NathanWolf** [comment]
I installed that plugin, see no issues. 

Do you have any errors in your logs or anything at all helpful?

**Comment by tacticalskirt** [comment]
maybe it just has to be loaded second, i'll try uninstalling and reinstalling it

**Comment by NathanWolf** [comment]
Any updates?

**Comment by NathanWolf** [comment]
Please reopen if you're still having issues.
