### ISSUE TITLE
Trait command on NPC's

### ISSUE THREAD

**Issue by AntonioC94** [elBukkit/MagicPlugin#336]
Hello nathan!
Is a little question about the trait command.
I tried to use that trait using a command of a own plugin.
The command is `/razas elegir `, this command is to open a GUI to select your race (The plugin is about races yes).
I tried to use this trait with @p at the end of the command 

`/mtrait command razas elegir @p`

but dont work , so... do you have idea about this to solve my problem?
Regards!

**Comment by NathanWolf** [comment]
Try `/mtrait console false` to make the player cast it

By default command traits use the console to run the command.

But note they will need permission for the command~

**Comment by AntonioC94** [comment]
Oh! , Its true, I didnt looked the console. 
Now works ,Thank you ^^

**Comment by AntonioC94** [comment]
A little question more , this trait its own of magic plugin right?
I want to say.. I will not have problems with citizens plugin

**Comment by NathanWolf** [comment]
The Magic traits do rely on Citizens, if that's what you mean.

**Comment by AntonioC94** [comment]
Yes, I was doubting about the possible "incompatibility" (I have more plugins adding more options to citizens) , But sorry for that ^^ , Thank you again

**Comment by NathanWolf** [comment]
Well hopefully it's not an issue but I do wonder what happens if some other plugin tries to add a "command" trait...

**Comment by AntonioC94** [comment]
Time to experiment muahaha .
Just for finish but... A NPC can have than more 1 mtrait? , for example... hat & command ? 
And in that case.. How can i look , all the traits for a NPC?

**Comment by NathanWolf** [comment]
NPCs can have many traits, yes ... I'm not really sure how to check them, that's kind of a Citizens question. Maybe just `/trait`?

**Comment by AntonioC94** [comment]
Aaam yes, I did it.  Is the basic command `/npc` to look all the properties including all the traits for that NPC.
I think, by the moment, I dont have more question about this, so... Thank you so much again ^^
