### ISSUE TITLE
Spells Dissapearing??

### ISSUE THREAD

**Issue by tacticalskirt** [elBukkit/MagicPlugin#337]
i upgraded to student and a bunch of my spells vanished? dunno whats up with that. is that supposed to happen? is this a bug? i really liked those spells and i cant even manually add them to a wand anymore

**Comment by NathanWolf** [comment]
Your wand was upgraded to multiple hotbars. You should have gotten a message in chat when you ranked up, along the lines of

`Press Q while your Wand is active to cycle hotbars`

**Comment by tacticalskirt** [comment]
my spells are not there

**Comment by tacticalskirt** [comment]
they arent in my spellbook anymore either

**Comment by NathanWolf** [comment]
Do you have access to the console on the server you're on? Can you do

```
/mage describe tacticalskirt spell_inventory
```

And paste what it says, along with a couple of the spells that have gone missing?

**Comment by NathanWolf** [comment]
... assuming tacticalskirt is your MC IGN

**Comment by NathanWolf** [comment]
Er, sorry, spell inventory is on wands.. I guess both would be helpful

```
/mage describe tacticalskirt spells
/wandp tacticalskirt describe spell_inventory
```

**Comment by NathanWolf** [comment]
Please reopen if you're still having issues.
