### ISSUE TITLE
Spell upgrade?

### ISSUE THREAD

**Issue by iWessa** [elBukkit/MagicPlugin#338]
Hi Nathan!

Can you please explain me how to upgrade my spells? 
I thought if I have 50/50 casts I could upgade to level 3 but all my spells are not getting higher than level 2.
[photo](http://prntscr.com/ipurq0)

Kind regards,

iWessa

**Comment by NathanWolf** [comment]
Where it says “Requires Squire” that means you need to rank up first. Collecting all of the spells for your sword at your current rank should do that.

**Comment by iWessa** [comment]
Thanks! one more question. Maybe it's another plugin that's blocking it, but I use essentials and worldguard. While I make a region and have without any permission or commands, like: pvp = deny.
My friend (normal player) can't use his sword nor wand. It says: You do not have permission to use it here.

Any solution? I'm getting so annoyed, I can't find it

**Comment by NathanWolf** [comment]
Certain spells are PvP restricted but most are not.

**Comment by NathanWolf** [comment]
If it says “use” versus “cast” that sounds more some other plugin though. Try

/mage check

While holding the wand, it should tell if you it’s some permission on Magic’s side.

**Comment by iWessa** [comment]
If he has OP permission and does a /mage check command he does he that he has enough permission to use everything, but when de-opped it says: Im sorry but  you dont have enough permission to perform this command. Please contact the admin.
When he goes out of the region that I made with world-edit & worldguard, he can use his wand again. But I didn't add any permission to that region?

Kind regards,

iWessa

**Comment by NathanWolf** [comment]
You would need to do the command on him then, having him opped is going to change the outcome.

/mage (player) check

Again, though, if it’s not a few specific spells and the whole wand suddenly becomes unusable that doesn’t sound like Magic doing it.

**Comment by iWessa** [comment]
Hi Nathan,

Me and my friend tried it yesterday, while he was opped and deopped. I did see the same message as he saw. Is there another solution possible? Maybe essentials/worldguard related? 

Without this solution I'm not possible to play. Because I want certain mobs spawn in certain regions where you can fight and use the wand/sword.

I hope you can help me forward.

**Comment by NathanWolf** [comment]
What do you mean by "it did the same message as he saw"? I thought the message he got was "Im sorry but you dont have enough permission to perform this command", meaning he couldn't even run the command?

If you can run the command and it shows all green, it may be worth screenshotting it and showing me anyway.

Also a screenshot of the exact message you get when trying to use a wand would help, and more information about when it actually happens. Swinging the wand? Right-clicking it? Can you drop the wand, is it activating at all, etc?

**Comment by iWessa** [comment]
Okidoki, I will show you. I know from experience when we right-click the wand an inventory is opening. In this inventory you can store any items you want and reopen (it just works like a chest). Sadly, because I have an other plugin for this. 

With "it did the same message as he saw" I ment: if I do /magic check quincey_023, I see the same message as he does /magic check. But that was yesterday, maybe I'm wrong. 

I will show you screenshots and commands. Is it okay if I come back tomorrow? I can't test it today.

**Comment by NathanWolf** [comment]
Ok, that's fine by me... but how are you using the wand at all if right-click is being intercepted by another plugin? Does that plugin just activate on right-click of any item? Did you switch wands to use Q instead?

I'm already very suspicious of what this other plugin is doing...

**Comment by iWessa** [comment]
The title of the chest that is opening is something Magic related I believe. It says something like: "Wand / Master Sword" for example. 

I've contacted you earlier about that issue when right-clicking. 
I couldn't change my spells, and you said you can change it to another key, like Q. I changed it and it worked! So we can use the spells for wands and swords. 

"I'm already very suspicious of what this other plugin is doing...", I'm curious :P

**Comment by NathanWolf** [comment]
> I know from experience when we right-click the wand an inventory is opening. In this inventory you can store any items you want and reopen (it just works like a chest). Sadly, because I have an other plugin for this.

What I mean is, you have some other plugin that makes it so when you (do something? right-click an item?) an inventory opens that lets you store items?

If so that's sounding a lot like what is causing your issues with wand right-clicking, and maybe these permission issues, too.

I may be mis-reading what you're saying though.

**Comment by iWessa** [comment]
"What I mean is, you have some other plugin that makes it so when you (do something? right-click an item?) an inventory opens that lets you store items?" I understand what you saying. Perhaps my [Bags2](https://www.spigotmc.org/resources/bags-2.45989/). 

"and maybe these permission issues, too." This I do not really understand to be honest.

"I may be mis-reading what you're saying though." You get me right :)

But, the real problem here is that people who are not 'opped (admin)' cannot use wand in a region that I made. The weirdest thing is, I already made 1 region earlier and in that region the players can exactly use the wand.

**Comment by NathanWolf** [comment]
I tried out Bags2, it is definitely what is causing your right-click issues.

I couldn't reproduce the permission issues, though. So hopefully when you get a chance to show me the exact message and output of `/mage check` I can help with that.

Looking at my messages, I was wrong- the no permission message for a spell is `You don't have permission to use that here.` Which sounds like the one you were getting. The check command should tell us why.

Have you tried just casting something like Blind or Poison?

Some spells, anything that breaks blocks, will not be available in a region where you have no build perms.

**Comment by iWessa** [comment]
Alright! That's great. 

Nathan, I'm very sorry, but I'm not an coder. Is there a way / code to change the right-click to perhaps pressing B or something. Or change the item? Because I think it is the item that is making trouble. 

**_Have you tried just casting something like Blind or Poison?_** This, I don't know.

I only made the region, with: /rg define NAME. I didn't add any of the permissions/restrictions to the region. And after he said he couldn't use the wand, I added permissions to allow spells, wands etc, but didn't help either.

**Comment by NathanWolf** [comment]
When you make a region, no one can build there. If they can't build there, they can't modified blocks with spells, either.

First thing to try is casting a spell that doesn't change blocks in any way. 

If that works, then this is your problem.

If you still want to allow spells that break or place blocks, do

`/region flag NAME allowed-spells *`

You will have issues with Bags2 and Magic together, unfortunately. This doesn't seem avoidable unless you're willing to rebuild the RP to change Magic wands to a different item. Bags2 is taking over right-click (and who knows what else) of all hoe items, it doesn't seem to care about whether it is a bag or not.

**Comment by iWessa** [comment]
**_it doesn't seem to care about whether it is a bag or not._** Well, I guess I have to delete that plugin? That was the only plugin that was suiting my idea ;P

**_When you make a region, no one can build there._** Weird that in my other region it does work, even with the permission: /rg flag NAME build deny.

**_/region flag NAME allowed-spells *_** I will try this command tomorrow tho.

**Comment by NathanWolf** [comment]
The bags plugin doesn't seem to be configurable at all. How is it working for you? Are you not using Magic's RP, or do your bags just look like wand and spell icons?

You don't have to delete it, necessarily, but it seems like it's going to mess with wands. If you're OK with wands using Q instead of right-click then maybe it's fine.

**Comment by iWessa** [comment]
That's pretty sad. I mean I can't use the resourcepack of bags2, because of the Magic resourcepack. If I want to use them both it changes the wands in hoe's (the original item). 

Magic's RP? I can't find it on your page? Is that Magic World?
Never heard of it.

I think I will delete the bag plugin, because otherwise you have too many bags (and free bags), because I want them to pay for a bag. 

Btw I will test this command tomorrow: 
**_/region flag NAME allowed-spells *_**

**Comment by iWessa** [comment]
Sorry, couldn't work on the server today. I will connect you tomorrow!

**Comment by iWessa** [comment]
Hi Nathan!
IT WORKED!! I tried I myself. I also made a global region (for the whole server) and noticed that I had the same problem. So I opped myself again, forced the command for a small region (like a cave) and deopped myself again, and outside that region I couldnt use my wand but when I went inside I could!!

Thank you so much for helping me. If I could give you 10 stars, I did <3<3

**Comment by iWessa** [comment]
The LAST question Nathan. Really the last question. Is there a command for blocking magic missle? Because when I go out of the region I can't use fireball but I can use magic missle

**Comment by NathanWolf** [comment]
Most spells should be available within a region, Fireball isn't because it can break blocks and start fires.

If you want to deny ALL spells somewhere, use "blocked-spells *". If you have a region inside of that where you do want spells to work, use "blocked-spells -" to return things to normal.

**Comment by iWessa** [comment]
Got it! Thank you very much
