### ISSUE TITLE
Configuration files/folders confusing me

### ISSUE THREAD

**Issue by jamesol1** [elBukkit/MagicPlugin#339]
I open the /yml's with notepad++ and the all of the lines of text has # before it so the entire thing is commented out. So do i have to go through each yml file and remove the # before all the lines (excluding the notes for players)? I don't mind doing that, it's just i haven't experienced configuration like this.
The folders i have in my 'Magic' plugin folder are all empty by default. Is that correct? Right now the only thing that seems to work on the plugin is the default strike spell on the beginner wand. The enchanting table doesn't seem to have spells for sale or anything. I'm just confused. 

Thanks!

**Comment by NathanWolf** [comment]
You don't really need to mess with configs unless you want to customize.

There is nothing to edit in Magic's configs, the comments are in there to show you examples of what you can add.

If you are holding a wand and right-clicking on an enchant table and not seeing a menu come up, then something is broken!

**Comment by jamesol1** [comment]
Thanks for the very fast reply!
Ok that makes sense. So you remove the hashtag of lines you want to add to the plugin? Also is it normal that the folders in the magic plugin folder are empty?

**Comment by NathanWolf** [comment]
The defaults folder should have files in it. Those files show you what the default configs look like, but you can not edit them.

So yes if you want to add or modify the plugin, you either remove the hashes to uncomment lines, or (most commonly) you would copy+paste something from the default configs and change it.

The best approach is to play around with the plugin first, and if there is something you feel needs changing, change that specific thing.

For instance if you feel like Blink needs a longer cooldown, you would add that to your plugins/Magic/spells.yml like this:

```
blink:
  parameters:
    cooldown: 90000
```

The empty folders are mainly there for those who want to create completely new spells, wands, mobs. Most often you would copy an existing spell into the proper folder, rename it and start modifying it.

So is the enchanting table working for you?

**Comment by jamesol1** [comment]
The enchanting table is now working thanks. Silly error on my part. 

Just to clarify the empty folders are for creating new stuff etc. The .yml files (not the ones in the default folder) are there for editing pre-existing spells/settings etc. Not all of the settings are in the .yml files so you will most of the time have to add in stuff from the .yml files of which have all the possible options.

Thanks for clearing that up!

**Comment by jamesol1** [comment]
One quick question:
How do i remove/disable spells? I can't edit the .yml's in the defaults... do i put something like...
Blink:
   Disable: true

**Comment by NathanWolf** [comment]
That’s pretty much all right! To disable a spell do

```
blink:
  enabled: false
```
