### ISSUE TITLE
Config option "wand_undroppable: true" does not prevent players from putting wands in shulker boxes

### ISSUE THREAD

**Issue by malonnnn** [elBukkit/MagicPlugin#340]
It works for all other containers though.

using Magic 7.3-SNAPSHOT-a8a61

Thanks!

edit:
tested a few other things like donkey/llama inventories, they work okay, its just shulker boxes

**Comment by NathanWolf** [comment]
Oops, fixed in latest dev build, targeted for 7.3

**Comment by malonnnn** [comment]
@NathanWolf 

It doesn't seem to have worked, running Magic 7.3-SNAPSHOT-29695 now

**Comment by NathanWolf** [comment]
Hm the change should be in that version. Is it working for you with other containers? You're not opped?

**Comment by malonnnn** [comment]
Okay, after further testing, players cannot put wands into a shulkerbox/chest, but they are able to take them out if they were already stored, that's where my confusion came in.

So I supposed it's fixed :)

Thank you!
