### ISSUE TITLE
Wand tooltip showing wrong info

### ISSUE THREAD

**Issue by SullyTheUnusual** [elBukkit/MagicPlugin#342]
I just upgraded my Beginner Wand to Apprentice, and here's the tooltip:

https://imgur.com/a/SNqPB

**Comment by NathanWolf** [comment]
Hm- upgraded it via the normal rankup process?

I did change the descriptions for the canned wands that you get via /mgive ... but that shouldn't have affected rankup.

That also does look broken, it should be a newline :\

**Comment by SullyTheUnusual** [comment]
Yeah, upgraded it by unlocking spells.

**Comment by NathanWolf** [comment]
Huh, I can't reproduce it... I could undo that change but I can't see how that would have happened. Is it maybe something in your custom configs, did you do anything with the wand configs?

**Comment by SullyTheUnusual** [comment]
Not that I can see...  You want my Magic folder? lol

**Comment by NathanWolf** [comment]
Hm - maybe? Does the wand recipe give you “wand” or “beginner”?

It looks like you got a “beginner” wand which is outdated, I’m in the process of changing it to just be a demo wand that is not tied to player progression.

Does that make sense? Any chance you’re getting a beginner wand instead of the default wand?

**Comment by SullyTheUnusual** [comment]
Crafting a wand gives me "Wand" at the top, and the lore looks correct.  Wands who have already been given on first login seem to be affected, though.  Sent you my folder via PM on Spigot.

**Comment by SullyTheUnusual** [comment]
Ok,now I upgraded my Apprentice wand to Master and the icon never changed.  I'm not sure what I broke now.  lol

**Comment by NathanWolf** [comment]
oooooh whoops! I'm guessing you're working off of this suggestion in my config.yml:

```
# e.g. welcome_wand: beginner
```

... that should be changed to "welcome_wand: wand" 

But now I guess you have the problem of people all have the "beginner" wand .. hm

Assuming you want that to work just like "wand" I think you want to put this in wands.yml:

```
beginner:
  inherit: false
  migrate_to: wand
```

I'm hoping both of those changes will get players to switch over to the "wand" template. Sorry for the trouble!

**Comment by SullyTheUnusual** [comment]
No problem, thanks for the help again!  I upgraded to build #2381, and make your suggested changes.  The master wand I have still shows the "\n" in the lore.  I tried "/mgive <player> master", but it seems to give the regular "wand".  I checked wands.yml, and there's still an entry for "master", so not sure what happened.

**Comment by NathanWolf** [comment]
Huh- it seemed like putting the descriptions on quotes fixed them for me, did it not update when you held it?

I should also clarify what I've done with these wands now, though. The `/mgive wand` wand is the only "real" wand now. It is the one that will let you learn spells that are bound to your player class.

The other wands, beginner, apprentice, student, master - these are preset example wands meant to demo what spells a player might have when they get to each of those ranks.

You can of course change this all back to how it was if you want, and it sounds like you might have a "master" wand in your wands.yml already? If you let me know what you're trying to do with them I'm sure I can help out!

**Comment by SullyTheUnusual** [comment]
Ok, it looks like the lore fixed itself when I changed tools, and then changed back.  It's back to the first icon though (wood_hoe:1), but I've unlocked all spells.  Is there a way to update the icon?  Thanks again, sorry for the hassle.

**Comment by NathanWolf** [comment]
No hassle- you can update the icon via `/wandp configure icon wood_hoe:4`

Little weird that it's not updated though.

So are you using the master/apprentice/etc wands on your server, like players can get them? I think if so you'll want to customize them a little so they work more like the class-based `wand`

**Comment by SullyTheUnusual** [comment]
The old wands are still in Magic/defaults/wands.defaults.yml, but I added the "migrate_to" text you posted to my Magic/wands.yml, so I'm thinking that should take care of it.  I just thought maybe the icon would update when using "mgive <player> wand" based on what spells were learned.  Not a big deal though, since there's a command to change the icon (thank you!), and I doubt the situation would come up very often.  As long as the icons update normally when players' wands upgrade, everything is fine.  :)

**Comment by NathanWolf** [comment]
Ok cool- yeah I think the migrate_to is the way to go!

I am thinking of further changing the wands in the defaults so they aren't even upgradeable at all, just to be totally clear that they are demo wands and hopefully no one will get in this situation again.
