### ISSUE TITLE
No sound when casting spell

### ISSUE THREAD

**Issue by iWessa** [elBukkit/MagicPlugin#343]
Hi Nathan!

I downloaded the new version of Magic!
Congratz on the logos for the spells! <3

The problem is that I don't hear spell sounds anymore when casting.
I tried to enable the sound in the config manually, but doesn't work

I hope you can help me out!

Kind regards,

iWessa

**Comment by NathanWolf** [comment]
Ooops I broke the resource pack, it's fixed now. You can get the update immediately by
```
/magic rpcheck
/magic rpsend
```

Thanks for the head's up!

**Comment by iWessa** [comment]
Thanks! Dope <3
