### ISSUE TITLE
How can I make skill trees?

### ISSUE THREAD

**Issue by poolcool2** [elBukkit/MagicPlugin#345]
The config files somewhat confuse me, I want to make a skill tree where the players chose a type of mob and then have strong spells related to that mob, but weaker everything else.

example: a Enderman class which can have stronger teleport spells, regular basic attacks, and weaker everything else
and a Witch class, with strong buff and debuff spells
and each class also having some spells unobtainable or just unusable, like enderman class not being able to use water based spells.

how would I go about doing this?
If I could get a link to a instructional video that would teach me how to do this, that would be much appreciated

**Comment by NathanWolf** [comment]
The bending configs are probably the best thing to look at:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/examples/bending/classes.yml

You would start by making classes like that, giving each class a set of spells. Then allow a player to choose a class

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/examples/bending/spells.yml#L649

There are no instructional videos for any of this, you're going to have to be able to learn by example and by reading the wiki.

**Comment by NathanWolf** [comment]
Did that help?
