### ISSUE TITLE
Air Scooter does not consume mana over time

### ISSUE THREAD

**Issue by VoidAngel** [elBukkit/MagicPlugin#346]
Hey just a quick bug report. 
Ive found that in v 7.3.1 (and possibly the lower versions) air scooter does not consume mana over time. It seems to take the initial mana cost though. This allows players to use air scooter infinitely.
Im on spigot 1.12.1 and using the default spell config with no errors in console.

**Comment by NathanWolf** [comment]
Thanks, I see it- I'll fix it for the next dev build.

**Comment by NathanWolf** [comment]
I've also made Levitate, Air Scooter and Boon prevent mana regen while active.

This ensures that a player's regen rate doesn't overtake the active cost drain, allowing them to keep the spell active forever. People may complain....
