### ISSUE TITLE
Wands don't work while standing on redstone ore

### ISSUE THREAD

**Issue by SullyTheUnusual** [elBukkit/MagicPlugin#349]
Wand and sword won't cast spells or switch to spell mode while standing on redstone ore.

**Comment by NathanWolf** [comment]
Did you mean redstone wire, or actual ore?

**Comment by NathanWolf** [comment]
Hm, nevermind you did mean ore.. how weird. Seems like standing on redstone ore fires off constant interact events.. I bet I need to filter them out.

**Comment by NathanWolf** [comment]
Should be fixed in latest dev build. This was also breaking wands when standing on pressure plates.

**Comment by SullyTheUnusual** [comment]
Yep, it's fixed.
