### ISSUE TITLE
Make the Cure spell cure zombie villagers

### ISSUE THREAD

**Issue by SullyTheUnusual** [elBukkit/MagicPlugin#352]
Maybe at a higher tier?  I just thought it would be a fun addition.  :)

**Comment by NathanWolf** [comment]
That is a fun idea 😄 

I'll have to look at how it's done in vanilla, wonder if it's something more sophisticated than replacing the mob.

If so... kind of morbid to think when you "cure" a zombie villager you're actually just killing him and spawning a new villager in its place... how existential.

**Comment by SullyTheUnusual** [comment]
It looks like the Zombie Villager is removed, and the Villager is spawned in (according to monsters/EntityZombieVillager.java), so yeah, kinda morbid.  lol

**Comment by NathanWolf** [comment]
This is in the current dev build and will be in 7.5.3 as Cure Level 5
