### ISSUE TITLE
How much lagg does Magic create?

### ISSUE THREAD

**Issue by jamesol1** [elBukkit/MagicPlugin#354]
I'm planning on making a small server primarily based around the Magic plugin. It's really just for fun i know I'm not going to be making any money back. But i would like to know how good of a host/amount of GB I'd need to have the plugin working for like 10 people on at once.
I'm assuming it comes down to what and how many spells are being used. Also automata I'm sure would cause lagg. I could potentially trim down the spells based on how intensive they are etc.

**Comment by NathanWolf** [comment]
It shouldn’t be bad at all with only 10 players, even with automata.

I can’t really suggest exact specs but if you can easily upgrade later, just start with the smallest instance you can get and see how it goes.
