### ISSUE TITLE
Disable the use of wand and brooms

### ISSUE THREAD

**Issue by AntonioC94** [elBukkit/MagicPlugin#355]
Hi nathan, so... its simple, i was looking the API and.. where is the code to disable the use of wands and brooms?
Regards!

**Comment by NathanWolf** [comment]
There is nothing like that in the API, best to just use permissions. You can set them via your plugin if you want. Magic.wand.use will disable all wands and brooms for a player if negated.

**Comment by AntonioC94** [comment]
Oh! I didnt saw that.. In my opinion more easy C:

**Comment by NathanWolf** [comment]
Great- I assume this is OK to close then?

**Comment by AntonioC94** [comment]
yes C:
