### ISSUE TITLE
GravityUpdater Conflict

### ISSUE THREAD

**Issue by BSKCorp** [elBukkit/MagicPlugin#365]
I had posted a similar issue on Spigot itself between Magic and Ore Announcer I think it was. Once Magic was removed (a earlier version) the error stopped showing up in my server logs. Only on start up. Decided to wait a bit, I just recently updated Spigot and it's buildtools just yesterday. Added in Magic 7.3.8 and now I get a strange Thread exception from Areashop lib updater and Ore Announcer again. 

https://pastebin.com/DLSfLwfg

Once I remove Magic, it does not appear. Any clues?

**Comment by NathanWolf** [comment]
I'm afraid I have no clues. The only way some other plugin would be able to crash those plugins like that is if they had included the org.common.json package in their own jar and there were conflicts.

But Magic doesn't do that, there's nothing from org.* at all or any external libraries for that matter.

I thought the OreAnnouncer dev helped you to resolve this?

**Comment by NathanWolf** [comment]
I do see what you mean, though. The error seems to happen very reliably with Magic installed, but not without.

I have no idea why that would be but I will see what I can find out.

**Comment by NathanWolf** [comment]
Finally got this fixed in 7.4.2 - sorry about that!

**Comment by BSKCorp** [comment]
Oh awesome, XD And no need to apologize. I ran a "Dev" friendly technic pack that always used the latest versions and reported bugs. I enjoy doing it. Thanks for the update.
