### ISSUE TITLE
Equipping spells

### ISSUE THREAD

**Issue by grisstyl** [elBukkit/MagicPlugin#366]
I have a spell that has an icon set to a pumpkin. When I shift-clicked it to put it in my inventory it was equipped and is unremovable. I didn't test this for other equipable items like armor.

**Comment by NathanWolf** [comment]
Oh good catch! Just need to add pumpkins to the wearables list in materials - feel free to PR if you’re up for it!

**Comment by grisstyl** [comment]
Submitted
