### ISSUE TITLE
Local resource pack

### ISSUE THREAD

**Issue by 1Z2O3R4O5A6R7K8** [elBukkit/MagicPlugin#374]
Hi where i live good internett is imposibel and right now that makes me unable to load a server becouse of the resource pack, i would like to have it instaled localy so i still can use it. unfortunatly i cant finde a place where it works, the link on the png i added to this message takes you to a 404 page. hope this can be fixed.

![rf4gdgrd](https://user-images.githubusercontent.com/39034473/39677032-e9e746d8-5174-11e8-9d3d-133f3ab6fd6f.PNG)

**Comment by NathanWolf** [comment]
Thanks, I fixed the link on the wiki. The RP download is here:

https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-RP-7.zip

Just bear in mind it updates frequently. If you ever update the plugin and some new items don't look right you may also need to redownload the RP.

**Comment by 1Z2O3R4O5A6R7K8** [comment]
Wow that was quic: Love the service here. i will bear that in minde.
