### ISSUE TITLE
magic plugin rankup.

### ISSUE THREAD

**Issue by Baracos** [elBukkit/MagicPlugin#375]
Hey Nathan. 

I have a problem. i did whit my wand /wand enchant and become Wizzard. there is a way to get Conduit but how i do that? i already bought al the spells in the enchantment table. and is there a command to rankup from Wizzard to Engineer?

**Comment by NathanWolf** [comment]
The real way:
https://github.com/elBukkit/MagicPlugin/wiki/Progression#engineering-magic

Otherwise these commands should get you maxed out:
```
/wand add rollback
/wand add absorb
/wand add backup
/wand enchant 1000
```

**Comment by NathanWolf** [comment]
I hope this answered your question! If not, please re-open.
