### ISSUE TITLE
MagicMobs API

### ISSUE THREAD

**Issue by christophe6** [elBukkit/MagicPlugin#383]
Is there any way to spawn/create and manage magic mobs with the magicapi?

**Comment by NathanWolf** [comment]
Yup, easiest way is via [MageController.spawnMob](https://github.com/elBukkit/MagicPlugin/blob/master/MagicAPI/src/main/java/com/elmakers/mine/bukkit/api/magic/MageController.java#L406)

**Comment by christophe6** [comment]
Thanks a lot!

**Comment by christophe6** [comment]
Does magic support amor stand mobs for example 3d modeled mobs placed on wooden hoes with durability?

**Comment by NathanWolf** [comment]
Not complex animated ones, but you could use LibsDisguises to make a mob with an armorstand disguise that is wearing a specific item.

**Comment by NathanWolf** [comment]
https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/examples/elworld/mobs.yml#L67

**Comment by christophe6** [comment]
Oh thanks! Got it!
