### ISSUE TITLE
"Negative Review"

### ISSUE THREAD

**Issue by SulphurSlap** [elBukkit/MagicPlugin#389]
I have to post here since the stupid system on spigot won't make me reply to your reply on my review.

OK so, I was the person that recently posted a review on how I can't drop wands, but for some reason or another the author told me it was a negative review and he said how frustrating it is. Well it's quite frustrating hearing four stars is a negative review.
His reply:
"Wands are undroppable by default. This is configurable. **Leaving a negative review** without asking about simple things like this first is really frustrating."
I was scrolling down the reviews, and someone gave the author one star and would probably give him 0 stars if it was an option, but the author didn't even answer the question, he just, as always complained and said this is the worst review.

_When someone gives a 4-1 star, please to spare people reviewing in the future some time, take it as constructive criticism and not your bullshit statement as a "negative review"._

Heck I might get banned or blocked from here because the author is so needy for a positive review on here.

**Comment by NathanWolf** [comment]
I dunno if killme locking this means OP can't see my response, but I'm just going to put my explanation here anyway. Hopefully

Leaving a review for support is a dumb thing to do, no matter how many stars you give it. As you can see, it just gives me a single chance to respond, and no way for either of us to follow up. This is why it asks very clearly in project page not to do this. There are many avenues for support (github issues, which you seemed to have no problem finding), Spigot discussions page, Discord. Reviews are not one of them.

As for being "so needy for a positive review", the Spigot projects list is really the only place where people can kind find my plugin. The ranking algorithms there are such that 1 4-star review is enough to drop me off the first page, and it takes 10 5-star reviews before it recovers. So by "leaving a negative review", yes 4 stars is negative and you've just buried my plugin.

I try to be very accommodating to anyone asking for help... but, yes, it's frustrating. It's frustrating to work hard making users happy, but have one bad egg ruin it. It's frustrating that you can't read and follow the most basic of instructions. It makes me not want to help you at all, and you coming here and leaving yet another trashy BS passive-aggressive "issue" really drives the point home.

We do this for free, in our own spare time, and your complete lack of appreciation for that fact makes you look like an entitled ass.
