### ISSUE TITLE
How to use command release spells？

### ISSUE THREAD

**Issue by AaronHzy** [elBukkit/MagicPlugin#390]
How to use command release spells？

**Comment by NathanWolf** [comment]
I’m sorry, I’m not sure what you mean. Could you please elaborate?

**Comment by AaronHzy** [comment]
I want use command release spells
Don't use wands

**Comment by NathanWolf** [comment]
You can use the /cast command, but it's not really meant for players.

I suggest you take a look at another plugin- MagicSpells, Heroes and SkillAPI are all good alternatives. This plugin really revolves around the wand items, and is not meant for players to use commands.

**Comment by AaronHzy** [comment]
OK Thank you!
