### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by AntonioC94** [elBukkit/MagicPlugin#393]
Hi nathan! so.. I was editing my custom plugin, to get skill points from magic api and i have this error (just in the last version). Maybe the API is different? 
Error : https://hastebin.com/xefimaruta.vbs
My code: https://hastebin.com/kemesabila.cs

Line 66 = 16 `Mage alumno = main.api.getMage(nombre);`

**Comment by killme** [comment]
Are you sure magic is marked as a dependency of your plugin in your plugin.yml, that it is installed and that it loaded on your server?

**Comment by AntonioC94** [comment]
Yes, was an stupid error by me. MagicAPI was not inicializate in my onenable jeje, thank you :)
