### ISSUE TITLE
Wand effects broken

### ISSUE THREAD

**Issue by christophe6** [elBukkit/MagicPlugin#395]
Hello

It seems like wand effects do not work anymore. When I do /mgive redeffects, I receive the item. I open my wand inventory, the item disappears but I do not see any effects. It's not a texturepack issue sadly :( . Thanks!

**Comment by NathanWolf** [comment]
It changes the color of some of your spells, like magic missile.

It does not add any particle effects to your wand, though it will color the “bubble” effects if you add them.

This is how it’s always worked.

**Comment by christophe6** [comment]
Oh thanks!
