### ISSUE TITLE
All wands freeze and/or lose targeting.

### ISSUE THREAD

**Issue by hackharvester** [elBukkit/MagicPlugin#397]
Every once in a while, all wands on my server will either freeze their regeneration, or stop targeting. 

Example Default: The default wand casts the magic missile spell correctly, but does not regen. (this only happens on default wands)

The custom wands maintain generation, but projectiles revert their target to the players position, and any other type of spell may directly impact the player, with the exception of equipping or damaging. 

Example Custom: My server has a UFO wand, which is a small ufo that casts the "Glide" spell. 
The UFO launches the player, displays the messages, but does not give elytra or allow the player to glide.

We also have the Spark Wand, which simply shoots a flare. 
The Spark Wand fires the flare, but at the player's location. As in the flare does not move, and explodes on the player. Interestingly however, it tracks the player as if it were "glued" to them.

**Comment by NathanWolf** [comment]
Are you saying these things don't happen consistently, but sometimes the custom wands work and sometimes they don't?

Can you reproduce any of this behavior reliably? If so, could you provide the configs of the wands that cause the problem?

I have not seen (nor seen reported) issues with default survival wands stopping their mana regen. Indeed, mana regen isn't tied to the wand anymore (btw what version of the plugin do you have?)

**Comment by hackharvester** [comment]
My version is the latest up on spigot, also nope, no correlation as far as I can tell. They all stop working at the same time, and don't fix until a restart. https://pastebin.com/E8LHAFMY - Configs for custom wands in no particular order. Thanks for the fast reply btw!

**Comment by NathanWolf** [comment]
Very weird! I’ll yes this out when I can. Have you checked for errors in your logs around the time things stop working?

**Comment by NathanWolf** [comment]
Please do check for errors the next time this happens. I'm hoping there will be something there to help me track this down.

I tried out your wand configs, it's just me testing and I only had about 10 minutes to run around randomly casting, but things seemed ok. There's nothing odd about your wands that I think would cause issues other users wouldn't be seeing, especially since you are having issues with the default wands as well.

So my best guess at this point would be a plugin incompatibility issue but that will be very hard to track down without some error logs.

One random note btw: Glide doesn't actually give an elytra anymore, but it should still allow the player to glide.

**Comment by hackharvester** [comment]
Glide is still giving players elytra on the newest version downloaded from spigot. I have no idea what's going on at this point. Also, no errors are attached. Thanks for the help though, ill begin removing plugins one at a time.

**Comment by hackharvester** [comment]
Ill check the configs out, Brackets might have screwed with the files.

**Comment by hackharvester** [comment]
After a quick look, it seems all my configurations are still default, with the exception of the resource pack being disabled and replaced by my custom pack.

**Comment by NathanWolf** [comment]
When you say "default" do you mean that they are empty files (just yaml comments) or that you copied all of the default configs into your own configs at some point?

**Comment by hackharvester** [comment]
They are the plugin generated configuration files, with the exception of the resource pack being disabled so that I can load my own adaptation of it. (same models as the OG with some added JSONs pointed at the diamond sword)

**Comment by NathanWolf** [comment]
Just so I'm completely clear could you please pastebin your spells.yml?

I mean to say it should be completely empty except for comments.

**Comment by hackharvester** [comment]
Spells.yml Is completely empty. Also, I tracked down a few issues. ProtocolLib didn't like my version of spigot, and was causing issues with the plugin, so was McMMO (mcmmo broke on update), and Teleport+. On updating, (as said before) McMMO broke completely, ProtocolLib behaved, and Magic runs without delay, complains, or issue. I'll update you in a day or two of testing to see if the bug persists. Thank you for your help!

**Comment by hackharvester** [comment]
Forgot to mention, Glide no-longer gives the player Elytra. Still no clue what made that happen.

**Comment by hackharvester** [comment]
An update of all plugins and the server itself has fixed the issue
