### ISSUE TITLE
can't cast spells.

### ISSUE THREAD

**Issue by Daviduhh** [elBukkit/MagicPlugin#398]
When a player cast spells i am getting this in the console and nothing happens.

https://hastebin.com/isuqayakah.cs

how do i fix this?

**Comment by NathanWolf** [comment]
I believe that's an issue with your WorldGuard configuration. If you can't fix the core problem, you can fix spell casting by turning off WorldGuard integration, put this in plugins/Magic/config.yml

```
region_manager_enabled: false
```
