### ISSUE TITLE
Change wand ID 

### ISSUE THREAD

**Issue by Kasty123** [elBukkit/MagicPlugin#402]
Hi i need to change wand IDs because i have residence plugin on my server and with magic plugin residence cant function 

Magic version 5.5.3
MC server version 1.8

**Comment by NathanWolf** [comment]
What is residence doing that is interfering, exactly? Does it have an RP or GUI menus?

You can change the items wands use, but it's going to break the RP unless you also remake that, which is going to get complicated.

**Comment by NathanWolf** [comment]
Please re-open if you still need help with this.
