### ISSUE TITLE
how to chagen the Languages to Chinese

### ISSUE THREAD

**Issue by Philip6034** [elBukkit/MagicPlugin#403]
how to chagen the Languages to Chinese
I don't good at english

**Comment by NathanWolf** [comment]
Download this file: 

https://raw.githubusercontent.com/elBukkit/MagicPlugin/master/Magic/src/examples/localizations/messages.ZH.yml

And place it in `plugins/Magic/messages/`

It is a little out of date but should be a good start.

**Comment by NathanWolf** [comment]
Please re-open if you need more help!
