### ISSUE TITLE
Signs

### ISSUE THREAD

**Issue by T13m3n** [elBukkit/MagicPlugin#407]
How do i use signs or make an gui for people to select classes? And when they select iT get the items immediatly?

**Comment by NathanWolf** [comment]
See the Star Wars class chooser for an example of how you'd set this up:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/examples/stars/spells/starshop.yml

Magic has no support for signs at all, but I'm sure you can find some plugin that runs commands from signs. Or just use NPCs:

https://github.com/elBukkit/MagicPlugin/wiki/NPC
