### ISSUE TITLE
Sandblast spell issue

### ISSUE THREAD

**Issue by TofPlays** [elBukkit/MagicPlugin#409]
So I have these flags in a region:
build deny
block-place deny
block-break deny
allowed-spells *

However, when I cast the sandblast spell, after the sand touches the ground it drops on the ground as items. It is because block-place flag is disabled. But if I enable that flag players will be able to place blocks, which I don't want. So does that mean that I can not have the Sandblast spell working normally in a region that I don't want players placing blocks?

**Comment by NathanWolf** [comment]
It's because of "build: deny". It's a known bug the WorldGuard devs are not interested in fixing. They recommend not using that flag. I think block-place: deny on its own is supposed to be fine though.

**Comment by TofPlays** [comment]
So I guess I have to deal with it? no way around it? 
I tried:
build allow
block-place deny

but sand still pops up as items

**Comment by NathanWolf** [comment]
Have you tried removing the build flag completely? They just recommended I not use it at all.

Otherwise, you could ask them for help. I'm kind of done with their dev team, they've been nothing but jerks anytime I've ever asked them anything. Sorry :(

**Comment by TofPlays** [comment]
Oh, thats sad to hear. and also may I ask, is there an option to disable the blocks from popping up, for example on explosion spells where blocks go everywhere and drop as items,

**Comment by NathanWolf** [comment]
Does removing the build flag not fix it?

**Comment by TofPlays** [comment]
It didn't fix it

**Comment by TofPlays** [comment]
it's the block-place: deny thats preventing it

**Comment by NathanWolf** [comment]
Can you just remove all of those flags? 

No one can break/build in a region by default, unless they are members or owners. I'm not even sure why those flags exist, except maybe so you can set them to allow to let people build/break.

**Comment by TofPlays** [comment]
Oh yes! I simply removed block-place  block-break  and build flags,  Now as a default member i cant break or place blocks and sanblast works fine!   thanks for helping :)
