### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by vicehound** [elBukkit/MagicPlugin#411]
I can't tell you how long I've been playing minecraft now that I have this plugin and I love grinding down mobs and casting to learn new spells. however, I think I've run outa room in my inventory. Now spells seem to be disappearing. Is this working as intended?

**Comment by NathanWolf** [comment]
Once you run out of room you wand inventory gets new pages. Click outside the inventory to switch pages.

**Comment by vicehound** [comment]
Thanks mate!!
