### ISSUE TITLE
Spells as Items (Quest and Dungeon rewards)

### ISSUE THREAD

**Issue by Koszatniczek** [elBukkit/MagicPlugin#413]
**G'evening mortals.

I'd like to ask, as I really despise giving the players all the freedom in getting the spells to wreak havoc with - would it be possible, and if so how hard would it be to do to turn the Spells into soft of ... item currency?**

**Say, a Fireball spell. Instead of it going into the wand memory:**
- You get a "Fireball Book/Scroll" item from a dungeon chest / buy it from another player / loot it
- Once ... Used? Read? The spell from the book goes into the wand memory [Like now]
- The spell can be "Pulled out" of the wand memory, and converts back into a Book for storage
- When a player dies, his wand drops. It can not be "used" by other players as it is bound, BUT! another player may dissect it and pull the spells from out of the wand for his own use [As Spell Books]

**The goal of mine is to make the system more controllable, as in who can get what kind of spell and how (I don't want every spell to be just ... bought. I want more challenge for stronger spells, like them being an ultra-rare drop from a MythicMob, or found in a chest at the end of a hard dungeon/quest)

Also, I'd like the spells to be kind of a currency - giving the ability for the players to store their spells, trade them with each other ... kill other players for their spells, or even raid their homelands to get inside their spell vaults [Using the Kingdoms+ plugin for a faction-like system]**

I'm afraid without those changes, it's just a matter of a few days until everyone knows every spell, and there are just the strongest spells flying around. I'd like to add more challenge, so the ones who DO get all the powerful spells can feel they have actually gotten somewhere, and not just reached what everyone else already had. [Kind of like playing a MMO where everyone else played it for years before you, and already got all the max levels and end gear - boring, and without any point or challenge...]

**Comment by NathanWolf** [comment]
You have some options here, but I'm not sure what will work best for you.

First, some editorializing:
- it should take a few weeks for a casual player to get all of the spells. Maybe less for a hardcore player, though SP earn cooldowns prevent heavy grinding.
- SP cooldowns and shop prices are customizable should you wish to simply slow down progression
- I don't think your proposals will prevent players from quickly collecting all of the spells, in fact I suspect the opposite may happen as now players can skip cooldowns by killing other players and taking their spells.
- What you're proposing will, I think, end up with a very unbalanced situation with many ultra-powerful spells that prevent new players from progressing at all.

That all said, there are a few things you can do:

1. Make wands unbound so players can take them. There is no way to have a wand that is bound (unable to be used by other players) but able to be picked up by other players.

In plugins/Magic/wands.yml:
```
wand:
  keep: false
  bound: false
```

2. Allow players to remove spells from wands, and then absorb them via other wands.

In plugins/Magic/config.yml:
```
allow_spell_dropping: true
```

I have not tested this feature in quite a while, your mileage may vary.

3. Allow combining wands on an anvil, so a player could take another player's wand and add all of its spells and mana to their own wand in one go. Also haven't tested this in a while, not sure how well it works.

In plugins/Magic/config.yml:

```
enable_combining: true
```

I don't believe any of this addresses your main concern. If you really want to prevent players from obtaining all of the spells, where everyone's end game is the same, you probably need to develop a branching class system instead, to differentiate each players' paths and experience.

The Star Wars and Bending configs are one example of how to do this, I plan on making something more complicated with multiple classes in the RPG configs, but it is nowhere near ready yet.

My personal feeling is that what you have proposed will create a very hostile and griefy experience for most players, but I could be wrong!

Let me know what you think of all of that.
