### ISSUE TITLE
Get wand spells

### ISSUE THREAD

**Issue by christophe6** [elBukkit/MagicPlugin#414]
Hi

I'm trying to get wether a player has all the spells for his wand path but it seems like the getSpells() list is empty and hasSpell(String spell) always returns false. I do not know why because the player has the spells.

CODE: https://hastebin.com/yutivebice.cs

Thanks!

**Comment by NathanWolf** [comment]
More info: maybe try
```
mage.getActiveClass().getSpells()
```

Or hasSpell- MageClass and Wand share the [CasterProperties](https://github.com/elBukkit/MagicPlugin/blob/master/MagicAPI/src/main/java/com/elmakers/mine/bukkit/api/magic/CasterProperties.java#L13) interface, but classes should always work while wands (with the current survival setup) will only work when active and held.

**Comment by christophe6** [comment]
Wow, thanks! Got that fixed with the getActiveWand() method. I'm trying to upgrade a wand to the next path but the energy is not modified upon upgrade. Do you know a fix for that?
`    		if(MagicPlugin.getAPI().getMage(player).getActiveWand() != null) {
    			if(MagicPlugin.getAPI().getMage(player).getActiveWand().getPath().getKey().contains("year")) {
    				if(MagicPlugin.getAPI().getMage(player).getActiveWand().getPath().hasUpgrade()) {
    					MagicPlugin.getAPI().getMage(player).getActiveWand().setPath(MagicPlugin.getAPI().getMage(player).getActiveWand().getPath().getUpgrade().getKey());
    					MagicPlugin.getAPI().getMage(player).getActiveWand().saveState();
    					
    					return;
    				}
    			}
    		}`

**Comment by NathanWolf** [comment]
Sorry for the late reply! So this is kind of a tricky area, just calling setPath won't really "upgrade" the wand, it just changes the path.

You instead need to call WandUpgradePath.upgrade() - here's an example (this is from UpgradePathAction)

```
com.elmakers.mine.bukkit.api.wand.WandUpgradePath path = wand.getPath();
            WandUpgradePath nextPath = path != null ? path.getUpgrade() : null;
            if (nextPath != null && path.checkUpgradeRequirements(wand, null) && !path.canEnchant(wand)) {
                path.upgrade(wand, mage);
                return SpellResult.CAST;
            }
```

Let me know if that makes sense!

**Comment by christophe6** [comment]
Sorry for the late reply but it did work ;)! Thanks!
