### ISSUE TITLE
Add the support for Residence& Plotsquared

### ISSUE THREAD

**Issue by HansscMe** [elBukkit/MagicPlugin#415]
My server is running residence and plotsquared,I think magic is a good plugin and want to use it.But it does not suuport these plugins in my server.could you add the support for these plugins?
thx

**Comment by NathanWolf** [comment]
Residence is supported via generic break/place event interrogation. I have tested it and it works well. I have not tested with PlotSquared, but the same approach may work. Try adding this to your plugins/Magic/config.yml (this requires 7.6.4 or later)

```
generic_protection:
  - Residence
  - PlotSquared
```

This is assuming plot squared is called "PlotSquared" in plugin.yml.

**Comment by NathanWolf** [comment]
If this didn't work, please re-open and let me know.
