### ISSUE TITLE
WARN Trying to update hotbar but the wand has gone missing

### ISSUE THREAD

**Issue by austin652** [elBukkit/MagicPlugin#419]
None of the spells are showing in the players hotbar or inventory and they can only use one spell, this wasn't happening before but now it is, I have no idea what the problem is. I've even swapped configs for an older one I had just to see if that fixed it and it didn't

**Comment by NathanWolf** [comment]
A few other users on Discord have reported this. I currently have no idea what's causing it, but I have not seen it myself.

The message basically spells it out, the plugin thinks the player is holding a wand, is trying to update the hotbar, but the item the player is holding doesn't match the wand.

Not sure how this could happen (especially all of the sudden) unless you have some other plugin messing with the player's inventory.

> None of the spells are showing in the players hotbar or inventory and they can only use one spell

What do you mean by this, exactly? Right-click on wands isn't working?

**Comment by austin652** [comment]
Alright so I just got more information on it myself, so what happens is that when a player opens their inventory to put spells in their hot bar, they can add it to the hot bar and it works but once they use that spell it just vanishes from their hotbar and wand

**Comment by NathanWolf** [comment]
Are you using default configs? Wands in inventory mode? I'm not totally understanding what you mean about adding spells to the hotbar.

**Comment by austin652** [comment]
This is what I mean
![image](https://user-images.githubusercontent.com/19559876/46109903-ef1ea280-c1af-11e8-8539-62a70850ccae.png)

**Comment by austin652** [comment]
![ezgif-2-28ba5bb4d0](https://user-images.githubusercontent.com/19559876/46109949-12e1e880-c1b0-11e8-84e0-4fa4aab4f4b0.gif)
This is what I mean

**Comment by austin652** [comment]
See how at the end after placing it and using it in the hot bar, it disappears from the inventory

**Comment by NathanWolf** [comment]
So you are on 7.6.13 now, right?

**Comment by austin652** [comment]
correct

**Comment by NathanWolf** [comment]
Do you happen to know the version you were on before that?

**Comment by NathanWolf** [comment]
And follow-up (sorry for all the questions)- when you get a new wand, does it start out with an empty hotbar like that?

I have not been able to reproduce any of this, so basically I'm just really confused at this point.

**Comment by austin652** [comment]
I try to keep the plugin updated so it should have been 7.6.12

**Comment by austin652** [comment]
yes a new wand starts out with an empty hot bar

**Comment by NathanWolf** [comment]
Can you try going back to 7.6.12?

I'm trying 7.6.13 myself and not seeing any of this. I'd be curious to know if the problem goes away on the previous version.

**Comment by austin652** [comment]
Still doesn't work but I noticed another warning
WARN Failed to save wand state for wand to : ItemStack{STICK x 0}

**Comment by NathanWolf** [comment]
Seems odd- did you have a stick in your hand... ?

**Comment by NathanWolf** [comment]
And did you update anything else on Sunday besides Magic? If it's not the plugin version it must be something else...

**Comment by austin652** [comment]
I asked and nobody had a stick when they logged in

**Comment by NathanWolf** [comment]
I've narrowed this down to a Spigot issue, I believe from this commit:

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/8164f4b25bb557d4ded2db42ca4e6abb423bb5ee#src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaItem.java

.. not sure what to do about it yet.

**Comment by NathanWolf** [comment]
This is assuming you are on latest 1.13 Spigot, something I should've asked from the get-go.

**Comment by austin652** [comment]
I'm actually 4 versions behind the latest, git-Spigot-f823ac5-c1ecaa2 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**Comment by NathanWolf** [comment]
This commit is 11 deep, so I think it's the problem.

**Comment by austin652** [comment]
Well at least I know it might not be something on my end

**Comment by NathanWolf** [comment]
I have submitted a PR that fixes this issue. We'll have to wait for Spigot to accept it- in the meantime if you can go back to an older version of Spigot that should fix it for now.

**Comment by austin652** [comment]
What version should I go to specifically?

**Comment by NathanWolf** [comment]
http://jenkins.elmakers.com/view/all/job/elSpigot/111/

... I’ll probably redact this once you grab it

**Comment by austin652** [comment]
I've got it

**Comment by NathanWolf** [comment]
My PR got accepted, you can update to latest Spigot again without issue.
