### ISSUE TITLE
Love the Magic Plugin! Is there a way to change the default wand/item names? Sorry, having trouble finding it...

### ISSUE THREAD

**Issue by SpyralMalus** [elBukkit/MagicPlugin#420]
Love the plugin! We are having a ton of fun with it! I was wondering if there is a way to change the default names of the wands and items. For instance I'd like to rename the Master Wand into the Elder Wand, but when looking in the Items/Wands files/folders they seem to be more or less empty. I guess I was expecting a .yml file or something where I could update existing names, lore, stats etc of the default items/wands. Am I missing it somewhere or is this not possible?

**Comment by NathanWolf** [comment]
Everything is customizable but it’s a little different than most plugins. Please start here and let me know if you have more questions!

https://github.com/elBukkit/MagicPlugin/wiki/Customization
