### ISSUE TITLE
Can't aim most spells in caves

### ISSUE THREAD

**Issue by leveljaap** [elBukkit/MagicPlugin#424]
Hello,

With all those issue's I'm making, it's almost like I hate this plugin. It's the exact opposite though. This is the very best plugin I know, which is why I really want all these issues solved.

I have found that a lot of spells can not be aimed in naturally generated caves. The strange thing is that they CAN be aimed inside player-made structures. Some of the spells that can't be aimed are Blast and Magic Missile. I am guessing that all spells that work with fireworks don't work, as things like Arrow and Fireball DO work. I would appreciate it if you'd do something about this because then I don't have to take a load of weapons with me when I go mining. If I have to provide more information, I gladly will (though this issue should be really easily reproducable).

Thanks

**Comment by NathanWolf** [comment]
Oooohhhh you know I bet I know why that is, 1.13 added a new block for “cave air” ... I bet that needs to go on the transparent block list.

Should be an easy fix, I’ll test it out and let you know! Thanks for the report.

**Comment by NathanWolf** [comment]
Hm so actually it seems like I addressed this already- it should have been fixed way back in 7.6.7 - can I ask what version of Magic you're on?

I added void_air and cave_air to all places that use air, and I just tested by going to a newly generated cave (on 1.13) and cast some spells (like Magic Missile) and it seems fine.

**Comment by NathanWolf** [comment]
Hm well for most spells anyway ... seems like some spells, like Torch, have hard-coded checks for air. I'll need to fix that.

**Comment by leveljaap** [comment]
Yeah it probably is because I'm using 7.6.6. This is the latest version available on Multicraft though... I'll try installing it manually, thanks.

**Comment by leveljaap** [comment]
And it works for me now! Pretty annoying that this version can't be installed through Multicraft but whatever. It works now. Thanks a lot.

**Comment by NathanWolf** [comment]
Hm, I wonder where Multicraft gets its versions from?
