### ISSUE TITLE
Magic 1.8.8 | Setting mana on a wand

### ISSUE THREAD

**Issue by Daviduhh** [elBukkit/MagicPlugin#427]
Hey, i use the version for 1.8.8 (the gamemode that i do is in 1.8.8 the best)

But, i was wondering if i can set the mana of a wand to like 80 in stead of 50, because i added some spells to his wand but he can't cast them because the 'mana cost' is to high.

-Davide ;)

**Comment by Daviduhh** [comment]
/wand configure mana_max 80 is not working, it just says 'wand configured' but nothing is happening

**Comment by NathanWolf** [comment]
Are you doing it on your own wand?

I guess try `/mage configure mana_max 80` but it should do the same thing.

Really you're just hacking around the real problem, players are meant to progress along a path that will keep their mana upgraded to match spells available to them. 

I'm not sure what you're trying to do here, if it's just playing around then it's probably fine to fix things by hand like this, but if you're trying to establish a real gameplay mechanic for players to gain spells and increase mana this is not the right way to go.

**Comment by Daviduhh** [comment]
I am trying some things out :)
But,```/mage configure mana_max 80``` gives me:
Set mana_max to 80 for [Owner] _CobbleStone

**Comment by Daviduhh** [comment]
And yes, i am doing it on my own wand

**Comment by Daviduhh** [comment]
this is the wand.yml btw
```#
# Modify this file to change the available default wands.
# New wands can be added, existing wands modified or removed (disabled)
#

#
# This is the Wand configuration file for the Magic plugin.
#
# This defines all of the wand "templates" that can be created with the
# /wand and /wandp commands.
#
# To see the default wands and configurations, look in defaults/wands.defaults.yml
#
# See https://github.com/elBukkit/MagicPlugin/blob/master/WANDS.md for more information.
#
# Once a wand is created, it is its own unique item. It may be modified after that,
# and may bear no direct relationship back to the template that created it.
# 
# The name and description, of a wand should be defined in messages.yml as
#  messages.wands.<wandkey>.name
#  messages.wands.<wandkey>.description
#
# Note that wands can also be renamed on an anvil.
#
# There are two special entries in here:
# - The "default" wand is used as a template when creating a new and with /wand.
# - The "random" wand has a different and specific configuration format.
#
# General format:
#
# <wandkey>:
#
#       # If true, this wand can not be enchanted, combined or otherwise modified
#
#       modifiable: true
#
#       # Set to false to disable a preset wand
#       enabled: <true|false>
#
#       # Casting cost and cooldown reduction
#
#       cost_reduction: (0.0-1.0)
#       cooldown_reduction: (0.0-1.0)
#
#       # Overall and specific protection
#
#       protection: (0.0-1.0)
#       protection_physical: (0.0-1.0)
#       protection_fire: (0.0-1.0)
#       protection_falling: (0.0-1.0)
#       protection_blast: (0.0-1.0)
#
#       # Regeneration values are added every second
#
#       health_regeneration: (0-20)
#       hunger_regeneration: (0-20)
#
#       # If non-zero, this wand will use the Mana system instead of XP
#
#       xp_regeneration: (0-200)
#       xp_max: (0-?)
#
#       # This provides bonus damage and effects to some spells
#       # and increases the overall range of all targeted spells
#
#       power: (0.0-1.0)
#
#       # Increases player walk/fly speed- is limited by Bukkit
#
#       haste: (0.0 - 0.4-ish)
#
#       # Applies a potioneffect to the player while holding the wand
#       # also used by many spells that have visual effects when cast with this wand
#
#       effect_color: <hex color, eg 'FF0000')
#       spells:
#           - <spellname>
#       materials:
#           - <materialname>```

**Comment by Daviduhh** [comment]
???

**Comment by NathanWolf** [comment]
Was there a question there somewhere? Are you saying setting mana_max still isn't working?

I forgot you were on 1.8 - forget about the /mage command, that's for current versions of the plugin. If /wand isn't working then idk what's up.

```
/wand configure mana_max 800
/wand describe
```

What does it say?

**Comment by Daviduhh** [comment]
![2018-10-18_15 53 51](https://user-images.githubusercontent.com/38431841/47159404-1881a880-d2ee-11e8-8565-a77d49fb28c9.png)

**Comment by Daviduhh** [comment]
btw, are you dutch? because it will be a little bit easyer for me to communicate :P

**Comment by NathanWolf** [comment]
Wow, xp_max, really.... I really thought it was mana_max even 5 years ago or however old that is.

Ok, anyway, try `/wand configure xp_max 80`

To change it for all wands, put this in your wands.yml
```
wand:
  xp_max: 80
```

And no I'm not Dutch, but sometimes I wish I was.

**Comment by Daviduhh** [comment]
/wand configure xp_max 80 worked, thx mate.

Whhahaha, why? ther are some awesome things about being Dutch (eating 'hagelslag') and having an awesome school system xd
Are you American?

**Comment by Daviduhh** [comment]
And mana regerantion?

**Comment by NathanWolf** [comment]
All the parameters you may want to change can be seen in your screenshot, or you can look in plugins/Magic/defaults/wands.defaults.yml (this file is read-only, but has all the default wand parameters).

So `xp_regeneration` is what you want to change for regen.

And yeah I'm American, which is a little embarrassing atm to be honest but I'm hoping to try to improve the situation in November.

I've never been to the Netherlands, but I did a lot of research into it a while ago when I was considering moving somewhere out of the country. It seemed like a very beautiful place with nice people and a level-headed government :)

**Comment by Daviduhh** [comment]
Well, thx for al the help :) I wish you goodluck with everything, and if you ever wanna learn some dutch, i can help you out ;)

Dankjewel Nathan, veel suc6 nog en bedankt voor deze geweldige plugin waar heel mijn server plezier aan heeft.
PS: Je moet echt hagelslag proberen
