### ISSUE TITLE
Removing the breaking block particles when repairing blasts

### ISSUE THREAD

**Issue by leveljaap** [elBukkit/MagicPlugin#428]
Hello,
I have noticed that some spells that do block damage show breaking particles while repairing the damage. This is quite annoying because a lot of people on my server do not have very good computers so they start lagging when a blast lvl 4 or anything similar repairs. Is there a way to disable these particles? Will removing the line `particle: block_crack` from the code of the individual spells work?
Thanks.

**Comment by NathanWolf** [comment]
huh- of all the particle effects, this is the one that's really a problem for people?  If so I can tone it down on my side, but I'm a little skeptical that this would be the worst offender.

Putting this in spells.yml will turn it off completely in the meantime if you want:

```
blast:
  effects:
     undo_block: []
```

**Comment by leveljaap** [comment]
Well some spells like Flash Bang (or whatever it's called) cause problems too but of the most commonly used ones this is by far the most troublesome. And thanks, I'll try that.

**Comment by leveljaap** [comment]
Thanks! It worked!
