### ISSUE TITLE
Different version of texture pack for different versions of client minecraft

### ISSUE THREAD

**Issue by DarkFort** [elBukkit/MagicPlugin#432]
If a player has join from version 1.8, the plugin offers to install a texture pack suitable for this version. If the player join from 1.13, it offers to install a texture pack suitable for this version. The same with the other versions. The client version can be obtained from ViaVersion or ProtocolSupport. I propose to implement this feature in your plugin, it is suitable for servers that run on several versions of Minecraft.

**Comment by NathanWolf** [comment]
This would be interesting and not too hard to do if there is a way to detect each players' client version.

**Comment by killme** [comment]
I'd argue it would probably more appropriate for a more specialized resource pack plugin.

(This would also not work when running viaversion on BungeeCord)

**Comment by NathanWolf** [comment]
Hm- wouldn't that me the main use case? What other way is there to have a mix of players on different versions?

**Comment by NathanWolf** [comment]
I think if this was really needed, server owners can now set it up themselves using `alternate_resource_packs` - it won't be automatic, but players can set their desired RP and I think that's probably good enough.
