### ISSUE TITLE
Problem with version of the texture pack in the config

### ISSUE THREAD

**Issue by DarkFort** [elBukkit/MagicPlugin#433]
Problem with version of texture pack in the config on different versions. The core of PaperSpigot 1.12.2 is installed, but in the Magic plugin config there is a link to the version of the texture pack of the Magic v8

**Comment by NathanWolf** [comment]
The config that appears in plugins/defaults/ is just the core defaults, it's not actually what the plugin is using. It will be using the v7 RP in 1.12.2.

I don't think I'm going to fix this, fixing it would mean we lose all of the comments in that file, and I think that's more important the one RP line.

**Comment by NathanWolf** [comment]
Though, that said, if I were to implement the RP-per-version feature the way #432 is asking for that would kind of fix this issue anyway. There would be a map in config.yml of versions to resource packs instead.
