### ISSUE TITLE
no default config

### ISSUE THREAD

**Issue by ashillion** [elBukkit/MagicPlugin#435]
#339 I install on 1.13.2 and it puts the Default and Data folders in the plugin directory, but there are no config files in them.
In game magic commands show up but I cannot get a wand or use/cast.

**Comment by NathanWolf** [comment]
Any errors in your logs on startup? Make sure you have the most recent release of Magic (from spigotmc, NOT dbo), there were some fixes required for 1.13.2

**Comment by ashillion** [comment]
Redownloaded from spigotmc and BAM! Config-y goodness for me to spend hours on!!!!!
Thanks!!!

**Comment by NathanWolf** [comment]
I’m glad you got up and running!

Before you start hacking away please read the comments at the top of the config files, and then go on to the Customization section of the wiki- configuring this plugin is a little different than most other plugins!

(You can’t edit the default files...)
