### ISSUE TITLE
[Request] CMI Integration (and maybe more on Residence?)

### ISSUE THREAD

**Issue by mercurialmusic** [elBukkit/MagicPlugin#436]
New-ish to the plugin, so my apologies if this has been covered already, but my searches haven't turned up much. With the slow death of Essentials, [CMI](https://www.spigotmc.org/resources/cmi-240-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/) is posed to be the better replacement. Would love to see integration with that for warps, etc. It is premium (and so worth it), but there's an API section on the Spigot description page with links to a jar that can be used by developers and a [GitHub](https://github.com/Zrips/CMI-API) repository.

Less important but would be cool, the same developer is also the current dev for [Residence](https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-13-1.11480/), which we would prefer to still use since we use it on our other servers. It would be really cool if a player's residence also showed up in the recall spell. The existing integration with Residence is also massively appreciated.

**Comment by NathanWolf** [comment]
Hi, and welcome!

So I don't use Essentials myself, but I wasn't aware it was dying. EssentialsX seems very active and used, does it not?

So unfortunately I generally don't/can't integrate with anything that doesn't have a public Maven-available API. I have looked into Residence before, but it was such a hassle to build that I bailed on the idea.

And I definitely never integrate with premium plugins. How would I even test it?

So I'm afraid to say that both of these are kind of a no, sorry!

For warps, if you want to use Recall, you can use the builtin `/mwarp` command to add warps that you can use with Recall. I do realize it's a bit of a hassle to have to manage two separate warp lists, but I think that's going to be your best option.

**Comment by mercurialmusic** [comment]
Certainly understood. Thanks for the response and suggestion! I'll definitely look into the /mwarp feature. EssentialsX is the one I meant -- we moved away from it a while ago as well (like many seem to be doing), but while I know there is still occasional work being done, it hasn't received an official update since March and hasn't fully updated to 1.13 -- not dead yet, but seems like it's going that way.
