### ISSUE TITLE
EMP Spell in 1.13

### ISSUE THREAD

**Issue by mercurialmusic** [elBukkit/MagicPlugin#439]
I've tried to test this rather extensively, but since I'm still new to the plugin I fully acknowledge it may be something I'm messing or missing. 

I haven't been able to get a response from the EMP spell. The effects all work, but I can't seem to get it to power or unpower anything. Tested on several redstone elements, notably the lever and redstone block, which I understood to work best with the spell, but nothing happens. All of my tests were tried with the default configs and also with altered configs to extend the timing of the spells, but I couldn't get it to work on my server (using as many redstone elements as I could come up with) or the sandbox.elmakers.com server (using a lever on a door -- I'm sorry I broke a tree to make a lever! I replanted though!). I did get a response from someone in Discord that it is working on their 1.12.2 server, but I only had one other response from a friend formerly associated with PWS that it's not working in their 1.13 configuration either (so I think it's not just me!).

Using Magic 7.6.15 on Spigot (git-Spigot-947a8e7-17ff1e0 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)).

**Comment by NathanWolf** [comment]
The PowerBlock action is still using legacy MaterialData methods. These *were* working as of 1.13, but it seems like somewhere along the way to 1.13.2 they must've broken.

Unfortunately it will be challenging to fix this and retain backwards compatibility. I don't really want to interact with the new BlockData API entirely by reflection.

I haven't been really active in development lately, so maybe it's time to fork off 8.0 which would be a 1.13 and up only version of the plugin. I'll give it some thought.

**Comment by mercurialmusic** [comment]
It would definitely be appreciated. We've been very excited to bring Magic to our servers. Also happy to support the development.

**Comment by NathanWolf** [comment]
I looks like this may be a little more complicated than I thought. The new BlockData API doesn't seem to have a way to flip levers. There is a Powerable.setPowered interface, but that only makes the block powered (as if receiving a signal), it doesn't set the block to produce power.

I'll keep this open but I will need to look around for a fix.

**Comment by mercurialmusic** [comment]
I obviously can't speak for everyone, nor do I understand the underlying code necessary, but I'd be just as happy if there's any redstone component that could be activated, if that makes things easier -- buttons? Thanks for trying to figure it out though! This spell is a pretty important one in terms of immersion.

**Comment by NathanWolf** [comment]
I finally got this fixed in 7.7.5

Sorry for the long delay!
