### ISSUE TITLE
No enchantments

### ISSUE THREAD

**Issue by NoobPlayer03** [elBukkit/MagicPlugin#44]
Enchanting does not work... No enchantments display.

**Comment by NathanWolf** [comment]
I just replied to your review (thanks for the stars!), I'll copy+paste here:

That is not a bug, it's a feature :) The latest versions use a skill point system for wands, not enchanting- if you right-click an enchant table with a wand you'll see the spell shop. Set "enable_sp: false" in config.yml to bring back the old enchanting system.

Let me know that clears it up!

**Comment by NoobPlayer03** [comment]
Thank you so much! Im making a kitpvp server with magic, hopefully it will work well.

Sent From my Awesome i5C
