### ISSUE TITLE
Combat log plugin issue

### ISSUE THREAD

**Issue by Blamo27** [elBukkit/MagicPlugin#440]
Hello,

There is an issue with combat log plugins.
Indeed, the plugin is called CombatTagPlus, but we actually tried with other plugins such as CombatLog or CombatLogX. The problem is that, even if we turn on the option avoiding the loss of any Magic items, the player still loses them.

Video link: https://streamable.com/6ral9

Is there a way to prevent that ?
Thanks.

**Comment by NathanWolf** [comment]
Probably not, unless you can turn off whatever feature in that plugin that is taking players’ items.

**Comment by Blamo27** [comment]
@NathanWolf The feature doesn't take the players items, it's just "instant kill" them.

**Comment by NathanWolf** [comment]
I can't imagine why that would make a difference unless the plugin is doing something special to the players' items on death, though?  

I'll clone the code and see if it's doing anything weird. This would unfortunately be hard to test on my own, I imagine.

**Comment by NathanWolf** [comment]
Ok I pushed a new option that *may* fix this- you can now set `logout_delay: 1` in config.yml. This will delay processing logout for 1 tick, which should mean it happens after CombatTagPlus has killed the player.

On a side note, this may be part of the reason you had so many issues that I could not reproduce with the file-locking mechanism. If a player combat logs by switching servers, they'd get killed after magic has already processed their logout, which would force their player data to load again, but now it's loading while they are already on the other server. Just a theory, though.

Please let me know if this helps! Also my build server seems to be back up so you can grab this fix in the dev build here (this also includes your NCP fix for gliding- both are untested, though)

http://jenkins.elmakers.com/job/MagicPlugin/2821/com.elmakers.mine.bukkit.plugins$Magic/

**Comment by Blamo27** [comment]
@NathanWolf On our server, CombatTagPlus block the /warp command, allowing players to switch from a server to another. So the problem you are referring to can not normally produce.

Okey thanks, we will test both fixes and I will let you know if it helps !

**Comment by Blamo27** [comment]
@NathanWolf ?

**Comment by NathanWolf** [comment]
I don't know if I'm going to be able to do anything more about this, sorry!
