### ISSUE TITLE
Arrow spells fail when close to a wall on the right

### ISSUE THREAD

**Issue by Ferocimo** [elBukkit/MagicPlugin#442]
Hello,

Arrow spells are all fired a little too far to the right relatively to the player. As a result, when a player is very close to a wall placed on his right, the arrow is fired directly on the wall, making the spell fail, even when the player clearly aimed on the left.

This is particularly an issue in certain cases, like when a player is trapped in an enclosed space and trying to use such spells.

Thank you for looking into this.

**Comment by NathanWolf** [comment]
All spells fire from the location of the wand. This can't be (easily) changed on a per-spell basis.

You can change it for an entire wand, but I will tell you it looks and feels very weird to have projectiles shoot out straight from your eyeballs.

**Comment by Ferocimo** [comment]
Okay I see what you mean ; keep me updated then if one day you make it possible for specific spells or actions like "projectile".

**Comment by NathanWolf** [comment]
Oh, wait, it's totally possible- my bad. Try:

```
arrow:
  parameters:
      source_location: body
```

**Comment by Ferocimo** [comment]
That's exactly what I wanted, I set the source location to the head and it's perfect. Thank you !
