### ISSUE TITLE
Could I use it?

### ISSUE THREAD

**Issue by HarrySteve06magic** [elBukkit/MagicPlugin#444]
Hi Nathan.
I stumbled across this mod and today I would like to ask you if I could use it on an Harry Potter server because its just awesome and , if you have time could you help me with the tecnical part of it because all of this for me is incomprehensible 'mumbo jumbo" and maybe help me create some other neat plugins that are only real in my fantasy...for now.
Let me know soon and I know I'm being repetitive ,but this plugin is awesome, and if you want, we could do great things together.
PS:I'm still building the various ambientations so I it may take a while to open a server.

**Comment by NathanWolf** [comment]
You can of course use it, but I haven't much time to spend on the plugin or supporting it these days. You'd have to be prepared to learn on your own, or perhaps with some help from the Discord or spigotmc community.

For starters, check out this wiki page- there is a built-in HP config that can get you started, at least.

https://github.com/elBukkit/MagicPlugin/wiki/Potter

**Comment by HarrySteve06magic** [comment]
Thanks a lot Nathan.
When the server will be completed I will make you our "Minister of magic" for your help.
