### ISSUE TITLE
Cost_reduction in mana only ?

### ISSUE THREAD

**Issue by Ferocimo** [elBukkit/MagicPlugin#445]
Hello,

My question is simple : is there a parameter like cost_reduction, but that only decreases mana cost, and not item cost ? 
For instance, a spell cost 100 mana and 6 TNT to launch. Ideally I would want to have a "mage" parameter that reduces mana cost to 50, but the spell would still consume 6 TNTs.

I had trouble testing things to find out an answer by myself because "/mage configure cost_reduction [x]" command seems to malfunction.

Thank you.

**Comment by NathanWolf** [comment]
No, costs are costs. There is a TakeItem action, but I don't think it has a way to cancel a spell if the player doesn't have the item.

**Comment by NathanWolf** [comment]
Suggest you just give mana bonuses if that's what you're looking for.

**Comment by Ferocimo** [comment]
I see, thank you, I'll think about it.
