### ISSUE TITLE
Tracking spell tracking vanish players

### ISSUE THREAD

**Issue by Ferocimo** [elBukkit/MagicPlugin#446]
Hello,

The tracking spell reveals administrator hidden with the /vanish command. That's obviously a big concern for any kind of investigation we want to make. 

Now, if it is too much of a trouble to ignore vanish players with that spell, could you make a permission that make people who got it immune to that spell ? We would then give that permission to administrators.

**Comment by NathanWolf** [comment]
Magic only supports plugins that set "vanished" metadata when vanishing them. Otherwise I have no way to know if a player is vanished.

If your vanish plugin can do that, they won't be targetable by any spells.

**Comment by Ferocimo** [comment]
It's EssentialsX, so I guess that plugin doesn't have that metadata ?

**Comment by NathanWolf** [comment]
It looks like not. Looking at the source code, there some API I could use to determine if a player is vanished via Essentials though. I'll keep this open until I get a chance to add that.

**Comment by NathanWolf** [comment]
Magic now has Essentials integration for vanished player detection, this should fix the problem.
