### ISSUE TITLE
TNT and creepers hit by magic won't destroy anything

### ISSUE THREAD

**Issue by Ferocimo** [elBukkit/MagicPlugin#447]
Hello,

A TNT launched by a spell, such as the one posted below, will normally destroy blocks. But, if it's affected by a spell, such as "push", it will only destroy blocks in areas that the player is allowed to modify (build / break). That means that if a player ignites a TNT on the border of an enemy faction's claim, and then pushes it in the claim, the TNT will explode without doing any damage (even though using a traditional "TNT canon" would perfectly work).

Moreover, a creeper electrified by Magic, like with the spell chainlightning, will only destroy blocks if it blows up in an area where the player that electrified it can build or break. However if it's electrified by a normal lightning it will indeed destroy blocks normally.

How can I fix that ?

**Comment by NathanWolf** [comment]
Are you saying you want players to be able to break blocks with magic explosions even if they have no permission to break?

**Comment by Ferocimo** [comment]
I'm saying that I want things to be able to explode even if players interracted with them, if the area doesn't prevent them from doing that.

For instance in enemy claim there is no TNT protection. A TNT blowing up in a claim would destroy blocks. Therefore it would also be the case if the TNT is pushed by the player. Of course it wouldn't be the case if the player would push the said TNT in an area that prevents TNT detonation.

**Comment by Ferocimo** [comment]
In other terms, normally a TNT or a creeper isn't tied to a player. If the area isn't protected against that, it shouldn't prevent explosions if the "source" of the TNT or the creeper is a player and not just nature.

**Comment by NathanWolf** [comment]
For any spell you want to bypass break permission you can put on `bypass_break: true` in parameters. This should work for push, chainlightning, grenade or any other spell.

**Comment by NathanWolf** [comment]
To be clear, the default behavior is to error on the side of caution. It's much more common to have people complain about "magic griefing" then complaining about not being able to grief with magic. This is possibly the first time ever, in fact :joy:

**Comment by Ferocimo** [comment]
Actually I often use that parameter, but I didn't think it would work for spells that don't really destroy blocks like push or chainlightning (at least for us it doesn't destroy blocks). It does work as intended now, thank you ! 

(and yes, using Magic on a Factions server may cause some... unusual... requests !)
