### ISSUE TITLE
"boon" spell causing tons of issues

### ISSUE THREAD

**Issue by Ferocimo** [elBukkit/MagicPlugin#451]
Hello,

The way the "boon" spell now works is causing tons of various issues. When the spell ends (because it is cancelled or you run out of mana), the effects given by boon are not withdrawn, you are in fact rollbacked to the state you were in before you cast the spell. That means, if you had poison 1:30 before casting the spell, then you cast it and then un-cast it after one minute, you will be rollbacked to your poison effect that lasts 1:30 again. Also, if you were on fire before casting the spell, you will be on fire again when it ends.

Even more annoying : when you activate Boon, and then electrify a creeper with chainlightning, and the creeper explodes, when Boon will end the creeper will actually spawn back to life !

Of course feel free to tell me if there is a way to fix this on our end.

**Comment by NathanWolf** [comment]
I would just disable the spell for now. Spells.yml:

```
boon:
  enabled: false
```

**Comment by Ferocimo** [comment]
I think I'll rather modify it to make it work like it worked before (just adding effects for a set amount of time), waiting for a solution for this.

**Comment by NathanWolf** [comment]
Should be easy enough- something like this is how it used to work:

https://github.com/elBukkit/MagicPlugin/blob/1.8/src/main/resources/defaults/spells.defaults.yml#L377

**Comment by NathanWolf** [comment]
I've changed the way Boon works in the latest dev build, so it can be toggled on/off without all these weird side-effects. I also added some cool particle trail effects so the player has wings while enabled.
