### ISSUE TITLE
Cant save spell hotbars / inventories

### ISSUE THREAD

**Issue by Challenger8168** [elBukkit/MagicPlugin#454]
Hello, I have the latest version installed on Spigot 1.12.2 and it works perfectly. It is a very cool plugin, but unluckily, I cant save spells I put in my hotbar / inventory. Whenever I cycle with the drop key and re-enable it with 2 right clicks and cycle back to the third spells, it has changed completely. Also, you can just relog and have the same effect. This is very bad, because I think it would be great if you could save your hotbar spells.

**Comment by Challenger8168** [comment]
Well, I want everybody to be able to save them, so I cant just give them creative

**Comment by NathanWolf** [comment]
No, I mean it doesn't work in creative mode. The symptoms you're describing sound like creative mode issues.

If you're seeing this in survival then it sounds like a bug, or (more likely since no one else has reported it) some plugin incompatibility issues.

**Comment by NathanWolf** [comment]
Any updates?
