### ISSUE TITLE
Bug with Arrows on 1.13.2

### ISSUE THREAD

**Issue by HansscMe** [elBukkit/MagicPlugin#456]
The spells Arrow_ice,Arrow_fire,Arrow_blink,Arrow_bomb,Arrow_grapple,Arrow_poison and Arrow_shock could NOT spawn a flying arrow.
The arrow will hit the shooter.

Enviroment:
*paper 1.13.2 lastest
*Magic 7.6.18

**Comment by NathanWolf** [comment]
Those spells are used by the Magic Bow, they don’t work with wands.
