### ISSUE TITLE
How do i hold spells 

### ISSUE THREAD

**Issue by AliGamingTV** [elBukkit/MagicPlugin#460]
meaning i want to hold a spell any spell because i want to but it in the shopkeeper 

if their is a command plz tell me it and can you tell me how to get books magic books

**Comment by AliGamingTV** [comment]
and how do i craft the magic books Nathan

**Comment by NathanWolf** [comment]
What magic books? The spellbook (used for casting spells) is called "spellbook". The recipe books are "recipe:<name of crafting recipe" or "recipe:*" for all recipes.

**Comment by AliGamingTV** [comment]
Thx so much

**Comment by AliGamingTV** [comment]
now my server is good to goo!

**Comment by AliGamingTV** [comment]
another question how do i restart the whole plugin like a fresh start for all the players

**Comment by NathanWolf** [comment]
You can delete plugins/Magic/data while the server is shut down. This will reset most progress, like spells learned, cast counts, mana limits.

Players will still have their wands, though.

**Comment by AliGamingTV** [comment]
and can i have unlimited mana

**Comment by AliGamingTV** [comment]
Thx
