### ISSUE TITLE
Exception thrown

### ISSUE THREAD

**Issue by omegadmm** [elBukkit/MagicPlugin#461]
![capture](https://user-images.githubusercontent.com/24850883/50719528-d8b39d00-1062-11e9-95e9-46bb5296752c.PNG)
This was thrown each time I ran it.

**Comment by NathanWolf** [comment]
Fixed in current dev build. Will release it at some point.

**Comment by omegadmm** [comment]
Sweet.

**Comment by NathanWolf** [comment]
That one is generally because your server lost its outbound internet connection. It's pretty rare for Amazon S3 to go down (like 5 9's). Should be harmless, though, it's just checking for new versions of the resource pack.

**Comment by NathanWolf** [comment]
Fix released in 7.6.19
