### ISSUE TITLE
Brooms use

### ISSUE THREAD

**Issue by HarrySteve06magic** [elBukkit/MagicPlugin#467]
Does worldguard work for brooms too?

**Comment by HarrySteve06magic** [comment]
But can you prevent players to ride the broom in certsin areas?

**Comment by NathanWolf** [comment]
Yes. /region flag whatever blocked-spells broom

**Comment by HarrySteve06magic** [comment]
Also wanted to ask you if for using this mod on a server w/ a different texture pack I have to change some blocks or particles and if it works along the conquest reforged mod

**Comment by NathanWolf** [comment]
You would either need to merge the two resource packs, or else put `example: norp` in Magic's config file to turn on skull icons.

**Comment by HarrySteve06magic** [comment]
Thx for your help, btw the server's name will be WizardingWorldMC.
I'll let you know when it will be open.
