### ISSUE TITLE
Boon spell not upgrade-able

### ISSUE THREAD

**Issue by Ferocimo** [elBukkit/MagicPlugin#468]
Hello,

The boon spell seems to never be considered as "cast". As a result, activating it does not give you SPs nor increases the "cast count" for upgrading the spell.

(if you do not have that issue yourself I can post the spell config if you want)

As always latest version etc etc.

Thank you.

**Comment by Ferocimo** [comment]
@NathanWolf This is quite an issue, many players are complaining that they can't upgrade their spell. Do you know any quick fix I could do, while keeping the spell as close as it is currently working ?

**Comment by NathanWolf** [comment]
Unfortunately it's probably an issue with the new implementation of the spell, a bug that I'll need to fix. The spell never really finishes so it never awards SP.

In the meantime you could go back to using the timed version that I sent a while back.

**Comment by Ferocimo** [comment]
Hmm, I see. Is it "easily" possible to configure the spell so it earns SP and is counted as cast on "beginning" and not at the end of the spell ?

Meanwhile I'll just use the older version.

**Comment by NathanWolf** [comment]
I think this will be fixed in the next dev build / release.

**Comment by NathanWolf** [comment]
In release 6.9.20

**Comment by Ferocimo** [comment]
Confirm it is fixed, thank you.
