### ISSUE TITLE
MMob natural spawning

### ISSUE THREAD

**Issue by Curtis73** [elBukkit/MagicPlugin#476]
Hey, is there a way to disable mmobs from naturally spawning? I looked around the default configs but couldn't find anything.

**Comment by NathanWolf** [comment]
What do you mean? How are they naturally spawning?

**Comment by Curtis73** [comment]
They're just spawning normally in the PvP world

**Comment by NathanWolf** [comment]
There's nothing in the plugin that would do that. You need to use MagicWorlds to swap vanilla spawns with magic mob spawns. 

If you have some other plugin that is replacing vanilla spawns then magic mobs will be attached to the spawned mobs IF you have them spawning with custom names that match your mmob configs.

**Comment by Curtis73** [comment]
Ah, that'd be it. Thank you!
