### ISSUE TITLE
Custom wand inventory won't open when right-clicking

### ISSUE THREAD

**Issue by bryceaj22** [elBukkit/MagicPlugin#478]
![crackle](https://user-images.githubusercontent.com/47934545/53295063-528d1a80-37b8-11e9-9f8b-f74893628f36.PNG)

My wand1 (Crackle) won't open its spell inventory when I right-click or press Q. I'm Wondering if i'm missing something important under the wand that allows me to cycle through spells. All help is appreciated, thanks.

**Comment by NathanWolf** [comment]
It looks like you dropped the y from `mode: inventory` on base_wand

**Comment by bryceaj22** [comment]
Thank you, I found a solution.
