### ISSUE TITLE
Grief prevention integration is forced.

### ISSUE THREAD

**Issue by dryter97** [elBukkit/MagicPlugin#480]
Like the title said i want to remove the integration of grief prevention. simple you can say just turn the true to a false on the grief prevention corner. k fine lets do it... restart server ho its turn back at true. i got grief prevention on my server at well i just want my players to do what they want where they want. some spell got lock when they enter a region. by exemple a player when is trust on this claim cant use some spell has fireball or earthquake. i tried my best about it but nothing can be found nothing seem to let me turn it to false. i tried whit permission whitout any succes and at this point i just come there because its clearly not working properly. each time i turn it to false its turning back to true. what can i do to solve that?

if i did all stuff properly maybe you can solve it on your side? any way let me know if i just pass throught something usefull about it.

**Comment by NathanWolf** [comment]
Don't edit the default. Edit plugins/Magic/config.yml

**Comment by dryter97** [comment]
nothing on it about integration

Le lun. 11 mars 2019 à 18:28, Nathan Wolf <notifications@github.com> a
écrit :

**Comment by dryter97** [comment]
> `#
# Modify this file to change the overall behavior of the Magic plugin.
# only include the options you want to modify.
#
# You can also add individual files to the config/ folder
#
# To see all available options, look in this folder:
# https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/main/resources/defaults/config
#
# Options for sub-components (spells, wand templates, chest populator, etc) are 
# found in separate files.
#
# For customization help see: 
# https://github.com/elBukkit/MagicPlugin/wiki/Customization
#

#
# Examples:
# Note that a "#" character means the line is commented out and has no effect.
# Make sure to not comment out the lines you add, there should not be a space in front of the name, indentation is important.
# Use http://www.yamllint.com if you have issues with your config, make sure not to use tabs!
# 

# Load one of the included example configurations instead of the defaults.
# Current options: potter, safe, survival
# Any customizations will still be loaded on top of the example configs.
# example: potter

# Add one or more of the included example configurations on top of the defaults.
# The config.yml potion is not loaded, for sanity's sake.
# add_examples:
#   - potter
#   - survival

# Some common fields that you might like to override:

# Give new players a wand when they first join
# welcome_wand: beginner

# Whether or not to show any messages (in chat) 
 show_messages: true

# Whether or not to show messages on every spell cast (in chat)
 show_cast_messages: false

# Enable/Disable Sound Effects
 sounds: true

# Prevent rapid sending of chat messages from the plugin (in milliseconds)
# message_throttle: 3000

# Set this to 1 to just turn costs off, or you can use it to scale costs down.
# cost_reduction: 0.0

# How much to reduce costs and cooldowns when using /cast (versus a wand)
# cast_command_cost_reduction: 1.0
# cast_command_cooldown_reduction: 0.0

# Whether wands can be crafted on a crafting table
 enable_crafting: false

# Whether wands can be combined on an anvil
 enable_combining: true

# Whether wands can be upgraded on an enchanting table
 enable_enchanting: true

# Whether or not using a wand on an anvil will organize its inventory
 enable_organizing: true

# Enable/Disable automatic spell upgrades
 enable_spell_upgrades: true

# This can be used to scale spell and wand prices up and down without
# Having to invidivudally configure "worth" for each spell.
#
# If you have a default Gringott's install, you may want to change this to "0.01" to make the emeralds
# match up.
# worth_base: 1

# Disable the resource pack
# default_resource_pack: ""

# Turn on skull-based spell icons (may be needed if you're not using the RP)
# url_icons_enabled: true

`

**Comment by dryter97** [comment]
> #
# Modify this file to change the overall behavior of the Magic plugin.
# only include the options you want to modify.
#
# You can also add individual files to the config/ folder
#
# To see all available options, look in this folder:
# https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/main/resources/defaults/config
#
# Options for sub-components (spells, wand templates, chest populator, etc) are 
# found in separate files.
#
# For customization help see: 
# https://github.com/elBukkit/MagicPlugin/wiki/Customization
#

#
# Examples:
# Note that a "#" character means the line is commented out and has no effect.
# Make sure to not comment out the lines you add, there should not be a space in front of the name, indentation is important.
# Use http://www.yamllint.com if you have issues with your config, make sure not to use tabs!
# 

# Load one of the included example configurations instead of the defaults.
# Current options: potter, safe, survival
# Any customizations will still be loaded on top of the example configs.
# example: potter

# Add one or more of the included example configurations on top of the defaults.
# The config.yml potion is not loaded, for sanity's sake.
# add_examples:
#   - potter
#   - survival

# Some common fields that you might like to override:

# Give new players a wand when they first join
# welcome_wand: beginner

# Whether or not to show any messages (in chat) 
 show_messages: true

# Whether or not to show messages on every spell cast (in chat)
 show_cast_messages: false

# Enable/Disable Sound Effects
 sounds: true

# Prevent rapid sending of chat messages from the plugin (in milliseconds)
# message_throttle: 3000

# Set this to 1 to just turn costs off, or you can use it to scale costs down.
# cost_reduction: 0.0

# How much to reduce costs and cooldowns when using /cast (versus a wand)
# cast_command_cost_reduction: 1.0
# cast_command_cooldown_reduction: 0.0

# Whether wands can be crafted on a crafting table
 enable_crafting: false

# Whether wands can be combined on an anvil
 enable_combining: true

# Whether wands can be upgraded on an enchanting table
 enable_enchanting: true

# Whether or not using a wand on an anvil will organize its inventory
 enable_organizing: true

# Enable/Disable automatic spell upgrades
 enable_spell_upgrades: true

# This can be used to scale spell and wand prices up and down without
# Having to invidivudally configure "worth" for each spell.
#
# If you have a default Gringott's install, you may want to change this to "0.01" to make the emeralds
# match up.
# worth_base: 1

# Disable the resource pack
# default_resource_pack: ""

# Turn on skull-based spell icons (may be needed if you're not using the RP)
# url_icons_enabled: true

**Comment by dryter97** [comment]
`#
# Modify this file to change the overall behavior of the Magic plugin.
# only include the options you want to modify.
#
# You can also add individual files to the config/ folder
#
# To see all available options, look in this folder:
# https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/main/resources/defaults/config
#
# Options for sub-components (spells, wand templates, chest populator, etc) are 
# found in separate files.
#
# For customization help see: 
# https://github.com/elBukkit/MagicPlugin/wiki/Customization
#

#
# Examples:
# Note that a "#" character means the line is commented out and has no effect.
# Make sure to not comment out the lines you add, there should not be a space in front of the name, indentation is important.
# Use http://www.yamllint.com if you have issues with your config, make sure not to use tabs!
# 

# Load one of the included example configurations instead of the defaults.
# Current options: potter, safe, survival
# Any customizations will still be loaded on top of the example configs.
# example: potter

# Add one or more of the included example configurations on top of the defaults.
# The config.yml potion is not loaded, for sanity's sake.
# add_examples:
#   - potter
#   - survival

# Some common fields that you might like to override:

# Give new players a wand when they first join
# welcome_wand: beginner

# Whether or not to show any messages (in chat) 
 show_messages: true

# Whether or not to show messages on every spell cast (in chat)
 show_cast_messages: false

# Enable/Disable Sound Effects
 sounds: true

# Prevent rapid sending of chat messages from the plugin (in milliseconds)
# message_throttle: 3000

# Set this to 1 to just turn costs off, or you can use it to scale costs down.
# cost_reduction: 0.0

# How much to reduce costs and cooldowns when using /cast (versus a wand)
# cast_command_cost_reduction: 1.0
# cast_command_cooldown_reduction: 0.0

# Whether wands can be crafted on a crafting table
 enable_crafting: false

# Whether wands can be combined on an anvil
 enable_combining: true

# Whether wands can be upgraded on an enchanting table
 enable_enchanting: true

# Whether or not using a wand on an anvil will organize its inventory
 enable_organizing: true

# Enable/Disable automatic spell upgrades
 enable_spell_upgrades: true

# This can be used to scale spell and wand prices up and down without
# Having to invidivudally configure "worth" for each spell.
#
# If you have a default Gringott's install, you may want to change this to "0.01" to make the emeralds
# match up.
# worth_base: 1

# Disable the resource pack
# default_resource_pack: ""

# Turn on skull-based spell icons (may be needed if you're not using the RP)
# url_icons_enabled: true

`

**Comment by dryter97** [comment]
```
#
# Modify this file to change the overall behavior of the Magic plugin.
# only include the options you want to modify.
#
# You can also add individual files to the config/ folder
#
# To see all available options, look in this folder:
# https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/main/resources/defaults/config
#
# Options for sub-components (spells, wand templates, chest populator, etc) are 
# found in separate files.
#
# For customization help see: 
# https://github.com/elBukkit/MagicPlugin/wiki/Customization
#

#
# Examples:
# Note that a "#" character means the line is commented out and has no effect.
# Make sure to not comment out the lines you add, there should not be a space in front of the name, indentation is important.
# Use http://www.yamllint.com if you have issues with your config, make sure not to use tabs!
# 

# Load one of the included example configurations instead of the defaults.
# Current options: potter, safe, survival
# Any customizations will still be loaded on top of the example configs.
# example: potter

# Add one or more of the included example configurations on top of the defaults.
# The config.yml potion is not loaded, for sanity's sake.
# add_examples:
#   - potter
#   - survival

# Some common fields that you might like to override:

# Give new players a wand when they first join
# welcome_wand: beginner

# Whether or not to show any messages (in chat) 
 show_messages: true

# Whether or not to show messages on every spell cast (in chat)
 show_cast_messages: false

# Enable/Disable Sound Effects
 sounds: true

# Prevent rapid sending of chat messages from the plugin (in milliseconds)
# message_throttle: 3000

# Set this to 1 to just turn costs off, or you can use it to scale costs down.
# cost_reduction: 0.0

# How much to reduce costs and cooldowns when using /cast (versus a wand)
# cast_command_cost_reduction: 1.0
# cast_command_cooldown_reduction: 0.0

# Whether wands can be crafted on a crafting table
 enable_crafting: false

# Whether wands can be combined on an anvil
 enable_combining: true

# Whether wands can be upgraded on an enchanting table
 enable_enchanting: true

# Whether or not using a wand on an anvil will organize its inventory
 enable_organizing: true

# Enable/Disable automatic spell upgrades
 enable_spell_upgrades: true

# This can be used to scale spell and wand prices up and down without
# Having to invidivudally configure "worth" for each spell.
#
# If you have a default Gringott's install, you may want to change this to "0.01" to make the emeralds
# match up.
# worth_base: 1

# Disable the resource pack
# default_resource_pack: ""

# Turn on skull-based spell icons (may be needed if you're not using the RP)
# url_icons_enabled: true


```

**Comment by dryter97** [comment]
thats only what i get. ill add it manualy like where he's suposed to be. so default is like what's suposed to be here if i understand. ill just copy the default and drop it there insteed of copy pasting stuff arround

**Comment by dryter97** [comment]
finaly working like i did. sorry for disturbing, maybe honestly you could put the default file where its suposed to be properly instead of leaving it on the default config folder. Thx a lot 👍

**Comment by dryter97** [comment]
for those not sure if the issus is fix ill just post the way i make it work:

taked the default config from plugins/magic/default/config.defaults.yml
replace config.yml at the plugins/magic whit config.default.yml
removing the .default word in config.default.yml
reloading the plugins or restarting if you prefer
working!

closing the post now

**Comment by killme** [comment]
You generally only copy over the options that you've changed.
