### ISSUE TITLE
Move interaction with ladders

### ISSUE THREAD

**Issue by martdamp** [elBukkit/MagicPlugin#489]
When casting a move and looking up or down when in a ladder block then the magic move doesn't work. When you look forward the move does work.

**Comment by killme** [comment]
May be a vanilla issue, no interact or animate events are fired when left clicking towards the air block here. They are fired when clicking on the block. No arm movement animation is shown when clicking into the air as well.

![2019-04-08_19 38 01](https://user-images.githubusercontent.com/1255353/55744758-f1eb3180-5a35-11e9-842b-92fa89328fad.png)

**Comment by NathanWolf** [comment]
Bummer :(
