### ISSUE TITLE
Strange console error

### ISSUE THREAD

**Issue by Gavatoss** [elBukkit/MagicPlugin#491]
I am using version 1.9 spigot.
I get an error to the console when using the /wand command and opening the plug-in.

Note: I used the /wand command on the last line.
http://www.mediafire.com/file/jk3dkm67akn4g1k/latest.log/file

**Comment by NathanWolf** [comment]
Looks like a config problem, have you customized configs?

**Comment by Gavatoss** [comment]
I didn't change the settings. I changed the spigot version a few times, but it doesn't work.

**Comment by NathanWolf** [comment]
And you are sure you're using the correct Magic version for your spigot version? There is a version list here, if you are on 1.9 for some reason (not 1.9.3) you can't be using the latest plugin version.

https://www.spigotmc.org/resources/magic.1056/

**Comment by Gavatoss** [comment]
I installed magic (6.0.4) and got the error again ;
http://www.mediafire.com/file/jccpbzc1bb17iq8/latest.rar/file

**Comment by NathanWolf** [comment]
I can't see that file, can you just use pastebin or hastebin or something that's not a rar'd download?

I just tried latest Magic on 1.9.4 and it works fine. Are you stuck on version 1.9 for some reason?

Try deleting all the files in plugins/Magic, it really looks like you messed with the configs somehow.

**Comment by NathanWolf** [comment]
I meant to note that if you can use 1.9.4 or above you can use the latest Magic. I'll try to test 6.0.4 on 1.9 when I get a chance.

**Comment by killme** [comment]
Updated their comment with a proper link.

**Comment by killme** [comment]
Then again, those errors don't really make sense considering `GENERIC_KNOCKBACK_RESISTANCE` was introduced at the same time as the enum it is in.

**Comment by Gavatoss** [comment]
https://hastebin.com/igosisumij.md

**Comment by NathanWolf** [comment]
I found spigot 1.9, downloaded magic 6.0.4 and I have no errors.

If you've tried deleting plugins/Magic and starting fresh, then I don't know what to tell you at this point, sorry.
