### ISSUE TITLE
Can't remove wands 

### ISSUE THREAD

**Issue by BLX-S** [elBukkit/MagicPlugin#492]
I tried destroying the wands and unbinding them but I can't manage to get them out of my inventory. Sidenote I also can't figure out the wand ID's required for the wand destroy command. Does anyone know how I can remove all my wands?

**Comment by NathanWolf** [comment]
You're trying this via code? What have you tried to do?

The wand destroy command doesn't use ids, it just destroys the wand you're holding.

**Comment by BLX-S** [comment]
No, I'm doing this as an OP ingame on a server. For example I just did /wand and I succesfully got an empty wand afterwards I did /wand destroy and it made my wand act like a regular object but it still looks like a wand and it still says magic missile (wand).

**Comment by NathanWolf** [comment]
Ah, ok- yeah that's an oversight, I'll fix it. It needs to clear a few more flags other than just wand data.

**Comment by NathanWolf** [comment]
Fixed in latest dev build.

http://jenkins.elmakers.com/job/MagicPlugin/2869/
