### ISSUE TITLE
Spell removal bug (?)

### ISSUE THREAD

**Issue by 4kz** [elBukkit/MagicPlugin#493]
Hello there, just a question if I may.. Why by removing a spell upgrade such as missile|2 also the "missile" spell is removed from a mage?
I thought that they were seperate spells..
the spells are being removed trough the MagicAPI.

**Comment by NathanWolf** [comment]
They are configured as separate spells, but a player only knows a spell or not. You can't remove a spell level from them. You could remove the spell then re-add it as the first level, but that's a little messy.

Even if you were to remove it, spell levels are based on cast count so they'd just level it up right away again anyway.

**Comment by 4kz** [comment]
well they aren't assigned by cast count on my server.. Any chanche you could add a feature to remove spell levels trough the API? If not I can try the workaround you suggested

**Comment by NathanWolf** [comment]
I know this is crazy old but I just added a setSpellLevel method for this.
