### ISSUE TITLE
1.14 sandbox server - most spells not working

### ISSUE THREAD

**Issue by jamesol1** [elBukkit/MagicPlugin#494]
Hi Nathan,
Not sure if you saw my messages in the discord about this. But most spells arent working currently in the 1.14 sandbox so it's currently pretty unusable. I was hoping you would perhaps revert the server back to 1.13.2 so we can use it for making spells again! If you need it up in 1.14 fair enough, just wondering.
Thanks

**Comment by NathanWolf** [comment]
I could definitely put it back on 1.13, I did not realize how broken it was.

I might have to wipe the world though...

Could you list a few of the spells that aren’t working?

**Comment by jamesol1** [comment]
Don't think anyone would mind a world wipe, as long as that doesnt wipe the spells people have. Well 'Water Bolt3' and 'aurball3' dont work. Two of which i have on my spell list.

**Comment by NathanWolf** [comment]
Ok, thanks, I'll try those out when I get a chance. I'd like the 1.14 compatibility to be stable, I haven't seen any issues with default spells but I haven't tested all of them, either.

I'll revert the sandbox for now.

**Comment by jamesol1** [comment]
Thanks!

**Comment by jamesol1** [comment]
Hey! Sorry to pest you on the sandbox server again. But one issue with the server is that the spell config don't reload when you open and close your wand. So i can't update my spells or add new ones.

**Comment by NathanWolf** [comment]
Hm, thanks kind of weird. I copied some data files back, that may help.

I also put Citizens back on there, so hopefully the reload NPC will show up.

I’m traveling tomorrow so I won’t be able to really check on the servers for a few days.

**Comment by jamesol1** [comment]
The map is a seemingly random survival one, so the npc's aren't at the spawn. Unfortunetly i don't think the spell config reload with the wand is working.

**Comment by NathanWolf** [comment]
Allright I fixed up spawn and got the NPCs back.

Still not sure what's wrong with the auto-reloading though. I'll look at that when I get a chance.

**Comment by jamesol1** [comment]
Thanks again! Server is working well.

**Comment by NathanWolf** [comment]
Glad to hear it!

So I tried out the 3 spells you mentioned, on my local 1.14 test server. They seem fine? What was wrong with them, did they not work at all on the sandbox server?

The effects on the seraphic fireball are freaking awesome ....

**Comment by NathanWolf** [comment]
Oh, wait- is it the block-based effects? I do see some errors in the console but the spells seemed to work anyway. I'll see about getting that fixed though!
