### ISSUE TITLE
Add Targeting Filter Based on Potion Effects

### ISSUE THREAD

**Issue by TofPlays** [elBukkit/MagicPlugin#495]
A homing projectile that will only target the entities that are poisoned
    - class: CustomProjectile
      target_potioneffect: POISON

And in parameters:
track_target: true

You might wanna look at how betonquest does this, its an open-source plugin:
https://github.com/Co0sh/BetonQuest/wiki/Conditions-List
look for potion effect condition there.

**Comment by NathanWolf** [comment]
I think this could be done as a base spell targeting filter, so it could be used for homing in projectiles or any other targeting.

**Comment by NathanWolf** [comment]
Well nearly a year later... I've added `target_potion_effects` and `ignore_potion_effects` parameters.

Both take a list of potion effect types. The `target` parameter will target entities with *any* of the given potion effects, the `ignore` parameter will skip entities with any of the effects.
