### ISSUE TITLE
Issue with html color codes 

### ISSUE THREAD

**Issue by jamesol1** [elBukkit/MagicPlugin#497]
For a while ive noticed some html color codes don' t work. For instance this is meant to be slategrey (a kind of mid grey). But when it put it on my spell it comes up as light blue.

        tick:
        - particle: redstone
          color: "708090"
          particle_count: 3
          particle_offset_x: 0.175
          particle_offset_y: -0.175
          particle_offset_z: 0.175
          location: target

**Comment by NathanWolf** [comment]
Please re-open if you're still having issues here.
