### ISSUE TITLE
Arrow spells not working.

### ISSUE THREAD

**Issue by Ferocimo** [elBukkit/MagicPlugin#498]
Hello,

Since 1.13 it is no longer possible to spawn flying arrows with spells. You said on issue https://github.com/elBukkit/MagicPlugin/issues/456 that it was made to be used with magic bows. We didn't implement those, and we created numerous "arrow spells" that are fired from the wand (about 8 spells in total).

Those spells can't be use anymore because the plugin doesn't recognize the projectile type "TippedArrow". Could you fix this ?

Thank you.

**Comment by NathanWolf** [comment]
Nothing really changed with TippedArrow, the plugin just uses MC's internal entity names for things.

Could you please provide an example of one of your arrow spells? In #456 I thought you were referring to the builtin ones, my apologies.

**Comment by Ferocimo** [comment]
It wasn't me on #456, we're just having the same issue. 

This is our modification of the basic "arrow" spell... You will probably say it's badly configured (it certainly is), but it worked fine previously.
https://pastebin.com/xZEXgWhC

**Comment by Ferocimo** [comment]
Here is another basic one.

https://pastebin.com/71xWp7FS

**Comment by NathanWolf** [comment]
Have you tried them without `source_location: head`?

I think if you try to launch from the head it's going to immediately hit the caster's head. Though I don't know how or why that would've worked before.

**Comment by Ferocimo** [comment]
Actually we set it to head as a fix to this issue : https://github.com/elBukkit/MagicPlugin/issues/442

**Comment by NathanWolf** [comment]
Ah, what a tangled web... 🕸 

Could you try adding `start: 1` and see if that fixes the issue? If it does, you can lower that number down until it feels good. That'll spawn the arrow some distance out in front of the player.

I don't know of any way to just outright prevent an arrow from hitting the caster. In vanilla I believe it launches a little from the right and forward as well (basically shoots out of the bow, not out of your head)

**Comment by Ferocimo** [comment]
Just so you know, I should have mentionned that it creates an error in console : 
[20:24:21] [Server thread/WARN]: [Magic] [33m Bad projectile class: Tipped_Arrow[0m

I'm gonna eat something and test what you said after. I'll be right back.

**Comment by Ferocimo** [comment]
(this also happens with TippedArrow)

**Comment by NathanWolf** [comment]
It says that for the spells you pasted? That would be weird since it's printing exactly what you put in the `projectile` parameter, and you don't have the underscore in there.

What I suggested is not going to work if it's completely failing to spawn the projectile, that was meant to prevent it from hitting the caster.

They didn't change the entity name in 1.13 or 1.14, it's still EntityTippedArrow in the MC source. Let me know if you find after you test.

**Comment by Ferocimo** [comment]
No, sorry I miss-pasted, that's why I added it also happens with TippedArrow. With the spell I posted above, it says this as error : [Server thread/WARN]: [Magic] �[33m Bad projectile class: TippedArrow�[0m

It doesn't work either with modifying what you suggested. I should clarify that, when you cast the spell, it says "your spell failed !" and the error pops in the console. I really don't think it's an issue related to the spawning location of the arrow, since that if it were the case, I would see it somewhere and it wouldn't say that the spell failed.

I thought that they changed it to Tipped_Arrow instead of TippedArrow, so I tried that but it didn't work. Neither did "Arrow".

**Comment by NathanWolf** [comment]
Are you running Spigot or some other variant?

It's pretty weird, it really is just instantiating the NMS entity, the name of that hasn't changed. Have you tried your spells on the sandbox server?

**Comment by Blamo27** [comment]
@NathanWolf Paperspigot

**Comment by NathanWolf** [comment]
Oh... I may not be able to do anything about that if that's the case :( I'm guessing Paper is doing some weird renaming of the NMS classes.

**Comment by Blamo27** [comment]
Are you sure about that ? It's just a fork from Spigot ?

**Comment by NathanWolf** [comment]
I am not sure about anything in Paper, I don't really support it though generally it doesn't break anything.

But if it works in vanilla Spigot and not in Paper, that does narrow down the problem.

**Comment by Blamo27** [comment]
Same thing with Spigot 😢

**Comment by Ferocimo** [comment]
It also fails on a sandbox server, either with Paper or Spigot. I think you could recreate this bug just by using the same spell I pasted previously.

**Comment by NathanWolf** [comment]
Well that's good news, thank you. I'm sorry I misunderstood. Yes it seems like this got broken in the latest Magic build.

Ok, thank you for your patience, I'll get it fixed for the next release!

In the meantime if you go back to 7.6.20 you should be ok, 7.7 really has nothing but 1.14 compatibility changes (which is what broke this in 1.13)

**Comment by Ferocimo** [comment]
Thank you very much, will be looking forward next build then !

**Comment by NathanWolf** [comment]
Fixed in 7.7.1 (Just released)

**Comment by Ferocimo** [comment]
I confirm it's fixed, thank you !
