### ISSUE TITLE
Having certain configs enabled breaks the resource pack.

### ISSUE THREAD

**Issue by NABrr** [elBukkit/MagicPlugin#502]
After enabling the extra configs of War, Stars, and Bending: Some of the default wands only appeared as sticks and no longer had their custom models. Blasters from the Stars config had no model as well. Also, as in prior builds of Magic, unless this changed, lightsaber models showed always open and never closed to just the hilt. Unsure if it's just a confliction or somehow the resource pack that my server gives is bugged.

**Comment by NathanWolf** [comment]
Sorry for responding so late- there is a special RP that gets used when you include the war configs, but it should still be working. This is how my dev server is setup.

If you're still having issues and want support, please show me the configs you've got to add in the examples.

**Comment by NABrr** [comment]
Main thing is that apparently some tiers of wands have certain models. One of my players stated that after I enabled the other configs aside from default that the wands just became sticks. I reset the config to default but the wands are still broken. When I had Stars enabled, the sabers didn't work quite right and blasters were sticks. When war was enabled as well, its items looked right.

**Comment by NathanWolf** [comment]
Wanda being sticks is pretty odd since the item they use is the wooden hoe.

Can you share the configs you’re using via hastebin, please?

**Comment by NABrr** [comment]
Ok, here is a pastebin of my config https://pastebin.com/W8tX2Yzi

**Comment by NathanWolf** [comment]
Sorry for never getting back to this. Please re-open if you're still having problems. The config you pasted had a pretty general Yaml issue, a space in front of `add_examples`.
