### ISSUE TITLE
Minecraftpros discord gone - magic plugin discord?

### ISSUE THREAD

**Issue by jamesol1** [elBukkit/MagicPlugin#503]
I was wondering given that minecraftpros (which had a magic plugin support section) if you guys would be interested in making a magic plugin discord for help, sharing spells, general chat etc.

**Comment by NathanWolf** [comment]
The one on minecraftpros is basically the official one. I don't think we need a separate discord, especially considering I've not personally been on discord in a while. There are lots of good people there who can help already, don't think we should start from scratch.

**Comment by NathanWolf** [comment]
Oh.. wait.. I missed the title. That discord is gone.. ??

**Comment by jamesol1** [comment]
Yes minecraftpros has been deleted.

**Comment by NathanWolf** [comment]
Well that sucks. Yeah I think we could start a new server ...

**Comment by jamesol1** [comment]
Ah nice one. It probably would be small but if you put the link up on the spigot page when you make it, i'm sure it could grab a fair few people.

**Comment by NathanWolf** [comment]
Allrighty- pretty bare bones for now: https://discord.gg/6TYYth
