### ISSUE TITLE
spell broom and item Broomstick 1.14.1

### ISSUE THREAD

**Issue by Yukyxy** [elBukkit/MagicPlugin#505]
Hello the server crash if the player use Broomstick

https://pastebin.com/9PHVbHh5

crash logs https://pastebin.com/mgHMPxeW

**Comment by NathanWolf** [comment]
Brooms aren’t compatible with creative mode.

Creative mode in general is not supported by this plugin.

This is also not a server crash, just an error.

If this is not correct, please re-open and provide more details.
