### ISSUE TITLE
"Superkill" doesn't work (I'm OP)

### ISSUE THREAD

**Issue by TristanPFox** [elBukkit/MagicPlugin#506]
The ability looks dark like its on cooldown, and I cant cast. 1.13.2

**Comment by NathanWolf** [comment]
That spell requires 300 mana- are you using an Uberwand, or some wand with a lot of mana?

**Comment by TristanPFox** [comment]
Yes I have enough mana :/

**Comment by NathanWolf** [comment]
I don't know what's up then, sorry.

**Comment by TristanPFox** [comment]
That's fine, just wanted to post the bug so it was known

**Comment by NathanWolf** [comment]
What wand are you using? Can you post a screenshot of what it says when you hold that wand with Superkill active and use the command `/mage check`?

**Comment by TristanPFox** [comment]
I actually just logged back in after a long while and its working now! :)
Anywhere I can learn how to use the animate spell better? Having a really
hard time understanding it. It says the golem was born, and then defeated

**Comment by NathanWolf** [comment]
Animate is not a spell really meant for casting, it is used by a block golem thing that may not really exist anymore TBH

If you want to see something similar (very dangerous, probably don't cast in a non-testing world) you can try `/cast birth_hunter`
