### ISSUE TITLE
spell broom and item Broomstick 1.14.1 1.14.2

### ISSUE THREAD

**Issue by Yukyxy** [elBukkit/MagicPlugin#507]
Please don't close the spell broom and item Broomstick doesn't works in 1.14.1 1.14.2
gamemode 0 look impossible to fly :
https://www.youtube.com/watch?v=bOpS-rgpSWY&feature=youtu.be

and no gamemode 1 with broostick crash the server, the server is freezing..

> Brooms aren’t compatible with creative mode.
> Creative mode in general is not supported by this plugin.
> This is also not a server crash, just an error.
> If this is not correct, please re-open and provide more details.

https://zupimages.net/up/19/22/aqxi.png
you say that the server does not crash but if it crash :(

**Comment by NathanWolf** [comment]
You really could've just reopened the other issue like I asked :(

What version of Magic are you on? For 1.14 you need 7.7.2 or brooms (and a few other things) will be broken.

The creative mode issue is a Spigot problem, there's nothing I can do about it. This plugin **_does not support creative mode_**

**Comment by Yukyxy** [comment]
Sorry I do not know github well :( (and my english is not good)
I use Magic 7.7.2
[Magic] Loading Magic v7.7.2-59630c0

**Comment by NathanWolf** [comment]
Ok thank you- and can you please add the output of /version ? Are you using Spigot, Craftbukkit, Paper or something else?

Brooms have been working ok for me, and I've never seen that TRAP error crash a server before.

**Comment by Yukyxy** [comment]
spigot 1.14.2 https://zupimages.net/up/19/22/tknh.png

**Comment by Yukyxy** [comment]
it's "armor_stand_marker: true" the bug, on false the broomstick works but the height is not good...

https://zupimages.net/up/19/22/pivp.png

**Comment by NathanWolf** [comment]
Yes, I changed this in the builtin broom spell in recent versions. This is why it's always a good idea to use or at least inherit from the default spells. If you have your own spell and RP you'll need to adjust. 

The RP that fixes the offset is here: https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-RP-8-1.zip

**Comment by Yukyxy** [comment]
thank you
