### ISSUE TITLE
mobs custom or spell decoy : appearance doesn't work 1.14.2

### ISSUE THREAD

**Issue by Yukyxy** [elBukkit/MagicPlugin#511]
spigot 1.14.2
the decoy spell or the mobs custom their appearance does not work anymore.
example:
The mob should look like npc but it looks like a creeper...
Decoy should take the appearance of the player but it's a simple creeper...
mob:
https://pastebin.com/8XcdGnny
 " disguise:
    type: player
    name: Adepte
    skin: _wcdc
  item: appearance_gardien"

decoy:
https://zupimages.net/up/19/22/zp0i.png
https://pastebin.com/yeTJA9r9

**Comment by NathanWolf** [comment]
Do you have LibDisguises and ProtocolLib and have verified they're working?

**Comment by Yukyxy** [comment]
ok sorry i just updated LibDisguises it's ok now
