### ISSUE TITLE
spell config

### ISSUE THREAD

**Issue by owenhaines** [elBukkit/MagicPlugin#513]
For some reason the link isn't working to get to the default config for spells, as I'd rather not go through and type out each spell I was wondering where the framework for the default spells are so I could copy paste and change.

**Comment by NathanWolf** [comment]
Where did you find a broken link? I'd like to update them.

https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/main/resources/examples/survival

**Comment by owenhaines** [comment]
I believe it's fixed now, not sure how but it's taking me to the correct place, thanks for getting back so quickly though!
