### ISSUE TITLE
1.14.2 bugs

### ISSUE THREAD

**Issue by PhvntxmX** [elBukkit/MagicPlugin#514]
Airscooter spell not working
Hat spell error - https://pastebin.com/bitAJz0x
Tendril, cage & tent spells are not working
Poison arrow doesnt deal any damage
Tall grass, double plants etc counts as full blocks, so projectile cant go through it
Magic sword texture is broken
![Безымянный](https://user-images.githubusercontent.com/51493955/59131249-eb6c2e00-8982-11e9-977b-9571011da690.png)

**Comment by NathanWolf** [comment]
Thank you! These should all be fixed in the latest dev build.
