### ISSUE TITLE
Hat Spell is Broken

### ISSUE THREAD

**Issue by llronaldoll** [elBukkit/MagicPlugin#515]
![image](https://user-images.githubusercontent.com/5334591/59171187-3f5c4b80-8b18-11e9-9f48-2e021af6a651.png)

when using several spells with the warlock wand, do not count it acts like a hoe, and I get these errors in the console, has some problems with the icons of the wand store minecraft and spigot 1.14.2
![2019-06-10_00 36 48](https://user-images.githubusercontent.com/5334591/59171295-babdfd00-8b18-11e9-8872-078c12598166.png)

**Comment by llronaldoll** [comment]
this happens for example when using the Hat spell

![image](https://user-images.githubusercontent.com/5334591/59172097-abd94980-8b1c-11e9-8fcf-42a88ed1e2c8.png)

**Comment by NathanWolf** [comment]
The Hat spell will be fixed in the next dev build, thanks for pointing that out!

The appearance shop looks OK to me, though. Are you using the default RP? What are you using to show the shop? 

And the Warlock wand is not actually a wand. It's just an item for Warlock mobs to hold.

**Comment by NathanWolf** [comment]
Update: I wasn't checking the magic sword, that model should be fixed now- thanks!
