### ISSUE TITLE
Fireball Spell Permission Issues

### ISSUE THREAD

**Issue by doctorblanket** [elBukkit/MagicPlugin#516]
I have updated to the newest version and am still having this issue. The spell isn't working even when players are given the permission for it. It only works for me, seemingly because I'm op'ed. No error is returned to the console when cast. The error given to the player is "you don't have permission to use that here". This happens even when they are in the wild. All other spells are working.

**Comment by NathanWolf** [comment]
Do players have build and pvp permission in the wild?

**Comment by doctorblanket** [comment]
Yes

**Comment by NathanWolf** [comment]
It definitely sounds like a PvP or build issue of some kind given the message, the Fireball spell requires both.

Can you have a player hold a wand with Fireball active and then you use the `/mage <player> check` command? That will list all of the reasons why a spell might not be castable.

**Comment by doctorblanket** [comment]
Yep ok, it looks like the spell does work in areas labeled for pvp. Thank you for the help. My apologies.
