### ISSUE TITLE
MMOB command not spawning creature when called from a plugin.

### ISSUE THREAD

**Issue by P-paj** [elBukkit/MagicPlugin#518]
/mmob spawn raider x y z world 3 spawns 3 - properly spawns raiders when ran by me in game.
using it in console works to spawn them as well.

However when using a custom plugin to dispatch a console command using
Bukkit.getServer().dispatchCommand(Bukkit.getServer().getConsoleSender(), "mmob command")
Doesnt work! =(( It says they are spawned, tells me the location where they are supposed to be spawned, (i quintuple checked that they are spawning at the correct location and world) but they never really show up

**Comment by P-paj** [comment]
![mmob spawning code](https://user-images.githubusercontent.com/51720134/59299430-979b6680-8c5a-11e9-8fb9-e70eb398cd52.JPG)



![spawnconfirmed](https://user-images.githubusercontent.com/51720134/59299476-b568cb80-8c5a-11e9-9370-84e46ef3d8fc.JPG)

**Comment by NathanWolf** [comment]
Are you sure something's not blocking mob spawning at the target location?

I just tried it myself from console, `mmob spawn warlock 15575 70 20192 world` and it worked. You've tried it yourself from console as well?

**Comment by P-paj** [comment]
Only conflating plugin would be griefprevention, which i'm fairly sure magic has some support for correct? Thanks for this insanely fast response haha. I'd love to know some greifprevention settings to mess with to allow them (the mobs are being spawned in admin claimed areas so players cant grief these locations)

**Comment by NathanWolf** [comment]
Magic has no plugin integration having to do with mob spawning, it's just pvp and build permissions for the most part. I'm not familiar enough with GP to know if it would block mobs from spawning.

WorldGuard would be the main suspect- but if the command works when you run it manually from the console, but not via your plugin, there may be something else wrong.

**Comment by P-paj** [comment]
Plugins Here:
GriefPrevention
Essentials
EssentialSpawns
Holograms
Luckperms
Mcmmo
Votifier
Worldedit
 No worldguard right now.
But yeah it definitely runs through console, the same exact command when ran through t he plugin though makes console say the the mobs were spawned, but nothing happens.

**Comment by NathanWolf** [comment]
There should be literally no difference between dispatchCommand(consoleSender) and running a command via console- so that is really pretty weird.

I would suggest having your plugin log the exact command it's running, then try running that command yourself.

**Comment by P-paj** [comment]
can report with results in 1 min

**Comment by P-paj** [comment]
im a dumbass, they are being spawned far in the sky because " " + y+2 +" " the why is being treated as a string, with the 2 being tacked at the end of it lmao

**Comment by P-paj** [comment]
actually it still didnt spawn the raider at the listed position...

**Comment by P-paj** [comment]
![verbose](https://user-images.githubusercontent.com/51720134/59300810-17770000-8c5e-11e9-8fba-960fa456ee37.JPG)

**Comment by P-paj** [comment]
ALL IS GOOD IN THE HOOD y+2 needed to be in parenthesis, sorry for edit spam.
