### ISSUE TITLE
Some spells can't be learnt

### ISSUE THREAD

**Issue by leveljaap** [elBukkit/MagicPlugin#520]
Hello,
Nobody on my server can learn "extra" spells like workbench and stuff. They're using custom paths but I don't see any problem in my config. Some help would be appreciated. These are the paths:

```holyapprentice:
  name: Apprentice
  icon: wood_hoe:2
  migrate_icon: wood_hoe
  inherit: default
  spell_count: 1
  extra_spells:
  - familiar
  - workbench
  - flare
  - stun
  spells:
  - missile
  - arrow
  - blast
  - cure
  - heal
  - bubble
  - torch
  - push
  - pull
  - recall
  - reflect
  - frost
  - stream

undeadmage:
  name: Undead Mage
  icon: wood_hoe:1
  migrate_icon: wood_hoe
  inherit: default
  spell_count: 1
  extra_spells:
  - flare
  - stun
  - workbench
  - monster
  spells:
  - missile
  - arrow
  - blast
  - poison
  - fireball
  - torch
  - push
  - pull
  - recall
  - blind
  - reflect
  - curse
  - wither
  - disarm

neophyte:
  name: Neophyte
  icon: wood_hoe:4
  migrate_icon: wood_hoe
  inherit: default
  spell_count: 1
  extra_spells:
  - flare
  - stun
  - workbench
  - tracking
  spells:
  - missile
  - arrow
  - blast
  - cure
  - bubble
  - fireball
  - torch
  - push
  - pull
  - peek
  - recall
  - reflect
  - fire
  - frost
  - disarm

cleric:
  name: Cleric
  icon: wood_hoe:10
  migrate_icon: wood_hoe
  inherit: default
  spell_count: 1
  extra_spells:
  - flare
  - stun
  - workbench
  - glide
  spells:
  - missile
  - arrow
  - blast
  - cure
  - heal
  - bubble
  - torch
  - push
  - pull
  - recall
  - admission
  - mine
  - chop
  - fling```

Am I doing something wrong?

**Comment by NathanWolf** [comment]
If you could wrap them in a code block (The "<>" in the toolbar) that'd help, but if I'm reading that right it looks ok.

The extra spells don't show up in the spell shop at all?

**Comment by leveljaap** [comment]
They do show up, but when you click them you just get "You already know <spell>"

Also I tried putting it in a code block but it didn't work for some reason. I'll try again by editing it

**Comment by NathanWolf** [comment]
Try changing it to 3 of those apostrophies on a single line before and after the block

Or just attach your config as a file, that may be easier :)

If I can get your path config I can test it out.

**Comment by leveljaap** [comment]
Hello,

Here are the configs. Had to convert them to txt otherwise I couldn't upload them. I uploaded all the configs I changed, just in case.

[paths.txt](https://github.com/elBukkit/MagicPlugin/files/3287591/paths.txt)
[spells.txt](https://github.com/elBukkit/MagicPlugin/files/3287592/spells.txt)
[wands.txt](https://github.com/elBukkit/MagicPlugin/files/3287593/wands.txt)

**Comment by NathanWolf** [comment]
This was a bug with the "limit spells to path" feature, it wasn't allowing learning extra spells from paths.

I have fixed this bug in the latest dev build if you'd like to try that out:

http://jenkins.elmakers.com/job/MagicPlugin/2881/com.elmakers.mine.bukkit.plugins$Magic/

**Comment by leveljaap** [comment]
Ohh thanks a lot. Is it stable? I have a decent amount of players on my server so I'd hate anything getting corrupted or something like that

**Comment by NathanWolf** [comment]
Well honestly it's been a little touch and go since the 1.14 updates. I'm hoping it's stable now but if you don't to risk anything, I would suggest removing `limit_spells_to_path` from your wand configs, which will also fix the problem. 

Test that option of course, I'm not entirely sure that you need it but I could be mistaken. Can your players have more than one type of wand?

**Comment by NathanWolf** [comment]
And to be clear there should *not* be any data-corruption bugs. Mainly there have just been various issues with spells not working, but that's also been mainly on 1.14

What server and plugin version are you currently on?

**Comment by leveljaap** [comment]
Yeah, players can also have magic bows and swords. The spells became available on multiple wands and that was a problem. I'm on 1.13.2 with plugin version 7.7.4.

I'm gonna test the dev build now, thanks for the help.

**Comment by NathanWolf** [comment]
Oh, ok, then I can see why you needed that option. 

And if you're on 7.7.4 already then this snapshot is 100% fine. This fix is literally the only difference :)

All the instability started at 7.7 ... I'm hoping it's all cleared up at this point though. Lots of changes were needed for 1.14 compatibility.

**Comment by leveljaap** [comment]
As far as I've tested, everything works now in the dev version. Thanks for all the help!!
