### ISSUE TITLE
Error Using Survival + Stars Configs

### ISSUE THREAD

**Issue by DarkFort** [elBukkit/MagicPlugin#521]
Error - https://pastebin.com/vEP7heg6
Magic 7.7.4-fd3f986
git-Paper-83 (MC: 1.14.2)

An error occurs when I add a parameter
add_examples:
- survival
- stars

**Comment by NathanWolf** [comment]
Have you tried it without "survival" in the list? Survival is already included by default so it may be trying to add it twice.

**Comment by NathanWolf** [comment]
Please re-open if this is still an issue.
