### ISSUE TITLE
Pollinate Can't Make Double Plants in 1.14.2

### ISSUE THREAD

**Issue by PhvntxmX** [elBukkit/MagicPlugin#522]
Pollinate spell cannot plant double plants
Portal spell error - https://pastebin.com/L040p0YL

**Comment by NathanWolf** [comment]
I see the nether portal material changed in 1.13, I missed that. That'll be fixed in the next dev build.

Pollinate not being able to create double plants is probably a more complex issue- I'll leave this issue open so I can look into that when I have time.

**Comment by NathanWolf** [comment]
This will be fixed in the next dev build, and released in 7.7.6
