### ISSUE TITLE
(Not an issue) Question about models

### ISSUE THREAD

**Issue by leveljaap** [elBukkit/MagicPlugin#523]
Hello.

I was wondering what program you used to create your models, and if I would be able to add new models/edit existing models of the resource pack.

Thanks.

**Comment by NathanWolf** [comment]
I didn't create any of them myself, most were donated. Cubik is the tool of choice, from what I understand. You can do whatever you want with the RP :)

**Comment by leveljaap** [comment]
Okay, thanks a lot! I'll check it out!

Sorry for the late response btw...
