### ISSUE TITLE
How to download the resource pack

### ISSUE THREAD

**Issue by leveljaap** [elBukkit/MagicPlugin#524]
I'm probably stupid but I couldn't find the latest version of the resource pack anywhere. It says it merged with the plugin but I can't find it in the plugin files anywhere either. Did the resource pack stay the same since it was merged? If not, where can I download it?

**Comment by NathanWolf** [comment]
The URL shows up in your server logs on startup, and is in the configs in defaults/.

Also here: https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/defaults/config/rp.yml

The current one (for 1.13 and up) is this: https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-RP-8-1.zip

**Comment by leveljaap** [comment]
Thanks! Exactly what I was looking for!
