### ISSUE TITLE
RP (Well.. Not an issue more of a question)

### ISSUE THREAD

**Issue by weads** [elBukkit/MagicPlugin#526]
I have the resourcepack equipped but the wands and spells are just the purple and black untextured blocks, how do I fix this?

**Comment by NathanWolf** [comment]
Are you using the automatic download feature, or did you download it yourself? It sounds like you have the wrong version for your MC version.

**Comment by weads** [comment]
the wand and spells appeared as untextured without and with the RP, is there a rp for 1.12+?

**Comment by NathanWolf** [comment]
You've got bigger problems them. Without the RP they should look like normal items, mostly hoes.

There are RPs for various versions, the plugin will choose the correct version if you've left the default settings alone.
