### ISSUE TITLE
Players can't earn SP after one cast

### ISSUE THREAD

**Issue by leveljaap** [elBukkit/MagicPlugin#527]
Last time I incorrectly stated this was a problem but this time it actually is. For example, when a player casts magic missile they get 7 SP like they should but after that NO spell gives any SP until they rejoin. Any fix?

**Comment by NathanWolf** [comment]
I am not aware of anything that would cause that. Each spell should have its own SP cooldown. Are any errors showing up in your logs?

**Comment by leveljaap** [comment]
I'm afraid I don't see any error anywhere. I think it started happening when I downloaded the new update, because I know for sure it didn't happen before that.

**Comment by leveljaap** [comment]
Ah I just discovered I was stating false facts again. However, that means Magic Missile has a tremendous cooldown because it just doesn't give any SP after the first cast. I'm certain this wasn't the case earlier.

**Comment by leveljaap** [comment]
All spells seem to have longer cooldown now. In the config I made it so that Wound had the same SP cooldown as magic missile (which worked) but that now has the same problem as well.

**Comment by NathanWolf** [comment]
It's 15 minutes by default for all spells. Magic Missile is shorter but only for levels 1 and 2, to help new players level up.

If you want to pastebin the spell changes you've made, I can take a look.

**Comment by leveljaap** [comment]
It seems the problem was caused by a mistake in the spells config that I made. I fixed it now though so everything is good. Thanks for all the help!
