### ISSUE TITLE
EMP Troubles in 1.14.3

### ISSUE THREAD

**Issue by mercurialmusic** [elBukkit/MagicPlugin#528]
Not quite related to #439 -- for that one I was able to get what I needed by using redstone blocks (still didn't work on any of the other powerables). Now in Spigot 1.14.3 (CraftBukkit version git-Spigot-d05d3c1-fca4157 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)) I'm getting the "Something went wrong!" error using the default EMP spell -- won't fire at all now, and this error in console: https://gist.github.com/mercurialmusic/9ee64e5becf0cb7fe50309db606e57ea

Thanks!

**Comment by NathanWolf** [comment]
I finally got this fixed in 7.7.5

Sorry for the long delay!

**Comment by mercurialmusic** [comment]
Thank you for this! It is functional now on buttons and we're very excited for that, but just for the sake of ironing out wrinkles, it does fail completely if the spell detects a redstone block in the area, error here: https://gist.github.com/mercurialmusic/14ea9b666548108027b3da26d06b6684

**Comment by NathanWolf** [comment]
Oops, thanks! I think I've got that fixed, though I didn't get a chance to test it. Dev build is building now.
