### ISSUE TITLE
1.14.3 undroppable 

### ISSUE THREAD

**Issue by Yukyxy** [elBukkit/MagicPlugin#529]
Hi i use undroppable: true on the wand but my player can put the wand in the chest and other container, it's a bug ? or is there another solution please?

thank you in advance

**Comment by NathanWolf** [comment]
For containers you also need `unstashable: true`

**Comment by Yukyxy** [comment]
Thank you No i  have tried unstashable: true
But doesn’t work too...

**Comment by NathanWolf** [comment]
Hm, that ought to work ... make sure you're not opped while testing, there are permissions that override this behavior. (This is good advice in general when testing this plugin)

**Comment by Yukyxy** [comment]
bad file it works now
