### ISSUE TITLE
CME on Block Undo in  1.14.3

### ISSUE THREAD

**Issue by Yukyxy** [elBukkit/MagicPlugin#530]
Hello I have this error https://pastebin.com/VAzTL1qt

**Comment by NathanWolf** [comment]
That kind of looks like an internal Spigot/MC error. Does this happen consistently?

**Comment by Yukyxy** [comment]
yes frequently

**Comment by NathanWolf** [comment]
Sorry for never coming back to this, but I never did see this problem myself. Do you know if it's still happening?

**Comment by NathanWolf** [comment]
I still couldn't ever reproduce this, going to close the issue until it comes back up again.
