### ISSUE TITLE
Resource Pack Broken Textures

### ISSUE THREAD

**Issue by ImajunationMyth** [elBukkit/MagicPlugin#531]
Hey, loving the plugin and its' features so far. Just a bit of QoL stuff. I'm using the Magic-RP-8-1 Resource pack in 1.12.2 and there are various missing/purple & black textures for some of the items. The Bow and various swords have this purple & black texture and I don't know how to fix it. I tried the Magic-RP-5 Resource Pack though it doesn't offer the alternative models for the wand.

I couldn't find a resource pack version for 1.12.2, how would I go about with this?

**Comment by NathanWolf** [comment]
if possible, I would suggest letting the plugin manage the RP. This is the default setup, if you don't put an RP link in your server.properties, the plugin will use the correct version for your server version.

If you need to man age it manually, the link for 1.12 is 

https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-RP-7.zip
