### ISSUE TITLE
Support - Scoreboard

### ISSUE THREAD

**Issue by Crafterpotter** [elBukkit/MagicPlugin#532]
I coding a scoreboard but I would like to show AC on the scoreboard and the years but what are the API codes

**Comment by NathanWolf** [comment]
Sorry for the late response! Assuming you have AC set up as a custom currency, you would just call `Mage.getCurrency("ac")`

**Comment by NathanWolf** [comment]
Going to assume you got this working or gave up on it. Please re-open if you'd still like help.
