### ISSUE TITLE
PermaFrost > PermaMelt 

### ISSUE THREAD

**Issue by ImajunationMyth** [elBukkit/MagicPlugin#535]
Need to reiterate, Plugin's awesome.

The PermaFrost spell is a useful spell for covering stuff in frost and snow however In case you might happen to do it accidently, it can't be undone by PermaMelt. The PermaFrost skill seems to shoot a projectile while the PermaMelt spell doesn't really do anything. The PermaFrost spell changed the biome in that specific area and if you try to use the PermaMelt spell it doesn't do anything.

Is it supposed to, and if so, how would we go about fixing that? 

I'm using the 1.12.2 plugin version.

**Comment by NathanWolf** [comment]
Unfortunately permafrost is not really undoable.

permamelt should remove the snow, but it just hammers the biome to desert. 

Once you change the biome of a chunk, there's no way to change it back. The spell should be showing as "Not Undoable" in its lore to be clear.
