### ISSUE TITLE
Creating a Wand From Scratch

### ISSUE THREAD

**Issue by Romanova123** [elBukkit/MagicPlugin#539]
After creating a wand by holding a piece of redstone and doing /wand create, I added some spells to it. However, the spells don't work at all. I can drop the redstone at any time, despite binding it to myself. I can't switch or cast spells.

**Comment by NathanWolf** [comment]
That command is normally used to create simple magic items. Wands that cast spells require a lot of properties to be set to really function- they need mana, inventory modes, etc.

What might be easier is to `/mgive wand` then `/wand configure icon redstone` and start from there with a working wand. This would be linked to the mage class, though.

Alternately, you could try assigning a template to your newly created wand with `/wand configure template base_wand`. You'd still need to give it mana, e.g. `/wand configure mana_max 200` and `/wand configure mana_regeneration 20`.

After doing all of this you can `/wand save mywand` to save it as a new template. It'll show up in plugins/Magic/wands/mywand.yml, so you can take a look at how it's set up.

It's possibly easier to just write the template file by hand, though.

**Comment by Romanova123** [comment]
Thank you so much, sir!
