### ISSUE TITLE
Deleted Wand while in creative.

### ISSUE THREAD

**Issue by GottaSlay** [elBukkit/MagicPlugin#540]
Managed to restore it but the spellbook pages are lost. Any way to get them it back?

**Comment by NathanWolf** [comment]
How did you restore it?
Spells are kept in player data, not on the wand item. You should've just spawned in a new wand, most likely. If you have a new wand and the spells are gone, then they're probably gone. Not sure how that could've happened, though.

This plugin is 100% incompatible with creative mode.

**Comment by GottaSlay** [comment]
I managed to restore it and the spellbook pages, Sorry for the troubles!
