### ISSUE TITLE
Funky Build Permissions Error in 1.14.4 with Magic Mobs and Automata

### ISSUE THREAD

**Issue by mercurialmusic** [elBukkit/MagicPlugin#544]
I know you don't really support interactions with Residence, but leaving this here just in case. Not really sure which one is causing it so I'm leaving it in both places. I did not get the error in Spigot 1.14.3, but the spam crashed me in 1.14.4 using git-Spigot-1981d55-860b354 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT) with Magic build#2884 and Residence 4.8.6.6: 
Massive spam: https://gist.github.com/mercurialmusic/000606b66273ae32e9f3ec5fd6e424f7
Automata error: https://gist.github.com/mercurialmusic/24b047ca33842e32c695f3e14f3ed54c

I have both WorldGuard and Residence, mostly use Residence for player region protections, WG mostly for fine-tuning some mob behaviors. I do not have any global regions. Magic mobs spawn and work just fine but spam console like crazy. I had not tried automata before tonight but got the second error repeatedly (not spam, just with each attempt) when trying to spawn some hunters. The seed blocks spawned but then disappeared. 

Both errors persist even when I disable residence in the world they're in. Even if there's not a great fix, would appreciate advice. Thanks!

**Comment by NathanWolf** [comment]
I think I can see how this would happen with automata, there was a missing check for player-less permissions.

I believe I have fixed this in the current dev build, could you try it out please?

http://jenkins.elmakers.com/job/MagicPlugin/2885/

I decided to allow non-players (automata, command blocks, etc) have build/break permission when using these generic event-based checks. I'm not sure if that's the right way to go, so let me know what you think.

**Comment by mercurialmusic** [comment]
I very much appreciate this - will test it tonight. As for perms, I think it's perfectly fine - any block-breaking spells from mobs will be undone, and it wouldn't be the smartest thing to put automata in a world with player builds anyway. I'm excited.

**Comment by mercurialmusic** [comment]
Yes! It's beautiful. Thank you. :)
