### ISSUE TITLE
Sandbox npc's despawned

### ISSUE THREAD

**Issue by jamesol1** [elBukkit/MagicPlugin#549]
Hey
With the sandbox server the npc's seemed to have disspeared. This has happened before, no idea why. But yeah theres no way of reloading configs etc atm.

**Comment by jamesol1** [comment]
Is there any way you could fix this nathan? Perhaps reverting it back to 1.13.2?

**Comment by NathanWolf** [comment]
Sorry, just had the wrong version of citizens on there. It's fixed now.

I do want to figure out why the auto-reloading broke when I get a chance, too.
