### ISSUE TITLE
Magic and MVI

### ISSUE THREAD

**Issue by xkitox** [elBukkit/MagicPlugin#55]
Whenever a player has a  wand in their inventory and switches between worlds, they get an "Invalid JSON detected" error and their inventory gets erased!  Any help would be sooooo awesome, as this is my fave plugin, and I cant use it!

**Comment by NathanWolf** [comment]
Unfortunately I don't think I can fix that on my side - it has to do with how MVInv is saving inventory items :(

Are they maybe alternative per-world-inventory plugins? I don't think MVInv is maintained anymore, though I may be mistaken there. Sorry!

**Comment by xkitox** [comment]
Awesome, thanks for the quick reply.  I will try PWI, although it's a lil outdated, hopefully it works :)
