### ISSUE TITLE
Chests can be broken and the item can be picked up twice.

### ISSUE THREAD

**Issue by JeansouLiu** [elBukkit/MagicPlugin#550]
When I use the wand to hit a chest, the chest will disappear and the item in the chest will appear.And after a while, the chest will appear, and the item is still in the chest.

**Comment by NathanWolf** [comment]
What spell are you using? What server and plugin version? Any protection plugins that may be trying to preserve chest contents?

**Comment by BZEagle** [comment]
> What spell are you using? What server and plugin version? Any protection plugins that may be trying to preserve chest contents?

No protection plugins.Just in a village.
Server:PaperSpigot 1.13.2
I am using the latest version of magic.
spell:Magic Missile

**Comment by NathanWolf** [comment]
I have not been able to reproduce this, unfortunately. The chest disappears, no item is spawned for me.

**Comment by NathanWolf** [comment]
If you're still having this issue, please let me know if you are able to test without any other plugins installed.
