### ISSUE TITLE
How can I set up the command block?

### ISSUE THREAD

**Issue by june1105** [elBukkit/MagicPlugin#551]
I mean the command for the /wand enchant xp
Or, could you tell me the permissions for it?
I tried Magic.commands.wand.enchant.xp  / Magic.commands.wand.enchantxp and so on....
sorry for asking a simple question

**Comment by NathanWolf** [comment]
It is honestly a little weird to use a command block for this, or to use this randomized enchanting system too- but that's up to you!

The command is `/wandp @p enchant xp`, and you don't need any permissions if running it that way from a command block.

**Comment by NathanWolf** [comment]
Please re-open if you're still having questions about this.
