### ISSUE TITLE
Velocity transform

### ISSUE THREAD

**Issue by jamesol1** [elBukkit/MagicPlugin#557]
http://sandbox.elmakers.com/#default.fury
I found an interesting setting you used on your 'fury' spell of which randomises the way the projectiles move in the spell. The specific effect im talking about in that spell is the black smoke that shoots upwards. I believe this setting creates this:
        **velocity_transform:
            orient: false
            x: rand(-3,3) * cos(t)
            y: rand(3,10)
            z: rand(-3,3) * sin(t)**
I was wondering how could i go about using this for say a magic missile type spell? Aka getting this randomized moving projectile to shoot forward instead of up and function as a damage missile spell that follows the swirling effect.

I couldn't find anything on the wiki to help with using this effect.

**Comment by NathanWolf** [comment]
I can't remember if this velocity is relative to the player's facing direction. If it is, I think you could just swap y and z in there... if it's not then this may not be doable.

**Comment by NathanWolf** [comment]
Were you able to get this working?
