### ISSUE TITLE
Inactive icon for wands being unresponsive

### ISSUE THREAD

**Issue by 4kz** [elBukkit/MagicPlugin#559]
As the title describes wands' icons are being unresponsive:
after setting up a wand's 'icon_inactive' property using a spell will show such icon only a few milliseconds after (noticeable) and (this is what really concerns me) will take random amounts of time to become active (a time that has nothing to do with the cooldown of the spell used) even 7-8 seconds later than the cooldown of the spell.

 Is this known? Is there a fix for it? Thanks in advance.

P.S. I'm using the latest release version of magic.

**Comment by NathanWolf** [comment]
Are you aware of how the mana system works?

**Comment by 4kz** [comment]
Yes I am, my spells don't require mana. I can cast the spells despite the icon being inactive.

**Comment by NathanWolf** [comment]
I'm afraid I don't know what would cause this, then, sorry.

Other reasons for spells to go inactive include permissions, regions (build and pvp), etc. I think if there is no cooldown or mana on a spell it should not go inactive when cast.

**Comment by 4kz** [comment]
Maybe I didn't explain myself clearly:
the problem is that it takes too much time for the wand's icon to change making it unreliable and not usable for pvp. Thanks for the reply.

**Comment by NathanWolf** [comment]
No, you explained correctly. If it's not being caused by cooldown, mana or any of the other things I listed then I don't know what would cause that. I assume you don't see this happening on the sandbox or survival test servers?

**Comment by 4kz** [comment]
I can try looking in the sandbox server but I really doubt it's caused by any other thing since the spell is actually castable while the icon is showing the wand as disabled, it's just the icon not changing

**Comment by 4kz** [comment]
I also tried using icon_inactive_delay to low values but it doesn't seem to work

**Comment by NathanWolf** [comment]
To be clear, you are talking about *spell* icons changing, right?

The wand icon does not actually change based on the spells. Wands can have active/inactive icons, too, but those change depending on if the spell inventory is open or not.

**Comment by 4kz** [comment]
I was talking about wand icons, I thought they would change based whether
or not they can cast something, I'm incredibly sorry if I was mistaken ahah

Il giorno mer 14 ago 2019 alle ore 18:00 Nathan Wolf <
notifications@github.com> ha scritto:

**Comment by NathanWolf** [comment]
oooooh whoops ok! No, sorry. Glad I asked :)

Wand inactive icons are used for lightsabers or other wands where you can "open them up" and they change visual appearance. We had Lucious Malfoy's cane wand using that mechanic, too.
