### ISSUE TITLE
MCMMO support

### ISSUE THREAD

**Issue by DevL0rd** [elBukkit/MagicPlugin#560]
Using a spell in the magic plugin doesn't count as kill for mcmmo, no experience is gained.

Not sure if this is the right place to submit this issue or if its a mcmmo thing

**Comment by NathanWolf** [comment]
Most spells use splash potion damage. If McMMO doesn't count that, there's not much I can do about it.

If you need to, change all spells to use physical damage. This will affect balance as now armor blocks magic damage. In spells.yml:

```
default:
  parameters:
    magic_damage: false
```

**Comment by NathanWolf** [comment]
Did you get this sorted out?

**Comment by DevL0rd** [comment]
i did that change but it never fixed it. sorry about the late response

**Comment by NathanWolf** [comment]
It's been over a year, I'm going to close this. Sorry I was never able to do anything about this, but I feel like it's something wrong on the MCMMO side.
