### ISSUE TITLE
Spell icons not appearing

### ISSUE THREAD

**Issue by Zanforian** [elBukkit/MagicPlugin#562]
I am running a 1.14 server and have tried installing the resource pack both as the default server pack, and by downloading it to my client. While both correctly display textures for wands, brooms, ect, spell icons still just appear as diamond axes.

**Comment by NathanWolf** [comment]
Have you tried letting the plugin handle it? It's possible you're downloading the wrong version. if you just install the plugin and leave your server.properties alone (no RP in there) it will be automatic.

Sorry for the late response.

**Comment by NathanWolf** [comment]
Did you get the resource pack issues worked out?

**Comment by Zanforian** [comment]
Hey, sorry I just gave up on using the plugin for now. None of the spells were impactful enough to be worth acquiring and the plugin just seemed pulled in too many directions so I just stopped trying to make it work.

**Comment by NathanWolf** [comment]
Hm, ok, well thanks for the feedback!

**Comment by TofPlays** [comment]
> Hey, sorry I just gave up on using the plugin for now. None of the spells were impactful enough to be worth acquiring and the plugin just seemed pulled in too many directions so I just stopped trying to make it work.

Basically what you're saying is you couldn't learn the plugin.
The spells given are more than enough to understand how stuff works if you look at the examples and figure it out. Besides, there's a discord server with amazing community support.

The plugin is a canvas and its up to you how awesome it will be (even tho it already is given the amount of cool spells it already has)

**Comment by Zanforian** [comment]
> Basically what you're saying is you couldn't learn the plugin.
> The spells given are more than enough to understand how stuff works if you look at the examples and figure it out. Besides, there's a discord server with amazing community support.
> 
> The plugin is a canvas and its up to you how awesome it will be (even tho it already is given the amount of cool spells it already has)

That's fine and all but I'm not interested in creating my own spells or learning a system, the time investment just isn't worth it to me. This is why I decided to stop using it. If there was another magic type plugin for 1.14 I would have tried that.
