### ISSUE TITLE
Server shutdown when load resourcepack

### ISSUE THREAD

**Issue by Laxider** [elBukkit/MagicPlugin#564]
my server shutdown when anywhere player load RP for login in my server.
https://imgur.com/UPCDNBO

**Comment by Laxider** [comment]
PD: version 1.14.4

**Comment by NathanWolf** [comment]
Resource packs actually have nothing to do with the server, though. The server just gives a URL to the players' client, the client then loads the RP directly from it host (Amazon S3 in the case of Magic's official RPs)

So I honestly can't see how the two would be related at all.

**Comment by Laxider** [comment]
no, sorry its my world, one chunk have problems, sorry, close issue.
