### ISSUE TITLE
Need to update builtin schematics to a new format

### ISSUE THREAD

**Issue by YanisBft** [elBukkit/MagicPlugin#567]
Iron bars don't have the right blockstates when spawning cage structure through Cage spell.

![image](https://user-images.githubusercontent.com/16228338/64287419-f58cd100-cf5f-11e9-96a4-9a3b2507eb5e.png)

**Comment by NathanWolf** [comment]
That probably will not get fixed, TBH.

**Comment by NathanWolf** [comment]
At some point I'm hoping to implement support for Sponge schematics.

**Comment by NathanWolf** [comment]
Support for Sponge schematics was added, and builtin schematics updated.
