### ISSUE TITLE
Can't Open Spell Progression in 1.14.4

### ISSUE THREAD

**Issue by TristanPFox** [elBukkit/MagicPlugin#568]
Can't Open the Spell Progression menu by casting or by right-clicking on the enchantment table in 1.14.4

**Comment by NathanWolf** [comment]
Do you have any custom configs? Anything else that would be getting in the way? Running latest Magic?

Nothing really changed here and it seems to be working for me still.

**Comment by NathanWolf** [comment]
Was this a plugin compatibility issue? Still having problems?
