### ISSUE TITLE
How to create naturally spawning mobs

### ISSUE THREAD

**Issue by leveljaap** [elBukkit/MagicPlugin#569]
Hello,

The question is basically in the title already. I believe I read somewhere that one can let magic mobs naturally appear but I haven't been able to figure out how to do this. Could you explain it to me?

Thanks,
leveljaap

**Comment by NathanWolf** [comment]
You need the MagicWorlds plugin:

https://github.com/elBukkit/MagicWorlds/wiki#randomly-spawning-magic-mobs

**Comment by leveljaap** [comment]
Alright thanks!
