### ISSUE TITLE
Spell blocks glitching inventory...

### ISSUE THREAD

**Issue by xkitox** [elBukkit/MagicPlugin#57]
Hello.  When I press Q, it switches to what  I call my "spelll blocks", which is good.  The problem comes because sometimes when I log out or switch worlds, then go back to my world with my wand, those spell blocks become ACTUAL ITEMS that I can select and it appears in my hand.  When I press Q again, it goes back into the mode where they are just spells (spell select mode), but when I press Q again to go back to my inventory, my inventory is wiped clear, with nothing in it but my wand.  I really hope I explaind this okay lol.

**Comment by NathanWolf** [comment]
Are you using a per-world-inventory plugin?

**Comment by xkitox** [comment]
Yes, I am using the plugin PWI.  Does Magic have known issues with that plugin?  I started using it because MVI wouldn't work - -

**Comment by NathanWolf** [comment]
I do not know specifically but in general I've never seen a per-world inventory plugin that really works with wands.

I'll see about testing PWI out myself, maybe there is something I can do. It sounds like it's handling wand data ok but not the spell inventory.

In the meantime if you want you can put your wands into chest mode - try this command:

/wand configure mode chest

While holding a wand, and see if there are still issues?

**Comment by xkitox** [comment]
Alright I will try this for now.  Thank you for your help :)
