### ISSUE TITLE
Music spell fails with IllegalArgumentException

### ISSUE THREAD

**Issue by grisstyl** [elBukkit/MagicPlugin#570]
The music spell is failing with an IllegalArgumentException, stating that it "Cannot get the ID of Modern Material."

**Steps to reproduce**

1. Cast `music` spell.

[Console output](http://prntscr.com/p4ea76)

**Comment by NathanWolf** [comment]
This should be fixed in the next dev build, thanks!

**Comment by NathanWolf** [comment]
Released in 7.7.5
