### ISSUE TITLE
Support custom items as crafting input

### ISSUE THREAD

**Issue by grisstyl** [elBukkit/MagicPlugin#571]
Putting this down as a feature request just in case. It would be really cool and unlock a ton of potential if custom items could be used as input for custom crafting recipes.

**Comment by grisstyl** [comment]
I'll try again and get back to you about this.

**Comment by grisstyl** [comment]
So the problem that I'm encountering is, for example, I have an item saved to the config named `ashwindereggs` which are phantom membranes with a custom display name and lore. 

When I create a recipe that requires say `ashwindereggs` and a glass bottle to output the wand `lovepotion`, the output is only available when only a glass bottle is placed into a crafting table.

**Comment by NathanWolf** [comment]
Would you mind sharing your crafting configs and that item? I can try it out.

Also if you get a chance you could try crafting a lightsaber via the stars configs... I haven't checked in a while but if that's broken too then there's definitely an issue in the code.

**Comment by grisstyl** [comment]
Can confirm that Lightsabers are not craftable as intended.

**Comment by grisstyl** [comment]
Blasters are craftable. Some sort of issue with the recipe registering custom items as input.

**Comment by NathanWolf** [comment]
Thank you for testing! I'll see if I can figure this out.

**Comment by grisstyl** [comment]
Of course! Good luck!

**Comment by NathanWolf** [comment]
I think I've fixed custom crafting in the latest dev build. If you get a chance to try it out, please let me know :)

**Comment by grisstyl** [comment]
Will do!

**Comment by grisstyl** [comment]
Looks like everything is working as intended. Awesome! Thanks Nathan.

**Comment by NathanWolf** [comment]
Released in 7.7.5
