### ISSUE TITLE
Creating mobs riding other mobs

### ISSUE THREAD

**Issue by leveljaap** [elBukkit/MagicPlugin#575]
Hello,
My question is fairly simple. I'm wondering if it's possible to create magic mobs riding something, for example the baby zombie on a chicken or the skeleton on a spider. If this is possible, how do I do this? If it's not, could this be added?

**Comment by NathanWolf** [comment]
I've added some options to SpawnEntity that will allow this. You'll need the latest dev build. See the piggyback example spell:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/examples/survival/spells/piggyback.yml

**Comment by leveljaap** [comment]
Ahh thanks!! Great!
