### ISSUE TITLE
Alohomora doesn't close doors

### ISSUE THREAD

**Issue by christophe6** [elBukkit/MagicPlugin#576]
Hi

After updating to 1.13 and updating to the latest version of magic, I found out Alohomora doesn't close the doors it opens. This is my configuration for alohomora:
`alohomora:
  parameters:
    bypass_build: true
    destructible: doors
  worth: 10`

Is there something I can do about it?

Thanks!

**Comment by NathanWolf** [comment]
I don't think there's anything you can do about this... the undo system will need to be updated to store extended block state, since doors don't use their data bytes anymore.

I will leave this open in hope of fixing it at some point.

**Comment by christophe6** [comment]
Thanks! But this currently breaks the gameplay on my server. I'm using this code right now to easily close and open doors, if you'd like to have it.
`	public static void setDoorOpen(Block block, boolean open) {
		BlockData data = block.getBlockData();
		if(block.getBlockData() instanceof Openable) {
			if(!((Openable) data).isOpen() && open) {
				((Openable) data).setOpen(true);

				block.setBlockData(data);
			} else if(((Openable) data).isOpen() && !open) {
				((Openable) data).setOpen(false);

				block.setBlockData(data);
			}
		}
	}`

**Comment by NathanWolf** [comment]
I think I've got this fixed for you. Unfortunately it didn't quite make it into 7.7.5 but you can grab the dev build here:

http://jenkins.elmakers.com/job/MagicPlugin/2896/com.elmakers.mine.bukkit.plugins$Magic/

**Comment by christophe6** [comment]
It's fixed indeed! Thank you very much for helping me this quickly!
