### ISSUE TITLE
Team/Faction Support For Mobs and Players

### ISSUE THREAD

**Issue by leveljaap** [elBukkit/MagicPlugin#577]
Hello,
I was wondering if I could somehow put Magic Mobs in a vanilla team (created with /team). I'm creating Goblins but if they hit eachother with a spell or arrow they get angry at eachother, which I want to avoid. By putting them in vanilla teams this is possible. However, I can't detect them properly with command blocks, not even with @e[name=Goblin], meaning I can't use commands to put them in a team. Is there some way to do this through the config?

**Comment by NathanWolf** [comment]
There is no way to do this, though that is a really interesting idea. I'll try to add it if I find the time and it's not too complex.

**Comment by NathanWolf** [comment]
After looking into the API and the way scoreboards work, I don't think putting mobs on teams will actually do anything.

If you are able to get that working somehow with vanilla commands please let me know.

Otherwise I think what I need to do is implement custom team support.

**Comment by NathanWolf** [comment]
Custom team support now exists, see the stars rebel/imperial mobs for an example.
