### ISSUE TITLE
Some magic turns into 99, I can't use him, what should I do?

### ISSUE THREAD

**Issue by Longcg** [elBukkit/MagicPlugin#578]
![%@_AH~LN634KYQ1S@L(V`TK](https://user-images.githubusercontent.com/46647646/65140933-3269c500-da42-11e9-9732-e0582a788e11.png)
![@U@RI8}$~Q4 CW ER18F053](https://user-images.githubusercontent.com/46647646/65140935-34cc1f00-da42-11e9-9a41-f6703eb8978b.png)
I make sure their cooldown is as short as a few seconds

**Comment by NathanWolf** [comment]
This will happen if you don't have permission to cast the spell. Looks like in your case it's probably PvP.

**Comment by Longcg** [comment]
> This will happen if you don't have permission to cast the spell. Looks like in your case it's probably PvP.

But I have not canceled any permissions, what should I do?

**Comment by NathanWolf** [comment]
Do you not have a PvP manager, such as WorldGuard, PvPManager, Factions, etc?

What about build protection?

**Comment by Longcg** [comment]
> 您没有PvP管理器，例如WorldGuard，PvPManager，Factions等吗？
> 
> 那么建筑保护呢？

He solved it himself, but thank you very much.
