### ISSUE TITLE
Materials.yml does not accept alternate block types

### ISSUE THREAD

**Issue by dumptruckman** [elBukkit/MagicPlugin#58]
Using smooth_brick works but only on plain stone brick. Stone brick variants (cracked, mossy, etc), are not covered by this. smooth_brick:2 and smooth_brick|2 ought to make it work for cracked brick but it doesn't work for any of them when using it that way.

**Comment by NathanWolf** [comment]
Hm- yeah this might be a bit of a pain to fix, especially to keep it efficient.

I think we'd have to consider the current format (sans :data modifier) as a wildcard for backwards compatibility.

I know you don't really need this anymore, but I'll consider implementing it maybe anyway.

**Comment by NathanWolf** [comment]
Closing this, I don't really think it could be done efficiently.
