### ISSUE TITLE
Potion Effects Not Always Working

### ISSUE THREAD

**Issue by grisstyl** [elBukkit/MagicPlugin#580]
The `target_source` property for the `AreaOfEffectAction` does not work. The caster isn't targeted at all.

**Comment by NathanWolf** [comment]
`target_self` is what you're looking for, I think.

**Comment by grisstyl** [comment]
Actually, it looks like AreaOfEffects might not be working at all.

**Comment by NathanWolf** [comment]
I am dubious...

**Comment by grisstyl** [comment]
I just tested with `protegototalus` in my configs which was working last time I checked. [Here's](https://gist.github.com/grisstyl/234a0296641a67f12c6ac3ef6ea895c0) the spell I'm testing with right now.

**Comment by grisstyl** [comment]
The spell works fine when not attached to an AreaOfEffect by the way which is where my conclusion came from. I thought at first it was a problem with `target_source` (a property of AreaOfEffect) but I'm thinking it's something else.

**Comment by NathanWolf** [comment]
There would be so many spells in the default configs broken if AOE wasn't working, though.

**Comment by grisstyl** [comment]
Okay, I narrowed it down. The AOE isn't working specifically **when attached to a CustomProjectile**

**Comment by grisstyl** [comment]
Or maybe it's the potion effect applied by the AOE that isn't working. Super weird because the message will display for me but the effects aren't applied. This could explain why `protegototalus` isn't working.

**Comment by grisstyl** [comment]
Wondering if you had a chance to look into this any further.

**Comment by NathanWolf** [comment]
I played with this a bit and honestly it seems like it may be a vanilla Spigot or Minecraft issue :(

Potion effects sometimes (randomly, it seems, I can find no pattern) just don't work. I can see in the code the Bukkit method to apply the potion effect is getting called, but it just doesn't work.

I tested with the vanilla Poison spell as well, since that one is easy to test on mobs- sometimes it works, sometimes it doesn't. I'll see if I can dig any deeper when I find the time.

**Comment by grisstyl** [comment]
That's really unfortunate. Seems like there's been a lot of structural changes in MC code lately. Keep me updated!

**Comment by NathanWolf** [comment]
Yeah :( I can't imagine what else is going on... I traced the code to the Bukkit call, saw it was getting called, but still no effects in-game.

I have no idea how long it's been like this, I haven't had a chance to look through Spigot commits. It's possibly just some new bug that will get fixed quickly?

**Comment by NathanWolf** [comment]
Did you ever figure this out... ? It's been like a year, whoops XD
