### ISSUE TITLE
Bug? with SelectorAction that gives a potion on select

### ISSUE THREAD

**Issue by grisstyl** [elBukkit/MagicPlugin#583]
Not sure if I'm doing something wrong [here](https://gist.github.com/grisstyl/0025a867b995f4d179c0b3a7b3d3277d) but when I select an option from the `potionshop` it puts a potion of swiftness in my inventory.

**Comment by grisstyl** [comment]
[Here's](https://github.com/grisstyl/BetterPotter/tree/custom-crafting) the link to the whole branch if you need more than the gist provides.

**Comment by NathanWolf** [comment]
This is because there is a potionshop in the default configs that you are inadvertently inheriting. Oops, sorry!

Just add this to the top of the spell and it should be fine:

```
potionshop:
  inherit: false
```

**Comment by grisstyl** [comment]
Got it! Thanks Nathan.
