### ISSUE TITLE
Me as an Owner don't have the SP cooldown on spells?

### ISSUE THREAD

**Issue by GottaSlay** [elBukkit/MagicPlugin#585]
I'm gaining SP every time I cast a spell while everyone else is gaining it at the correct pace. How do I fix this? Also as an owner, I have the abilities to cast destructive spells on lands that are claimed by players with ProtectionStones. I'd like to fix this as well.

**Comment by NathanWolf** [comment]
Don't use this plugin while opped. If you absolutely need to for some reason, give yourself "-Magic.bypass"

No idea why your SP cooldown isn't working though, sorry.

**Comment by GottaSlay** [comment]
Players are also reporting the spell Recall not doing anything? I just tested it myself with the same perms they have and it did in fact do nothing. Placed down a bed, slept in it and used recall on it, didn't work?

**Comment by NathanWolf** [comment]
Not sure about that one either, sorry. 

It is working on the dev servers. It uses vanilla spawn locations, do you maybe have some other plugin managing beds that is getting in the way?

**Comment by GottaSlay** [comment]
No.. i do not. I tried it without having my base protected by ProtectionStone and it still didn't work. Just says "Recall failed"

**Comment by NathanWolf** [comment]
It can be picky about there being space around your bed - sorry, I thought you meant the bed icon wasn't showing up. If the telepeort is failing that's usually a space issue of some kind.

**Comment by GottaSlay** [comment]
Hmm. I tested with my bed in a wide space and unfortunately no luck. Its okay though. Hopefully the leveled up abilities in it work.

**Comment by NathanWolf** [comment]
Well unfortunately you can't level it up if you can't successfully cast it.

You could add some warps to it if your server is set up for that, or else allow recall on death at level one or some other feature.

**Comment by GottaSlay** [comment]
Recall on death is a good idea. Could you advise me on how to do that
please?

**Comment by NathanWolf** [comment]
In plugins/Magic/spells.yml you would add

```
recall:
  parameters:
     allow_death: true
```

Normally that is unlocked at level 2 so you may also want to change the level up messaging to not be confusing:

This would go in messages.yml:

```
spells:
  recall|2:
     upgrade_description: ""
```
