### ISSUE TITLE
How to lower the cooldown on SpellPoints?

### ISSUE THREAD

**Issue by GottaSlay** [elBukkit/MagicPlugin#588]
So I managed to fix the spellpoints cooldown for myself (opped). But my players would like the cooldown to be lowered and i cant find anything about it in the configs?

**Comment by GottaSlay** [comment]
Solved by editing spells.defaults.yml

**Comment by GottaSlay** [comment]
If you could help with this? A player's reporting that he's only receiving 1 SP per spell after cooldown.

**Comment by grisstyl** [comment]
**DO NOT edit the default files. Your changes will not be reflected in-game**

To edit the SP cooldown globally, in the `spells.yml` file:
```
default:
  earns_cooldown: x
```
Replace "x" with how long you want the cooldown to be, in milliseconds. This can be done on a per-spell basis as well by replacing "default" with the desired spell's key.
