### ISSUE TITLE
Broom doesn't fly anymore

### ISSUE THREAD

**Issue by Elsopeen** [elBukkit/MagicPlugin#59]
Hello,
I want to signal that the brooms (and the spells "broom" and "superbroom") doesn't work anymore. Before the 1.9 update, they worked fine, but now, none works at all. The spells create the ridable entities, but they don't fly and so Sorcerers cannot travel with upgraded or not brooms. Unfortunately, there isn't any error log in the console, so I can't provide you one.
Hoping you'll find a way to fix this issue,
Best regards,
Elsopeen

**Comment by NathanWolf** [comment]
I haven't seen this issue myself- is this just using the default survival configs? What specific Spigot version (like the output from /version).

When you say they don't fly, do they hover but not move forward? Does the player immediately dismount?

**Comment by Elsopeen** [comment]
We use for the most the default configs, but it worked fine before, so I don't think that comes from the Magic's configs. We currently are running on "CraftBukkit version git-Spigot-3104eb1-bf43ca6 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)".
For the part "don't fly", they literally don't fly, the player is forced to mount the broom entity, but they don't move at all from the ground.

**Comment by NathanWolf** [comment]
I have had any issues with them - did this just start happening when you updated to 1.9? Anything going on with regions, maybe blocking mob spawning?

**Comment by Elsopeen** [comment]
Yeah, this bug appeared when we updated to 1.9, and there isn't any mob spawning blockage.

**Comment by NathanWolf** [comment]
I am seeing this problem now too on the latest Spigot. I do not yet know what the issue is.

**Comment by azgaviperr** [comment]
I do have the same troubles on my server. 
My player stand on place but he can't move. 
I do not get any error in the console.

**Comment by NathanWolf** [comment]
Something recently changed in Spigot and it definitely seems to have broken brooms. I will have to narrow in on what changed and then try to figure out if it's something I can work around. (Hoping so!)

**Comment by NathanWolf** [comment]
Gack, apparently this was not a change in Spigot but something I broken when switching to use Spigot's ArmorStand API. Well, arguably it's the API that's broken... but anyway I undid that change and all is well.

Brooms should work again in dev build#1514 and up- I will release an update to spigotmc.org sometime this week.
