### ISSUE TITLE
Item Consumption

### ISSUE THREAD

**Issue by mythguy1226** [elBukkit/MagicPlugin#591]
Hi, I am currently trying to use magic to create guns on my server and cant seem to figure out how to make the guns consume items for ammo. Is there a way to even do this?

**Comment by NathanWolf** [comment]
Sure, just swap out mana for an item in the costs.

E.g. the pistol

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/examples/war/spells/pistol.yml

Replace

```
    costs:
      mana: 1
```

with 

```
    costs:
      coal: 1
```

or whatever item.

Then on the gun (wand) itself you probably want to remove all mana, regen, etc.

**Comment by mythguy1226** [comment]
awesome thanks!
