### ISSUE TITLE
Spell Shop

### ISSUE THREAD

**Issue by Appollio** [elBukkit/MagicPlugin#592]
We are running Magic 7.7.4-fd3f986, and Bukkit 1.14.4, and when trying to upgrade/ buy spells for the wand, nothing opens at the enchanting table, with either click.

**Comment by NathanWolf** [comment]
Whenever you're having a problem with such a basic feature that clearly can't be broken for everyone, it's helpful to give some more information.

- Any errors in your server console when using the enchantment table?
- Any errors on startup?
- Was this working previously? If so, what changed?
- Have you customized Magic's configs at all?
- Any plugins (GUI shops, etc) that could be getting in the wy?
- Are you able to test without other plugins active?

**Comment by Appollio** [comment]
There are no errors at all, it just opens the basic enchantment table gui, nothing on startup, and it hasnt been working since we added the plugin.
No customizations at all, just making wands ingame. 
None that i could see why. we currently have DungeonMaze, Shopkeeper, mythicmobs, and a few others that are just basic functionality.
Ill see about removing the others and trying again.

**Comment by NathanWolf** [comment]
When you say "making wands ingame" do you mean crafting them? Are the wands actually working otherwise?

**Comment by Appollio** [comment]
We are able to craft the basic wand ingame. also I was seeing if i could make custom wands, like "Wand of Flame" with fire spells and etc, (Dont know if you can lock a wand from including all the players spells.)
The wands work, we can add spells via the commands, but are unable to open the Spell Shop or enchanting table.

**Comment by NathanWolf** [comment]
Can you try `/cast progressmenu`?

I guess worse-case you could use NPCs or command blocks for progress, but it's a little weird for it to not work via the enchantment table.

**Comment by Appollio** [comment]
"Internal Error occurs while attempting to perform this acction"

**Comment by NathanWolf** [comment]
There should definitely be errors in your log if you're getting a message like that.

**Comment by Appollio** [comment]
Ok, ill see about troubleshooting any errors.
Would this be from something going wrong when adding it to the server?

**Comment by Appollio** [comment]
I was able to work out the errors, appriciate it. it functions perfectly now.

**Comment by NathanWolf** [comment]
I would be curious to know what was wrong with this, in case others run into the same issue.

**Comment by Appollio** [comment]
Hey there, I believe it was either Elite Weapons or uber recipes that was
blocking the ui for the enchanting table.
