### ISSUE TITLE
No permission to cast explosive spells

### ISSUE THREAD

**Issue by GottaSlay** [elBukkit/MagicPlugin#595]
For a while now our players have been reporting that they're not able to cast some of the spells, (mainly explosive ones). [https://i.imgur.com/fyT6s1H.png](url) We are not quite sure why's this since nothing in worldguard or essentials seem to be preventing it.

**Comment by NathanWolf** [comment]
If building or pvp are prevented in an area (like by WorldGuard) that would do it.

While holding a wand with the spell active, and not opped, try `/mage check`
