### ISSUE TITLE
World Guard for terrain affecting spells

### ISSUE THREAD

**Issue by LowFiPies** [elBukkit/MagicPlugin#6]
Hello.

I'm facing a problem where normal players are unable to cast terrain affecting spells. Like Grenade spell witch tosses a primed tnt that destroys terrain; and rolls it back afterwards.

Players who try to cast such spells get the error message "You don't have permission to cast that here".

I've tried to look for the permission for that but I couldn't find it.
Could you please help me?

**Comment by NathanWolf** [comment]
Sorry for the late reply!

Spells that make block changes require block-breaking or building permission by default. So if they are in a region where they can't break blocks by hand, they can't break blocks with spells either.

You can turn off the WG integration completely if you don't want this, or add "bypass_break: true" to the spells you want to allow. Or you can get the WGCustomFlags plugin and set spells you want to allow via the allowed-spells flag.
