### ISSUE TITLE
Automata haven't the permissions to be casted

### ISSUE THREAD

**Issue by Elsopeen** [elBukkit/MagicPlugin#60]
Hello again,
I created a world with MagicWorlds to have a "corrupted-by-magic" world on which sorcerers would be able to fight against the automatas, but the command blocks say in output that they don't have the permission to cast their spell in this world, whatever the area. Here is the visual proof of that:
![2016-03-12_11 09 58](https://cloud.githubusercontent.com/assets/16364961/13722358/109c7a02-e843-11e5-96a8-66b11135ceda.png)
I don't think it can be from my permissions because I defined that in this world, these spells (automata ones) can be casted. Maybe it's a commandBlock permission that I haven't noticed...
Hoping you'll be able to help me with that,
Best regards,
Elsopeen

**Comment by NathanWolf** [comment]
Do you use WorldGuard, Towny, Factions or any of the other supported protection plugins? Automata don't have build permission in any protected region.

**Comment by Elsopeen** [comment]
Yes, we use WorldGuard, but the flag "build" is set to allow, so I don't know if there is any other modification to do to make the Automatas work

**Comment by NathanWolf** [comment]
If they are in a region then the "passthrough" flag must be set for them to work.

Alternately you can customize the spells to bypass build permissions but obviously this can be a bit dangerous.

Another option is to use WGCustomFlags and flag the region with allowed-spells *

**Comment by Elsopeen** [comment]
I activated the bypass build, and it works fine now, the automatas can spawn. If I have any issue again with the automatas, I'll say it to you.
