### ISSUE TITLE
Add support for placeholders in damage parameters (mythicmobs specifically)

### ISSUE THREAD

**Issue by t0xic1** [elBukkit/MagicPlugin#600]
Request to add support to include MythicMobs placeholders inside damage parameters

Link to the MythicMobs page : https://www.mythicmobs.net/manual/doku.php/skills/stringvariables

![testo](https://user-images.githubusercontent.com/18641452/67623650-b83a1680-f81f-11e9-8815-8782ca932023.png)

Example how it would work below ^^

This would greatly help with scaling for mobs and players aswell.

**Comment by NathanWolf** [comment]
I think you should be able to do this now by using PAPI to bridge the two plugins.
