### ISSUE TITLE
Spell Permissions

### ISSUE THREAD

**Issue by mythguy1226** [elBukkit/MagicPlugin#604]
Hi, so I'm trying to make a gun system on my server with magic and I want the default group to have access to all gun spells so when they buy the gun/wand that they can just start casting.. but the issue is that they also need access to /cast for other functions on the server. I dont want them to be able to use /cast with those spells but /cast for the others. Is there a way that I can keep certain spells to being used in only wands?

**Comment by NathanWolf** [comment]
No, I don't think so. Players are not meant to have /cast. Is there a better way you could give them access to whatever they need, maybe a special item with a GUI or something?

**Comment by mythguy1226** [comment]
Yes, I found a better way to go about how I permit users thank you.

**Comment by NathanWolf** [comment]
Great, glad to hear it!
