### ISSUE TITLE
Capture spell doesn’t work on 1.14 mobs

### ISSUE THREAD

**Issue by KingofAnomaly** [elBukkit/MagicPlugin#606]
When I cast the spell(in survival mode) on any of the mobs from 1.14 such as pandas and foxes nothing happens.

**Comment by NathanWolf** [comment]
This should be fixed in the latest dev build.

Unfortunately now since each mob has its own spawn egg material, we have to keep updated mappings of every mob to its spawn egg. This map is in config.yml, so in the future you are always able to update it yourself if needed.
