### ISSUE TITLE
Secure/lockpick spell is glitched & permanent

### ISSUE THREAD

**Issue by NightScythe1987** [elBukkit/MagicPlugin#607]
Using the secure spell works fine at first on my server (1.14.4) and you can use the key fine too. But when using lockpick to open the chest it completely breaks it. It becomes unable to open with or without the key, and when destroyed in creative drops nothing, and leaves a very glitched invisible block in its place which cannot be walked through and acts like a barrier block that pushes you back. This is on the september release of magic.

**Comment by NathanWolf** [comment]
Thank you for the report! Sorry about that.

This will be fixed in the next dev build and released as part of 7.8.1

**Comment by killme** [comment]
446d56d43aff39b33ed9133946c6a20f3467f454
