### ISSUE TITLE
Meshing RP's with my own

### ISSUE THREAD

**Issue by zaccieslak** [elBukkit/MagicPlugin#608]
So I have a PaperSpigot server, and have nothing in the server.properties, which means that the URL found in the config.default should be used. I changed the config.default URL to a URL that was the meshed RP's, but when I reload the server or /magic reload, the old config.default somehow re-writes itself and overwrites the config.default file I just put in. 

I've also tried deleting the URL in the config.default and putting the hash for the meshed RP's into my server properties, but it still overwrites the file and doesn't pull from my server.properites hash. 

I'm wondering if there is a way to make it stop reverting back to the default URL so that I can use the meshed RP zip. 

Thank you!

**Comment by NathanWolf** [comment]
Your answer is at the top of the file you've been editing... tl;dr edit the files in plugins/Magic, not the defaults.

```

#
# !! IMPORTANT !!
#
# If you wish to customize this plugin, edit the "config.yml" file instead.
#
# DO NOT JUST COPY THIS WHOLE FILE INTO YOUR config.yml !!!!
# If you do this, updating the plugin in the future may not work as expected.
#
# This file is merged from the files in the following folder:
#
# https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/main/resources/defaults/config
#
#
# This turns on the survival configs by default.
#
# Set
# example: ""
# in your config.yml to turn this off.
#
```

**Comment by zaccieslak** [comment]
Okay, so I uploaded the config.yml file into the main "plugins/Magic" folder, and it still isn't recognizing the RP. I think I understand that I need to upload a new .yml into the plugins/Magic/config folder, which I did, but nothing changed. 

I'm just looking to disable Magic from automatically using the RP associated with Magic

Thank you for all your help by the way.
![magic_config](https://user-images.githubusercontent.com/51010650/68534492-d3feeb80-02fa-11ea-99bc-25fb782d9026.PNG)

**Comment by NathanWolf** [comment]
that file looks really big- did you copy it?

Delete that file, edit the file that is already in `plugins/Magic/config.yml` on your server. If you need to, download it and then re-upload it after editing (if you can't log into your server and edit files directly).

The file will be blank except for some comments that explain how it works.

Add one line to that file, at the end on a new line with no spaces or # in front of it:

`resource_pack: ""`

Those are two double quotes with nothing in them.

All this information can be found on the wiki

https://github.com/elBukkit/MagicPlugin/wiki/ResourcePack

**Comment by NathanWolf** [comment]
Alternately, just put your merged RP in server.properties as normal, Magic will turn off its own RP functionality if you do that.
