### ISSUE TITLE
Disguising Magic Mobs

### ISSUE THREAD

**Issue by mythguy1226** [elBukkit/MagicPlugin#610]
Hello, I was trying to add custom disguises from libsdisguises to a mob. But I realized that I can't disguise a mob as a player. Is there a special way to do this? Or is it not possible?

**Comment by NathanWolf** [comment]
It is possible, so long as you're willing to use the player's current skin. There's no way to specify a texture/profile.

See the madscientist example:

https://github.com/elBukkit/MagicPlugin/blob/5f3942e89deb758ad0df1fd1bafe53cb2ff8fc30/Magic/src/main/resources/examples/survival/mobs/madscientist.yml

**Comment by mythguy1226** [comment]
okay that is useful.. but the problem is that I made custom disguise that is a player disguise.. and that disguise takes what the skin was at the time that you made it. For ex: I changed my skin to a composite superman skin and then made a disguise for it using certain values. I then changed my skin back and was able to disguise as composite superman. Is there a way for me to use that disguise?

**Comment by NathanWolf** [comment]
No, sorry.

**Comment by mythguy1226** [comment]
Okay, Thanks anyways.

**Comment by NathanWolf** [comment]
If you are curious for more info, there is a long-standing feature request open for this:

https://github.com/elBukkit/MagicPlugin/issues/392

Basically it's a little complicated, I'd have to add a command that lets you dump a player's full profile in some kind of copy+pasteable format to put back in the config, and then figure out how to pass that along to LibsDisguises. Probably doable, but with all the other backlog of bugs and features it's probably not likely to get implemented.
