### ISSUE TITLE
Wands lose their damage when being created.

### ISSUE THREAD

**Issue by zaccieslak** [elBukkit/MagicPlugin#613]
Hey there! I was wondering if there was a way to keep stats on an item. 
I have a system on my server where players can upgrade their weapons through obtaining different blades, and "forging" them together to create a new blade. This increases the damage of the weapons to surpass vanilla damage. Every time I try creating a wand out of the new weapon, it loses all of it's attributes and damage. Is there a way so that the NBT data of a sword can be transferred/meshed into a wand?

**Comment by NathanWolf** [comment]
Unfortunately I don't think so, with the current way wands work. They are constantly re-creating the underlying items from scratch and don't check or store existing NBT.

This is something I'll keep open in case it could be improved in future versions, but for now I don't think you can mix wands with other custom attributes. Sorry!

**Comment by zaccieslak** [comment]
Okay thanks man for the fast reply and awesome explanation! You're doing great things ^^

**Comment by zaccieslak** [comment]
So! Found out the fix for this:

In the wand.yml's, need to do:

item_attributes:
- generic_attack_damage: 9
- generic_attack_speed: 1.6

Then just configure the lore to include the attack damage/speed and whatever other wand-specific attributes like mana/mana regen/etc. 

So that means that I can make an NPC that'll trade a custom item with custom attributes and custom model data for a wand with the exact same custom model/attributes. Only problem is: https://github.com/elBukkit/MagicPlugin/issues/615 - There doesn't seem to be a way to pull Custom Model Data onto wands. I've been trying to figure out how you even got your icons to be numbered like that when in the resource pack, there's nothing that correlates to the icons haha.

**Comment by NathanWolf** [comment]
Oh I didn't realize you were looking to set item attributes (versus some completely custom data)- glad you found that!

For what it's worth, the feature I just added for you to use CustomModelData should (in theory) work with any arbitrary NBT tags as well.
