### ISSUE TITLE
PvP delay after spell

### ISSUE THREAD

**Issue by DeadEyeDonny101** [elBukkit/MagicPlugin#614]
Hey I've been having a problem with this plugin. When I cast a spell, straight after I cannot attack a player with either regular combat mechanics, swords, axes, and even spells. I am currently running the latest version of this plugin on my 1.13.2 paper based server.
Notes
- There is no problems when I tested this with mobs, spells and vanilla swords,axes.
- This is not teleportation spell specific, rather most spells, teleportation, throwing, pvp, others.

Thank you for your time :)

**Comment by NathanWolf** [comment]
Are you able to test this in isolation (no other plugins)? It almost sounds like something an anti-cheat/anti-kill-aura plugin would be doing.
