### ISSUE TITLE
ArmorStandProjectile Items

### ISSUE THREAD

**Issue by zaccieslak** [elBukkit/MagicPlugin#617]
The ArmorStandProjectile class' parameters don't seem to support custom items pulled from resource packs. (1.14.4) - "gold_sword:1" should be the master sword, and it's just showing up as a gold sword. I tried using "gold_sword:24" which is a custom axe I made, and was still a gold sword :3

This is for the "right_arm_item:" parameter.

**Comment by NathanWolf** [comment]
Probably it needs to be unbreakable .. I thought it did that by default but maybe it’s an option. I’ll check and get back to you!

**Comment by zaccieslak** [comment]
Okay thanks so much man!

**Comment by NathanWolf** [comment]
Please try adding `unbreakable_items: true` to the spell's parameters

**Comment by NathanWolf** [comment]
Were you able to give that a try?
