### ISSUE TITLE
how can I translate to Chinese

### ISSUE THREAD

**Issue by Philip6034** [elBukkit/MagicPlugin#627]
I want to translate to chinese

**Comment by NathanWolf** [comment]
There's a wiki page: https://github.com/elBukkit/MagicPlugin/wiki/Messages

Someone started a Chinese translation a while back but it is not complete:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/examples/localizations/messages.ZH.yml

You basically copy `plugins/Magic/defaults/messages.defaults.yml` to `plugins/Magic/messages.yml` and edit it.

**Comment by Longcg** [comment]
> I want to translate to chinese

I also have this plan, we can translate together.

**Comment by qsefthuopq** [comment]
See here:
https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/examples/localizations/messages_CN.yml
