### ISSUE TITLE
Recall spell does not work

### ISSUE THREAD

**Issue by kriskenesei** [elBukkit/MagicPlugin#628]
Dear Creators!

We just obtained our first Wands on our server, with some friends. Wonderful plugin so far, amazing work! :)

We tried casting the "Recall" spell, and it just displays "Recall failed" whenever we try to use it.
The config is essentially all defaults, apart from the potter package having been enabled.

Is there any chance you might know what the issue could be? It seems not to be a permission node issue, admins cannot use the spell either. Thanks a lot in advance! :)

Kris

**Comment by NathanWolf** [comment]
Have you slept in a bed? The Level 1 version of Recall only allows you to return to your bed, unless you set up some unlockable or unlocked warps.

**Comment by kriskenesei** [comment]
I have! This may be a plugin incompatibility issue then, one of them may be blocking the respawn location. We are running bPermissions, dynmap, EssentialsX (base, chat, protect, spawn), mcMMO and Vault (and Magic ofc).

**Comment by kriskenesei** [comment]
Update: we removed EssentialsX altogether and now beds are definitely working as intended (/kill respawns the player at the bed). We also determined that the spell works with the death location! So it's just the sleep location that still doesn't work. I don't think that any of the other plugins mess with the spawn, so I'm not sure what might be breaking it at this point.

**Comment by NathanWolf** [comment]
Oh, so does the menu work, but when you click the bed you get the "Recall failed" message?

If that's the case I may need to look into it, but it has always been pretty finicky about it, since it won't teleport you to where you are inside the bed. I'll do some testing when I get a chance and see what I can do.

**Comment by kriskenesei** [comment]
Yes, the menu works as intended - but clicking on the bed option displays the "Recall failed" message above the toolbar.

Thanks for your help by the way, it is much appreciated. We will try moving the beds around later on today to help a bit with the testing, maybe putting them somewhere more open will fix this issue. :)

**Comment by kriskenesei** [comment]
Update: we tested the issue with various bed positions, including open spaces with absolutely no obstructions, and it still does not work unfortunately. It can probably locate the respawn point (the bed option appears/disappears from the Recall menu depending on whether the bed is still in place or not). It just cannot teleport the players there...

**Comment by NathanWolf** [comment]
Thank you for testing so thoroughly!

I think I have a simple fix ready, if you want to grab this dev build you can try it out:

http://jenkins.elmakers.com/job/MagicPlugin/2930/com.elmakers.mine.bukkit.plugins$Magic/

**Comment by kriskenesei** [comment]
It is working perfectly now, you fixed it! :)
Thanks a bunch, this was some amazing support. For an amazing plugin!
It's so cool that all this magic is accessible via the vanilla client.
