### ISSUE TITLE
Unable to control broom

### ISSUE THREAD

**Issue by Longcg** [elBukkit/MagicPlugin#632]
I may be doing something wrong, but I can't find the reason. Suddenly, the player couldn't control the broom flying and stayed in place after taking off. It was controllable before.
![20200125173815](https://user-images.githubusercontent.com/46647646/73119304-d805e580-3f9a-11ea-9b79-0e40445a35c5.png)
![{_P P4}R(3AV@Q`79@8D5CX](https://user-images.githubusercontent.com/46647646/73119307-dfc58a00-3f9a-11ea-8f7f-43fe1fce40f6.png)

**Comment by MrRayhonda** [comment]
I am and have been having this issue for so long now... It's horrible :( So many of my users bug me daily when I'll have it fixed but No luck on my end tinkering bc am big dumb. No error put out that I can see.

Particles and sounds work perfectly and I can rotate on the broom but I cannot control it or anything else.

**Comment by NathanWolf** [comment]
Have either of you updated Spigot and not Magic? What versions of both do you have?

Do you see a message like this in your logs?

`An error occurred while registering entity movement accessors, vehicle control will not work`

Vehicle movement controls are one of the hackier parts of NMS code that change on every update, so they will definitely break if you're not on the latest version of the plugin.

**Comment by MrRayhonda** [comment]
I use the latest paper for 1.15.2 there were no logs in my console and I also have the latest magic 7.8.2 hmmm

**Comment by Longcg** [comment]
I use the paper(80) for 1.15.2 there were no logs in my console and I also have the latest magic 7.8.2 .

**Comment by MrRayhonda** [comment]
note: flying is enabled on my server and it was originally disabled  when the broom did work back in 1.13.x and also when it stopped working in 1.14.x

**Comment by Longcg** [comment]
For PaperSpigot users.
If "armor-stands-tick" is set to false in the paper.yml file, then broom will not move.

**Comment by MrRayhonda** [comment]
THAT WAS IT?! LOL It was an issue for so long and the solution was so simple! I love this! IT WORKS! :D
