### ISSUE TITLE
GriefDefender Compatibility 

### ISSUE THREAD

**Issue by CraftyBr** [elBukkit/MagicPlugin#634]
Hey, I was wondering if there was any way for Magic to support the plugin "GriefDefender" (https://www.spigotmc.org/resources/griefdefender.68900/). It's a plugin that is very similar to GriefPrevention (which does have Magic Support) but currently, all magic spells completely ignore the claim protection from GriefDefender.

**Comment by killme** [comment]
You could try using the generic protection config option <https://github.com/elBukkit/MagicPlugin/issues/464#issuecomment-454129363>. Does that plugin have a public API / maven repository with an API jar?

**Comment by CraftyBr** [comment]
Yes, it does have an API (located on the GitHub page [here](https://github.com/bloodmc/GriefDefenderAPI))

**Comment by ItsDoot** [comment]
For accessing it through maven, you'll have to use jitpack for now.

**Comment by NathanWolf** [comment]
Hi, sorry for leaving this hanging for so long- but do you still need this? Are you still using Magic+GriefDefender, if so did you try `generic_protection`?

**Comment by CraftyBr** [comment]
Hello, thanks for getting back to me. I was unable to sort out my issue and
I'm currently no longer working on the project anymore. Thanks again for
the reply

Regards,
CraftyBr

**Comment by NathanWolf** [comment]
Thanks for letting me know!
