### ISSUE TITLE
BlockLocker Compatibility

### ISSUE THREAD

**Issue by Longcg** [elBukkit/MagicPlugin#636]
BlockLocker is a plug-in similar to LockettePro. It is very popular in high version. Hope to be compatible!(https://www.spigotmc.org/resources/blocklocker.3268/)

**Comment by NathanWolf** [comment]
Did you change your mind on this?

**Comment by Longcg** [comment]
> 您改变主意了吗？
Sorry I changed my mind and now use LockettePro.
