### ISSUE TITLE
Wands breaking with custom model data

### ISSUE THREAD

**Issue by grisstyl** [elBukkit/MagicPlugin#639]
I didn't really know how to describe this issue so I recorded a little bit of what was going on.

[Video](https://www.youtube.com/watch?v=_Ui21VzLpj8&feature=youtu.be)

Perhaps related to #635

**Comment by grisstyl** [comment]
It appears that when I toggle the menu with the wand while it's doing this the bouncing will stop but the wand no longer functions.

**Comment by grisstyl** [comment]
![image](https://user-images.githubusercontent.com/6733216/73586196-4a7d3680-446f-11ea-9d88-3bf1c118fdd1.png)
Noticed these messages in console when I logged in.

**Comment by killme** [comment]
Could you post the full log? Or at least all messages logged for Magic.

Also, what Minecraft version?

**Comment by grisstyl** [comment]
1.15.2 Spigot with the latest Magic. Nothing relevant is logged.

**Comment by NathanWolf** [comment]
Well I can definitely reproduce it...

It's odd since it seems to work fine in config, it's something about the in-game commands that is making it go weird.

**Comment by alexis-evelyn** [comment]
I just noticed this with the magic hat and the wolf wand. The basic wand works perfectly though.

```
{ "predicate": { "custom_model_data": 108}, "model": "item/magic/wand_wolf" },
{ "predicate": { "custom_model_data": 110}, "model": "item/magic/wizard_hat" }
```

**Comment by grisstyl** [comment]
Seems to be resolved in the latest dev build.
