### ISSUE TITLE
how to play magic on minehut last version?

### ISSUE THREAD

**Issue by lostinikea** [elBukkit/MagicPlugin#640]
I downloaded the magic plugin for my server because it looked like a lot of fun! I've tried multiple commands to add wands and such but none of them work on my minehut server. Help!

**Comment by NathanWolf** [comment]
I have no idea, sorry. This will run on any flavor of Spigot, but the details of installing plugins on a particular host are not something I can help with.

**Comment by NathanWolf** [comment]
Were you able to figure this out? @ pranuv222 would also like to know.
