### ISSUE TITLE
Chop ignoring worldguard regions

### ISSUE THREAD

**Issue by NeoFalcon1605** [elBukkit/MagicPlugin#644]
Using magic version 7.8.2, worldguard version 7.0.1-beta, mc version 1.14.4

A normal player was able to use chop to break part of a server build protected by worldguard.  I tested this myself while deopped with no worldguard bypass permissions and chop would still ignore block-break and block-place being denied.

**Comment by NathanWolf** [comment]
You were definitely not opped while you tested it?

I just tried it myself with a newly-created region and some trees in it. Casting inside the region is not allowed at all (You are not allowed to use that here), casting from outside the region into the region the projectile would hit a tree but nothing would happen.

I double-checked the Drop action to make sure it has this:
```
if (!context.hasBreakPermission(block)) {
            return SpellResult.INSUFFICIENT_PERMISSION;
        }
```

And double-checked chop.yml to make sure it has no bypass flags or anything.

Have you customized the spell at all? Do you maybe have it in the allowed-spells flags on the region?

**Comment by NeoFalcon1605** [comment]
I'm pretty sure I wasn't.  I was using the spell book if that makes any difference?  And I've not customised the spell.  I can't get on the server currently to check all the region flags again though

**Comment by NathanWolf** [comment]
Did you ever figure this out? Did you have bypass perms maybe? :D

**Comment by NeoFalcon1605** [comment]
I had actually forgotten about this but yeah I suspect it was everyone having the bypass perms that were cleaned up recently, thank you.

**Comment by NathanWolf** [comment]
Ahhh terrifying that everyone had full Magic perms for like half a year? 😂 

Wonder how many players you have floating around with super OP items 😢

**Comment by NeoFalcon1605** [comment]
I suspect not many due to a variety of things hopefully at least.  I think it was closer to maybe 1-2 years though, basically someone decided not to read the permissions page properly which was fun
