### ISSUE TITLE
MCMMO skills cause issues with 

### ISSUE THREAD

**Issue by marvinej** [elBukkit/MagicPlugin#645]
using a wooden hoe as wands makes mcmmo go crazy. the only way i can think of to fix this is to disable herbalisim or have you change the default items to non mcmmo items like leather cap or something.

**Comment by NathanWolf** [comment]
You can change the items to whatever you want, in either plugin. If you change Magic's wands, you'll also have to change the RP or make your own.

I won't be changing the defaults.
