### ISSUE TITLE
Translation assistance

### ISSUE THREAD

**Issue by qsefthuopq** [elBukkit/MagicPlugin#647]
I need your webpage source to translate the website http://mine.elmakers.com/
But the link in wiki is invalid: https://github.com/elBukkit/MagicPlugin/wiki/WebSite

BTW, please take a look at the private message in Discord.
I'm looking forward to your reply.

**Comment by NathanWolf** [comment]
Oh I moved it to a separate repo: https://github.com/elBukkit/MagicMeta/tree/master/src/web

Can you please tell me where you found that link so I can update it?

**Comment by qsefthuopq** [comment]
Just the link above
https://github.com/elBukkit/MagicPlugin/wiki/WebSite

**Comment by qsefthuopq** [comment]
Then which files include the text?

**Comment by NathanWolf** [comment]
I mean where did you find that link? Is it on the wiki somewhere?

So a lot of the text you actually add to config.inc.php, that's where the main page description would go.

The rest of the text comes from your Magic config files, which you will need on the webserver, there is a location to edit in the config.inc.php file to point to your config YMLs

So if you've already translated the in-game text, use those translations in your configs and the website should pick them up.

There is also some text in index.php that won't be super easy to translate, unfortunately, since it's embedded in the HTML. But I don't think there's much of it, just the section headings I think.

**Comment by qsefthuopq** [comment]
It's in the wiki page **WebSite**
`MagicPlugin web source`

**Comment by NathanWolf** [comment]
Thank you!

**Comment by qsefthuopq** [comment]
In fact I don't know about coding and how to set up a website,I will send you these files once I finish the translation.

**Comment by qsefthuopq** [comment]
So how to install it in my server?

**Comment by NathanWolf** [comment]
I'm sorry, I think this may be too complex if you have no experience setting up a website :(

You would at least need to know how to enable php on your webserver.

If you want to try, just download that entire "web" folder from github and put it on your webserver.

But honestly you may be better off just skipping it. All of that information is basically available in-game, you can give out books to players with all of the spells in them, for instance, which will use your localization files.

**Comment by qsefthuopq** [comment]
Could you pack it into jar file to let me have a try?Or is it possible to set up a new website on your dev server?

**Comment by NathanWolf** [comment]
Just go here: https://github.com/elBukkit/MagicMeta

And use the "Clone or Download" button, download it as a zip

The "web" folder is the one you want to put on your webserver

If you want to give me your localization files and I find the time, I can try to make the website have  a language selector. Not sure offhand how hard that'll be though.

**Comment by qsefthuopq** [comment]
Use this file:
https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/examples/localizations/messages_CN.yml

**Comment by NathanWolf** [comment]
Ok, here you go:

http://mine.elmakers.com/?lang=CN

The intro page is not translated. If you'd like to try to translate it I can see about making a switch for that, too.

Here is (most of) that text:
```
<div style="margin-left: 128px;">
		Welcome to the official Survival server for the Magic plugin by elMakers!
		<br/><br/>
		Log in and play at <span class="minecraftServer">mine.elmakers.com</span>.
		<br/> 
		You may also view our <a href="http://map.elmakers.com"/>dynmap here</a>.
		<br></br>
		Magic is a plugin for the <a href="http://www.bukkit.org" target="_new">Bukkit</a> minecraft server, you can find development builds on our <a href="http://jenkins.elmakers.com">Jenkins CI Server</a>.
		<br/>
		<span style="font-style:italic; font-weight: bold">Thanks for looking!</style>
	</div>
```

**Comment by qsefthuopq** [comment]
Use the files in my fork:
https://github.com/qsefthuopq/MagicMeta/tree/CN/src/web

**Comment by NathanWolf** [comment]
I just copied that in by hand

I had to change the filename to be consistent with the others for the language switch to work.
