### ISSUE TITLE
Possible bug with Flight Duration

### ISSUE THREAD

**Issue by GrantisMantis** [elBukkit/MagicPlugin#651]
Here is a Spell I created, I noticed that it works as intended WHILE the caster is alive. However, if the caster dies, the duration on the Flight disappears and players are left floating in place until killed.

AoEImmobilize:
  actions:
    cast:
    - class: AreaOfEffect
      actions: 
       - class: Velocity
         direction: 0,0.2,0
       - class: Delay
         delay: 100
       - class: PotionEffect
         duration: 3000
         add_effects: 
          SLOW: 7
       - class: Fly
         duration: 3000
         speed: 0.001
  effects:
        cast:
           - class: EffectSingle
             sound: kitpvp.freeze
             location: origin
             color_override: color
             source_location: body
             effectlib:
                 class: Sphere
                 particle: smoke_normal
                 radius: $radius
                 height: 3
                 enable_rotation: true
                 particles: 60
                 speed: .1
                 duration: 500
                 disappear_with_origin_entity: true
  parameters:
    cooldown: 12000
    target: self
    radius: 7

Hopefully, there is something that can be done about this :)

**Comment by PhvntxmX** [comment]
cancel_on_death: true

**Comment by NathanWolf** [comment]
Thank you @PhvntxmX - @GrantisMantis did that work for you? I think cancel on death is what you want.
