### ISSUE TITLE
Bubble duplicate items in chest

### ISSUE THREAD

**Issue by qsefthuopq** [elBukkit/MagicPlugin#653]
See the gif
https://sm.ms/image/qtv6osJHLORkecC
Cast Bubble then open the chest will duplicate items in chest

Using 1.15.2 Spigot

**Comment by NathanWolf** [comment]
So the steps are

1. Put item in chest
2. Cast bubble around chest
3. Remove item
4. Wait for undo
5. Item reappears in chest?

If so I can not reproduce that... do you have any chest protection plugins or anything similar? Are you able to reproduce this on my dev server or without any other plugins?

**Comment by qsefthuopq** [comment]
I find that it is caused by FurnitureLib.
https://www.spigotmc.org/resources/furniturelibary-protectionlib.9368/

**Comment by NathanWolf** [comment]
Thank you for letting me know, I will add that to my list of incompatible plugins.

**Comment by Azurzar** [comment]
Hi! Is still being existen the incompatibility at this time? Would be possible to solve it just disabling Bubble or certain stuff from Furniture?
