### ISSUE TITLE
"Mine" spell doesn't drop any ores

### ISSUE THREAD

**Issue by PhvntxmX** [elBukkit/MagicPlugin#656]
Spigot 1.15.2 & Magic 7.8.3-snapshot
"Mine" spell only breaks blocks and nothing drops out of it

**Comment by PhvntxmX** [comment]
am i being ignored or what

**Comment by NathanWolf** [comment]
No, I just don't have a lot of time for this anymore. When someone reports a bug that no one else has reported I have to go test it out myself. I literally never play Minecraft anymore except to go hunt for bug reports. As you can imagine this is not super high on my priority list, life-wise.

**Comment by NathanWolf** [comment]
Hm, so first impression is this looks like a bug or change in Spigot. I'm calling Block.getDrops() on a diamond ore block and it returns an empty list. I'll keep looking but I may have to turn to Spigot's bug tracker.

**Comment by NathanWolf** [comment]
Turn out you now have to specify a tool. The default is air, so punching, and most ore blocks won't drop items if punched.

This will be fixed in the next dev build and release 7.8.3 which I will probably try to get to today.
