### ISSUE TITLE
Request support for Land

### ISSUE THREAD

**Issue by XXY218** [elBukkit/MagicPlugin#657]
Hello, I have been using Magic for almost a year, and recently my protection plugin switched from Residence to Lands，I hope Magic can also support Lands, I tried to contact them and they told me

> If it doesn't already support Lands, they can add this support easily by using our LandsAPI on github: github.com/Angeschossen/LandsAPI

For example, you can set to prevent casting in the land, or prevent some characters from casting magic. (It would be better if you could prevent the character from using the specified magic. If this requirement is difficult, you can ignore the bracket content request) :)

**Comment by NathanWolf** [comment]
That may be doable, it looks pretty ready to go.

But, it may be even easier ... if Residence was working for you, it's possible you can use the same generic protection integration with Lands. Try this in plugins/Magic/config.yml:

```
generic_protection:
  - Lands
```

**Comment by XXY218** [comment]
Oh my god, amazingly fast and efficient way, this is great
