### ISSUE TITLE
Resource Pack Issues

### ISSUE THREAD

**Issue by 10595870** [elBukkit/MagicPlugin#658]
Hey Nathan, hope you're well

The resource pack is working fine, wands appear exactly how they should. The only thing that doesn't work is the icons in the wand screen, all of which are still diamond axes. Any fix to this? I found another thread posting the same issue but he said he just gave up. 

Also, any way to stop zombie pigmen dropping lightsabers? No worries if not, 

Thanks for any help

**Comment by 10595870** [comment]
resource pack is left blank in server.properties, all i did was press yes when the plugin asked me if i wanted to install the Magic Resource Pack.

I am using an inventory sorting plugin, could this affect it?

**Comment by NathanWolf** [comment]
Do you know where you saw that other thread? That doesn't sound familiar, I'd be sad if I missed someone having trouble.

So, it sounds like something weird may be going on with unbreakable items. The gold swords the pigman hold should appear normal, it's only items with the unbreakable flag that should be getting different item models.

Can you please let me know what version of Magic and Spigot you're using, and also which RP version it's showing is being downloaded in your server logs?

**Comment by 10595870** [comment]
The original thread was https://github.com/elBukkit/MagicPlugin/issues/562

Okay, great news, as I was restarting my server some of the changes I was making before must have taken effect. The icons now appear as cubes as opposed to diamond axes. Is this correct?


![2020-03-18_14 51 59](https://user-images.githubusercontent.com/62342548/76973603-14fdb100-6928-11ea-8863-70f0be6fdf3f.png)

**Comment by 10595870** [comment]
Thank you for the very fast response, as well

**Comment by NathanWolf** [comment]
In recent RP's they should appear as flat icons, that looks like maybe an older RP where it's still using skulls (or you maybe configured it to use skulls?)

At least it's a step in the right direction!

**Comment by 10595870** [comment]
Agreed! Any thoughts on the zombie pigmen with lightsabers? Zombies in the Overworld also spawn with the re-textured chainmail as well

CraftBukkit 1.15.2
Magic v7.8-8ff6649
RP is https\://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-RP-1.15.zip

**Comment by NathanWolf** [comment]
The chainmail is not surprising, there's no way to override armor in any special way. Sadly I probably just need to remove the robes, it used to be chainmail didn't appear in vanilla survival.

As for the lightsabers.. not really. Can you kill a pigman and pick one up? If so you could try `/mitem describe` on it and show me the results .. if it's not unbreakable then something really odd is going on with the RP. If it *is* unbreakable then something odd is going on with your pigmen :)

I'll check my dev server when I get a chance, too. Maybe something weird changed that I haven't noticed.

**Comment by 10595870** [comment]
Good news and bad news

Good news is that the problem is fixed in regards to the pigmen, I must have solved it at the same time I solved the icon issues

Bad news is I think I wasted your time a bit here. Than kyou for the help, sorry for bothering you by being a bit of an idiot

**Comment by NathanWolf** [comment]
Haha, no worries... you are far from the most annoying customer I've had XD

**Comment by Hito2158** [comment]
The Resource Pack wont load at a server can anyone help me or send me the resource pack so i can get it into minecraft

**Comment by NathanWolf** [comment]
Have you looked at this?

https://github.com/elBukkit/MagicPlugin/wiki/ResourcePack#loading-issues

What does `/getrp` say? What about `/getrp url`?

**Comment by Hito2158** [comment]
it says This command has been disable because this Server has a recourcec pack configured in server.properties

**Comment by NathanWolf** [comment]
So it is telling you exactly what the problem is, as is #1 in the link I pasted.

**Comment by Hito2158** [comment]
i dont now bot i dont have it

**Comment by NathanWolf** [comment]
You will need to turn off your server resource pack to let the plugin handle RPs for your server. This is done by clearing the `resource-pack` entry in server.properties.

**Comment by Hito2158** [comment]
thanks its working now
and can you sand me the resource pack for the version 1.19.3 because i on an another server were it not ther its just not existing and the server team there try evrethink but it wont work

**Comment by NathanWolf** [comment]
No, sorry. Use `/getrp url` to get the URL to the RP you need. I don't have a list of them all offhand.

**Comment by Hito2158** [comment]
ok but thanks for anythink
