### ISSUE TITLE
Plugin doesn't work (Minehut server)

### ISSUE THREAD

**Issue by pranuv222** [elBukkit/MagicPlugin#659]
Hi! This is my first installation of a plugin to a server on Minehut, which might explain my struggles. I've installed the plugin via Minehut but nothing changes on the server. the /mage and /magic commands etc are available, but unresponsive. The crafting recipe for a wand doesn't work. 

Furthermore, under "Data" and "Defaults" there appears to be nothing within these folders. There is a magic.jar file, but that's about it related to the plugin. Please advise as I'm so excited to try out this plugin.

**Comment by NathanWolf** [comment]
Do you have access to your server logs? It sounds like you should expect to see some errors there.

**Comment by NathanWolf** [comment]
Seems like you are not the first person to have issues with Minehut. Unfortunately the person at #640 never came back with a response either.
