### ISSUE TITLE
Chest Dupe with any destruction spell

### ISSUE THREAD

**Issue by PureTrippH** [elBukkit/MagicPlugin#660]
Hello! I am running the plugin on a 1.12.2 spigot server, and one of my players pointed out that there is a dupe using the blast spell or any destructible spell to duplicate all of the contents of the chest. Im sure it has to do with the contents of the chest being quickly taken out before destroying it, then having the chest be reloaded before the destruction, with the new set of items. I can see if he can film a demonstration, but for now that is the description of how to do it

**Comment by NathanWolf** [comment]
The plugin normally handles this by detecting when players interact with a chest that is scheduled to undo, but if you can provide a video that might help me in case there is some edge case I have missed.

Often though it ends up being some other plugin that is interfering with the process somehow.

I think in light of how many people have this issue I'm going to make all containers indestructible to magic by default. If you are interested in seeing if that fixes your issue, you can try out the dev build here:

http://jenkins.elmakers.com/job/MagicPlugin/2945/com.elmakers.mine.bukkit.plugins$Magic/
