### ISSUE TITLE
Cast effects are not displayed if the spell has a self targeting mode

### ISSUE THREAD

**Issue by PhvntxmX** [elBukkit/MagicPlugin#661]
Maybe this is not an bug, but in the previous version it does not appear.
Works normally if "cast" effect replaced with "cast_self" in spell's effects section.
Spigot 1.15.2 & Magic 7.8.4-snapshot

**Comment by NathanWolf** [comment]
Hm, yeah I *think* it's supposed to use `cast` if `cast_self` isn't there. It's meant to be an *optional* way to override effects when a spell targets yourself.

So I think I agree that is a bug, I will take a look.

**Comment by NathanWolf** [comment]
If you have a simple example I'd appreciate it, otherwise I can work something up.

**Comment by PhvntxmX** [comment]
Fling spell, cloak

**Comment by NathanWolf** [comment]
Thanks! Shame I just uploaded a release...

**Comment by NathanWolf** [comment]
But really Fling's effects are totally broken? I'd be shocked if I didn't notice that myself... checking now.

**Comment by PhvntxmX** [comment]
Only land effect is showing

**Comment by NathanWolf** [comment]
Hm so it seems ok to me, I see the particles for both of those spells. Are you able to test on my dev server?

Those are hooked up via `default` in spells.yml. Have you edited that by any case? Specifically it's this part, which makes `cast_self` default to `cast`:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/defaults/spells/default.yml#L110

**Comment by PhvntxmX** [comment]
Yea, sorry, seems like this is my fault

**Comment by NathanWolf** [comment]
No worries! Sorry I have not been super responsive here. I appreciate you stepping in to answer other peoples' issues.

**Comment by PhvntxmX** [comment]
Sorry for wasting your time because of my stupidity

**Comment by NathanWolf** [comment]
Dude, no seriously don't worry about it! You're all good.
