### ISSUE TITLE
Brooms Only Float

### ISSUE THREAD

**Issue by HenrickTheBull** [elBukkit/MagicPlugin#666]
I've noticed that our brooms in our server only allow players to float the don't fly anywhere. I'm going to post our plugins here. Don't know if any are blocking the brooms or not.

Plugins:
[Sun, 29. Mar 2020 20:35:24 MDT INFO] Plugins (49): AcceptTheRules, AdvancedPortals, Autorank, BentoBox, Brewery, Citizens, ClientStats*, CoreProtect, CreativeItemControl, DiscordSRV, eGlow, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, Griswold*, Harbor, HolographicDisplays, HyperDrive, Jobs, Lottery, LuckPerms, LWC, Magic, MarriageMaster, mcMMO, Multiverse-Core, MythicMobs, NametagEdit*, OpenInv, PerWorldInventory, PlaceholderAPI, PlayerParticles, PluginLibrary, ProtocolSupport, Statz, SuperVanish, Towny, TownyNameUpdater, TridentCraft, UltimateShops, UltimateTimber, Vault, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuard-Towny*

**Comment by NathanWolf** [comment]
What Spigot and Magic version do you have? A mis-match there is often the cause.

Are players in creative mode?

**Comment by HenrickTheBull** [comment]
I'm no longer able to give you this info. I'm no longer involved with the server that this request was for, so I'm closing it. Sorry for wasting your time.
