### ISSUE TITLE
[Translation] Complete in Spanish by ChrisTVH

### ISSUE THREAD

**Issue by ChrisTVH** [elBukkit/MagicPlugin#667]
Just as I said in spigot that I would translate the plugin completely into Spanish, at least the message was a pretty hard job but I honestly hope that the Spanish and Latin American community will enjoy it.

https://mega.nz/#!Y4QjDA4Y!_pbXyHU6_S4YXc1GBbJ4COyQnp_CHDpggLZuZANpHqE

**Comment by nrgumento** [comment]
**GRACIAS CAPO**

**Comment by MaxiiARG** [comment]
GENIO! TE AMO!

**Comment by NathanWolf** [comment]
Just so you all know, all you need to do to enable this now is put `language: ES` in plugins/Magic/config.yml
