### ISSUE TITLE
1.9 dupe spells using 2 hand

### ISSUE THREAD

**Issue by DanielTenebris** [elBukkit/MagicPlugin#67]
Hello, i live in Russia so excuse me for my english.
With the second hand, you can duplicate the spell .
In the video below, all demonstrated: 

https://www.youtube.com/watch?v=EYPkBHS2sXA

Please fix this. =(

**Comment by NathanWolf** [comment]
Hi! I thought I had fixed this already- what version of Magic do you have?

**Comment by NathanWolf** [comment]
I'm sorry to say Magic 5.x isn't really getting updating anymore. No idea if you're still using it or having these problems, I apologize if so.

I don't think this is an issue on later builds of Magic, so I'm going to close this issue for now.
