### ISSUE TITLE
Adding scoreboard scores to spell costs

### ISSUE THREAD

**Issue by KingofAnomaly** [elBukkit/MagicPlugin#672]
Adding the ability to use vanilla scoreboards to spells could add the ability for players to create abilities based on vanilla Minecraft statistics such as breaking certain blocks or swimming in water. It will also help to connect magic to many more plugins that also use vanilla scoreboards.

**Comment by NathanWolf** [comment]
Can you elaborate on this? You'd like scoreboard stats to be useable in equations or something?

**Comment by NathanWolf** [comment]
Oh I missed the "spell costs" title ... still not super sure how this would work, though.

**Comment by KingofAnomaly** [comment]
So basically I used the vanilla minecraft scoreboard for an event and wanted my players to be able to buy items using their scoreboard scores. I could make it so that a command takes the score away each time the buy an item but that only takes the score away and doesn't stop them when they go below 0 and there is no way that I know of to even detect a score.

**Comment by NathanWolf** [comment]
You might be able to do this in the next release if you have PlaceholderAPI. You can now use placeholders everywhere, might work for costs but not sure. I think PAPI can pull from scoreboard scores.

**Comment by NathanWolf** [comment]
Did you ever get to try this out via PAPI?
