### ISSUE TITLE
spells.yml has only comments inside..?

### ISSUE THREAD

**Issue by Cryotol** [elBukkit/MagicPlugin#674]
I wanted to lower the cooldown to earn SP but I cannot find it in any place, since what i believe we needed to edit (spells.yml) only has comments inside.

I tried copying the spells.default.yml into spells.yml and change the value of earns_cooldown, no change.
I tried deleting the whole spells.default.yml , no change.

Please help me understand how this is changed, since i am possibly way off, thank you.

**Comment by Cryotol** [comment]
Found out how to: Pasted everything from spells.defaults to spells.yml and changed the earn cooldown individually

**Comment by NathanWolf** [comment]
It's a much better idea to just put what you want to change in the config files. You should only have to put this in your spells.yml:

```
default:
    # Spells take 15 minutes to return to full SP earning potential
    earns_cooldown: 900000
```

Changing that number to whatever you want.

Pasting the entire config is not recommended, it will make updating much harder. See the configuration guide for more details.

https://github.com/elBukkit/MagicPlugin/wiki/Customization

**Comment by Cryotol** [comment]
Alright, thanks!
