### ISSUE TITLE
Server crash when using a magic item

### ISSUE THREAD

**Issue by Curtis73** [elBukkit/MagicPlugin#676]
There appears to be an issue that causes the server to crash whenever you consume certain magic items (For reference, I used the sorting ticket exactly as it is from the default configs)
Upon use, the server immediately shuts down, before reporting the following error: https://pastebin.com/pC4U8fPQ
I have tried this on a server with only magic installed, so I'm pretty sure this is related to Magic in some way

**Comment by NathanWolf** [comment]
Were you in creative mode?

**Comment by Curtis73** [comment]
I was in creative mode - just tried it in survival and it works fine with no crashes!

**Comment by NathanWolf** [comment]
Thought so!

Sadly this bug has been here about forever, it happens anytime I remove the item in the hand of someone in creative mode. I think it needs to be fixed on Spigot's side but I really don't know.
