### ISSUE TITLE
Additional Placeholder Support

### ISSUE THREAD

**Issue by maximeCX** [elBukkit/MagicPlugin#678]
There's should be in the RPG system an option for full time action aka 24h action without going out. 
That says <HEALTH> / <MAX HEALTH> |||||| <MANA> / <MAX_MANA> 
Or create more place holders for 
<wand_hold_player_mana> / <wand_hold_player_mana_max> for placeholderapi, that would be very cool. Total spells placeholders 
Spell Points placeholder for scoreboard and such and chest menus.

**Comment by NathanWolf** [comment]
New placeholders in the next release: magic_sp, magic_spell_count, magic_mana and magic_mana_max

**Comment by NathanWolf** [comment]
The next release will also allow you to use placeholders in magic configs.
