### ISSUE TITLE
I would like to add other stuff to the resource pack

### ISSUE THREAD

**Issue by GitItGoing** [elBukkit/MagicPlugin#680]
Hi guys! This should be very simple

I would like to integrate my resource pack with yours, all my resource pack does is changes the music on the music disks in minecraft 1.15.2 is there a way I can get the resource pack since my current one is in server.properties?

Thanks!
GitItGoing

**Comment by NathanWolf** [comment]
The most recent version is here: https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-RP-1.15.zip

But if you are on an older version of Spigot you may need an older version of the RP.
