### ISSUE TITLE
Broom creative messages when in survival

### ISSUE THREAD

**Issue by Curtis73** [elBukkit/MagicPlugin#683]
Hey,
There appears to be an issue regarding broom messages - if you're in survival and try to activate your broom in an area where the spell is disabled, you get told that both the spell is disabled and you can't cast it in creative, despite being in survival.
The broom still activates as it should, so this is just a cosmetic problem.
![image](https://user-images.githubusercontent.com/14040165/80711368-28379b00-8ae8-11ea-9cfe-5be3e148219f.png)

**Comment by NathanWolf** [comment]
Oops, thanks for pointing that out- that code was hastily written in a fit of complaint-induced rage.

Will be fixed in the next dev build!

**Comment by Curtis73** [comment]
Excellent - thank you!
