### ISSUE TITLE
Issues With Merging Resource Pack

### ISSUE THREAD

**Issue by Moving-Light** [elBukkit/MagicPlugin#685]
Hi!  I am having some trouble understanding how to merge the resource pack.  My issue is that we have the Magic plugin and Quality Armory installed and both of them use the diamond axe for textures.  Most of the time it is not an issue until some of your spell icons turn into guns.  If you could explain the steps to fix this that would be great.  I can send the resource pack for Quality Armory if needed.  Thanks!

**Comment by NathanWolf** [comment]
If there is another tool you can use, the easiest thing is to rename the diamond_axe.json to some other tool, and make sure to edit the file appropriately so the vanilla version remains the same.

Then in plugins/Magic/items.yml put this:
```
spell_icon: <whatever tool you chose>
```

**Comment by npritzer** [comment]
so that is why it all broke, I did not change the diamond_axe.jar.  Let me look at that now

**Comment by npritzer** [comment]
Another edit, I just found I was looking at the wrong pack.  I will see if this works in a few minutes

**Comment by npritzer** [comment]
How would I combine the sounds?  I merged the sounds folder but I do not want to mess up the sounds.json file

**Comment by NathanWolf** [comment]
If your other plugin has a sounds.json also you'll have to merge the two files, there's no way around it.

**Comment by npritzer** [comment]
ok

**Comment by npritzer** [comment]
So I merged the packs and the textures all broke.  I am attaching the resource pack.  If you could see what I messed up, that would be great.  Thanks!
[Magic and QualityArmoryV1.0.40.zip](https://github.com/elBukkit/MagicPlugin/files/4576194/Magic.and.QualityArmoryV1.0.40.zip)

**Comment by NathanWolf** [comment]
I'm not sure how you zipped that up, but Minecraft did not like it. Make sure to test locally first, it would not even show up in the RP list in the MC client.

Also note you have the mcmeta set for an older version of MC but that was maybe intentional.

Here's the command I use (from inside of the RP folder) to zip it up:

` zip -r -X ../Magic-RP-1.15.zip *`

**Comment by npritzer** [comment]
It is a bug with my windows.   You need to unzip it first.  Could the issue
be that I am trying to use a 1.15.2 resource pack with 1.12.2?

**Comment by NathanWolf** [comment]
It needs to function as a zip. Find a different zip tool if you have to.
