### ISSUE TITLE
Mobs not dropping SP anymore

### ISSUE THREAD

**Issue by Ferocimo** [elBukkit/MagicPlugin#686]
Hello,

We have Magic version 7.9.1-SNAPSHOT-a9a407c on a Minecraft 1.15.2 paper server. We have several "warlocks" in our config, which drops SP. In the loot table we added : "- sp:30".

But they seem to only drop MHF_QuestionMark heads now, even though it previously worked.

Could you have a look at this ?

Thank you.

**Comment by NathanWolf** [comment]
I just tested the builtin warlocks and their SP drops are still working. I can't think of anything that's changed in that area.

Do they just have the wrong icon? As in, do you get SP when you pick them up or do you just get a player head item?

I may need to see your full configs since the builtin ones are working, but there's no real trick to setting it up nor any recent changes.

**Comment by Ferocimo** [comment]
This is our mobs.yml config, do you need other parts of our config ? 
https://pastebin.com/ybiryTiX

It is dropping a simple player head, which is not giving SPs to players. I'm surprised too that this stopped working on our server because we haven't touched that part for ages.

**Comment by Momonche** [comment]
I have the same issue but not only on mob drops, it's on SP item drop
https://www.youtube.com/watch?v=eIDE-3eSiQo

**Comment by NathanWolf** [comment]
If it looks right in your inventory like in @Momonche 's video but then you drop it and it changes, I don't really know what could be causing that.

@Ferocimo can you try that same thing, please? Like `/mgive sp:100` then drop it?

**Comment by Momonche** [comment]
Ok I just find the problem,
I use PlayerHeads and there is a config : 

fixdroppedheads: true         [true/false]    Whether or not to update the name,lore on dropped head items (fixes heads broken by pistons/water)

That make SP head become Question head

Maybe @Ferocimo use this plugin ?

**Comment by Ferocimo** [comment]
Yes exactly, it works fine now. Thank you.
