### ISSUE TITLE
discord/way to connect with people using this plugin

### ISSUE THREAD

**Issue by albrechet** [elBukkit/MagicPlugin#687]
Hi Nathan, I'm really sorry about contacting you through this "Issues" page as I wouldn't say I'm having an "issue" with the plugin, but more just trying to find a place to chat about spell creation and stuff like that. Do you have a discord, or a chatroom where people can talk about the plugin, and if you do could you link it to me. Again I'm really sorry about using this to ask but I couldn't find anything about a discord. If you don't I'd gladly create one and moderate it. Thanks again for creating such a great plugin!

**Comment by NeoFalcon1605** [comment]
https://discord.gg/QHH2RSq if that doesn't work the link should be on the Spigot page.
