### ISSUE TITLE
Dragonball Spell Does Not Earn SP

### ISSUE THREAD

**Issue by Svennieboy777** [elBukkit/MagicPlugin#688]
Hi, both spells do not function how they are supposed to be.

**Comment by NathanWolf** [comment]
What are you expecting them to do? What version of Spigot and Magic are you on?

**Comment by Svennieboy777** [comment]
My apologize, both spells work. It was a bug from our side. I have 2 more questions tho.
1. Is it possible to change the shop GUI's you created? as example the hat shop?
2. Dragonball doesn't give SP, is this a bug or supposed to be?

**Comment by NathanWolf** [comment]
Dragonball should give SP, but only if you hit something with the fireball itself. Mobs or players going into the poison cloud doesn't count.

It is very easy to make your own shops, yes. Just take one of the builtins and put something similar in your spells folder.

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/examples/survival/spells/shops.yml#L1

**Comment by Svennieboy777** [comment]
Thank you.

**Comment by Svennieboy777** [comment]
Okay, i already see the issue with dragonball. You cannot hit an entity with the dragonball itself. Do you have any solutions for it?

**Comment by NathanWolf** [comment]
Why can't you? I thought it would hit and explode like normal.

If that is the case though you (or me) could add an AreaOfEffect action to ping everyone around for 1 damage or something.

**Comment by NathanWolf** [comment]
I've added a 1-damage AOE to Dragonball to fix the SP earn issue.
