### ISSUE TITLE
Blocks added after 1.9.3 not affected by certain spells

### ISSUE THREAD

**Issue by unbeatablegamer** [elBukkit/MagicPlugin#690]
I can't remember exactly which spells this happened with, but I think one of them was worm death?

**Comment by unbeatablegamer** [comment]
Can now elaborate. Wave spell does not work on granite, diorite, or andesite, for example. Instead gets stuck and does not move forwards.

**Comment by NathanWolf** [comment]
I'll add those 3 to the default destructible list. Feel free to change your own in spells.yml,
```
wave:
  parameters:
     destructible: whatever,blocks,you,want
```
