### ISSUE TITLE
"Fury" spell targetting caster on a horse

### ISSUE THREAD

**Issue by Ferocimo** [elBukkit/MagicPlugin#691]
Hello,

We have Magic version 7.9.2-SNAPSHOT-363ebb5 on a Minecraft 1.15.2 paper server. 

Casting the Fury spell while on a horse will also target and hurt the caster. I think it is because it is targetting the horse itself and the player happens to be in the way, but ideally there should be an exception for a hourse mounted by the caster.

This is not an urgent issue, but thank you for looking into this.

**Comment by NathanWolf** [comment]
Thanks! This seems to have revealed some consistency issues with how the "target self" flag works. I'll get it fixed up for the next release.

I'm also going to add a flag to skip targeting mounts, which will be on by default. Otherwise it's just gonna kill your horse instead :(

**Comment by NathanWolf** [comment]
It is worth noting, though, that it turns out the behavior of fury hitting you on the way down was intentional.

So the real fix here is having it avoid targeting your mount.

But if you're standing right near an enemy you *can* get hit with the projectile accidentally.

**Comment by Ferocimo** [comment]
I completely agree that you could be hurt by your projectile if you're in the way, it has always been that way and makes total sense. As you said the real problem here is it targets your mount, which means you get damaged 100% of the time even with no enemies nearby...

**Comment by NathanWolf** [comment]
Agreed, that's been fixed :)
Spells now avoid targeting the caster's mount by default.

**Comment by Ferocimo** [comment]
Great, that works with latest version indeed. Thank you !
