### ISSUE TITLE
Better version outpout

### ISSUE THREAD

**Issue by Momonche** [elBukkit/MagicPlugin#692]
Hello !

I follow the development of Magic of Jenkins and use it like a changelog, but It's hard to know what build I use cause "/ver magic" didn't tell what build I'm using

Can you add the build number in /ver magic output ?

/ver magic
![LW2kiGKxFo8s](https://user-images.githubusercontent.com/37519498/82431644-32b5d680-9a8f-11ea-8a7e-cefd347d30e0.png)

/ver Citizens show the build
![008rS108KvXq](https://user-images.githubusercontent.com/37519498/82431671-3cd7d500-9a8f-11ea-907f-bed78ae10172.png)

**Comment by NathanWolf** [comment]
Sorry, I prefer the git revision. It tells *me* what you're running, even if you didn't get it from my build server :)
