### ISSUE TITLE
API Rankup

### ISSUE THREAD

**Issue by Curtis73** [elBukkit/MagicPlugin#693]
I'm using the API to rank up certain players that reach the end of their path, using the following code:
`mage.getBoundWand("wand").upgrade(false);`
This ranks the user up fine, However, the `upgrade_commands` specified in the paths.yml are only activated if the user is holding their wand at the time the code's called.
If they're not, then their wand will still rank up correctly, but none of the commands will be executed.
I'm not sure if this is a bug or not but thought I'd report it just in case

**Comment by NathanWolf** [comment]
It's probably not 100% intentional, no- but a lot of the progression stuff is still more tied to wands than I'd like it to be. Commands *should* run either way (upgrade items are another story). I'll take a look, seems worth fixing, thanks!

**Comment by NathanWolf** [comment]
Yup, note to self that this problem is mainly within UpgradePathAction:

```
    @Override
    public SpellResult perform(CastContext context) {
        Mage mage = context.getMage();
        Wand wand = mage.getActiveWand();

        // For now... eventually I need to separate out the wand part, but not doing it now.
        if (wand == null) {
            return SpellResult.NO_TARGET;
        }
```

Sounds like it's time to handle this case :)

**Comment by NathanWolf** [comment]
Oh, wait, you're using `mage.getBoundWand("wand").upgrade(false);` .. so the problem may be deeper than that.

For what it's worth that's not *entirely* how getBoundWand is meant to be used but I suppose it might work?

The idea with those are more like they are stored wands in case the player has lost the physical wand item... but I think maybe if they still have the item it should work out the same.

At any rate you *should* be able to do something more like mage.upgrade() - the wand really shouldn't be involved at all, ideally. I'll let you know if I get some new API working for that.

**Comment by Curtis73** [comment]
Ah - thank you! I did start off using getActiveWand(), but iirc that only worked if the user was holding their wand at the time the code got executed.
I've had a look but I've not been able to find mage.upgrade() or anything similar, though I really don't mind waiting for you to get some new API up and running

**Comment by NathanWolf** [comment]
Ok, I bit the bullet and did it- the spellshop should now work fully without a wand, and there's some new API.

Here's what the spell shop now uses, which I think should work for you too:
```
        CasterProperties caster = mage.getActiveProperties();
        ProgressionPath path = caster.getPath();
        ProgressionPath nextPath = path != null ? path.getNextPath() : null;
        if (nextPath != null && path.checkUpgradeRequirements(caster, true) && !path.canProgress(caster)) {
            path.upgrade(mage, mage.getWand());
            return SpellResult.CAST;
        }
```

In this case it's OK for the wand to be null. 

Currently if there's no wand it will skip any `upgrade_items` you have configured... I think I can fix that, though.

**Comment by Curtis73** [comment]
That works perfectly - thanks again!
