### ISSUE TITLE
A faster way to cast spells.

### ISSUE THREAD

**Issue by LakeArcFox** [elBukkit/MagicPlugin#694]
Sometimes switch spells is a little slow, and some spells are designed to be cast very fast.
I wonder if a player can cast spells by pressing hotbars.
which means when I press "1", I will cast spell 1 automatically.
One existing mode is "Inventory Mode", and in this mode players select spell by pressing 1-9.
A faster way is that players directly cast spells by pressing 1-9.
Sorry for my bad English.
:)

**Comment by NathanWolf** [comment]
use the tweak menu from the enchant table and switch to "quick cast" mode on your wand.

**Comment by LakeArcFox** [comment]
Thanks, though I didn't find this, but I have written a plugin to make this.
