### ISSUE TITLE
Latest update adding NBT to magic items is messing up everything

### ISSUE THREAD

**Issue by Ferocimo** [elBukkit/MagicPlugin#695]
Hello,

With the latest Magic update, you added an NBT tag to all magic items, named "magic_key: "[Name]"". This has caused some tremendous issues on our server, since we're using magic items for a lot of our systems, and these items often need to be given exactly as they are when we save them, without a single additionnal NBT data or anything. Typically, Magic gives the player an item which he can then sell. But, because of this new NBT, he can't sell it because our Shop plugin doesn't recognize it as the same item we set up in the config (and we can't add the Magic NBT in the shop config). There are lots of other issues as well but I won't ellaborate. 

As a result we had to downgrade to latest version. I don't know if this magic NBT is an important feature for your developpment, but we would greatly appreciate if you could make an option to disable it completely in the config, otherwise we won't be able to update anymore...

Thank you for your time.

**Comment by NathanWolf** [comment]
Yikes, sorry!
I hadn't considered that *at all*. My bad!
I've turned it off in the latest dev build.

**Comment by Ferocimo** [comment]
Thank you ! The problem is gone from latest version now. However since we updated it seems most spells won't work in PVP anymore, even though they still work against mobs... Do you have any idea about what might have caused this ? If you prefer I can create a separate issue of course, this current one is fixed.

**Comment by NathanWolf** [comment]
Yup, I'm really batting 1000 lately 😂

I just released 7.9.5 which fixes _that_ particular bug.

**Comment by Ferocimo** [comment]
You're very reactive and effective ! Thank you, it is fixed, everything seems back to normal. I'll let you know if I find anything else.
