### ISSUE TITLE
Can't use MagicAPI

### ISSUE THREAD

**Issue by apatuka** [elBukkit/MagicPlugin#697]
Hi i instantiate the api with this line:

`MagicAPI api = new MagicAPI();`

But is not working:

MagicAPI is abstract; cannot be instantiated
        MagicAPI api = new MagicAPI();

How is the suitable way ? Thank you !

**Comment by NathanWolf** [comment]
See instructions here:
https://github.com/elBukkit/MagicPlugin/blob/master/MagicAPI/README.md

**Comment by apatuka** [comment]
Thanks !
