### ISSUE TITLE
No destruction

### ISSUE THREAD

**Issue by Arikae** [elBukkit/MagicPlugin#7]
Hi,

we've installed the plugin on our server but all destruction spells don't have a permanent effect.
Blocks disappear shortly to reappear after half a second.
Is there some configuration that we missed to set? :)

PS: We do not have WorldGuard or anything comparable running

**Comment by NathanWolf** [comment]
Oops, sorry- I didn't mean to close that- I also apologize for not seeing it until now, I need to figure out why I'm not getting emailed.

Anyway, that is the default behavior of the plugin- it's meant to be grief-free.

You can customize this by either turning the undo system of completely, or by customizing individual spells to remove the auto-undo timer.

**Comment by GreenShaman** [comment]
Napalm could use a good nerf.

**Comment by NathanWolf** [comment]
What a random place to put this comment- but Napalm isn't even a builtin spell :)

I have it as an unobtainable testing spell on my dev server.
