### ISSUE TITLE
[Feature Request] Allow usage without requiring additional texturepacks

### ISSUE THREAD

**Issue by FabTheZen** [elBukkit/MagicPlugin#70]
In some servers that can be a hindrance, as it gives an overhead and not everyone wants to force a custom texturepack anyway. It would be great to have an additional option to choose whether or not to use it.

Magic wands can be replaced by enchanted wood sticks in those cases.

**Comment by NathanWolf** [comment]
Add the following to your config.yml to turn off the resource pack:
```
default_resource_pack: ""
```

Note that spell icons will look weird, you can't enchant wooden sticks reliably anymore, and none of the custom sound effects will work. It will take quite a lot of custom config work to really make this plugin useable without the resource pack.

**Comment by FabTheZen** [comment]
Thank you for the clarification :)
