### ISSUE TITLE
MobArena integration not working

### ISSUE THREAD

**Issue by GxMaddock** [elBukkit/MagicPlugin#701]
As per the MobArena integration page I added "example: arena" to my plugins/Magic/config.yml then I added the suggested mage class but I received 10.06 22:59:08 [Server] INFO Failed to parse armor for class mage: magic:wizardhelmet as an error. That also happened for each of the items when I added them to an already working class. Let me know what you think.

**Comment by katiebosch** [comment]
+1 to this. After updating my server to 1.16 and updating my Magic and MobArena plugins, my Mage class no longer works despite making no changes to the configs. 
Magic version: 7.9.10
Mob Arena version: 0.104.2

**Comment by NathanWolf** [comment]
Do you still see this message in your logs?
>  [Magic] Integrated with MobArena, use "magic:<itemkey>" in arena configs for Magic items, magic mobs can be used in monster configurations

I'm not sure what could be going on there since it's still working for me :(

**Comment by NathanWolf** [comment]
Sorry, any updates here? It's still been working on my dev server fine.
