### ISSUE TITLE
Copy magic item

### ISSUE THREAD

**Issue by XXY218** [elBukkit/MagicPlugin#703]
**Detailed Description:** Hold a magic item, press F, and then press F without releasing, you can copy the item.

**Video:** https://youtu.be/XP2uR2R528M

**Magic Version:** 7.9.6

**Server Version:** Paper-354 (MC: 1.15.2)

**Comment by NathanWolf** [comment]
Is there any more to it than that? Do you double-press F and hold it? Does it only work with specific items or does it have to be a magic shield 

I've tried this myself every which way and have not been able to get it to happen. This has been reported before.

Are you able to test on vanilla Spigot?

**Comment by NathanWolf** [comment]
Ah, ok I was able to reproduce it on a remote server, so it must be ping-related. Thanks, I'll see what I can do!

**Comment by NathanWolf** [comment]
I think this is fixed in the latest dev build.

**Comment by XXY218** [comment]
> I think this is fixed in the latest dev build.

I slept last night so I did not reply in time, it has indeed been repaired now, thank you for your excellent work!
