### ISSUE TITLE
Wand crafting table click bug

### ISSUE THREAD

**Issue by TofPlays** [elBukkit/MagicPlugin#704]
Whenever I try to put the wands in the crafting table, I need to keep trying to click several times before it finally puts on the crafting table. It's like, I left click to put the item in the 9x9 crafting grid, and it pops back up to my cursor.
   It's way worse for some than others. One time, a player on my server kept trying to put an item on the crafting table for 3 minutes before he got it.
  Here's a video of recreating that: https://www.youtube.com/watch?v=kI85hl2_OPE&feature=youtu.be

**Comment by NathanWolf** [comment]
To be clear, I think this is a "feature", wands have not been allowed as crafting ingredients. Originally this was to prevent players accidentally using them for crafting (they used to be blaze rods, and you could easily smash them into powder by accident...)

But I think a system that allows for wands as crafting ingredients would be great- just a little more complicated to implement safely than fixing a bug would probably have been.

**Comment by NathanWolf** [comment]
This should be fixed in the latest dev build!

http://jenkins.elmakers.com/job/MagicPlugin/3098/
