### ISSUE TITLE
Left hand item consumed when opening wand menu

### ISSUE THREAD

**Issue by Ferocimo** [elBukkit/MagicPlugin#706]
Magic version 7.9.8-SNAPSHOT-1f9ae36
Minecraft Purpur 606 1.15.2 paper 372

Hello,

When you have a wand in right hand, and a consummable item in left hand like a golden apple for instance, opening the spell selection menu of the wand, with either right click or drop button, will make the player consume whatever is in his left hand. This is particularly problematic on PVP since many players use their left hand to hold their golden apples, and are forced to eat them when they chose a different spell.

Thank you for looking into this.

**Comment by NathanWolf** [comment]
Have you changed wands to use drop instead of right-click?

The default right-click set up does not work well with offhand items, but switching to drop mode should be fine. I will test using the drop button when I get a chance, there should be no reason for the offhand item to get activated when using drop mode.

**Comment by NathanWolf** [comment]
Yeah, drop mode seems fine (testing on 1.15, latest dev build).

I think that is the tradeoff. When 1.9 came out, I made drop mode the default to make it easier for players to use offhand items, but it was way too confusing for most people.

So I went back to right-click as the default, but you are welcome to change the default, or direct your players to the tweak shop in the enchantment table menu where they can choose drop mode themselves.

**Comment by Ferocimo** [comment]
You're right I probably mis-tested it, it works fine with drop mode. So indeed, there is a solution for pvp players. Just to know, wouldn't it be possible to make the menu opening considered as just one click and not a continuous right click ?

**Comment by NathanWolf** [comment]
I'm guessing that is a side-effect of me cancelling the click event (to avoid interactions with blocks and mobs when using a wand).

So probably there is nothing I can do about it, except maybe to report it as a but to Spigot?

**Comment by Ferocimo** [comment]
Okay I see, thank you for the explanation.
