### ISSUE TITLE
Suddenly stopped working [Minehut]

### ISSUE THREAD

**Issue by TotallyN0tASpy** [elBukkit/MagicPlugin#709]
The /plugins command says that the magic plugin is working, but the only thing that works is the command menu, everything else just stopped.

Trying to get any wands like /wand master just restate the command list, and the wand I had doesn't want to work.

For one thing I know is that the defaults.yml file wasn't downloaded when I added the plugin on the Minehut site, but I tried to copy the script from the GitHub page and see if that would help, but nothing I do seems to be working.

**Comment by NathanWolf** [comment]
Have you checked your server log for errors?

**Comment by TotallyN0tASpy** [comment]
I'll give it another try, and send you the error log.
I have to reinstall the plugin though.

**Comment by TotallyN0tASpy** [comment]
[https://hastebin.com/raw/ufoxeyolus](url)
Here, I must warn you it is a mess. I searched magic in the log and it's mentioned 269 times.

**Comment by TotallyN0tASpy** [comment]
Oh. I opened the server today and it is working again. I guess its fixed now.
Thanks for making a great plugin, this plugin makes my DND style server perfect.

**Comment by NathanWolf** [comment]
Sorry I couldn't figure anything ou there, but I guess I'm glad it started working again!
