### ISSUE TITLE
Please, ... I need some help here,,

### ISSUE THREAD

**Issue by Zegiond** [elBukkit/MagicPlugin#71]
I have my own RPG server with custom Spells e.t.c.. I used another plugin called More Items , but when i saw this one... I wanted to add it like crazy...so do I, but the problem is , any command i do, for example /mitem add  and any other command the site says, it just keeps showing the list of the commands... please help me, and if needed i can pay you to help me..Thx.. (Just to know, what i want is to make some items with custom powers, not Full mage system, you know, basic stuff, hold the item, right click to cast the spell , with cooldown e.t.c.. what i really liked was the ''Power'' or ''Spells'' this plugin has... tell me if thats possible to do...)

**Comment by NathanWolf** [comment]
That sounds like the plugin is failing to load, or you have an old version.

Please check your server logs for errors from Magic, and let me know the specific version of Magic and Spigot you're using.

**Comment by NathanWolf** [comment]
Any updates here?
