### ISSUE TITLE
Spells no longer work on people in creative mode

### ISSUE THREAD

**Issue by Aresiel** [elBukkit/MagicPlugin#710]
Ever since I updated spells dont work on people in creative mode.

**Comment by NathanWolf** [comment]
From the changelog in 7.9.4:
```
 - Spells will only target survival and adventure mode players. This can be controlled with the target_game_modes parameter.
```

This plugin does not support creative mode.

If you want to change this behavior, put this in plugins/Magic/spells.yml
```
default:
  parameters:
    target_game_modes: creative,survival,adventure
```

**Comment by Aresiel** [comment]
I must've missed that changelog, thanks!
