### ISSUE TITLE
Shops not giving items

### ISSUE THREAD

**Issue by Curtis73** [elBukkit/MagicPlugin#711]
Hey, there appears to be a problem on Magic 7.9.9 where items purchased via spells inheriting buyshop don't go into your inventory - it takes the cost, but the item is never handed out.
I've been able to reproduce it with the inbuilt Ollivander spell, though I'm not sure if any more are affected.

**Comment by NathanWolf** [comment]
Yikes! Thanks for pointing that out. That was an embarassingly bad refactor mistake. I just released 7.9.10 as a hotfix.

**Comment by Curtis73** [comment]
No worries haha - happens to the best of us!
Thanks once again for the speedy fix :)
