### ISSUE TITLE
Sandbox "magic register" permissions aren't working

### ISSUE THREAD

**Issue by Aresiel** [elBukkit/MagicPlugin#712]
The /magic register command also tells me I don't have permission.

**Comment by NathanWolf** [comment]
Thanks for the head's up on the Discord link, that's fixed now.

Not sure what happened with the permissions, though. I'll take a look when I can.

**Comment by NathanWolf** [comment]
Oh I'm guessing you are the one from Discord that got dumped into survival when the sandbox was dead?

Sandbox is back up, the register command seems fine but I'd like to figure out why Bungee has fallback like that when it shouldn't.

**Comment by Aresiel** [comment]
I am Aresiel#0666 in the discord, and alright.
