### ISSUE TITLE
EntitySelect action not displaying latest mobs

### ISSUE THREAD

**Issue by Ferocimo** [elBukkit/MagicPlugin#713]
Hello,

In the spell "airstrike", the EntitySelect action is not displaying the heads of latest mobs, such as llamas or bees.

Thank you for looking into this.

**Comment by NathanWolf** [comment]
These only exist so long as Mojang continues to make MHF_* accounts for every mob. There has never been one for a horse, and I don't see one for a llama either. I'll add bee. You're of course welcome to copy the mob_skins list from the defaults in config.yml and add any missing ones in the meantime.

**Comment by Ferocimo** [comment]
Damn. Is there a way to add a custom head for certain types of entities ? Because I could probably find all I need on Minecraft player heads website...

**Comment by NathanWolf** [comment]
Yeah you can copy this to your `plugins/Magic/config` folder and modify it:

https://github.com/elBukkit/MagicPlugin/blob/4cde2d6d64efc39bd3649dd34fa87abacfcf22f9/Magic/src/main/resources/defaults/config/mob_skins.yml

They don't *have* to be MHF so you can use whatever user skins you find, so long as that user doesn't change their skin :)

**Comment by Ferocimo** [comment]
Is there a way to make this work like for the "icons" of spells, or with a value ? Because I would like to set them up using : 
https://minecraft-heads.com/custom-heads/animals/635-horse

But there is no player usernames on this website...

**Comment by NathanWolf** [comment]
Not currently, sorry. I'll leave this open to see if I can add support for that.

**Comment by Ferocimo** [comment]
Okay, please let me know if you do.

**Comment by NathanWolf** [comment]
This will (finally) be fixed in 8.1
You can now use texture URLs for mob skins, and I've added skins for all mobs.
