### ISSUE TITLE
Placing water-loggable blocks in Bubble spell makes water, even in Nether

### ISSUE THREAD

**Issue by nightstick24** [elBukkit/MagicPlugin#715]
Hey there, the 1.16.1 PaperMC server I'm playing on has the mod - absolutely love it - but I noticed that if you use the Bubble spell to make water, then place something that can be waterlogged in that water - like a slab - the water stays in that waterlogged block instead of disappearing like it normally does. When you then update the waterlogged block, like by breaking it, you've got a water source block. This can be used to get water sources in the Nether.

**Comment by NathanWolf** [comment]
Thank you! There will be a fix for this in the next release.
