### ISSUE TITLE
Cloak Spell Deletes Armour if You Die While Cloaked

### ISSUE THREAD

**Issue by nightstick24** [elBukkit/MagicPlugin#716]
Hey there, on the 1.16.1 PaperMC server I'm playing on I noticed that when you use the Cloak spell it removes all your armour in order to make you invisible, as it should, normally when the spell ends your armour is properly added back again, but if you die while your armour is removed due to the Cloak spell the armour doesn't drop, and recasting the spell doesn't add it back again.

**Comment by NathanWolf** [comment]
Thank you for this bug report, that was a good catch. I apologize that it took me so long to fix such a bad bug, but the current release should fix it.
