### ISSUE TITLE
Disarm Spell will steal Villagers' held items

### ISSUE THREAD

**Issue by nightstick24** [elBukkit/MagicPlugin#718]
Hey there, so if you hold an item a Villager wants to trade in your main hand they'll hold whatever they want to trade in their hands. Like if you've got an Armourer who wants to trade emeralds for Diamond Leggings, say, if you hold an Emerald they'll hold the Diamond Leggings. If there are more than one trade they cycle through each one.

If you hold the item in your main hand and your wand in your off-hand with the Disarm spell selected you can right click the Villager to steal whatever they've got in their hand. So in the previous example you'd have an Emerald in your main hand and your wand on Disarm in your off-hand then you'd right click and the villager drops the Diamond Leggings.

It's probably not too big of an issue normally, but you can get some really powerful enchanted gear or books, and you only need one Emerald to be able to steal it, and they'll keep producing infinite items.

**Comment by NathanWolf** [comment]
Thanks- I will make that spell ignore villagers and wandering traders. You can grab the next dev build, or put this in your spells.yml:

```
disarm:
  parameters:
     ignore_types: villager,wandering_trader
```
