### ISSUE TITLE
Ocarina of the plugin

### ISSUE THREAD

**Issue by Elsopeen** [elBukkit/MagicPlugin#72]
Hello,
I recently found the ocarina you've created, with the different notes of the Ocarina, but I wonder the features its contains, because my server have also some TLZ worlds and grade, so that can be fun to have a working Ocarina to play as a Hero of Hyrule.
Hoping you'll answer soon,  (and that the ocarina can do something)
Best regards,
Elsopeen

**Comment by NathanWolf** [comment]
The Ocarina does nothing but play music. I've got no plans to change that any time soon, it would invoke making a complex spell combo system. Sorry!
