### ISSUE TITLE
Attributes only affect after reload

### ISSUE THREAD

**Issue by PhvntxmX** [elBukkit/MagicPlugin#722]
When I use spell 'attributeselector', the attributes changes my max health, movement speed etc. only after I enter the command /magic reload. Also if you wear an armor with attributes, it affects after reload. Holding a wand doesn't adjust the attributes, even after reload.
But if I use command /mage attribute instead, my stats changes immediately

**Comment by PhvntxmX** [comment]
Can it be fixed or not?

**Comment by NathanWolf** [comment]
The RPG configs are very much a work in progress.

Yes, it will get fixed, but please have a bit of patience- I'll take a look when I can!

**Comment by NathanWolf** [comment]
Classes and modifiers will now reload attributes when changed (in current dev build)

Still seems to be a few issues, from Discord:

> attributeselector works well, but there is still a problem when I hold a wand/wear an armor
> Also when I hold a wand with attributes and use spell attributeselector it applies the wand attributes too

**Comment by NathanWolf** [comment]
This should be fixed in the latest dev build, sorry for the long delay!
