### ISSUE TITLE
PAPI Breaking Stuff Again

### ISSUE THREAD

**Issue by mercurialmusic** [elBukkit/MagicPlugin#724]
This is very new, just reporting in case you weren't aware yet: https://gist.github.com/mercurialmusic/db436c922b990158f429e1ac260e8962

**Comment by NathanWolf** [comment]
What version of PAPI is that from? 
Would be annoying if they changed the API.. seems like that'd break 100's of plugins, kind of hard to believe?

In the meantime if you want you can set `placeholder_api_enabled: false` in `plugins/Magic/config.yml` to disable PAPI integration.

**Comment by mercurialmusic** [comment]
They updated today: https://www.spigotmc.org/resources/placeholderapi.6245/update?update=351340

Very annoying, especially since it's not the first time even this year that they've done that. I just rolled back the PAPI version for now, because yeah, it's several plugins that aren't able to hook into it anymore.

**Comment by NathanWolf** [comment]
Ok, thanks for the link!

Looks like it's easy enough to switch, I didn't realize I was using an already-deprecated version of their API. Should be a dev build available shortly, but sounds like you'll need to wait on other plugins anyway.

**Comment by NathanWolf** [comment]
Not tested, but hopefully fixed: http://jenkins.elmakers.com/job/MagicPlugin/3112/

**Comment by mercurialmusic** [comment]
Thank you!
