### ISSUE TITLE
Unwanted teleports

### ISSUE THREAD

**Issue by Boris-Scharinger** [elBukkit/MagicPlugin#725]
Whenever we use a wand, we get teleported to a place close by.
Sorry for asking, but how would we determine what to change to get rid of this unwanted behavior...
Thanks, Boris & Nicklas

**Comment by NathanWolf** [comment]
I ... have no idea. That's definitely not something this plugin is doing, unless you're using the Blink spell.

Are your wands compasses or something? Any other plugin that might treat a wooden hoe as some kind of teleportation device?

**Comment by Boris-Scharinger** [comment]
Hi Nathan - thanks for responding. The behavior is that e.g. when Magic Missile casts a spell, it moves the player to where the target is. Drives us mad - is this some configuration we can change?
Happens after fresh installation of the mod - no mod related config file changed.
CraftBukkit: 1.15.2, mod version 7.9.10. 
I doubt other mods interfere as we have only sethomes, myDogs, DriveBackup and tpcommands installed.

**Comment by NathanWolf** [comment]
That is really definitely not this plugin- what does "tpcommands" do?

Try this while holding the wand:

`/wand configure icon stick`

This will change the wand to a stick, I'm wondering if whatever is doing this is acting on a wood hoe swing.

**Comment by NathanWolf** [comment]
Did you figure this out?

**Comment by Boris-Scharinger** [comment]
Hi Nathan - /wand configure icon stick        helped us to get rid of the effect, I don't fully understand why...but I think we'll fine. Thank you! Regards, Boris

**Comment by NathanWolf** [comment]
Then you've got some plugin that is treating a wooden hoe as some kind of teleport tool.

Good luck!
