### ISSUE TITLE
SP just being gained once.

### ISSUE THREAD

**Issue by monito55** [elBukkit/MagicPlugin#727]
I have an issue where whenever I cast a spell, reminder I just do survival in the server. I don't get any xp. Here's how it acts, whenever I log off and relog into the server, just and only the FIRST attacks of every spell renders any gain of SP, but none after those yields a gain. After a few minutes, 10-15 minuts, I would consistenly just get one SP. just once.

**Comment by NathanWolf** [comment]
This is by design, so players can not just spam-collect SP and rank all the way up in a day.

It is customizable, if you wish to reduce the cooldowns.

Info can be found on the wiki:

https://github.com/elBukkit/MagicPlugin/wiki/SpellPoints#sp-cooldowns
