### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by SauronMC** [elBukkit/MagicPlugin#73]
I don't know if this is the correct place, but I've been receiving an error while on Spigot 1.9, using Magic 6.0.2

28.03 07:41:03 [Server] ERROR Could not pass event PlayerInteractEvent to Magic v6.0.2
28.03 07:41:03 [Server] INFO org.bukkit.event.EventException
28.03 07:41:03 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-BT52_03_27.jar:git-Spigot-2038f4a-cac90f6]
28.03 07:41:03 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-BT52_03_27.jar:git-Spigot-2038f4a-cac90f6]
28.03 07:41:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-BT52_03_27.jar:git-Spigot-2038f4a-cac90f6]
28.03 07:41:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-BT52_03_27.jar:git-Spigot-2038f4a-cac90f6]
28.03 07:41:03 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-BT52_03_27.jar:git-Spigot-2038f4a-cac90f6]
28.03 07:41:03 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [spigot-BT52_03_27.jar:git-Spigot-2038f4a-cac90f6]
28.03 07:41:03 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [spigot-BT52_03_27.jar:git-Spigot-2038f4a-cac90f6]
28.03 07:41:03 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-BT52_03_27.jar:git-Spigot-2038f4a-cac90f6]
28.03 07:41:03 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-BT52_03_27.jar:git-Spigot-2038f4a-cac90f6]
28.03 07:41:03 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-BT52_03_27.jar:git-Spigot-2038f4a-cac90f6]
28.03 07:41:03 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
28.03 07:41:03 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
28.03 07:41:03 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-BT52_03_27.jar:git-Spigot-2038f4a-cac90f6]
28.03 07:41:03 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-BT52_03_27.jar:git-Spigot-2038f4a-cac90f6]
28.03 07:41:03 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-BT52_03_27.jar:git-Spigot-2038f4a-cac90f6]
28.03 07:41:03 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-BT52_03_27.jar:git-Spigot-2038f4a-cac90f6]
28.03 07:41:03 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-BT52_03_27.jar:git-Spigot-2038f4a-cac90f6]
28.03 07:41:03 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
28.03 07:41:03 [Server] INFO Caused by: java.lang.NullPointerException
28.03 07:41:03 [Server] INFO at com.elmakers.mine.bukkit.magic.listener.PlayerController.onPlayerInteract(PlayerController.java:347) ~[?:?]
28.03 07:41:03 [Server] INFO at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source) ~[?:?]
28.03 07:41:03 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
28.03 07:41:03 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
28.03 07:41:03 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-BT52_03_27.jar:git-Spigot-2038f4a-cac90f6]
28.03 07:41:03 [Server] INFO ... 17 more

Figured I should drop it here, if you need anything else, please ask. Have been using your plugin for a long time now and I'm still loving it the same, excellent work.

**Comment by NathanWolf** [comment]
Ok, thanks!

This particular error was a problem in 6.0.2, I thought it would only happen with right-clicking a block, though. So that doesn't seem like it'd be the whole issue.

If it's not a problem, could you try updating to Magic 6.0.7 and see if that's any better? You'll need to be on a recent Spigot build, but it's always good to keep updated there as well.

**Comment by SauronMC** [comment]
Didn't realise there was another version up already, haha. Thank you! I should check your spigot page more often instead of the craftbukkit one.
