### ISSUE TITLE
High peeks in timings

### ISSUE THREAD

**Issue by Volgeop** [elBukkit/MagicPlugin#731]
Hi, I was flying through my world, where is also MagicWorlds enabled and there were tps drops... I looked into my timings and there was higher value of magic there. Look too please, on the latest phase of graph. https://timings.aikar.co/?id=503a4ff64e474242b96f80addd0b2141

**Comment by NathanWolf** [comment]
If the world is pregenerated and you don't allow spells here, I don't know what is going on. Try spamming `/magic list` to see if there are any spell casts going on there you don't expect.

**Comment by Volgeop** [comment]
Seems solved, was due to Automatas 😅 Thanks
