### ISSUE TITLE
Magic Mob Spawners not working

### ISSUE THREAD

**Issue by mythguy1226** [elBukkit/MagicPlugin#733]
Hello, very recently out of nowhere my spawners for magic mobs suddenly stopped spawning mobs. In console, it gives a warning saying "Skipping entity with id minecraft:zombie". Is there anything that could be causing this to specifically happen? I would like to know what could be making it skip entities so that I can more easily fix the bug.

**Comment by NathanWolf** [comment]
Did you figure it out?
