### ISSUE TITLE
Error on join

### ISSUE THREAD

**Issue by Volgeop** [elBukkit/MagicPlugin#734]
Hi, sometimes I get this error on player's join.
https://pastebin.com/CY6vzy8E

**Comment by NathanWolf** [comment]
That can happen if your server crashed at some point in the past while that player was offline. I'll just make that an info-level message.

**Comment by NathanWolf** [comment]
It also may just mean your sql server wasn't responding at the time. Are you using MySQL or SQLite?

**Comment by NathanWolf** [comment]
But yes as long as the player's data loads properly (they would lose all their spells if not) it is a benign warning and I will remove it in the next build.

**Comment by Volgeop** [comment]
Mysql.

**Comment by NathanWolf** [comment]
Ok- well that message really just implies that the server was unavailable, which would be kind of bad. I'll also add some additional checks in my code to make sure we can re-establish the connection if it goes down.

Do you know if you have players losing their magic progress?

**Comment by Volgeop** [comment]
No, any reports about losing progress. But isn't it bad when server is unavailable? Shouldn't I change something too?

**Comment by NathanWolf** [comment]
Yeah it is probably bad if your MySQL server goes away and comes back. That wouldn't really be a config thing or anything I could help with though. If you have service logs or something else you can correlate to know when mysql restarts, that'd be good to look at- otherwise it may be just something specific to Magic, if nothing else is having this problem.

**Comment by Volgeop** [comment]
https://pastebin.com/CMRvzgc7 @NathanWolf Can you look into my log? I don't know exactly what to find. But I see it's aborting sometimes?

**Comment by NathanWolf** [comment]
All I can really see from that is something is timing out trying to connect to your mysql server. Debugging mysql is definitely out of the bounds of what I can support here for this plugin, unfortunately. If you are using a hosting provider it may be worth asking them for help!

**Comment by Volgeop** [comment]
Ok closing it for now, until something new appear.
