### ISSUE TITLE
Problems with the mobs | Bug

### ISSUE THREAD

**Issue by MrPhiliip** [elBukkit/MagicPlugin#735]
I don't know what happens, but mobs no longer appear.

**Comment by NathanWolf** [comment]
Which mobs? Like with spells? Or mmob command? Or... like... just in general?

**Comment by MrPhiliip** [comment]
Just in general,  idk wthat happ
The difficulty is in normal

**Comment by NathanWolf** [comment]
Magic does not do anything with mob spawns. Are you using the MagicWorlds plugin?

**Comment by NathanWolf** [comment]
Any updates?
