### ISSUE TITLE
AreaEffectCloud (DragonBall) lasts permanently

### ISSUE THREAD

**Issue by SauronMC** [elBukkit/MagicPlugin#74]
The Dragonball spell seems to last permanently after its (first)? use. (Version 6.0.8 Magic, one version behind latest spigot build)
It doesn't seem to generate any errors in console.
The radius of the particles will slowly keep increasing, thus creating lag.
Hopefully you can put out a fix for this soon enough, thanks!

**Comment by NathanWolf** [comment]
It does last a while, but I've never seen it stick around permanently.

That's actually just the vanilla dragon fireball behavior... I'll see if I have any control over the effect cloud it spawns, I'd really like it to be a lot shorter.. but I don't think it really lasts forever, does it?

**Comment by NathanWolf** [comment]
I just checked the NMS code, it's all hard-coded so I won't be able to control it, it seems.

It lasts for two minutes, which seems like a lot. The best I can really do is increase the cooldown of that spell to longer than 2 minutes, which I will do for next release.

**Comment by SauronMC** [comment]
Ah, that's a shame. I'm not experienced with coding, but would it perhaps be possible to summon a custom AreaOfEffect cloud once it hits the ground? I'm aware that through the summon command you can fully customise the AoEffect cloud (duration, radius, etc), but it probably isn't as easy within code. 
If not, the two minute cool down should suffice, although it does get quite laggy for me after thirty seconds. Thanks for the quick reply!

**Comment by NathanWolf** [comment]
Hm- do you see that same lag when actually fighting the dragon? The effect should be identical.

I do want to add support for using AreaEffectCloud directly, that'll probably be in the next release. At that point I may re-do the Dragon Ball spell- but unfortunately it doesn't look like there's a way to use the new dragon fireball projectile without also using the vanilla effects, so I may leave the spell as-is.

**Comment by SauronMC** [comment]
The lag appears to be gone both during the fight and in the over world, so I guess it was merely a coincidence. (There is however a drop of 20 FPS during its bigger stages, which will affect those who can't afford a good machine, but this is in the End also the case, so it shouldn't be a major issue)
Never would've thought that the dragon fireball actually lasted two minutes, seems pretty unusual, but that'd be an issue on Mojang's side.

Two minute cool down should keep lag at a minimum, sorry for the inconvenience. Wasn't aware that it behaved like it should. Thanks again!

**Comment by NathanWolf** [comment]
No problem, thanks for your concerns!
