### ISSUE TITLE
I don't know how to use the plugin 

### ISSUE THREAD

**Issue by Steel-Zika** [elBukkit/MagicPlugin#740]
The wiki is so confusing I have no idea how NPCs work or how I get spells or buy them please help.

Thanks in advance!

**Comment by NathanWolf** [comment]
The wiki is more for people trying to set up the plugin on their servers, it's not really meant to be a player tutorial. The server you're playing on should've had some sort of info about how everything works.

The basic idea is that you craft a wand, and then you right-click an enchant table with your wand to buy spells, check progress or customize your wand. Much of this costs "spell points" (SP) which you earn by casting spells.

That's really about it. All the finer points should be explained in-game. Let me know if you have any more specific questions.
