### ISSUE TITLE
Recall NPE

### ISSUE THREAD

**Issue by mercurialmusic** [elBukkit/MagicPlugin#741]
Sorry I keep breaking things. ;-;

This one's a weird one, players are saying Recall no longer works for them, but I'm able to cast it fine so it makes me think of permissions? But dunno. Tried both inside and outside residences and WorldGuard regions and no changes (LOVE that new Residence integration btw, thank you for that!).

Console spam here (repeated about 1000x): https://gist.github.com/mercurialmusic/6fc50343f3599e8d357f4065d90d7490

Spam only happens when normal players cast it, not when I cast it.

When I cast it I was getting just:
`[16:22:20 WARN]: [Magic] Invalid material specified for recall|4 icon_wand: wood_hoeAllow`
without any changes in the behavior so I added a modification for the default spell to remove that trailing "Allow" and it fixed it for me, still not for them.

Using Magic 7.10.2 Snapshot b3180 on git-Paper-185 (MC: 1.16.2). Was doing the same on the 7.10.1 release so I tried the build to see if something changed. Seems to have happened right around the 7.10.1 release.

**Comment by NathanWolf** [comment]
Haha don't worry, you're not breaking things- I'm breaking things, and you're bringing it my attention. Thank you!

I think I have both of these fixed in the latest dev build:

http://jenkins.elmakers.com/job/MagicPlugin/3181/

**Comment by mercurialmusic** [comment]
Yup! I'm told it's all good now. Thanks yet again!
