### ISSUE TITLE
Resource pack

### ISSUE THREAD

**Issue by SuperCrafter072** [elBukkit/MagicPlugin#743]
I need to have a link to the download of the resource pack not only  implemented in the server so my players could download it instead of loading it every single time

**Comment by NathanWolf** [comment]
Check your server logs, the RP link for your server version will be there. If you don't see it use `magic rpcheck` on the console.

**Comment by NathanWolf** [comment]
Also worth noting is that the latest builds have some new features that give you some choices as to how to serve your RP.

Players can choose how to get the rp with the `getrp` command, and use `getrp url` to get the URL if they want to download it themselves.
