### ISSUE TITLE
Resource pack buggy

### ISSUE THREAD

**Issue by TakeoRenka** [elBukkit/MagicPlugin#744]
So I'm running the latest version and I added the response pack the wands are all there but spells are still axes and normal hoes start as error textures and switch from different magic items

**Comment by NathanWolf** [comment]
You should not have to do anything to get the correct version if the resource pack. Are you getting it from the server or did you download a specific pack?

**Comment by TakeoRenka** [comment]
I'm the one running the server and items like wood hoes and golden swords have texture errors and spells have no added texture

**Comment by NathanWolf** [comment]
Sorry, what I meant by that was are you letting the server give you the resource pack?

If you have just installed Magic and not touched the configs nor have put a resource_pack link in server.properties, then the server should be giving you the correct resource pack.

If you have downloaded a resource pack and added it to your client manually, you may have downloaded the wrong version.

This sounds like a resource pack / MC version mis-match, or else you have have a bad zip. I have not seen anyone report similar issues so I don't *think* it is an issue with the hosted RP's themselves.

All of the questions I can think to ask:

1. Do you have your client set to receive the RP from the server?
2. Do you have any other RP's installed in your client?
3. Have you set `resource_pack` in server.properties (you should not)?
4. What URL do you see in your server logs when using `/magic rpcheck`?
5. What server version and Magic version are you using?

**Comment by TakeoRenka** [comment]
> Sorry, what I meant by that was are you letting the server give you the resource pack?
> 
> If you have just installed Magic and not touched the configs nor have put a resource_pack link in server.properties, then the server should be giving you the correct resource pack.
> 
> If you have downloaded a resource pack and added it to your client manually, you may have downloaded the wrong version.
> 
> This sounds like a resource pack / MC version mis-match, or else you have have a bad zip. I have not seen anyone report similar issues so I don't _think_ it is an issue with the hosted RP's themselves.
> 
> All of the questions I can think to ask:
> 
> 1. Do you have your client set to receive the RP from the server?
> 2. Do you have any other RP's installed in your client?
> 3. Have you set `resource_pack` in server.properties (you should not)?
> 4. What URL do you see in your server logs when using `/magic rpcheck`?
> 5. What server version and Magic version are you using?

1 I believe so especially since the wand textures are there
2 no this is the only one I'm using
3 no I've not touched the config yet
4 it gives no url it says "Recourse pack configured in server.properties, Magic not using RP from config.yml"
5 I'm running paper spigot 1.16.3 and the latest magic version as far as I know

**Comment by NathanWolf** [comment]
Please try removing the resource pack configs from your server.properties and restart the server.

**Comment by TakeoRenka** [comment]
Thank you so much that fixed it
