### ISSUE TITLE
Textures error

### ISSUE THREAD

**Issue by Desmords** [elBukkit/MagicPlugin#746]
When selecting a spell, players inventory reset their spells textures to a diamond axe. How can I fix this?

![image](https://user-images.githubusercontent.com/37225172/93688405-4d946800-face-11ea-932f-7050640dccb9.png)

![image](https://user-images.githubusercontent.com/37225172/93688414-63099200-face-11ea-9457-36843407e67a.png)

**Comment by NathanWolf** [comment]
Does this happen if you don’t have the other resource pack installed?

**Comment by Desmords** [comment]
Yep

**Comment by Desmords** [comment]
If the player has /op or *, spells is normal loaded

**Comment by NathanWolf** [comment]
Do you have a plugin that might be preventing players from having unbreakable items?

**Comment by Desmords** [comment]
Yep, this is the plugin Itemfixer. Ty :)

**Comment by NathanWolf** [comment]
Well that makes sense. Can you turn that feature off? All of the icons rely on items being unbreakable.

Otherwise if you are on 1.14+ you could make your own RP that does not rely on that (or wait for me to make one, which I plan to do, but not necessarily soon).

**Comment by Desmords** [comment]
> Can you turn that feature off?

Yes
