### ISSUE TITLE
Droppable Wands

### ISSUE THREAD

**Issue by johnclark96** [elBukkit/MagicPlugin#747]
I was wondering if it possible to have Wands be dropped by certain mobs like Mythic Mobs plugin as well as not having Wands bound to players specifically?

**Comment by NathanWolf** [comment]
You can change this in plugins/Magic/wands.yml to make the craftable wand droppable:

```
wand:
  bound: false
  undroppable: false
  unstashable: false
```

That will also make it un-bound so any other player can pick it up and use it, but keep in mind spells and mana are gained by the player, not the wand (unless you do some more config-tweaking)

MythicMob can not drop magic items, you'd have to use magic mobs for that.

For further help, please join our Discord- github is really more for bug reports.  https://discord.gg/Vk5nK5h
