### ISSUE TITLE
[Translation] Updated Spanish translation

### ISSUE THREAD

**Issue by ChrisTVH** [elBukkit/MagicPlugin#748]
This is a new update of the previous translation and I also made some corrections since while I was checking it I found some small errors
[messages.zip](https://github.com/elBukkit/MagicPlugin/files/5271853/messages.zip)

**Comment by NathanWolf** [comment]
Thank you! This will be in the next release.

In the future if you have more updates, since you have a Github account could you try making a PR? It's pretty easy to do, especially if you get the (free) GitHub app.

Thanks again!
