### ISSUE TITLE
Implement Builtin Kits

### ISSUE THREAD

**Issue by ZadronZSX** [elBukkit/MagicPlugin#763]
I jumped on the server and went through the tutorial with the villagers only to discover that the wand crafting recipe is not functional. Then I ventured out of the protection area and was mutilated several times by mobs. Shortly after, I fell in a hole next to a house in a protected area right outside the spawn exit with no way out. I was sitting there for a while, thinking about coming here wanting to learn magic, before a skeleton crept upon my prison, knocked its deadly arrow, and releases it into my shoulder. I cry out in pain just before the skeleton ends my suffering with a final shot to my heart.

**Comment by NathanWolf** [comment]
Well that's a sad story, I'm sorry about that.

Was this your first time joining?

The recipe recently changed, was it a stick and "magic heart" item?

**Comment by NathanWolf** [comment]
Ah broken starter kit :(

I've been thinking of adding starter kits to Magic so maybe I'll leave this ticket open until then.

**Comment by ZadronZSX** [comment]
New issue, the projectile spell breaks terrain in the spawn area.

**Comment by NathanWolf** [comment]
Yup :)

Spells are allowed to break blocks in my spawn area. You shouldn't be able to permanently break them though, by hand or otherwise.

This is done with the `allowed-spells: *` WorldGuard flag.

**Comment by ZadronZSX** [comment]
How do you get more Galleons (money) on the server? I don't have enough for the recall spell.

**Comment by NathanWolf** [comment]
You can sort of earn them by killing mobs and selling loot, but you also get it from the spellshop using all that SP I gave you :D

**Comment by NathanWolf** [comment]
Well we have builtin kits now ... guess I should use them on my dev server
