### ISSUE TITLE
Inventory doesn't restore.

### ISSUE THREAD

**Issue by k0ded** [elBukkit/MagicPlugin#764]
The player inventory doesn't restore if the server crashes with the spell selection open.

**Comment by NathanWolf** [comment]
This should be handled. There are two possibilities:

1. The last time the world saved before the server crashed, the player did not have their wand open. So no problem.
2. The last time the world saved the player *did* have their wand open.

The case #2 their survival inventory is saved to Magic's player data. This always happens at the same time as world save to make sure things are in sync.

When the player next joins that stored inventory will be put back. You will see a message like this in your logs when that happens

> [14:17:12] [Server thread/INFO]: [Magic] Restoring saved inventory for player NathanWolf - did the server not shut down properly?

So either something else weird is happening there that I can not reproduce, or you have other plugins interfering.

If this is a frequent problem for your server I'd suggest switching wands to chest mode to avoid the issue.

**Comment by NathanWolf** [comment]
Please let me know if this has continued to happen.
