### ISSUE TITLE
path creator

### ISSUE THREAD

**Issue by RakashTv** [elBukkit/MagicPlugin#771]
Hello
is it possible to ask for fairly simple instructions on creating paths (I'd like to implement my own paths entirely) and how it interacts with classes.

**Comment by NathanWolf** [comment]
Sure- I think at a minimum a path needs a `spells` list with spells on it.  Then in your class config you just put `path: yourpath`

If you want your class to be able to rank up, then you'd add another path and put `upgrade: secondpath` on the first path.

There's more you can do with paths, but if you can get this much working it's a good place to start. Once you get this set up you could be able to `/mage activate yourclass` then `/cast spellshop` and see all of the spells in your first path.

**Comment by NathanWolf** [comment]
Just FYI `/mconfig editor path mynewpath` now gives you a nice template to start with.
