### ISSUE TITLE
Problems With showing SP

### ISSUE THREAD

**Issue by iKezzaUK** [elBukkit/MagicPlugin#78]
Hi NAthan, I love your plugin on PotterWorldMC, So i decided to apply it to my own server, but I am already having problems. I watched your video on Bukkit Dev, and noticed on your XP Bar, it had a number above, which is your SP, but that isnt showing on my server. Also, when you right click, it brings up the wand menu instead of putting it in your hot bar, how do i configure it to put spells into hotbar instead of the menu?

**Comment by NathanWolf** [comment]
Firstly, get out of creative mode :)

SP will show up once you've earned some, you have to hit something with a spell.

**Comment by iKezzaUK** [comment]
Ok, then about the hot bar?

**Comment by NathanWolf** [comment]
Are you in creative mode?

**Comment by iKezzaUK** [comment]
Its working now, never thought it would be so simple! Thanks :) Do you have access to the Texture pack they use in the survival world on potterworld? If so, could i possibly have the link to it?

**Comment by NathanWolf** [comment]
It is private, but to be honest it's almost entirely the John Smith Legacy RP (google it) with the survival Magic RP copied on top :)

**Comment by iKezzaUK** [comment]
How do you copy it ontop?

**Comment by NathanWolf** [comment]
Unzip both, drag the magic one over the JS one, zip it back up... it should pretty much be that easy.

**Comment by iKezzaUK** [comment]
Ok Thank you :)

**Comment by iKezzaUK** [comment]
Hi Nathan, Me again.
Im having problems with the way you said to combine the texture pack. I have unzipped both, copied magic over into the JSL Folder, zipped it back up and placed it onto mediafire and copied the .zip link, and the only RP working is the MAgic, no JSL :/

**Comment by NathanWolf** [comment]
Do you want to give me the link? :) 

I can unzip and take a look- it sounds like something must've gone wrong there.

**Comment by iKezzaUK** [comment]
https://www.dropbox.com/s/tzhf00ricraqas4/JSLM.zip?dl=1 Thats one i have tried, only loads magic

**Comment by iKezzaUK** [comment]
https://www.dropbox.com/s/i9vv2yd8dbfl2hg/JSL%20%26%20Magic%20RP.zip?dl=0 HEre is the other
Neither Work

**Comment by NathanWolf** [comment]
I think you need to use command-line zip for this, not sure what you used but MC is not even recognizing it as a resource pack.

Here is what I do- if you're on Windows I can't help much:
```
zip -r -X ../Test.zip *
```

Execute that from the root folder of the RP and it should work. I tested this by unzipping and re-zipping the one you made.

Also, when testing you can just drop the zip file in your ~/minecraft/resourcepacks folder and see if it shows up. No need to upload it just to test!

**Comment by iKezzaUK** [comment]
command line zip? Root folder?

**Comment by NathanWolf** [comment]
Hm- if you don't know how to use the command-line, you may have to google for your answer. There's maybe a different zip program out there that'll work, but the zip you uploaded did not.

Assuming you're on windows, I think you can do WindowsKey+R, type "command" hit enter, then type
```
cd <the path to your resource pack folder>
zip -r -X ../Test.zip *
```

May or may not work.

**Comment by iKezzaUK** [comment]
It just opened winrar and JSLM

**Comment by iKezzaUK** [comment]
Im trying to zip it now uusing windows explorer instead

**Comment by iKezzaUK** [comment]
It didnt recognize that one either, could you try putting the two together (1.9) and send me the file if it works?

**Comment by iKezzaUK** [comment]
It worked! Needed to unzip it first on single player

**Comment by iKezzaUK** [comment]
I have tried the rp again, after it working on single player and it still wont load, only loads magic

**Comment by NathanWolf** [comment]
If it works in single player, it should definitely work in multiplayer.

Are you sure you have the right RP URL in your server.properties?

It actually shouldn't "only load magic" either way- it either works or it doesn't. So I'm guessing you haven't put your RP URL in and Magic is just loading the default one.

**Comment by iKezzaUK** [comment]
#Minecraft server properties
#Fri Apr 08 17:16:06 BST 2016
spawn-protection=16
max-tick-time=60000
query.port=28001
generator-settings=
force-gamemode=false
allow-nether=true
gamemode=0
broadcast-console-to-ops=true
enable-query=true
player-idle-timeout=0
difficulty=1
spawn-monsters=true
op-permission-level=4
announce-player-achievements=true
pvp=true
snooper-enabled=false
level-type=DEFAULT
hardcore=false
enable-command-block=false
max-players=16
network-compression-threshold=256
resource-pack-sha1=http://download2229.mediafire.com/cuzjsbihyisg/d8d1suzo2euxf4p/JSLM+try+2.zip
max-world-size=29999984
rcon.port=30001
server-port=25566
debug=false
texture-pack=http://download2229.mediafire.com/cuzjsbihyisg/d8d1suzo2euxf4p/JSLM+try+2.zip
server-ip=185.38.148.162
spawn-npcs=true
allow-flight=false
level-name=world
view-distance=7
resource-pack=
spawn-animals=true
white-list=false
rcon.password=vzFORovKOhPS
generate-structures=true
online-mode=true
max-build-height=256
level-seed=
use-native-transport=true
motd=A Minecraft Server
enable-rcon=false
   
Thats whats in my server.propeties

**Comment by iKezzaUK** [comment]
Does it have to be in resource pack?

**Comment by NathanWolf** [comment]
yes, resource-pack. texture-pack is a holdover from 1.7

**Comment by iKezzaUK** [comment]
Ok

**Comment by iKezzaUK** [comment]
Hi nathan, It still isnt working :( John Smith Legacy and Magic work by themselves, but not together :(
If its ok, could i link you my website which has JSL and Magic and my mixture of both (That doesnt work) and have a look? If you have the time, could you combine both and email me the mixture @ khodgson2001@gmail.com ? I would be extremely grateful if you could.

**Comment by iKezzaUK** [comment]
The website is http://squishycraft.nn.pe/
