### ISSUE TITLE
Support with attributselector GUI

### ISSUE THREAD

**Issue by sakimoe** [elBukkit/MagicPlugin#786]
Good night @NathanWolf 
I was testing the plugin using the RPG configuration, I don't know if I need to do something else, it is necessary to install another plugin or what happens, when I try to use the "/cast attributeselector" command the icons do not appear and when I click on one of the options menu (GUI) nothing happens, I check if my attributes were changed with "/mage attribute" but they remain the same.
Also when executing the command I get this in the console
![imagen](https://user-images.githubusercontent.com/52462240/99472945-41caf380-290f-11eb-8350-f22bdd4824d8.png)
and when using / cast class selector, I get this error
![imagen](https://user-images.githubusercontent.com/52462240/99473050-6b841a80-290f-11eb-9da6-65ad9fc4798d.png)

I am using minecraft 1.12.2, the plugin version is 7.3.7

**Comment by PhvntxmX** [comment]
Your plugin version is outdated, I think this is the problem

**Comment by sakimoe** [comment]
Hi @PhvntxmX , could it be that, there will be no problems if I download the version for 1.16 even though I am using version 1.12.2? sorry I'm too noob in this of the mc servers

**Comment by PhvntxmX** [comment]
I think it will work, since the latest version of the plugin supports 1.9.3 and further.

**Comment by sakimoe** [comment]
😮 ok thank you very much, I'll try it ^^

**Comment by sakimoe** [comment]
wow xd it was because of that, thanks a lot bro
