### ISSUE TITLE
Smoothing Spell

### ISSUE THREAD

**Issue by Elsopeen** [elBukkit/MagicPlugin#79]
Hello,
I write this to suggest a new kind of spell that would be like the smooth tool of World Edit. As Magic has already an integration with World Edit, I thought that adding that tool to sorcerers could be great. I don't know if it is possible, but I think that would be great, players doing terraforming quicker than manually.
I hope this spell could be created, 
Best regards, and good luck if you think you can create it,
Elsopeen

**Comment by NathanWolf** [comment]
Magic doesn't actually have WE integration anymore, but I agree this would be nice to have! I've wanted to do it for a while now.

**Comment by NathanWolf** [comment]
2 Years later, I think this is finally implemented as the "flatten" and "raise" spells.
