### ISSUE TITLE
problem death 8.0.2

### ISSUE THREAD

**Issue by Yukylyu** [elBukkit/MagicPlugin#791]
Hi in the version Magic 8.0.2 the wand is duplicate after the death with the plugin dead souls. 
In the version 8.0.1 i have not this problem... 

What has changed since with the new version if magic?  please

https://www.spigotmc.org/resources/dead-souls.69409/

**Comment by NathanWolf** [comment]
Sadly what changed is avoiding item dupe issues on death with other plugins (Graves, MagicArenas).

Please go back to 8.0.1, I'll try out dead souls and see if I can make everything work together nicely.

**Comment by NathanWolf** [comment]
I think I got this fixed, if you'd like to try out the latest stable dev build:

https://jenkins.elmakers.com/job/Magic-Stable/10/

It's a tricky thing to make the event priority work with all different plugins, hopefully this didn't just break something else :joy:

**Comment by Yukylyu** [comment]
It works the wand is not duplicate thank you very much

**Comment by NathanWolf** [comment]
Hey I wanted to let you know that I found another issue with DeadSouls - if you pick up your soul with your wand inventory open, your soul items can get lost.

I have fixed this in the latest Magic dev build, but you will also need the latest DeadSouls that just came out (1.6)

This will also add a player's lost souls to Recall level 2.
