### ISSUE TITLE
Cast spell in deatheater mob in potter example

### ISSUE THREAD

**Issue by agfaya** [elBukkit/MagicPlugin#792]
In the potter example deatheather.yml file there is a typo error in the spell vermillious that generates an error when a mob uses the spell. Currently the spell appears as **vermillios** but it should be **vermillious**.

[https://github.com/elBukkit/MagicPlugin/blob/9cc03f375ebe25ebdf2c03b4769ee011544a1857/Magic/src/main/resources/examples/potter/mobs/deatheater.yml#L14](url)

**Comment by NathanWolf** [comment]
It's vermilliOUS not vermilliOS(a) :joy:

Thanks, will fix for the next build.
