### ISSUE TITLE
Use a List of Fallback Cost Types in Selector

### ISSUE THREAD

**Issue by sakimoe** [elBukkit/MagicPlugin#793]
Hello I have been looking but I can not find where I can change the costs of the spell store, I am using the RPG configuration, I want the spells to cost money instead of emeralds, I already have Vault and Essentials installed for the economy, I do not know if I'm salting something or what's wrong

**Comment by NathanWolf** [comment]
If you have a Vault economy installed it should be used for shops.  Do you see this message in your logs?

> [Magic] Vault found, 'currency' cost types available

I don't think there really is a spellshop in the RPG configs though. None of the classes are setup with paths or spells or really anything. Those configs are not ready for use yet.

**Comment by sakimoe** [comment]
Hello, sorry for replying late, and thanks for replying, if that message appears
![imagen](https://user-images.githubusercontent.com/52462240/99863589-77b4e580-2b64-11eb-8505-0bdcb37d33f5.png)

I'm using the spellshop that comes with the plugin by default. It is something strange, because the other stores appear to me with currency, only the spell shop appears with emeralds

**Comment by sakimoe** [comment]
Adjunto imagenes de como aparece, en la primera esta la tienda de hechizos y en la segunda otra tienda, en este caso puse la spsellshop
![imagen](https://user-images.githubusercontent.com/52462240/99863632-bf3b7180-2b64-11eb-9a15-852fbb6184d1.png)
![imagen](https://user-images.githubusercontent.com/52462240/99863671-edb94c80-2b64-11eb-83b0-7c81d301ca38.png)

**Comment by NathanWolf** [comment]
Ah yeah ok it's just broken in the RPG configs. But really I don't understand how any spells are even showing up in that shop, and I really want to stress that these configs are not useable at all right now.

I think you should be able to "fix" the spellshop currency with `/mconfig configure spell spellshop parameters.cost_type currency`

**Comment by sakimoe** [comment]
Holy u are a god!! thank you very much, that worked

**Comment by NathanWolf** [comment]
You're welcome- I'll fix that in the future, the reason it's weird is that the RPG configs turn off SP, the spellshop defaults to SP but shop fall back to using items if their primary currency isn't available.

I'll have to change it to a list of fallbacks... anyway, just thinking out loud now. Glad you got fixed up- I'm curious to know what you do with those configs :)

**Comment by sakimoe** [comment]
I am attaching the settings folder in case you like to see them, I would appreciate it if you correct me or point out if I am doing something wrong 😆 
[Magic.zip](https://github.com/elBukkit/MagicPlugin/files/5579629/Magic.zip)

**Comment by NathanWolf** [comment]
I am not sure I'd be able to review all of your configs, sorry :( It takes a lot of time.

**Comment by NathanWolf** [comment]
I have to say though, I looked over some of them and I think you are really going in the right direction. A lot of what I'm seeing looks very much like how I wanted to style the builtin RPG examples. In fact, I almost don't want to look too closely at your configs for fear of wanting to copy what you've done.

If you ever have any more specific issues, please don't hesitate to ask!

**Comment by sakimoe** [comment]
Don't worry, I sent you the configurations so that you can use them as an idea or if you want to use any of the ones I made, I would be happy to know that it helps, thanks for developing this plugin 😄

**Comment by NathanWolf** [comment]
Thank you, I appreciate that! I will be focusing on the RPG configs for the 8.2 release so that could be really helpful :)

**Comment by sakimoe** [comment]
Something I have tried to do is make races have a utility, whether they have unique abilities or have attribute enhancements, such as someone from the elf race has a mana buff or mana regeneration, a dwarf has a improvement in the strength attribute or something similar, I suppose it is something you already had in mind to do, I'll be waiting for 8.2
