### ISSUE TITLE
Another Question

### ISSUE THREAD

**Issue by iKezzaUK** [elBukkit/MagicPlugin#80]
How do i allow non ops to make wands?

**Comment by NathanWolf** [comment]
If you mean players, generally you let them craft wands. If you mean like admins and such, see the wiki for permissions:

https://github.com/elBukkit/MagicPlugin/wiki/Permissions

Also, if you're not reporting a bug please use the discussion forum for general questions:

https://www.spigotmc.org/threads/magic.28645/
