### ISSUE TITLE
Able to use enchanted books on enchantable wands

### ISSUE THREAD

**Issue by NathanWolf** [elBukkit/MagicPlugin#801]
This would be nice for wizard armor, but I think will be hard because ItemEnchantedBook is not 1.9 API.

**Comment by starstreakdwb** [comment]
Ok so how about just being able to combine,with an anvil, the spells from the book to a wand,  or can we already do that if we turn off the item protection?

**Comment by NathanWolf** [comment]
You can do that if you `/mconfig configure config enable_combining true`. It is a *very* old feature that lets you combine wands on an anvil.

I don't really recommend this, though, it's very hard to control. Better to just make upgrade items or spell items that you drop on the wand.

This has nothing to do with this issue, though, which is about vanilla enchanted books.

**Comment by starstreakdwb** [comment]
i thought it was an issue getting the enchanted book to combine with something.  or are you trying to directly place a wand effect on some armor and not need to hold the wand?

**Comment by NathanWolf** [comment]
The issue here is an enchanted book combining with an enchantable wand item, applying vanilla enchantments.

So nothing to do with spells at all.

This has actually been working for a while in the dev builds, but I keep the issue open until it makes it into an official release.
