### ISSUE TITLE
Keep Inventory Wand Dupe

### ISSUE THREAD

**Issue by Yukylyu** [elBukkit/MagicPlugin#802]
Hi (#791) dupe wand again 

i have the same problem with CMI and keep inventory the wand is duplicate when the player death :(

**Comment by NathanWolf** [comment]
Is this a CMI issue or do you just have the keep-inventory gameRule on?

(If it's the latter, it will be fixed in the next dev build)

**Comment by Yukylyu** [comment]
no it's cmi permission ^^' (i use this for my donjons)

**Comment by Yukylyu** [comment]
i have tested the devbuild  #3377 it's same :x

**Comment by NathanWolf** [comment]
:(
Unfortunately it's very hard to know what's going on there, I don't have the plugin and it is closed-source. I would think CMI is just setting the "keep inventory" flag on the death event, but if they're doing something weirder then it's really hard to diagnose.

I've got one more thing I can try if you're up for testing another dev build.

**Comment by Yukylyu** [comment]
thank you for your answer  yes i can test

**Comment by NathanWolf** [comment]
Thanks, if you're up for it please try this one: 

https://jenkins.elmakers.com/job/MagicPlugin/3378/

**Comment by Yukylyu** [comment]
you are amazing  ! it's works thank you very much
