### ISSUE TITLE
duplication issue

### ISSUE THREAD

**Issue by ibbotsoz** [elBukkit/MagicPlugin#803]
when killing another player using wand on occasions they will drop their inventory although keepinv is set to on. but when they respawn they will have all of their inventory and the player who uses the wand also gets the inventory which is dropped so all the items are duplicated.

player used fire spell on me. when i died they were able to pick up inventory and when i respawned i still had my inventory 
i used laser spell on a player when they died they dropped all their inventory which i was able to pick up, when they respawned they still had their inventory.
both were carried out while keep inventory was on

**Comment by NathanWolf** [comment]
Will be fixed in next dev build- thanks!
