### ISSUE TITLE
Potter Automatic Progression

### ISSUE THREAD

**Issue by valentijn123** [elBukkit/MagicPlugin#804]
Is there a way to add alohomora to the normal spellshop?

**Comment by NathanWolf** [comment]
Huh, github ate my comment :(

Alohomora is called "Admission" in the survival configs, it is available at Student.

**Comment by valentijn123** [comment]
No no no, i mean in the potter example if you want to granduete for year1 you need the spell alohomora but it is a exam spell can i turn this off and put alohomora in the normal year 1 shop?

**Comment by NathanWolf** [comment]
Oh - sure, `/mconfig editor path year1` and add it to the `spells` list, remove the `required_spells` section. You can do the same for year2 through year7.
