### ISSUE TITLE
Keep inventory dupe glitch

### ISSUE THREAD

**Issue by DrewDude05** [elBukkit/MagicPlugin#809]
Our server is an rp server so we keep keep inventory on for when we mess around, but when you get killed by magic it drops the items and keeps your inventory, is there anyway this can be fixed

**Comment by NathanWolf** [comment]
That sounds like something that got fixed a few versions back. What's the output of `/magic`?

**Comment by NathanWolf** [comment]
Were you able to check your plugin version or get updated?
