### ISSUE TITLE
Magic work problem

### ISSUE THREAD

**Issue by XaroNowicz** [elBukkit/MagicPlugin#81]
Hi! I have problem with this plugin on my server. Wands don't work as they should. I can't enchant them, right-click don't work, left-click work only if targeted. Some of spells and recipes don't work. It's seem like just half of plugin works.
I have server on bukkit,version 1.9, plugin's version 6.0.9.

**Comment by NathanWolf** [comment]
Please update to latest Spigot, or downgrade to Magic 6.0.4

**Comment by XaroNowicz** [comment]
I've downgraded to Magic 6.0.2 because i don't see 6.0.4 version. Left-click, spell inventory, recipes etc. are good. There is only one problem, i still can't enchant wands.

**Comment by NathanWolf** [comment]
Wands don't use vanilla enchanting anymore (unless you turn that back on in configs)

See here: https://github.com/elBukkit/MagicPlugin/wiki/Progression
