### ISSUE TITLE
"You're not trained to use that"

### ISSUE THREAD

**Issue by Desmords** [elBukkit/MagicPlugin#813]
I can't use many items. writes "you are not trained to use". How can I fix this?

![image](https://user-images.githubusercontent.com/37225172/101280628-3ca8e800-37db-11eb-9fd5-4a60b9f1939d.png)
![image](https://user-images.githubusercontent.com/37225172/101280632-3fa3d880-37db-11eb-91e0-29f94c237fa7.png)

**Comment by Desmords** [comment]
Can I unlock ALL classes with one command?

**Comment by Desmords** [comment]
![image](https://user-images.githubusercontent.com/37225172/101289736-67149880-380f-11eb-963f-c99c725b55ee.png)

**Comment by NathanWolf** [comment]
If you're trying to use the RPG configs, they are not really ready yet.

Otherwise I think that must be something you have configured? None of the other default configs should do that, except for lightsabers needing a jedi/sith choice and bending powers needing an element choice.

**Comment by NathanWolf** [comment]
Did you get this figured out? Were you trying to use the RPG configs?
