### ISSUE TITLE
Game Crashing because of resource pack

### ISSUE THREAD

**Issue by Xoduk** [elBukkit/MagicPlugin#818]
My game crashes every other time I try to load magic RP and crashes on disconnect as well, I don't know if others are having this problem, but it only does this on my server with magic and is fine on other servers with different RP...

**Comment by NathanWolf** [comment]
I’m afraid there’s nothing I can do about that. This is why the rp does not load by default, some computers just can’t handle it.

The plug-in should be usable without the RP. Sorry.

**Comment by NathanWolf** [comment]
Oh, but if you have not already tried it, use `/getrp lowres`, see if the low-res RP works better for you.

Unfortunately if it’s the wand models then there won’t be a fix, but if it’s the hi-res spell icons the lowres one may work better.

**Comment by Xoduk** [comment]
Ok thanks, all of a sudden after posting this the issue was resolved, but if it happens again I'll try the lowres version. Thanks for your help!
