### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by XaroNowicz** [elBukkit/MagicPlugin#82]
Hi, it's me again. I have problem, my players can't use their wands - "You do not have permission to have that!"(They can only use Wolf Wand) I have Accentials and PermissionsEX plugin. I gave them Magic.wand.use permission.

**Comment by NathanWolf** [comment]
Wolf wand require op or special permissions - it's not really meant for players! Why are you giving that one out?

**Comment by XaroNowicz** [comment]
I mean that was just test. I gave wolf wand my "Tester" player To test  un-op work. Still players can't use normal wands.

**Comment by NathanWolf** [comment]
Ah ok - well permission to use wands is default true - can they open the spell inventory but not cast spells? Do you have mcmmo or anything else that would prefer using a hoe?

**Comment by XaroNowicz** [comment]
I didnt try spell inventory, buy they can buy spells from enchant table. Yes, i have mcmmo but it doesnt work. I will delete that plugin and let you know for a while.

**Comment by XaroNowicz** [comment]
I've deleted mcmmo, still wands can' be used. Players can open spell inventory.

**Comment by NathanWolf** [comment]
Ok so wands are usable but spells won't cast? Have you tried something simple like Magic Missile? Some more complex spells can be blocked by build or PVP permissions.

Also check to make sure there are no errors in the logs.

Is the message "You don't have permission to cast that here"? Let me know the exact message please.

The other possibility is spell permissions but those are also given by default, as long as you have not negated them specifically.

**Comment by XaroNowicz** [comment]
Yes,spell won't cast, there is "You do not have permission to have that!"

From console:
> [CSRV] Changing working dir...
> [CSRV] Scanning for network conflicts... ['127.0.0.1:14030', '144.76.217.10:14030']
> [CSRV] Setting kernel resource limits
> [CSRV] Switching to unprivileged server user
> [CSRV] Executing Java...
> Loading libraries, please wait...
> [08:36:59 INFO]: Starting minecraft server version 1.9
> [08:36:59 INFO]: Loading properties
> [08:36:59 INFO]: Default game type: SURVIVAL
> [08:36:59 INFO]: Generating keypair
> [08:37:00 INFO]: Starting Minecraft server on 127.0.0.1:14030
> [08:37:00 INFO]: Using epoll channel type
> [08:37:00 INFO]: This server is running CraftBukkit version git-Bukkit-ab83272 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
> [08:37:00 INFO]: [Citizens] Loading Citizens v2.0.17-SNAPSHOT (build 1316)
> [08:37:00 INFO]: [WorldEdit] Loading WorldEdit v6.1;no_git_id
> [08:37:00 INFO]: [PermissionsEx] Loading PermissionsEx v1.23.4
> [08:37:00 WARN]: [PermissionsEx] This server is in offline mode. Unless this server is configured to integrate with a supported proxy (see http://dft.ba/-8ous), UUIDs *may not be stable*!
> [08:37:00 INFO]: [Accentials] Loading Accentials v3.1A
> [08:37:00 INFO]: [LoginSecurity] Loading LoginSecurity v2.0.14
> [08:37:00 INFO]: [WorldGuard] Loading WorldGuard v6.1
> [08:37:00 INFO]: [Sentry] Loading Sentry v1.9.0
> [08:37:00 INFO]: [Magic] Loading Magic v6.0.2
> [08:37:00 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
> [08:37:00 WARN]: The server will make no attempt to authenticate usernames. Beware.
> [08:37:00 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
> [08:37:00 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
> [08:37:00 INFO]: Preparing level "mapa"
> [08:37:01 INFO]: Preparing start region for level 0 (Seed: -3663045700561228268)
> [08:37:02 INFO]: Preparing spawn area: 0%
> [08:37:03 INFO]: Preparing spawn area: 65%
> [08:37:03 INFO]: Preparing start region for level 1 (Seed: -3663045700561228268)
> [08:37:04 INFO]: Preparing start region for level 2 (Seed: -3663045700561228268)
> [08:37:04 INFO]: [Citizens] Enabling Citizens v2.0.17-SNAPSHOT (build 1316)
> [08:37:04 INFO]: [Citizens] Unable to use economy handling. Has Vault been enabled?
> [08:37:04 INFO]: [WorldEdit] Enabling WorldEdit v6.1;no_git_id
> [08:37:04 INFO]: WEPIF: Using the Bukkit Permissions API.
> [08:37:05 WARN]: [WorldEdit] 
> **********************************************
> ** This WorldEdit version does not fully support your version of Bukkit.
> **
> ** When working with blocks or undoing, chests will be empty, signs
> ** will be blank, and so on. There will be no support for entity
> ** and biome-related functions.
> **
> ** Please see http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters
> **********************************************
> [08:37:05 INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.4
> [08:37:05 INFO]: [PermissionsEx] Initializing file backend
> [08:37:05 INFO]: [PermissionsEx] Permissions file successfully reloaded
> [08:37:05 INFO]: WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
> [08:37:05 INFO]: [Accentials] Enabling Accentials v3.1A
> [08:37:05 INFO]: ---
> Looking for a great host to host your great server?
> Look no further than Bisect Hosting!
>  
> http://bisecthosting.com
> ---
> [08:37:05 INFO]: Admin loaded!
> [08:37:05 INFO]: default loaded!
> [08:37:05 INFO]: Nekromanta loaded!
> [08:37:05 INFO]: Accentials error -> Unknown item STONE_SHOVEL in kit starter!
> [08:37:05 INFO]: loading ban
> [08:37:05 INFO]: loading ban
> [08:37:05 INFO]: [LoginSecurity] Enabling LoginSecurity v2.0.14
> [08:37:05 INFO]: [WorldGuard] Enabling WorldGuard v6.1
> [08:37:05 INFO]: [WorldGuard] (mapa) TNT ignition is blocked.
> [08:37:05 INFO]: [WorldGuard] (mapa) Lighters are blocked.
> [08:37:05 INFO]: [WorldGuard] (mapa) Lava fire is blocked.
> [08:37:05 INFO]: [WorldGuard] (mapa) All fire spread is disabled.
> [08:37:05 INFO]: [WorldGuard] Loaded configuration for world 'mapa'
> [08:37:05 INFO]: [WorldGuard] (mapa_nether) TNT ignition is blocked.
> [08:37:05 INFO]: [WorldGuard] (mapa_nether) Lighters are blocked.
> [08:37:05 INFO]: [WorldGuard] (mapa_nether) Lava fire is blocked.
> [08:37:05 INFO]: [WorldGuard] (mapa_nether) All fire spread is disabled.
> [08:37:05 INFO]: [WorldGuard] Loaded configuration for world 'mapa_nether'
> [08:37:05 INFO]: [WorldGuard] (mapa_the_end) TNT ignition is blocked.
> [08:37:05 INFO]: [WorldGuard] (mapa_the_end) Lighters are blocked.
> [08:37:05 INFO]: [WorldGuard] (mapa_the_end) Lava fire is blocked.
> [08:37:05 INFO]: [WorldGuard] (mapa_the_end) All fire spread is disabled.
> [08:37:05 INFO]: [WorldGuard] Loaded configuration for world 'mapa_the_end'
> [08:37:05 INFO]: [WorldGuard] Loading region data...
> [08:37:05 INFO]: [Sentry] Enabling Sentry v1.9.0
> [08:37:05 INFO]: [Sentry] Could not register with Denizen
> [08:37:05 INFO]: [Sentry] Could not find or register with Towny
> [08:37:05 INFO]: [Sentry] Could not find or register with Factions.
> [08:37:05 INFO]: [Sentry] Could not find or register with War. 
> [08:37:05 INFO]: [Sentry] Could not find or register with SimpleClans. 
> [08:37:05 INFO]: [Magic] Enabling Magic v6.0.2
> [08:37:05 INFO]: [Magic] EffectLib initialized
> [08:37:05 INFO]: [Magic] Loading config.yml
> [08:37:05 INFO]: [Magic] Based on defaults defaults/config.defaults.yml
> [08:37:05 INFO]: [Magic] Loading messages.yml
> [08:37:05 INFO]: [Magic] Based on defaults defaults/messages.defaults.yml
> [08:37:05 INFO]: [Magic] Loading materials.yml
> [08:37:05 INFO]: [Magic] Based on defaults defaults/materials.defaults.yml
> [08:37:05 INFO]: [Magic] Loading spells.yml
> [08:37:05 INFO]: [Magic] Based on defaults defaults/spells.defaults.yml
> [08:37:06 INFO]: [Magic] Loading enchanting.yml
> [08:37:06 INFO]: [Magic] Based on defaults defaults/enchanting.defaults.yml
> [08:37:06 INFO]: [Magic] Loading wands.yml
> [08:37:06 INFO]: [Magic] Based on defaults defaults/wands.defaults.yml
> [08:37:06 INFO]: [Magic] Loading crafting.yml
> [08:37:06 INFO]: [Magic] Based on defaults defaults/crafting.defaults.yml
> [08:37:06 INFO]: [Magic] Loading mobs.yml
> [08:37:06 INFO]: [Magic] Based on defaults defaults/mobs.defaults.yml
> [08:37:06 INFO]: [Magic] Wand enchanting is enabled
> [08:37:06 INFO]: [Magic] Wand crafting is enabled
> [08:37:06 INFO]: [Magic] Wand anvil organizing is enabled
> [08:37:06 INFO]: [Magic] Skin-based custom icons enabled
> [08:37:06 WARN]: [Magic] Unknown effect type explosion_huge
> [08:37:06 INFO]: [Magic] Loaded 355 spells
> [08:37:07 INFO]: [Magic] Loaded 14 enchanting paths
> [08:37:07 INFO]: [Magic] Loaded 104 wands
> [08:37:07 INFO]: [Magic] Loaded 14 crafting recipes
> [08:37:07 INFO]: [Magic] Loaded 7 mob templates
> [08:37:07 INFO]: [Magic] BlockPhysics not found- install BlockPhysics for physics-based block effects
> [08:37:07 INFO]: [Magic] LibsDisguises not found
> [08:37:07 INFO]: [Magic] Vault not found, virtual economy unavailable
> [08:37:07 INFO]: [Magic] dtlTraders not found, will not integrate.
> [08:37:07 INFO]: [Magic] Factions not found, will not integrate.
> [08:37:07 INFO]: [Magic] WorldGuard found, will respect build permissions for construction spells
> [08:37:07 INFO]: [Magic] Towny not found, region protection and pvp checks will not be used.
> [08:37:07 INFO]: [Magic] Lockette not found, will not integrate.
> [08:37:07 INFO]: [Magic] GriefPrevention not found, claim protection will not be used.
> [08:37:07 INFO]: [Magic] NoCheatPlus integration disabled, enable this in config.yml if you find Magic triggering NCP violations
> [08:37:07 INFO]: [Magic] dynmap not found, not integrating.
> [08:37:07 INFO]: [Magic] Activated MCStats
> [08:37:07 INFO]: [Magic] Adding crafting recipe for wizardhelmet
> [08:37:07 INFO]: [Magic] Adding crafting recipe for apprenticehelmet
> [08:37:07 INFO]: [Magic] Adding crafting recipe for divinghelmet
> [08:37:07 INFO]: [Magic] Adding crafting recipe for wizardchestplate
> [08:37:07 INFO]: [Magic] Adding crafting recipe for apprenticechestplate
> [08:37:07 INFO]: [Magic] Disabled default crafting recipe for GOLD_SWORD
> [08:37:07 INFO]: [Magic] Adding crafting recipe for battle
> [08:37:07 INFO]: [Magic] Disabled default crafting recipe for WOOD_HOE
> [08:37:07 INFO]: [Magic] Adding crafting recipe for default
> [08:37:07 INFO]: [Magic] Adding crafting recipe for broomstick
> [08:37:07 INFO]: [Magic] Adding crafting recipe for goggles
> [08:37:07 INFO]: [Magic] Adding crafting recipe for magichat
> [08:37:07 INFO]: [Magic] Adding crafting recipe for wizardleggings
> [08:37:07 INFO]: [Magic] Adding crafting recipe for apprenticeleggings
> [08:37:07 INFO]: [Magic] Adding crafting recipe for wizardboots
> [08:37:07 INFO]: [Magic] Adding crafting recipe for apprenticeboots
> [08:37:07 INFO]: No resource pack set, using default from Magic configuration
> [08:37:07 INFO]: Magic checking resource pack for updates: https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-RP-6.zip
> [08:37:07 INFO]: Server permissions file permissions.yml is empty, ignoring it
> [08:37:07 INFO]: Done (6.542s)! For help, type "help" or "?"
> [08:37:07 INFO]: Starting GS4 status listener
> [08:37:07 INFO]: Query running on 127.0.0.1:14030
>[08:44:04 WARN]: [Sentry] Could not register with Vault! the GROUP target will not function.
>[08:44:04 WARN]: [Sentry] Could not register with Vault! the GROUP target will not function.
>[08:44:04 INFO]: [Citizens] Loaded 8 NPCs.
>[08:44:04 INFO]: [Citizens] Loaded 8 NPCs.
>[08:44:04 INFO]: Resource pack hash set to 3e35e16893f4cd35bf7d8416efca8858, Padding resource pack hash to 40 chars
>[08:44:04 INFO]: Resource pack hash set to 3e35e16893f4cd35bf7d8416efca8858, Padding resource pack hash to 40 chars
>[08:44:06 INFO]: [Magic] Loading lost wand data
>[08:44:06 INFO]: [Magic] Loaded 0 lost wands
>[08:44:06 INFO]: [Magic] Loading automata data
>[08:44:06 INFO]: [Magic] Loaded 0 automata
>[08:44:06 INFO]: [Magic] Finished loading data.
>[08:44:06 INFO]: [Magic] Loading lost wand data
>[08:44:06 INFO]: [Magic] Loaded 0 lost wands
>[08:44:06 INFO]: [Magic] Loading automata data
>[08:44:06 INFO]: [Magic] Loaded 0 automata
>[08:44:06 INFO]: [Magic] Finished loading data.

**Comment by NathanWolf** [comment]
Hm- can you try this?

/pex user SomePlayer check Magic.cast.missile

Also do

/mage check SomePlayer

while that player is holding a wand with a spell they can't cast

Both of those will give us clues, at the moment unless you've negated casting permissions I really can't think of what's going wrong here.

**Comment by XaroNowicz** [comment]
/pex user SomePlayer check Magic.cast.missile:
Permission "null" has not been set for "Player "d0da6d1e-64dd-3fdc-bf9c-9c3a77d4493b/XarTest

/mage check SomePlayer:
[07:25:50 INFO]: Permission check for XarTest
[07:25:50 INFO]: id d0da6d1e-64dd-3fdc-bf9c-9c3a77d4493b
[07:25:50 INFO]: at 92 78 265 mapa
[07:25:50 INFO]: Has bypass: false
[07:25:50 INFO]: Has PVP bypass: false
[07:25:50 INFO]: Has Build bypass: false
[07:25:50 INFO]: Has Break bypass: false
[07:25:50 INFO]: Can build: true
[07:25:50 INFO]: Can break: true
[07:25:50 INFO]: Can pvp: true
[07:25:50 INFO]: Is disguised: false
[07:25:50 INFO]: Has pnode Magic.cast.missile: true
[07:25:50 INFO]: Region override: none
[07:25:50 INFO]: Field override: none
[07:25:50 INFO]: Magic Missile is erase: true
[07:25:50 INFO]: Magic Missile requires build: false
[07:25:50 INFO]: Magic Missile requires break: false
[07:25:50 INFO]: Magic Missile requires pvp: false
[07:25:50 INFO]: Magic Missile allowed while disguised: false
[07:25:50 INFO]: Magic Missile has build: true
[07:25:50 INFO]: Magic Missile has break: true
[07:25:50 INFO]: Can cast Magic Missile: true

**Comment by NathanWolf** [comment]
Hrm- well it says you have permission to cast it .. so I'm kind of stumped.

What did you mean by this?

"They can only use Wolf Wand"

**Comment by XaroNowicz** [comment]
I mean they can cast spells with Wolf Wand.

**Comment by NathanWolf** [comment]
But not a normal wand?

That's extremely strange if so. Have you customized any Magic configs at all? What wand are you giving them, or are they crafting them?

**Comment by XaroNowicz** [comment]
Normal wand can't cast "You have no permissions to have that" (have?)
I changed something in config but i've reinstalled plugin. I tried /wanp XarTest default and crafted as XarTest, it's the same problem.

**Comment by NathanWolf** [comment]
It really says "have that"? If so that's not a message from Magic :\

**Comment by XaroNowicz** [comment]
Impossible, there isn't wooden hoe in other plugins. Can i change wooden hoe?

**Comment by NathanWolf** [comment]
Hm, well are you absolutely certain that's the message? Could you maybe screenshot it?

And yes you can everything, but changing wand icons would involve making your own resource pack if you're using Magic's RP.

**Comment by XaroNowicz** [comment]
http://scr.hu/6irf/yfotn

**Comment by NathanWolf** [comment]
That is not a Magic error message, sorry.

You sure you don't have mcmmo or anything like that?

**Comment by XaroNowicz** [comment]
Its really strange. I've deleted Magic and i haven't that message. I've installed Magic again and i have that message.

**Comment by NathanWolf** [comment]
Strange indeed- here are all of the messages in Magic that refer to permissions:

![Magic Permissions](http://i.imgur.com/NkCygMG.png)

Unless you've changed the messages yourself in plugins/Magic/messages.yml it's definitely not coming from Magic.

I am unfamiliar with Accentials. I know WorldGuard can block specific items, but I'm not certain that's the right message for WG either.

When exactly does that error happen? When they open their wand, or just hold it, or try to cast it?

Any chance you've got player skull items blocked or something?

**Comment by XaroNowicz** [comment]
I haven't blocked player skull items. Error happen when i left/right-click. I can open inventory wand. Accentials is the same plugin as Essentials but for MC1.9
I've done test, deleted all plugins. It's message from Accentials. Sorry for problems and thank you very much for your time to help me. Problem solved.
