### ISSUE TITLE
Can I make a spell that creates multiple friendleys that will attack what you attack

### ISSUE THREAD

**Issue by Pr0ximit** [elBukkit/MagicPlugin#822]
Im helping work on a server that will include Moves from anime like Jutsu from naruto and was wondering if you could make low durability clones of your self that will attack what you attack

**Comment by NathanWolf** [comment]
Not easily, but you could make them attack whatever you're targeting when you use the move. The builtin monster spell does that, basically- just replace the random mobs with disguised husks (or something).

Sorry for the late reply, I didn't see the notification for this issue at all.
