### ISSUE TITLE
Lightsaber recipes not working

### ISSUE THREAD

**Issue by Kevenin** [elBukkit/MagicPlugin#824]
Hi, love the plugin so far. The players on my server love it.
I was trying to set the star wars example and make it work, but there seems to be a problem with the lightsaber recipes.
When I load the config, only the blaster recipes work.

I added my config folder and pictures to help

Thanks

![image](https://user-images.githubusercontent.com/13238483/103188667-62d01e00-4897-11eb-9edd-7c1d93ee7d71.png)
![image](https://user-images.githubusercontent.com/13238483/103188710-898e5480-4897-11eb-9d46-32e1d5e0c4bc.png)
![image](https://user-images.githubusercontent.com/13238483/103188723-9d39bb00-4897-11eb-85c7-365f69045aba.png)

[Magic_config.zip](https://github.com/elBukkit/MagicPlugin/files/5745824/Magic_config.zip)

**Comment by NathanWolf** [comment]
Can you please let me know what `/magic` says?

**Comment by Kevenin** [comment]
![image](https://user-images.githubusercontent.com/13238483/103218006-efa2c800-48e7-11eb-8ab5-8655d9028d0c.png)

**Comment by NathanWolf** [comment]
Thank you! Sorry for the confusion, but I changed the recipes in 8.2, which is what the website shows.

If you can’t or don’t want to update, I think the recipe was the same except you need two more nether stars representing the saber blade.

**Comment by Kevenin** [comment]
No thats ok! didnt think there was a new version. Ill update it now. Thanks!
