### ISSUE TITLE
Issue with Brooms not working

### ISSUE THREAD

**Issue by red-renegade117** [elBukkit/MagicPlugin#828]
As the title says im having issues on my server with the Broomstick not actually functioning properly. Players can craft it, modify it, and get on it but it does nothing aside from that. It merely floats in place and rotates but doesn't actually move in any direction. Any help with this would be massively appreciated, I love the plugin so far.

**Comment by NathanWolf** [comment]
Make sure `armor-stands-tick` is set to true in your paper.yml

**Comment by red-renegade117** [comment]
Awesome that fixed it! Thank you so much, its immensely appreciated!
