### ISSUE TITLE
[Spell Parameter] Health cost

### ISSUE THREAD

**Issue by Elsopeen** [elBukkit/MagicPlugin#83]
Hello,
I would like to know if there is a way to make a spell cost some health to the caster, as blood magic that costs blood, and Thaumcraft magic which costs vis. If there isn't any current way to make that, could you please create one ? I find that more role play to have a couterpart at spellcasting.
Best regards,
Elsopeen

**Comment by NathanWolf** [comment]
I can add health cost. I've no idea what you mean by "vis" though.

**Comment by Elsopeen** [comment]
The vis is the magical unity of the mod "Thaumcraft" to cast spells, it's just like mana.
Thanks for the health parameters, because I think that players could use abusively the spell Kill, which should have a counterpart.
Best regards,
Elsopeen

**Comment by NathanWolf** [comment]
"health" option for casting costs added in latest dev build. It won't stop you from killing yourself by casting spells.

I also added hunger while I was in there.
