### ISSUE TITLE
Item duplication with fireball spell

### ISSUE THREAD

**Issue by Deadpan110** [elBukkit/MagicPlugin#830]
Version 8.2.1

Put your fave items/tools/diamonds into a chest and explode it with a fireball, the items fall on the ground and then the chest re-appears containing all the items.

Nice profit - but I have a feeling ...it is a -bit- OP :)

**Comment by NathanWolf** [comment]
Are you using any kind of protection plugin, or something specifically protecting, locking or otherwise dealing with chests or dropped items?

Normally the items from chests broken by spells do not drop, I suspect there is a plugin causing a compatibility issue. This has happened before with protection plugins before I added special cases to make them behave better.

**Comment by Deadpan110** [comment]
Hi,
 These are the plugins I am using:
 Plugins (20): Alchema, BlueMap, Brewery, ChestsPlusPlus, ClaimChunk, DeadChest, Essentials, ExplosionRegen, FastLeafDecay, GroupManager*, Magic, MoneyFromMobs, NoEndermanGrief*, PlayerHeads, RecycleLeather, SilkySpawnersLITE, Skript, Vault, WildLoaders, YetAnotherTreeFeller.
 
 ExplosionRegen may be the cause, I will hopefully test later on when there is no one on the server.

The default config is available here:
https://github.com/MicleBrick/ExplosionRegen/blob/master/src/main/resources/config.yml

I have changed the following to suit my needs:
`# Blocks blown up by these entities will not be affected by this plugin
ignored_entity_explosions:
 - PRIMED_TNT`

I am guessing the fireball spell uses an entity, is there anything I can add to this list (I am mainly using that plugin for creepers - (I am not too fussed about wither or anything else really).

Side Note: Everyone on my server is loving this plugin - keep up the great work 👍

**Comment by NathanWolf** [comment]
This would almost certainly be due to ExplosionRegen.

You can probably ditch that plugin and let magic handle it if you want, putting this in your `plugins/Magic/config.yml` will likely do something similar (not really knowing what that plugin does but assuming based on its name):

```
# Turn on auto-rollback for creeper explosions and TNT
auto_rollback_duration: 10000
auto_rollback_speed: 0.5
auto_rollback_explosions:
- creeper
- primed_tnt
```

**Comment by Deadpan110** [comment]
Auto rollback for creepers and no more fireball chest duplication!
Working perfectly - many thanks for your help.
