### ISSUE TITLE
Support with Magic & World Guard 

### ISSUE THREAD

**Issue by sakimoe** [elBukkit/MagicPlugin#831]
Hello, I would like to know how I can do so that users can use abilities that destroy or change blocks in protected areas with World Guard

**Comment by NathanWolf** [comment]
`/mconfig configure config region_manager_enabled false`

Will turn off the WorldGuard integration

**Comment by sakimoe** [comment]
thanks ^^ and also, is there a way to make the wands usable in MobArena?

**Comment by NathanWolf** [comment]
Sorry I missed your second question, but yes see here for info on setting up MobArena classes that have wands in them:

https://github.com/elBukkit/MagicPlugin/wiki/MobArena
