### ISSUE TITLE
How to use Avatar wand?

### ISSUE THREAD

**Issue by xximmy4evrxx** [elBukkit/MagicPlugin#833]
Howdy! I'm trying to figure out how to use the Avatar wand, and it says I haven't been trained to use it. Is there a command I can use to train myself, or is it not possible? Thanks!

**Comment by NathanWolf** [comment]
There honestly isn't really a clear path to getting to Avatar (legitimately) in those configs. But yes you can use the wand if you unlock the avatar class manually:

`/mage unlock avatar`
