### ISSUE TITLE
Fireball does not work properly for my server

### ISSUE THREAD

**Issue by BlackCatJrXIII** [elBukkit/MagicPlugin#835]
On my friend's server, we noticed that the Fireball spell does not gain any casting usage to level up, nor does it earn us any SP. We can cast it with no problem, and it repairs the blocks. It just doesn't seem to make any progress. Is there a specific config or other plugin that would cause this issue?

**Comment by NathanWolf** [comment]
That is a bug, unfortunately. It is fixed in the current dev builds but not yet released.

**Comment by BlackCatJrXIII** [comment]
Ah, I see... Thank you for letting me know. The response time is very appreciated 👍
