### ISSUE TITLE
I crate server with your plagin and i need help

### ISSUE THREAD

**Issue by y0y011111** [elBukkit/MagicPlugin#840]
I need to know how to crate the point for the magic spell more easy to collect
if you can help me you dont know how mach I appriciate this

**Comment by NathanWolf** [comment]
Try this:
`/mconfig configure spell earns_cooldown 60000`

That will change the SP cooldown to 1 minute (default is 15 minues)

**Comment by y0y011111** [comment]
tenk you


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
בלי
וירוסים. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_9182347133914682422_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

‫בתאריך יום א׳, 24 בינו׳ 2021 ב-19:16 מאת ‪Nathan Wolf‬‏ <‪
***@***.***‬‏>:‬
