### ISSUE TITLE
How to remove friends?

### ISSUE THREAD

**Issue by keydrynn** [elBukkit/MagicPlugin#842]
You can add friends with the Gather spell, but can u remove them?

**Comment by NathanWolf** [comment]
That'll be in the next version. It may or may not currently be in the latest dev build, implemented but not tested.

**Comment by NathanWolf** [comment]
You can now aim down and cast to remove friends, but I have also disabled gather since it's really been a pain to support. If you want to keep it, do `/mconfig enable spell gather`.
