### ISSUE TITLE
How i can modify other language?

### ISSUE THREAD

**Issue by Fluzyk** [elBukkit/MagicPlugin#843]
**Hi, i  want modify other language (Russian). How i can do this?**

**Comment by NathanWolf** [comment]
There are a few languages builtin, see here: https://github.com/elBukkit/MagicPlugin/wiki/Messages#built-in-localizations

If yours is not in the list you'd have to customize all of the text yourself.

**Comment by NathanWolf** [comment]
Hello, I just noticed you edited the question - the answer is similar though, that same link above has instructions for how to customize the messages, and links to the russian translation file so you can search for what you want to change. Let me know if you need help!
