### ISSUE TITLE
Updated Spanish translation

### ISSUE THREAD

**Issue by ChrisTVH** [elBukkit/MagicPlugin#847]
Notes:
=====

**I finished the new translation even though it had few additions in terms of messages I decided to improve and make some corrections and ordering a little**

[translation_to_Spanish.zip](https://github.com/elBukkit/MagicPlugin/files/5967723/translation_to_Spanish.zip)

**Comment by NathanWolf** [comment]
I got this integrated, it'll be in the next release. Thank you very much!

I had to fix up a few issues with the various wand instructions, I'm hoping I got it all straightened out.

**Comment by ChrisTVH** [comment]
Ok thanks
