### ISSUE TITLE
Keep items on death causes duplicates w/ plugin 'DeathControl'

### ISSUE THREAD

**Issue by jshacar** [elBukkit/MagicPlugin#85]
I've noticed that items like the wands and the master sword stay bound to the player on death. However I'm using this plugin that allows you to pay to automatically return all of your items back to you. This means Magic is keeping an item (i.e. a wand) and DeathControl makes it again.
The DeathControl plugin has a filter list and so far i have filtered out 'wooden hoe' and 'golden sword' so that theses items will not duplicate. However as I implement more of the custom items you have created (the diving helmet for instance) - these items are duping as well.

So I have two options - filter more of the custom items with DeathControl or see if there is a way in the Magic config to prevent items staying on the player upon death. What do you recommend?

Thank you very much for your time and this amazing plugin - its one of the best that has ever existed.

**Comment by NathanWolf** [comment]
I guess I would recommend turning off the "keep" feature of all but the most important wands- like if you can exclude the wood hoe and golden sword and turn it off on the rest that'd probably be best.

You do this in wands.yml, for instance:

```
divinghelmet:
  keep: false
```

Will turn it off for the diving helmet. This won't have any effect on existing items, though, so if you already have a bunch of them out in the world this may be a bigger problem!

**Comment by jshacar** [comment]
Ah, yes I see - I think that will work perfectly. Thanks!
