### ISSUE TITLE
[item creation] Day/Night Token

### ISSUE THREAD

**Issue by Elsopeen** [elBukkit/MagicPlugin#87]
Hello,
I tried to crate token for the day and night spells as the Respawn Token, but even with Minecraft numeric IDs, they don't want to be as a correct item. Here is the wands for the token:
daytoken:
  mode: cast
  active_spell: day
  icon: minecraft:clock
  indestructible: false
  locked: false
  uses: 5
  keep: true
  effect_color: 'FF0000'
  spells:
    - day
    
nighttoken:
  mode: cast
  active_spell: night
  icon: minecraft:clock
  indestructible: false
  locked: false
  uses: 5
  keep: true
  effect_color: 'FF0000'
  spells:
    - night

Here are the messages for these token:
wands:
  daytoken:
    name: Jeton de Jour
    description: Changez l'heure du jour
  nighttoken:
    name: Jeton de Nuit
    description: Changez l'heure du jour

And here are the recipes: (item 347 is minecraft clock)
daytoken:
  output: daytoken
  output_type: wand
  materials:
    g: gold_ingot
    r: redstone
    e: ender_pearl
    c: 347
  row_1: "egc"
  row_2: "grg"
  row_3: "cge"

nighttoken:
  output: nighttoken
  output_type: wand
  materials:
    g: gold_ingot
    r: redstone
    e: ender_pearl
    c: 347
  row_1: "cge"
  row_2: "grg"
  row_3: "egc"

The recipes do work, but without the clock only. And the wands token are still wood_hoe instead of the clock I want them to be. So if you could help me to fix that, I really can't figure what's wrong...
Hoping you could help me,
Best regards,
Elsopeen

**Comment by NathanWolf** [comment]
You need to use Bukkit material names, not minecraft item names.

**Comment by Elsopeen** [comment]
I found a list of Bukkit/Spigot materials and now the recipes works, but not fine anyway... When I do the command /wand daytoken/nighttoken, I obtain the correct item with the correct text, but when I use the craft, I obtain a wooden hoe, whatever the craft I do (between the day or night token), which cannot cast the spell, and doesn't have the correct description...

**Comment by NathanWolf** [comment]
Odd. If you don't get it working I'll try it out when I can - won't be today though.

**Comment by Elsopeen** [comment]
Thank you, and don't worry I don't need that quickly

**Comment by Elsopeen** [comment]
Hello,
It works now, I think that's because the server has reboot, but that's a bit annoying to have to reboot the server to try new items :/ But it doesn't matter, I can all the time ^^.
Thank you for the support (even if the problem wasn't real)
Best regards, 
Elsopeen
