### ISSUE TITLE
Admin wand glitches plugin

### ISSUE THREAD

**Issue by RextubeHD** [elBukkit/MagicPlugin#876]
I was looking through the wands and accidentally pressed enter on admin now I can’t change it get rid of it or use an enchantment table to fix the way to cast spells

**Comment by NathanWolf** [comment]
Use 

/mitem destroy

While holding it.

can you elaborate on what you mean by “glitching the plugin”? It shouldn’t really have had any effects on other wands, enchantment table, or really done anything other than giving you an item that’s difficult to get rid of.

**Comment by NathanWolf** [comment]
I'm going to assume you're all set here, I am curious to know exactly what was happening so please feel free to leave more info if you want.
