### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by LazyGon** [elBukkit/MagicPlugin#877]
I translated all message into Japanese and I publish it here now.
If this plugin use my Japanese translation by default, I will be happy :)

File is renamed from messages.yml to messages.txt to upload.
[messages.txt](https://github.com/elBukkit/MagicPlugin/files/6089360/messages.txt)

Since this plugin has too many translation, I could not test all message.
So some mistranslation may be found.

**Comment by NathanWolf** [comment]
Thank you again, we now have a builtin JP language option.
