### ISSUE TITLE
Remove mana&Sp

### ISSUE THREAD

**Issue by hch9510** [elBukkit/MagicPlugin#88]
Hello,I'm korean
I prepare an RPG server
My server will be buying skill and upgrade without enchanting
And Remove mana&Sp
I want only cooldown
But I can't this
I am bad at English
would you please help me?

**Comment by NathanWolf** [comment]
Turning off SP is easy, put this in plugins/Magic/config.yml:
```
sp_enabled: false
```
Turning off mana is a little harder. In wands.yml, you can do this to turn off wand mana:
```
wand:
  mana: 0
  mana_regeneration: 0
```

But you will also have to remove mana costs on all the spells you want to use! So in spells.yml you would do
```
missile:
  costs:
     mana: 0

fling:
  costs:
    mana: 0
```

It might end up being a lot of work, sorry!

**Comment by hch9510** [comment]
oh, thanks awnser

**Comment by hch9510** [comment]
plugins/Magic/defualts/config.defaults  < that?

**Comment by hch9510** [comment]
hmm... change wand.defaults,config.defaults,spells.defaults
but return them

**Comment by NathanWolf** [comment]
No, none of the defaults - just the files in plugins/Magic are editable.
