### ISSUE TITLE
Can't craft magic book nor wand

### ISSUE THREAD

**Issue by JakonSU** [elBukkit/MagicPlugin#880]
as in the title
![image](https://user-images.githubusercontent.com/50838200/111036659-9ba47b80-8420-11eb-8a2e-5e23919415e2.png)

**Comment by NathanWolf** [comment]
Magic version, spigot version? Any other info?

**Comment by JakonSU** [comment]
Magic-8.4.1
spigot 1.16.4-Ro.1-snapshot

**Comment by JakonSU** [comment]
and all the other recipies works

**Comment by NathanWolf** [comment]
I think there may be some issues on the latest dev builds, but afaik crafting is fine in 8.4.1 - especially if the other recipes are working (including recipes that use the magic heart?)

Do you have any other crafting plugins installed?

**Comment by JakonSU** [comment]
Mytrip and SurvivalInvisiframes

**Comment by JakonSU** [comment]
Ok, I tried some more and found out, that crafting magic heart works, but using recipes with magic heart doesn't work

**Comment by NathanWolf** [comment]
Ok thanks, that is narrowing it down to recipes using custom items then. My guess is some other plugin is interfering, but possibly not.

Two things you could try if you are up for it:

1. Use `/mage debug 200` then try to craft, see if the debug messages in chat say anything useful
2. Try the latest dev build, I have some changes to crafting permissions though I don't *think* anything was wrong like you're describing, it's maybe worth a shot: https://jenkins.elmakers.com/job/MagicPlugin/

**Comment by JakonSU** [comment]
Ok, so using dev build actually fixed the problem, thank you very much for the help

**Comment by NathanWolf** [comment]
Thank you for letting me know! I guess I should release that as a hot fix, though I wish I knew what was actually broken.
