### ISSUE TITLE
 losing items in the shulkers using blast

### ISSUE THREAD

**Issue by ringman210** [elBukkit/MagicPlugin#881]
I was using blast to see what it was doing and what happened happened

**Comment by NathanWolf** [comment]
items in contains should always come back after destroying it with Magic. If they do not, you may have some plugin incompatibility. Are you using any specific protection plugins?

I will add shulker boxes to the list of indestructible blocks anyway though.

**Comment by NathanWolf** [comment]
This was likely the same issue as #883 and is now fixed.
