### ISSUE TITLE
Using "Collapse" you can lose your items in the shulker.

### ISSUE THREAD

**Issue by Cozary** [elBukkit/MagicPlugin#883]
I have found that if you use "Collapse" on a Shulker that is on the ground it will lose the items that are inside, but if the shulker is on a wall, when it falls it has no items but when it returns to its original place keep the original items.

**Comment by NathanWolf** [comment]
I will take a look for the root case of this, but in the meantime shulker boxes will be indestructible in the next release. You can work around the problem for now by doing the same if you want.

use `/mconfig editor materials containers`
And add `shulker_boxes`, it should look like this:

```
containers:
- chest
- furnaces
- brewing_stand
- dispenser
- hopper
- dropper
- trapped_chest
- barrel
- shulker_boxes
```

**Comment by NathanWolf** [comment]
I found the root issue, which is that a falling block landing in place of a destroyed block will take its place, but when the destroyed block goes to undo it thinks the block that's there now is the right type, so it skipped undoing.

Unfortunately this meant also losing any tile entity data, such as inventory collections.

This was probably a cause of many mysterious and random-seeming undo glitches when blocks are thrown about and might land back on the same place where they (or a block of the same type) was originally.

So I'm glad to have it fixed, it'll be in the next release. Still keeping shulker boxes indestructible as a secondary safety though, that was already the case for all other contains so it was an oversight.

Thank you!
