### ISSUE TITLE
[MagicAPI] can't get spell with UTF-8 char like (é,è,à,etc)

### ISSUE THREAD

**Issue by Poulpinounette** [elBukkit/MagicPlugin#887]
i try get a spell named F_Percée with the API its not work-

**Comment by NathanWolf** [comment]
I seem to have missed a bunch of issues.. sorry

I don't know why this would be, though, I build with utf-8 encoding- does your plugin do the same?

**Comment by Poulpinounette** [comment]
> I seem to have missed a bunch of issues.. sorry
> 
> I don't know why this would be, though, I build with utf-8 encoding- does your plugin do the same?

No problem. 

Yep UTF-8, i think its maybe because some spell in config contains UTF8 char :/
(i have update spell with utf8 char btw. but i wanna tell you ^^...)

**Comment by NathanWolf** [comment]
Please let me know if this is still an issue for you and I will look more closely, I use UTF in my config files a lot now so I'm not sure what the problem would've been.
