### ISSUE TITLE
Spell was removed from Wand

### ISSUE THREAD

**Issue by ThreeSmallLemons** [elBukkit/MagicPlugin#889]
I learned Flare a while ago, and today while adding it to my hotbar it disappeared, and is no longer in my spellbook. There's even an empty spot where it usually was. How do I fix this?

**Comment by NathanWolf** [comment]
Try `/wand describe spell_inventory`, see if it's listed in a different slot. Chances are it just moved somewhere else.

If you really can't find it, you can give it back to yourself with `/mage add flare` but it's very unlikely it's really gone from your spell inventory so that may just tell you that you have it already.

**Comment by ThreeSmallLemons** [comment]
> Try `/wand describe spell_inventory`, see if it's listed in a different slot. Chances are it just moved somewhere else.
> 
> If you really can't find it, you can give it back to yourself with `/mage add flare` but it's very unlikely it's really gone from your spell inventory so that may just tell you that you have it already.

it shows in the description of the inventory, but the slot it's listed in is empty

**Comment by NathanWolf** [comment]
This is even after you've relogged or let go of and held your wand again?

Sounds super weird if so :(
Have you perhaps customized the flare spell, does it have an invalid icon now? (You could try `/mgive flare` as a test)

Is anyone else missing it?

**Comment by ThreeSmallLemons** [comment]
I have since recovered the flare spell through removing it from the spellbook and then gaining it again. However, im noticing that the bottom of my spellbook is completely empty even though `/wand describe spell_inventory` tells me that there are things there. i've tried organizing it but it doesn't look like i can hold more than 4 lines of spells at a time (im a student at this point)

**Comment by NathanWolf** [comment]
Oh... hm, thank you that's interesting information.

it sounds kind of like the spellbook inventory display has gotten confused with the wand inventory mode, and you have spells hidden in a hotbar :(

Can you please paste for me the exact output of the `magic` command? I'm wondering if this is a bug I recently added when I re-did hotbars .. if not it may be fixed already (I could hope!)

**Comment by ThreeSmallLemons** [comment]
I'm not sure what command you want me to paste, sorry

**Comment by ThreeSmallLemons** [comment]
it tells me that i know 38 spells, but it is only displaying 36

**Comment by NathanWolf** [comment]
Just the command “/magic” or “/version magic”, so it prints out the version number :)

I am thinking you’ve found a bug, but it may have been fixed already in a more recent version.

**Comment by ThreeSmallLemons** [comment]
Magic 8.4.2-3095c41

**Comment by NathanWolf** [comment]
Ok, sorry about the trouble!

I think I have this issue fixed in the latest dev build, if you are able to try it out: https://jenkins.elmakers.com/job/MagicPlugin/3653/artifact/Magic/target/Magic-8.5-SNAPSHOT.jar

**Comment by ThreeSmallLemons** [comment]
The server owner is having a bit of trouble installing that snapshot. Any tips?

**Comment by NathanWolf** [comment]
Make sure you delete the old one (Probably Magic-8.4.2.jar)
Otherwise I think there's not much that can go wrong, just drop that jar in your plugins folder and make sure there's no other Magic jar in there!

**Comment by ThreeSmallLemons** [comment]
we're running the server through minehut, so im not sure if we have access to the plugins folder

**Comment by NathanWolf** [comment]
Oh, darn, yeah I think you will need to wait for me to release 8.5 then :(

Sorry about that! 

In the meantime if you can switch to using a wand, it does not have this bug.

**Comment by ThreeSmallLemons** [comment]
The wand does have the bug, somehow. It only occurs on chest spell mode. cycle does give me all my spells, but inventory mode doesn't have enough space for all my spells

**Comment by NathanWolf** [comment]
Yes, sorry I meant inventory mode does not have the bug. Chest and skill mode (the spellbook) would have the issues.

Chest, skill and inventory mode all have multiple pages and can hold an unlimited number of spells. Click outside the spell inventory to change pages.

**Comment by ThreeSmallLemons** [comment]
that works. thanks so much!
