### ISSUE TITLE
Sorry, one more matter

### ISSUE THREAD

**Issue by hch9510** [elBukkit/MagicPlugin#89]
I fixes them, but they return continuously

**Comment by Elsopeen** [comment]
And what it the matter ? Because we cannot help you if you don't precise your problem

**Comment by NathanWolf** [comment]
He's trying to edit the default configs, hopefully my response helps - you have to edit the files in plugins/Magic (NOT /defaults)

**Comment by Elsopeen** [comment]
Ah, I used to that too the first times ^^ Now is the problem fixed @hch9510 ? Otherwise, if you want a wand without mana or cooldown, do /wand wolf (this one is so great, but needs to be op or have the magic.commands.wand.wolf to obtain it)
