### ISSUE TITLE
Textures and The Enchantment Tabel dosent work.

### ISSUE THREAD

**Issue by YoungDevient** [elBukkit/MagicPlugin#891]
So i saw this plugin on the Multicraft site of my server, so i went and put it on, restarted my server and wantetd to start.
But i quickly realised that the Heart of magic looked different, and i could't open the spell inventory with right click.
Just like on the Enchantment Table, there it would just show me the normal Enchanting "Menu".
I first tried to dissable the other plugins i installed, but that didnt help either?

Any suggestions on what i'm probably doing wrong here?

**Comment by NathanWolf** [comment]
For textures you will need the resource pack. Make sure you have them enabled in your MC client for your server, and make sure you do not have a resource pack set in server.properties. 

For the enchantment table I'm not sure I understand, you're saying just normal enchanting of vanilla items is not working?

**Comment by YoungDevient** [comment]
Sorry not good in English,
So i have textures of the starter wand without 3D Textures and the heart of Magic wich has basically just a cube icon.
Right clicking with said Starter wand dosent work either.
You should be able to right click on the Enchanting Table to open the window to buy spells, but it will just not work for my friends  and me.

**Comment by NathanWolf** [comment]
Do you have any other plugins that might be looking for enchant table clicks?

If something is interfering, you may have to add an NPC as a workaround. Try
```
/mnpc add spellshop
```
And see if you can right-click that NPC to buy spells.
