### ISSUE TITLE
Add Option To Disable Special Brushes

### ISSUE THREAD

**Issue by swim709** [elBukkit/MagicPlugin#893]
The replicate spell / brush allows the user to copy and paste areas that are protected by world guard / grief prevention.

**Comment by NathanWolf** [comment]
Copy from or copy to?

**Comment by swim709** [comment]
Copy from, though I haven't tested the other way around.

There are some builds around the map that are protected, and a user has been making copies of them. I am okay with them having engineering I would just prefer if protected areas couldn't be copied.

**Comment by NathanWolf** [comment]
Can ask why?

There's nothing to prevent them copying from protected areas, but if they have the blocks or materia to afford it I don't see why its a problem.

**Comment by swim709** [comment]
Phantom said that the problem was because the user was outside the protected region when casting. So I thought perhaps it would have stopped them if they were inside the region. That led me to think it was just a bug causing this.

It's just a preference though I suppose.

Is there a way to disable the replicate brush?

**Comment by NathanWolf** [comment]
No, there's just no care about where brushes source from, protection is about being able to build/break in a specific area.

There is no way to disable those brushes (for players that already have them), but I have made a note to add a way to disable them.

**Comment by swim709** [comment]
I understand! Though it is possible to disable specific spells inside protected regions using flags so I just thought there would be something similar for this.

Thanks for the info though, and thanks for adding the feature request  :)

**Comment by NathanWolf** [comment]
The current dev build has these options, you can do these commands if you want to disable the brushes:
```
/mconfig configure config replicate_brush_enabled false
/mconfig configure config clone_brush_enabled false
```

**Comment by NathanWolf** [comment]
I think these made it into 8.7, and definitely will be in 9.0
