### ISSUE TITLE
Block duplication with BlockBreak action [MAGIC 8.5.2]

### ISSUE THREAD

**Issue by alekso56** [elBukkit/MagicPlugin#894]
Any spell that uses block break action duplicates blocks that have more than 1 hit required if they are destroyed after second hit manually.

1) place 2 hit block (diamond block)
2) hit block with spell that uses blockbreak (magic missile) twice
3) break block with pickaxe
4) wait for block to reappear with 1 lower hit
5) break block with pickaxe again.
6) you now have 2 diamond blocks, but you started with 1.
repeat for infinite profit.

https://user-images.githubusercontent.com/676987/115977955-b66c2300-a57c-11eb-8c79-1a59dacec609.mp4

**Comment by NathanWolf** [comment]
I believe I fixed this a while back, I apologize for not updating this issue. Undoing cracked blocks now follows the same rules as full breaks, meaning it won't undo if you break it the rest of the way by hand.

Please re-open this issue if you still have problems on the latest stable release (8.7.1) or 9.0 dev builds.

**Comment by NathanWolf** [comment]
Oops, this was not fixed. It is *really* fixed now in the 9.1 release.
