### ISSUE TITLE
armor stand projectiles?

### ISSUE THREAD

**Issue by zacharyki102** [elBukkit/MagicPlugin#898]
I've noticed while playing this version that armor stand projectiles seem to be broken? the armor stand spawns and does animations as usual but it doesn't actually move or follow the projectile's movement path.
screenshot of the issue (note the movement particles have left without the armorstand)

![image](https://user-images.githubusercontent.com/43279927/117496232-bf79ce80-af44-11eb-886d-cb845d633765.png)

**Comment by zacharyki102** [comment]
oh right, I ran into the problem while making my own spell but I'm demonstrating this issue using the chop spell. if that helps

**Comment by NathanWolf** [comment]
Can you please try the latest dev build: https://jenkins.elmakers.com/job/MagicPlugin/3706/

**Comment by zacharyki102** [comment]
That worked thanks a bunch!

**Comment by NathanWolf** [comment]
Fix will be included in upcoming 9.0 release
