### ISSUE TITLE
Villagers are spawning on top of my NPCS with Citizens plugin

### ISSUE THREAD

**Issue by Skyeeeeeeeeee** [elBukkit/MagicPlugin#899]
![image](https://user-images.githubusercontent.com/84057039/117911539-d4cb6180-b292-11eb-83ee-3c43f1fe69bf.png)
I have citizens and magic installed and for some reason villagers keep spawning on all of my npcs and lags the server and I can only get rid of them if I get rid of them 1 by 1. Is there a way I can stop this from happening or is there a command or something I can do to get rid of all the villagers.

**Comment by NathanWolf** [comment]
Did you happen to use the `/mnpc import` command at some point?

Can you please try `/mnpc list` and see if there are any magic NPCs listed?

**Comment by Skyeeeeeeeeee** [comment]
> Did you happen to use the `/mnpc import` command at some point?
> 
> Can you please try `/mnpc list` and see if there are any magic NPCs listed?


I've never used that command. There are a lot of magic npcs listed. Also if I try restarting the server it still won't get rid of them.
![image](https://user-images.githubusercontent.com/84057039/117915528-4f4baf80-b29a-11eb-8653-8b7837eba2e3.png)

**Comment by NathanWolf** [comment]
I think someone must've used the command. It is meant for replacing Citizens, it converts all of your NPCs to Magic NPCs so you can switch over and remove Citizens.

The easiest way to clean this up is to shut down your server and delete `plugins/Magic/data/npcs.yml` then start back up.

Then make sure no one has permission to Magic commands that you can't keep track of.

**Comment by Skyeeeeeeeeee** [comment]
Ok, that worked! Thank you so much!!
