### ISSUE TITLE
Growth Spell

### ISSUE THREAD

**Issue by Elsopeen** [elBukkit/MagicPlugin#90]
Hello,
I had an idea about a new spell (I could try to create it myself, but I don't know if I would succeed), a growth spell, that could make grass grows on dirt, and flowers, trees, crops grow as we applied bone meal on it.
If you want some caracteristics for the default level of the spell, I think that 5 block of radius, 3 bone meal applied, and 250 Mana consumed would be great. It could fit into the Apprentice path and could cost 450 SP.
I hope you could create a such spell,
Best regards,
Elsopeen

**Comment by NathanWolf** [comment]
This sounds kind of doable, or like a version of Pollinate.. maybe Pollinate could just change dirt blocks to grass?

**Comment by Elsopeen** [comment]
That would be great, but it's more for the crops that I suggested the spell ^^
Both could be done, couldn't them ?
I wish you good luck for this,
Sincerely,
Elsopeen

**Comment by NathanWolf** [comment]
Over two years later.... this will be included in 7.5.1
