### ISSUE TITLE
! Incompatibility with Ultra Permissions !

### ISSUE THREAD

**Issue by Greazi-Times** [elBukkit/MagicPlugin#904]
Hi there,

I am 1 of the "bord members" of Tech's Plugin's aka Ultra Permissions (UPerms).

We have seen that you have noted Ultra Permissions as a plugin that doesn't work with Magic.
I am here to tell you that this is false and that Magic in fact works with Ultra Permissions. Magic has a permission that isn't stated anywhere there for that magic doesn't work with Ultra Permissions. Because it doesn't show / be read with Ultra Permisisons (It isn't correct inside the plugin.yml) 

How do I know this?
I have setup a server that had a problem with this after digging and digging I found out that 1 permission isn't stated correct and there for that Magic doesn't work.

I would like to ask if the incompatibility with Uperms can be removed from the wiki.

--
Kind regards,

Greazi

**Comment by NathanWolf** [comment]
I'll try to find who reported this and get some verification. I didn't test it myself.

What is the permission that is missing from plugin.yml?

**Comment by Greazi-Times** [comment]
> I'll try to find who reported this and get some verification. I didn't test it myself.
> 
> 
> 
> What is the permission that is missing from plugin.yml?

I am not sure i wil look for the permission

**Comment by NathanWolf** [comment]
I think the issue here is with how UltraPermissions handles permissions defined in plugins.yml

PowerRanks had the same issue.

Recent release of Magic work around the problem, please re-open this ticket if you're still having problems.

**Comment by Greazi-Times** [comment]
Uperms searches the plugin.yml for all permissions and adds them to the overview.
We also have a database holding a lot of permissions from public plugins.

I am going to check if all permissions inside the plugin.yml are inside the database and maybe that is the issue.

**Comment by NathanWolf** [comment]
Oh thank you- to be fair, I am unclear if the behavior that was a problem for me is "incorrect" or not. Specifically I was using this method:

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/permissions/Permissible.html#isPermissionSet(org.bukkit.permissions.Permission)

Which for most other GM's I've dealt with (LuckPerms, EssentialsGM) returns false unless the player actually has the permission set via the GM.

UltraPermissions and PowerRanks return true for that method if the player has the permission via plugin.yml

I believe that kind of sums it up.. but really the javadocs aren't clear on how any of it is *supposed* to work so maybe that's the correct behavior, but it does not seem to be the most common behavior.

**Comment by Greazi-Times** [comment]
So when you define a default state in the plugin.yml luckperms will allow it by default if you haven't set * to false.

Uperms gives an option to set all default permissions to false and allows you to specify what permissions he really has. And most of the people are going the wrong way on this point. (Developers and Uperms users)
They are not looking on what is required and there by mis 1 very important permission like what happend with Magic they have missed a permission in there plugin.yml and there by fooled everyone.

I am going to look at what is the problem in Uperms and what is causing it not to work. en especially see what permissions Uperms shows in comparencen to the plugin.yml.

As I said earlier Uperms should take all permissions from the plugin.yml and if our database has not all permissions it should show up from the plugin.yml
