### ISSUE TITLE
Duplication glitch for wands

### ISSUE THREAD

**Issue by RaizaTakimaru** [elBukkit/MagicPlugin#907]
Someone on my server found out that wands can be duplicated in the following way:
1) Put a wand in a container (barrel, blast furnace, enderchest);
2) Then, drop a spell onto the wand in the container to learn the spell;
3) You'll now have gained an extra wand in your first (available?) inventory slot!

This is with spells being learned by the class, not loaded into the wand, so I'm not 100% sure you'll get an exact copy of the wand (doesn't seem like it, just a new wand with the extra spell on top of all it already knows, but again, not sure).

https://user-images.githubusercontent.com/83662707/120854668-c44e9400-c57d-11eb-9630-7011946e498b.mp4

**Comment by NathanWolf** [comment]
Thank you for the report- I was able to reproduce this easily.

Fortunately I guess in the default setup players can't really get spell items so this hopefully isn't a *major* problem, but I'll certainly get it fixed before the next release.

**Comment by RaizaTakimaru** [comment]
Thank you very much! It probably isn't major as we've made spells be learned by finding books and other hints on crafting recipes to make the spell items, and learn spells that way. Doubt many have used a method like that, and greatly appreciate you fixing it!

**Comment by NathanWolf** [comment]
This is fixed in the latest dev build, and will be in the upcoming 9.0 release
