### ISSUE TITLE
Cooldown display for Cycle mode wands

### ISSUE THREAD

**Issue by Saphirrcr** [elBukkit/MagicPlugin#916]
I would like to display the cooldown of the spell currently selected. 
However I am using the mode "Cycle" and thus the spell icon is never shown to the player. 

Of course the cooldown is displayed as a warning message in the action bar when a player attempts to use a spell on cooldown, but what I want for the user is a "permanent" display, for example by having the wand a stack of items.

I saw a post about bossbars too, but could not find documentation about it. #819 
I suppose I could use Skript but it might be unsuitable for my use of Magic.

**Comment by NathanWolf** [comment]
I think the new hybrid wand mode may work for you, it has a cooldown display but requires the resource pack.

This is in the current dev builds and will be in Magic 10 if you are interested.
