### ISSUE TITLE
Update for 1.17

### ISSUE THREAD

**Issue by Crist4n** [elBukkit/MagicPlugin#917]
This plugin need to be updated to 1.17 Plz we really need it

**Comment by NathanWolf** [comment]
This is not something you need to open an issue for. It's being worked on, it involves re-writing literally thousands of lines of code. Please be patient.

**Comment by NathanWolf** [comment]
See here: https://github.com/elBukkit/MagicPlugin/releases/tag/9.0-ALPHA1

*very* experimental version, use with caution!

**Comment by Crist4n** [comment]
There is a problem with the release @NathanWolf 

Some of the spell are not working



![image](https://user-images.githubusercontent.com/55767296/122250480-fb9c3980-cec9-11eb-86b0-7d5d1ebaf194.png)

**Comment by NathanWolf** [comment]
Indeed :(

I think I need to re-write the Projectile action to not use reflection at all. Not entirely sure I can spawn projectiles at arbitrary locations without it though.. bleh.

**Comment by NathanWolf** [comment]
I think the current dev build is pretty stable now on 1.17. The only known issue is that NPCs can get duplicated, but it should clean itself up- the real fix will rely on Spigot fixes or additions, currently being discussed here: 

https://hub.spigotmc.org/jira/browse/SPIGOT-6547

I'm going to close this issue now, we can open more specific ones for further 1.17 problems.
