### ISSUE TITLE
Spell Bug | Mount

### ISSUE THREAD

**Issue by DanielTenebris** [elBukkit/MagicPlugin#92]
How delete spell "mount"? This spell crash my server. I use latest magic version and spigot 1.9. (latest version)

Please help or fix.(

**Comment by NathanWolf** [comment]
To disable any spell you need to add something like this spells.yml:
```
mount:
  enabled: false
```

Sorry that I somehow missed all of your bug reports, it seems like github notifications are very hit-or-miss for me :(

That said, mount shouldn't crash your server so I'm not sure what's up with that.
