### ISSUE TITLE
Lands Integration

### ISSUE THREAD

**Issue by dlong93** [elBukkit/MagicPlugin#925]
Would we be able to get integration with this plugin?
https://www.spigotmc.org/resources/lands-land-claim-plugin-grief-prevention-protection-gui-management-nations-wars-1-17-support.53313/

Would hope for it to abide by the rules set by land owners so that they can't cause destruction or hurt players or animals within their claims.

**Comment by NathanWolf** [comment]
Can you please first try this?

`/mconfig configure config generic_protection Lands`

That will use damage and break/build events to try to abide by the plugin's rules, so no code required on either side

If that doesn't work out (or spams the chat in a way you can't turn off) let me know!

**Comment by dlong93** [comment]
I ran that, I'll have one of my dev's test it out when he has a chance and let you know!

**Comment by NathanWolf** [comment]
If that did not work, please let me know and re-open this issue if you want.

**Comment by dlong93** [comment]
My apologies for not responding before! This did what we needed!
