### ISSUE TITLE
right click enchanting table

### ISSUE THREAD

**Issue by bobbyoshi** [elBukkit/MagicPlugin#929]
so ive seen the other issue in the past and have used /mconfig example add survival etc. and it fixed it. now im having the issue since updating to the latest update. i tried removing all examples and re adding them again. still no good, i have no plugins that modify the enchanting table in any way. which i saw on a different post that could cause this issue. so im stumped. i zipped the files and have a drive link posted with them. please help

https://drive.google.com/file/d/1i4aa7bOXYz8wF0X-ByKVtPKyqtliy1YN/view?usp=sharing

**Comment by bobbyoshi** [comment]
sorry i should add incase its not implied, right clicking enchanting table with any wand is not bringing up the spell/wand upgrade gui, it does work with the spell shop npc,

**Comment by NathanWolf** [comment]
You must have survival set as the main example for the enchant table to work.

Try `/mconfig example set survival automata engineering chests spawnmobs`

**Comment by bobbyoshi** [comment]
oh i used add not set >.<

**Comment by bobbyoshi** [comment]
ok so that did not work, i did notice on boot, i got this error i didnt notice before

WARN Failed to find mcore

**Comment by NathanWolf** [comment]
That's nothing to do with Magic, probably Factions (MassiveCore).

**Comment by bobbyoshi** [comment]
ah i see, ok. so its still not working for some reason

**Comment by bobbyoshi** [comment]
yes
![Screenshot (25)](https://user-images.githubusercontent.com/86074588/122829992-53151d80-d2ad-11eb-9444-830131c9c47b.png)

**Comment by bobbyoshi** [comment]
example: survival
examples:
- automata
- engineering
- chests
- spawnmobs
add_examples: []

**Comment by bobbyoshi** [comment]
this is from the file

**Comment by NathanWolf** [comment]
Thanks- that looks right.

I'm not sure if it's intentional but you have a file, `plugins/Magic/config/new_changeme.yml` with a *lot* of customizations in it. Not sure if that was intentional, but if there's nothing in there you need I would try deleting it next. (Then do `/magic load`)

**Comment by bobbyoshi** [comment]
ok that wont delete the customizations will it? we have modified and rebalanced alot to make classes balanced from each other, i absolutely love the plug in, ill be donating again lol.

**Comment by NathanWolf** [comment]
Hm- well it will get rid of certain customizations, but there's not much in there that looks like you actually meant to change it. Shouldn't have any class or other balance configs in it- maybe take a look through the file and see if there's anything in there you actually meant to change.

Not really sure how it got there, my guess is a mis-typed editor command.

If you're nervous about deleting it, search for `enchant_click` and delete everything around that area. This config file is turning off the enchant table:

```
# This controls what players will see when interacting with an enchantment table
# These spells must exit in your configuration for this to work, and "enchant_block" needs to be set.
# enchant_click: progressmenu
# enchant_sneak_click: spellshop
enchant_click: ""
enchant_sneak_click: ""
enchant_click_requires_wand: true

# This can be used to set up a progression system based on clicking an enchant table with your wand.
# enchant_block: enchantment_table
enchant_block: ""
```

**Comment by bobbyoshi** [comment]
ok so i just delete everything you have showing there?

**Comment by bobbyoshi** [comment]
and yea sorry, im a little nervous, spent a long time going over everything and rebalancing them lol

**Comment by bobbyoshi** [comment]
you guys have done such an amazing job with this, i really think this is one of the best plug in out there. you should team up with mojang >.>

**Comment by NathanWolf** [comment]
yeah just delete all that stuff- but really I think you're better off without that whole file! I'd suggest reading through it, if nothing looks familiar in there you can delete it. Save a backup just in case, of course.

**Comment by bobbyoshi** [comment]
ok yea ill save a back up and give it a go thanks for all the help

**Comment by bobbyoshi** [comment]
it worked!!!

again, yall are the best. and i only needed to delete that one part of the script

thanks for all the quick responses, will be giving more of my support =)

**Comment by NathanWolf** [comment]
Glad you got it working!

And you helped me narrow in on why this maybe keeps happening to people, you are not the only one to have reported it.

**Comment by bobbyoshi** [comment]
awesome! im glad this could help!.
