### ISSUE TITLE
magic damage not working for players

### ISSUE THREAD

**Issue by bobbyoshi** [elBukkit/MagicPlugin#930]
i cant seem to figure it out, but spells like missle, or arrow_light, or wave, are breaking blocks and doing the abilities, but not doing any damage to mobs or players, ive been looking forever to see if i can figure it out, but havent had any luck. do you know by chance what im missing?

**Comment by bobbyoshi** [comment]
example of a spell. all these spells were working before at one point and then stopped recently

laser:
    # This has been added automatically so that anything you remove here does not get inherited back in from the default configs
    inherit: false
    icon: bamboo{CustomModelData:18001}
    icon_disabled: bamboo{CustomModelData:18002}
    legacy_icon: spell_icon:145
    legacy_icon_disabled: spell_icon_disabled:145
    icon_url: http://textures.minecraft.net/texture/7cc8e096a2ac99bf264b3e827f1e3aa07ba688d7b4f470128f741132625e
    example_thumbnail: https://thumbs.gfycat.com/SnivelingDependentHuman-size_restricted.gif
    example_link: https://thumbs.gfycat.com/SnivelingDependentHuman
    category: demolition
    worth: 6500
    earns_sp: 20
    earns_cooldown: 10
    upgrade_required_path: Ranger
    upgrade_required_casts: 1500
    pvp_restricted: false
    actions:
        cast:
        - class: PlayEffects
          effect: beam
          ignore_result: true
        -  class: Line
           ignore_result: true
           actions:
           -  class: Disc
              actions:
              - class: CheckBlock
                actions:
                - class: BreakBlock
                - class: PlayEffects
                  effects: burn
                  ignore_result: true
        -  class: Repeat
           actions:
           - class: Delay
           - class: Retarget
             actions:
              - class: PlayEffects
                effect: beam
                ignore_result: true
              - class: Line
                ignore_result: true
                actions:
                -  class: Disc
                   actions:
                   - class: CheckBlock
                     actions:
                     - class: BreakBlock
                     - class: PlayEffects
                       effects: burn
                       ignore_result: true
              - class: ConeOfEffect
                actions:
                -  class: Damage
    effects:
        cast:
          - sound: entity_guardian_attack
            sound_pitch: 0.5
            sound_volume: 0.5
          - sound: magic.zap_crack
            location: origin
          - sound: block_beacon_activate
            sound_pitch: 0.8
            sound_volume: 0.4
          - sound: block_conduit_activate
            sound_pitch: 0.5
            sound_volume: 0.9
        beam:
        -  sound: entity_guardian_attack
           sound_pitch: 2
           sound_volume: 2
        -  sound: entity_guardian_attack
           sound_pitch: 1.5
           sound_volume: 1.6
           location: target
        -  class: EffectSingle
           sound: magic.zap
           location: origin
           sound_volume: 0.1
           color_override: color
           effectlib:
             class: LineEffect
             particle: redstone
             iterations: 2
             color: ff0000
             particle_offset_x: 0.05
             particle_offset_y: 0.05
             particle_offset_z: 0.05
        -  location: origin
           effectlib:
              class: LineEffect
              particle: redstone
              iterations: 2
              color: ff0000
        burn:
        - location: target
          particle: smoke_large
          particle_count: 4
          particle_offset_x: 0.1
          particle_offset_y: 0.1
          particle_offset_z: 0.1
          target_offset: 0.5,0.5,0.5
    parameters:
        target: other
        target_type: LivingEntity
        target_mob: true
        fov: 0.1
        close_range: 10
        close_fov: 0.4
        allow_max_range: true
        player_damage: 1
        entity_damage: 2
        target_count: 5
        damage: 2
        range: 46
        size: .5
        start_at_target: true
        increment_data: false
        check_destructible: true
        destructible: destructible
        destructible_durability: 100
        break_durability: 4
        undo: 20000
        transparent: all_air
        radius: 0
        cooldown: 10000
        delay: 100
        repeat: 12
        undo_speed: 1
        orient: true
        axis: z
    costs:
        mana: 120
        arrow: 3

**Comment by NathanWolf** [comment]
Strange, normally that'd be from some PvP issue- but they don't hurt mobs either?

Could you please try doing `/mage debug 20` to turn on debug logs in chat, try a simple spell like `wound` and see what it says?

**Comment by bobbyoshi** [comment]
![Screenshot (30)](https://user-images.githubusercontent.com/86074588/123895064-d9240a80-d924-11eb-84c9-c36047c3c6fc.png)

**Comment by bobbyoshi** [comment]
yea so it says it did damage, but it actually doesnt

**Comment by bobbyoshi** [comment]
im pretty stumped

**Comment by NathanWolf** [comment]
I'm stumped too- does it happen with Wound as well? That one does physical damage.. most spells use "magic" damage so if you had some plugin blocking thrown potions for some reason that might do it.

**Comment by NathanWolf** [comment]
To be clear, testing with Wound would help since if that one works then we know it's a problem with thrown potion damage specifically.

**Comment by bobbyoshi** [comment]
ok i will check with wound here in a bit, sorry was at work today.

**Comment by bobbyoshi** [comment]
ok so wound does do damage. when used, 
![Screenshot (32)](https://user-images.githubusercontent.com/86074588/124035082-aa0fa680-d9c1-11eb-8b31-ec5ff5b31a16.png)

**Comment by NathanWolf** [comment]
Ah ok well that's *interesting* news at least!

I can think of two possibilities then

1. Something on your server is blocking thrown potions- try a splash potion of harm, just vanilla, throw it at something? Could be anti-cheat or some kind of protection / pvp plugin maybe?

2. Maybe anti-cheat blocking damaging from a distance? Does magic missile work at very short range?

Another approach to take is, was this working at some point in the past? What changed between then and now? (Updated the plugin, server, added/removed plugins, etc)

**Comment by bobbyoshi** [comment]
you were right, i turned off all the anti cheats, and it worked, so ive figured out which ones are fine and everything is working again.

you are the best! lol i thought i checked to make sure they all would work, but part of the corex built into the factions plugin that updated was what it was. thanks for all your help.

**Comment by NathanWolf** [comment]
You're welcome!
