### ISSUE TITLE
Skript, classes and incomplete documentation

### ISSUE THREAD

**Issue by bloggy** [elBukkit/MagicPlugin#935]
Hi there,

I am trying to cast skills using a skript but I am stuck.

I saw your example:

```
make player cast the spell "fling" with "pdy 1 pdx 0 pdz 0 min_speed 5 max_speed 5"
```

- But I can not find any information about these parameters you added there. Is there a list of all possible parameters?
- When killing an entity with a casted spell (like particle arrow or through bombs which is an "indirect kill"), how could I get the caster in the "on death" and "on damage" event? In the screenshot you will see what I mean (I casted the bomb skill on a zombie): https://i.imgur.com/pL1RjBl.png (for adding exp to the attacker's class I'd need the player who casted the skill instead of 'TNT' so I can give him the proper exp for the kill) - do you think you could add a skript expression for this? That would be awesome.

Thanks for your help!

**Comment by NathanWolf** [comment]
There is a reference manual here: https://mine.elmakers.com/reference/#spells

But probably if you're just trying to cast spells via Skript you don't need to worry too much about that, I probably shouldn't even have parameters in the Skript example.

Classes in Magic can be like RPG classes, but they are not used as such in the survival configs.

I will see if I can make the "caster" expression work inside of the damage event.

**Comment by NathanWolf** [comment]
> I will see if I can make the "caster" expression work inside of the damage event.

This should be working now, but I don't know how much I tested it. Please let me know if it is (or is not) working better for you.
