### ISSUE TITLE
Event priority ?

### ISSUE THREAD

**Issue by Blamo27** [elBukkit/MagicPlugin#94]
Hello, I have a problem :
https://github.com/MinelinkNetwork/CombatTagPlus/issues/65

Can you fix this issue please ?

**Comment by Blamo27** [comment]
@NathanWolf Is it a Magic issue ?

**Comment by NathanWolf** [comment]
Don't think so, but would have to try it myself, not sure when I'll get the time for that.

The event priority is already set in a very specific way to avoid conflicts with at least two other plugins, so if that is the problem it may not be something I can fix.

**Comment by Blamo27** [comment]
So can you create a specific version that fix conflicts between CombatTagPlus and Magic ? Even if that specific version doesn't avoid conflits with the two other plugins you mentionned...

**Comment by NathanWolf** [comment]
Not unless you never want updates.

**Comment by NathanWolf** [comment]
At any rate, best to not jump the gun. I will look at this when I can, setting up a test will take time, especially if it involves another player.

If the author is really only killing the player, then I don't see why that plugin would be doing anything with the death event.

**Comment by Blamo27** [comment]
Okay, please let me know if you discover anything. By the way, about CTP, we believe -but we're not sure- that it's a special kill when the player disconnect : something that manually drops everything on the floor, and erases the entire player inventory. That would explain the wand loss.

**Comment by NathanWolf** [comment]
Update on this: I tried it out for myself, and the basic issue is that Magic is not set up to handle players after they have logged out. Their data has already been forgotten and queued for asynchronous saving.

So when CombatTagPlus kills the player on logout, Magic sees the logout event and then the death event, and basically doesn't handle the death event at all.

This will be tricky to resolve in a clean way (like, very tricky). I can't just put the items back in the player's inventory, I have to save them in Magic's player data to return them when they relog and respawn. But I can't do this if that data is already saved and out of memory.

I'll keep this open and give it some more though, but I'm not currently seeing a lot of hope for these two plugins working well together.

**Comment by Blamo27** [comment]
Yes it can be a solution, but I think there is another solution.
If CTP can use the Magic API to check each item in the inventory to disable drop with them, and drop other items only, this could be fine.

**Comment by NathanWolf** [comment]
That would work as well, but I don't expect Byteflux would be real open to that option. He's not currently dealing with the player's inventory at all on death, it'd be kind of a pain to support this just for the sake of my obscure little plugin.

That said, I've been thinking about this- maybe I could delay forgetting/saving player data on logout for one tick. I'll have to think about this to see if there are going to be any negative side-effects, particularly with other plugins that handle Magic data.

**Comment by NathanWolf** [comment]
Ok I think I have this fixed. I'll need to keep an eye out for side-effects, but delaying player removal and saving on logout by one tick fixes the incompatibility issues.

Please try the latest dev build: http://jenkins.elmakers.com/job/MagicPlugin/1652/

**Comment by Blamo27** [comment]
Oh thanks !
But I'm still in 1.8.8, is it compatible ?

**Comment by NathanWolf** [comment]
Ha, I should've guessed as much.

No, it's not, but I just backported it for you.

http://jenkins.elmakers.com/job/MagicPlugin-1.8/37/com.elmakers.mine.bukkit.plugins$Magic/

**Comment by Blamo27** [comment]
Thank you so much :)

**Comment by Blamo27** [comment]
@NathanWolf 
The plugin didn't work at all when we put the version : no spell working, wand loss, etc. I don't know why :

> [21:53:32] [Server thread/WARN]: [Magic] Error loading mobs.yml
java.lang.IllegalArgumentException: The embedded resource 'defaults/mobs.defaults.yml' cannot be found in plugins/Magic.jar

> [21:53:32] [Server thread/WARN]: [Magic] Error loading items.yml
java.lang.IllegalArgumentException: The embedded resource 'defaults/items.defaults.yml' cannot be found in plugins/Magic.jar

**Comment by NathanWolf** [comment]
That is pretty odd- I just tried the jar myself, as well as uncompressed it and looked inside. Those files are definitely in there, and the plugin is working for me. (Tried the one straight off my Jenkins link)

You sure you don't have multiple versions in your plugin folder or... something?

**Comment by Blamo27** [comment]
What do you mean by multiple versions ?

**Comment by NathanWolf** [comment]
More than one copy of the plugin in your plugins folder- kind of a stretch, but only thing I can really think of there. I'll double-check to make sure I didn't have a weird/bad merge...

**Comment by Blamo27** [comment]
No more than one copy in my plugin folder :/

**Comment by NathanWolf** [comment]
Hrm- um maybe try re-downloading then? Here's a direct link:

http://jenkins.elmakers.com/job/MagicPlugin-1.8/37/com.elmakers.mine.bukkit.plugins$Magic/artifact/com.elmakers.mine.bukkit.plugins/Magic/5.5.6-SNAPSHOT/Magic-5.5.6-SNAPSHOT.jar

I really don't know what could be going on there, I ran that exact jar myself. That error is really weird- you could also try decompressing the jar and just seeing if those files are in there, in the "defaults" folder. They should be.

**Comment by dumptruckman** [comment]
Sounds like the jar file may be corrupted.

**Comment by Blamo27** [comment]
Thanks, this is working now, sorry it was my fault, I was trying to unload / and load the plugins without restarting.

**Comment by Blamo27** [comment]
@dumptruckman ?

**Comment by NathanWolf** [comment]
@Blamo27 You may want to update to the latest dev build- there was a pretty bad bug in the change I made to support CombatTagPlus, players could lose their inventories when logging out with their spell inventory active.
