### ISSUE TITLE
Aurelium Skills Support Not Working

### ISSUE THREAD

**Issue by FlamingLumberjack** [elBukkit/MagicPlugin#941]
I've been trying to use Magic with Aurelium Skills but for some reason they aren't linking and in the console it says that Magic has found Aurelium Skills.

**Comment by NathanWolf** [comment]
The mana integration was turned off by default until we can get it balanced.

In what way are you trying to use them together?

**Comment by FlamingLumberjack** [comment]
> The mana integration was turned off by default until we can get it balanced.
> 
> In what way are you trying to use them together?

**Comment by FlamingLumberjack** [comment]
Woopsies sorry I'm new to github I was just trying to make Magic level up Aurelium Skills levels and the mana I was told they should've been linked by default thanks for your help

**Comment by NathanWolf** [comment]
I *think* aurelium skills will get leveled up without any integration, that was a fix on their side to how they handle damage events.

The mana can be linked but it's problematic since you only start out with 20 mana in AS but some beginner magic spells require 50 to cast. So it can be done, but it takes a bit of setup. I'm hoping to figure that out and then provide it as a turnkey example, but it's not quite there yet.

**Comment by FlamingLumberjack** [comment]
So how could I manually link it?

**Comment by FlamingLumberjack** [comment]
I read about the reason the disabled AS support. I just have a suggestion since default mana is configurable in AS, you don't have to change each and every spell mana cost. The only thing that I think you should integrate is leveling up the sorcery skill whenever you use spells but anyways that's just my suggestion and I would really hate to see support for AS stop so maybe you could talk to the creator of AS and work something out.
AS Discord: https://discord.gg/Bh2EZfB

**Comment by NathanWolf** [comment]
> leveling up the sorcery skill whenever you use spells

I really thought they did that already- thrown potion damage increases your sorcerery stat. Does it not work?

>  I would really hate to see support for AS stop

No no, that's not happening at all. I just got a long string of people coming to ask why they mana was stuck at 20, it was a very confusing situation to have it on by default.

If you'd like to turn it back on and rebalance if yourself, just do `/mconfig configure config aurelium_skills.use_mana true`

**Comment by FlamingLumberjack** [comment]
Throwing potions does increase your sorcery level but my suggestion was to level up sorcery when using spells from Magic as well.

**Comment by NathanWolf** [comment]
Using spells that deal damage should increase your sorcery level then, since it appears the same as thrown potions :)

That should cover the majority of spells that would normally earn Spell Points.

**Comment by FlamingLumberjack** [comment]
It doesn't seem to be working I'm using Magic Missile and it isn't giving me any AS sorcery exp when I damage or kill mobs and I ran _/mconfig configure config aurelium_skills.use_mana true_  which seems to be working just fine.

**Comment by NathanWolf** [comment]
I see you closed this, I meant to respond but maybe you saw already :)

The latest release *should* resolve these issues, though it is still a work in progress. You'll get sorcery XP for spell use now, and mana is turned on by default with spell costs scaled down.

**Comment by FlamingLumberjack** [comment]
Yes I did see the new update thank you for your quick update you did a great job.
