### ISSUE TITLE
checkinventory support/bug

### ISSUE THREAD

**Issue by Azureblooet** [elBukkit/MagicPlugin#943]
Hello! I looked through the past issues to find the consume trigger and tried using it for a sweetberry perk. It works when you eat a sweet berry and its the last one you have but when it's a a stack it fails to detect it. because i assume there is a way, how do you set it to allow items reguardless of the stacksize?

**Comment by Azureblooet** [comment]
![image](https://user-images.githubusercontent.com/88201702/127699186-0930a228-b951-42b5-bc38-8cec4f03cfe7.png)
here's the spell if you need it

**Comment by NathanWolf** [comment]
Hey, sorry I completely missed this request somehow! :(

I think you are right and I need to add something like "exact_match: false` so it only checks the item type .. or maybe `ignore_count` .... oorrrrr maybe that should just be the default

**Comment by NathanWolf** [comment]
This will be fixed in the next dev build and Magic 10

**Comment by NathanWolf** [comment]
This should be fixed now, please let me know if you still have issues!
