### ISSUE TITLE
How to use config?

### ISSUE THREAD

**Issue by Incoconut** [elBukkit/MagicPlugin#944]
I already made a config from /mconfig editor config config but whenever I load it on my server, nothing happens? Am I doing something wrong?

What I edit on config is:
disabling the SP
changing the mana display

**Comment by NathanWolf** [comment]
Just be like `/mconfig editor config sp_enabled false`

but I think you may need to go into your config folder and delete some files- I'm not sure yet what happened, but the zip you sent me had a `defaults_store` file in it that was a copy of the whole config, you probably need to delete it.

**Comment by Incoconut** [comment]
No problem! Thank you so much!
