### ISSUE TITLE
Netherside Configuration

### ISSUE THREAD

**Issue by Ryvvik** [elBukkit/MagicPlugin#945]
I am trying to configure the netherside for the phase spell and my world is not named the default world. I cannot manage to get the text configuration correct for it to work could someone give me the exact text and what to replace with my world name.

**Comment by NathanWolf** [comment]
It might be easier to do `/mconfig editor spell phase` - there will be a map of worlds there, change the ones that say `world` to your world name.

**Comment by NathanWolf** [comment]
Please let me know if you were not able to get this working!
