### ISSUE TITLE
Resource pack

### ISSUE THREAD

**Issue by Kikai-hub** [elBukkit/MagicPlugin#946]
Hello, the plugin does not automatically install the resource pack on the stick.
I checked in advance, there are no packages on the server.

**Comment by NathanWolf** [comment]
Please look here and see if any of this helps: https://github.com/elBukkit/MagicPlugin/wiki/ResourcePack#loading-issues

**Comment by Kikai-hub** [comment]
> Пожалуйста, посмотрите здесь и посмотрите, поможет ли что-нибудь из этого: https://github.com/elBukkit/MagicPlugin/wiki/ResourcePack#loading-issues

I checked, it doesn't work

**Comment by NathanWolf** [comment]
Sorry, I have found there is a bug in the recent versions I will hopefully have fixed soon.

**Comment by Kikai-hub** [comment]
> Пожалуйста, посмотрите здесь и посмотрите, поможет ли что-нибудь из этого: https://github.com/elBukkit/MagicPlugin/wiki/ResourcePack#loading-issues

I checked, this function does not solve the problem

**Comment by NathanWolf** [comment]
This should all be fixed now, please let me know if you still have issues with the RP.
