### ISSUE TITLE
EffectLib v9.3 is not available on repository specified in pom.xml

### ISSUE THREAD

**Issue by LazyGon** [elBukkit/MagicPlugin#953]
IDE says v9.3 is not available.

These are repositories for effectlib fork of elbukkit and, as far as I checked, [this repository](http://maven.elmakers.com/repository/com/elmakers/mine/bukkit/EffectLib/) do not contain EffectLib v9.3.
```xml
    <repositories>
      <repository>
          <id>Maven Central</id>
          <url>https://repo1.maven.org/maven2/</url>
      </repository>
<!-- Use this repository ONLY if you need snapshot builds -->
        <repository>
            <id>elMakers</id>
            <url>http://maven.elmakers.com/repository/</url>
        </repository>
    </repositories>
```

**Comment by NathanWolf** [comment]
Oh yes you are right, 9.0 is the latest. I think I have run into some issues deploying to Maven Central after having updated to Java 16 for 1.17 … I’ll see if I can get that figured out, and in the meantime I’ll get 9.3 up on the elMakers repo.

**Comment by NathanWolf** [comment]
I've added it to the dev builds repo (the second elmakers one in your paste). I'll leave this open until I can get Central updated again, too.

**Comment by LazyGon** [comment]
Thanks for fast support!

By the way, is there any reason you don’t add issue page for EffectLib fork repo?
I think this issue is actually about the repo :)

**Comment by NathanWolf** [comment]
I've deployed 9.3 to Maven Central, and also added Issues to the EffectLib repo:

https://github.com/elBukkit/EffectLib/issues

Thank you!
