### ISSUE TITLE
Dragons

### ISSUE THREAD

**Issue by lisalovedragon** [elBukkit/MagicPlugin#956]
I see dragons as zombie horses but i have resources pack. What should i do?

**Comment by NathanWolf** [comment]
You need the LibsDisguises and ProtocolLib plugins for those to work- you can find them on spigotmc.org, let me know if you have any trouble!

**Comment by lisalovedragon** [comment]
> Aby ty fungovaly, potřebujete doplňky LibsDisguises a ProtocolLib- najdete je na spigotmc.org, dejte mi vědět, pokud máte nějaké potíže!

thanks
