### ISSUE TITLE
Mnpc's dont show up

### ISSUE THREAD

**Issue by KlixStyle** [elBukkit/MagicPlugin#958]
Since we added zNpcs and Citizens they will not show up.

**Comment by NathanWolf** [comment]
Citizens should be fine, I don't know what zNPcs is.

Why do you need 3 different NPC plugins?

If you are using Citizens you probably don't need magic NPCs.

**Comment by KlixStyle** [comment]
zNpcs has been removed but we kinda want to use the starshop from the stars example, still they dont show up.

**Comment by NathanWolf** [comment]
I don't think there are any Citizens incompatibilities... do you maybe have the Magic NPCs in a protected region, like worldguard without plugin spawning enabled?

**Comment by KlixStyle** [comment]
We fixed it now, thanks!

**Comment by NathanWolf** [comment]
Do you know what the issue was? Wondering if I need to add zNPCs or anything else to my incompatibilities list.

**Comment by KlixStyle** [comment]
Im pretty sure it was zNPCs
