### ISSUE TITLE
[SUGGESTION] ItemsAdder Support/Addon

### ISSUE THREAD

**Issue by Tim-Rambo** [elBukkit/MagicPlugin#959]
Since ItemsAdder is already using a resource pack for its contents
It would be nice to have an ItemsAdder addon for your plugin and since you are using resource pack as well.
As I would love a plugin where I can decide what the spells do.
Just contact the author and he will help you out with anything you need.

PS He is not available in the weekends

**Comment by NathanWolf** [comment]
As long as you unprotect the zip itemsadder creates, you can merge it yourself with Magic's RP

https://merge.elmakers.com/

As far as I know ItemsAdder won't properly merge items of the same type from different resource packs. I could be wrong, maybe try just putting Magic's RP in the IA resource packs folder first and see if it works.

That said, I don't like this dev, we have had some conflict in the past and I'm not really interested in working with this plugin.

**Comment by NathanWolf** [comment]
I apologize for my previous reaction ... 😅

LoneDev contacted me, it sounds like you should just be able to unzip Magic's rp and put it in ItemsAdders's resourcepacks folder. I'll pass along any more info I get on this.

The only other integration I could see being really nice to have is for magic's crafting recipes to show up in ItemsAdder crafting menus. I don't see a way to do this via the API, though, and the note in ItemsAdder's incompatibilities list about custom crafting plugins makes me think it may not be possible.

**Comment by NathanWolf** [comment]
LoneDev confirmed that custom model data should get merged correctly if you just unzip Magic's RP and drop it in ItemsAdder's resourcepacks folder. Please let me know if that's not the case for you.
