### ISSUE TITLE
Auto Leveling

### ISSUE THREAD

**Issue by Xzeajan** [elBukkit/MagicPlugin#96]
Is there a way to allow auto leveling without beeing required: Student, Apprentice, etc etc
So it just levels up with amount of casts.

Kind Regards
Jan

**Comment by NathanWolf** [comment]
You can put "upgrade_required_path: beginner" on every level of every spell, but this will obviously take a lot of work. 

I'm thinking of adding a feature for overriding properties of all spells, I'll keep this open til that's done, it'd make this kind of thing much easier.

**Comment by Xzeajan** [comment]
I am working with a limited amount of spells, instead of letting players pick all spells. 
Any chance you can give me an example for 1 spell? So I can apply this to all spells I use?

ps. love the Magic at the moment, really adds some dept to my server!

**Comment by NathanWolf** [comment]
Oh, sure - so for instance Magic Missile would be like this:
```
missile:
    upgrade_required_path: beginner
missile|2:
    upgrade_required_path: beginner
missile|3:
    upgrade_required_path: beginner
missile|4:
    upgrade_required_path: beginner
```

So you have to do it for every level of the spell.

The "overrides" thing I can try to add tomorrow maybe, that would really make this task a lot easier. Are you on the latest Magic build, or is your server on 1.8?

**Comment by Xzeajan** [comment]
I am owning the latest verion, my server is 1.9.2

**Comment by NathanWolf** [comment]
Ok! Yeah I have been wanting to do it for a while, it'd help so many people. I'll do it ASAP and let you know.

**Comment by Xzeajan** [comment]
You are awsome! Thank in advance!

**Comment by NathanWolf** [comment]
Dev Build#1651 supports an "override" config, which will apply settings to every spell. So in your spells.yml, you can now just do this:

```
override:
  upgrade_required_path: ""
```

And it will turn off the required path for all spell upgrades.

http://jenkins.elmakers.com/job/MagicPlugin/1651/com.elmakers.mine.bukkit.plugins$Magic/
