### ISSUE TITLE
Conflict with SlimeFun

### ISSUE THREAD

**Issue by NotAShelf** [elBukkit/MagicPlugin#962]
Slimefun is a plugin that offers CustomModelData to support texturepacks, and if Slimefun is installed together with Magic, Magic will override Slimefun item textures

steps to reproduce (if necessary)
- download and install slimefun on your server
- download and install magic on your server
- start the server

you will start with an item called "slimefun guide" in your inventory, which is normally an enchanted book but you will notice that its texture has been replaced by Magic

- right click the book
what you will see now is a visual clutter of Magic overriting slimefun modeldata
- you're done, you have successfully replaced the issue

**Comment by NathanWolf** [comment]
`/mexample add slimefun`

**Comment by NotAShelf** [comment]
sorry, what does this command do?

**Comment by NathanWolf** [comment]
Turns on the slimefun-compatible resource pack

**Comment by NathanWolf** [comment]
Otherwise, you have to merge the resource packs yourself. https://merge.elmakers.com

**Comment by NotAShelf** [comment]
that doesn't seem to be a command, might I be missing something?

**Comment by NotAShelf** [comment]
(for reference, I'm currently not using the non-official slimefun texturepact. It is just that Magic assigns its own textures to Slimefun's menus and items since they use custom model data)

**Comment by NathanWolf** [comment]
Gah, sorry- I really need to add that alias since I always type it :(

`/mconfig example add slimefun`

**Comment by NathanWolf** [comment]
The non-official slimefun RP is what is merged in the slimefun example

**Comment by NotAShelf** [comment]
Ah, I see. Thank you for your assistance, much better now.

**Comment by NathanWolf** [comment]
You're welcome!
I'm adding `/mexample` for the next release :joy:
