### ISSUE TITLE
BroomBooster crafting recipe

### ISSUE THREAD

**Issue by Dedvin** [elBukkit/MagicPlugin#965]
Players can't craft the broom booster after the last update.

**Comment by NathanWolf** [comment]
The recipe *did* change, players should learn it if they have a broomstick. Are you sure they're trying the new one?

https://i.imgur.com/lX5m9tC.png

And please let me know what server version you're on, I couldn't test them all so it's possible something is broken pre-1.17

**Comment by Dedvin** [comment]
They are using the new one. It seems to be only working for me when i'm in creative

> The recipe _did_ change, players should learn it if they have a broomstick. Are you sure they're trying the new one?
> 
> https://i.imgur.com/lX5m9tC.png
> 
> And please let me know what server version you're on, I couldn't test them all so it's possible something is broken pre-1.17

**Comment by NathanWolf** [comment]
I am not sure then, the recipe changes in 10.0 removed all of the custom crafting ingredients that generally caused issues like this. All the ingredients are vanilla now and so should "just work". Creative mode shouldn't matter at all unless you've got something else going on plugin-wise.

You could try changing the recipe to use some different items, see if that helps 🤷‍♂️ 

`/meditor recipe broom_booster`

**Comment by NathanWolf** [comment]
I took the fireworks out of this recipe, they were causing issues.
