### ISSUE TITLE
Spell suggestion (Pocket dimention)

### ISSUE THREAD

**Issue by DarkCode243** [elBukkit/MagicPlugin#968]
This spell would be like the phase spell but it would teleport you to a bedrock box that only you can teleport to where you can build a base. If you were to level up the spell the box would get bigger. You could locate the box somewhere in the sky millions of blocks away or on the nether roof.

**Comment by NathanWolf** [comment]
Sounds kind of similar to the creative example, I think it would have to rely on a custom world generator much like that example does.

The main difference is assigning unique coordinates to each player, ideally without having to have some centralized database. 

I wonder if you could break a player's UUID down into coordinates in a unique way.

Having the box grow bigger sounds like a pain, though- you'd have to base the coordinates on the max size possible anyway.

All in all, this sounds like something that would be much better suited as a custom plugin. I'll leave this open for a bit in case you or anyone else has any feedback, but I don't see this being something I would add to the plugin myself anytime soon.

**Comment by DarkCode243** [comment]
you could have it so that there is a set amount of pocket dimensions and when you first use the spell it would open a menu and you would pick which one you want then it is as simple as teleporting them there - like placing a marker on the recall spell it always teleports you to the same place. And for the increasing size its probably better to just have on size. And for generating the box you can make it that the first time you teleport there it does like a super shell spell but like a box.

**Comment by NathanWolf** [comment]
I would consider checking out the creative example. It can be seen on my demo server, go to the creative area. It relies on a world generator (that you could use) and PreciousStones. Each player gets one (or more, up to you) creative islands, and they can visit each other's islands.

Not exactly what you want, but maybe good enough and ready to go.
