### ISSUE TITLE
Upgrading Spells

### ISSUE THREAD

**Issue by aden54577** [elBukkit/MagicPlugin#97]
I have yet to figure out how to upgrade a spell on an existing wand. I tried /wand upgrade active_spell blast to upgrade blast on the wand I was holding but with no luck. Please reply ASAP. Thanks!

**Comment by NathanWolf** [comment]
Each level of a spell is actually its own spell. So if you want an upgraded version of a spell, you add it to the wand and it will replace any lower-level versions. Like:
```/wand add missile|3```

For Magic Missile Level 3. The | character is a pipe, like shift+\
