### ISSUE TITLE
Custom Wand Lore Support

### ISSUE THREAD

**Issue by I0nTech** [elBukkit/MagicPlugin#972]
From IonTech BTW

Also need some way to display cooldown reduction, power, cost reduction, strengths, weakness and protection on wands as percentages instead of enchant levels

For EX: Cooldown Reduction: +20% instead of Cooldown Reduction I  

I know that modifying messages works, but Idk how to set up the 20%

Also I need:

Mana_max_boost
Mana_regeneration_boost
Mana rage
Upgrades header
Upgrades slots
Power, cost reduction, cooldown reduction, cost reduction, strengths, weaknesses, protection

Also if possible, maybe something for attributes the wand grants, like Armor: +5 or Health: +10 (Not needed though)

(Also, is it possible to put multiple upgrades in 1 slot? Thanks in advance.)

**Comment by NathanWolf** [comment]
You can use `$percent` in messages in place of `$roman` to get them as percentages

Can't have multiple upgrades in 1 slot, but you can have more than one slot of a type on a wand.

I'll try to get some of these custom lore placeholders added, thank you for the list!

**Comment by I0nTech** [comment]
Alright! Thanks!

**Comment by NathanWolf** [comment]
I know we're not up to par with other item-based plugins but I'm hoping the placeholders are good for now.
