### ISSUE TITLE
Magic Bows with Infinity Duplication Arrows

### ISSUE THREAD

**Issue by Pixwl** [elBukkit/MagicPlugin#975]
Hey there!

I've had a couple of players on my server mention that they can get unlimited arrows by simply putting infinity on their magic bow. Not completely sure if this fits in here on GitHub but I would think that it would be more of a bug then a support question.

Thanks

**Comment by NathanWolf** [comment]
Sorry! This is fixed in the latest dev build, which I will probably release later today as 10.1

**Comment by Pixwl** [comment]
Ok, no problems. Thanks!
