### ISSUE TITLE
Having trouble enabling Engineering and other examples.

### ISSUE THREAD

**Issue by GeneralLeone** [elBukkit/MagicPlugin#976]
Hello, I've been trying to enable the engineering example via commands on a server, and I can't seem to get it to work. 
I've tried the command /mconfig example set engineering, but minecraft spits it back as invalid.

Am I doing something wrong with my commands, do I have to edit the config file or is there something else?
I'm on a 1.16.1 server running Magic 7.10.1-71b589a

**Comment by NathanWolf** [comment]
The mconfig command was introduced in Magic 8 - we are on 10.1 now, are you able to update to the latest version?

**Comment by GeneralLeone** [comment]
> The mconfig command was introduced in Magic 8 - we are on 10.1 now, are you able to update to the latest version?

Thank you, updated and now it works.
