### ISSUE TITLE
Phase spell not working

### ISSUE THREAD

**Issue by GeneralLeone** [elBukkit/MagicPlugin#977]
https://user-images.githubusercontent.com/91899089/136446150-6a6428d4-e1b3-4ec1-8588-110a44bb624e.mp4

I'm having a problem where the Phase spell isn't teleporting me to another dimension, I've attached a video showing the issue. Im running the latest version of Magic on a 1.16.1 server, everything else seems to be working just fine.

Thank you for the excellent plugin!

**Comment by NathanWolf** [comment]
You should get some instructions when you add the examples, or use `/mhelp examples.otherside`, basically you have to reconfigure it to recognize your default world.

**Comment by GeneralLeone** [comment]
Thanks, do I need to put my world name in quotation marks because of the spacebar or does that sort itself out?
