### ISSUE TITLE
Spell Inventory picking up Elite Mobs loot shower items which should be cancelled

### ISSUE THREAD

**Issue by ROOTCAUSED** [elBukkit/MagicPlugin#979]
I spoke to the elite mobs dev's and they're under the impression that it's something that'd need to be fixed in the magic plugin and that they cant implement a fix on their end
according to their dev:

eltemobs cancels the item pickup event at a low priority, so whatever system that plugin is using to pick items up just ignore cancelled and don't set it to low or lowest priority

https://github.com/MagmaGuy/EliteMobs/blob/master/src/main/java/com/magmaguy/elitemobs/items/ItemLootShower.java

it appears that with the spell inventory open, the cancellation of pickup for loot shower items is ignored. Would it be possible to have a compatibility fix for EliteMobs + Magic to prevent this behaviour, it'll kill gold based economies like mine if left unchecked unfortunately, and I really dont want to uninstall either plugin as our player base thoroughly enjoys both

**Comment by NathanWolf** [comment]
I'd be happy to fix this on my end if I can, but I may need more information on the problem.

Is it basically that EliteMobs is generating loot items that are not meant to be picked up (they just disappear on pickup?), but if you have your spell inventory open they instead get put in the player's survival inventory?

If that's all correct, then I may need to test it for myself. I have never used EliteMobs, is there a quick/simple set of steps from installing the plugin from scratch to generating a loot shower?

I am not entirely sure what would be going wrong. Looking at my code, I have two separate event handlers for item pickup. The first is at lowest priority, but is only there to do something similar to EliteMobs, detect and remove temporary items.

The other eventhandler is set to highest priority (should go last, other than monitor handlers), this is the one responsible for bypassing the spell inventory and putting item pickups in your survival inventory.

Both handlers are set to ignore cancelled events, so if I'm understanding everything it seems like they *should* work together.

**Comment by NathanWolf** [comment]
Nah, thanks though!
Will be fixed in the next dev build:

https://jenkins.elmakers.com/job/MagicPlugin/4010/

**Comment by CJBlakey** [comment]
Can confirm that the fix works! you're the man Nathan!
