### ISSUE TITLE
Glide

### ISSUE THREAD

**Issue by Xzeajan** [elBukkit/MagicPlugin#98]
Hello,

I am almost done with my server,
the only thing left I wish to edit is the glide spell
Is there a way to change the lenght of the duration to unlimited / until somone lands?

PS: I love this plugin so much, is there a way you wish to be credited in my server? (got no website, but I will be happy to build a statue at the spawn, with a sign or something? )

**Comment by NathanWolf** [comment]
Sure, just add this to your spells.yml:
```
glide:
  parameters:
      duration: 0
```

That'll make it last until they land.

And that's very kind of you, but no worries on the credit! I'm just glad you are enjoying the plugin :)

**Comment by NathanWolf** [comment]
Thinking more about this, you will need "undo: 0" to keep it from ending. But this is not really what you want, they'll keep the elytra until they try to remove it. I don't have a way for it to auto-end when they land, so I will need to think about this more!

**Comment by NathanWolf** [comment]
Glide now stops when the player lands.
