### ISSUE TITLE
How to disable block regeneration

### ISSUE THREAD

**Issue by ET3RN7L** [elBukkit/MagicPlugin#982]
Hello Nathan,

I recently installed your plugin into my server, but i'm having an issue. Whenever I destroy blocks or move them with spells they regenerate. Let's say I destroyed a house with meteors, in a few minutes the house regenerates. Is there a way to disable block regeneration? If there is please tell me!

**Comment by TheDarthFather** [comment]
This is intentional so you dont destroy your server. 
Later some magic spells will make permanent changes (not enebled by default)

However, you can override this if you want:
`/wand override undo 0`

**Comment by NathanWolf** [comment]
Thanks @TheDarthFather !

To follow up if you want these changes made to all spells on your server, you can use `/mconfig spell default parameters.undo 0`
