### ISSUE TITLE
My mobs dont have the custom player skin 

### ISSUE THREAD

**Issue by vibinnpytro** [elBukkit/MagicPlugin#983]

**Comment by vibinnpytro** [comment]
help me pls

**Comment by NathanWolf** [comment]
You need the LibsDisguises plugin. Use

`/mhelp LibsDisguises` in-game for more information and links.

If you need more help, it’d be great if you could join our Discord server:

https://discord.elmakers.com/

There’s a bot there that can answer a lot of these kinds of questions, as well as lots of other humans who can help too. 

This issue tracker is more for bug reports and feature requests. Thank you!
