### ISSUE TITLE
I would like to ask you a few questions about Brushes.

### ISSUE THREAD

**Issue by ookami0104** [elBukkit/MagicPlugin#987]
I'm Japanese and I use a translator, so my English may not be correct.
The last biome was fixed.
Thank you for your reply.

Now, I have one more question: ....

I would like to disable ores from Brushes.
I didn't know much about it.
I'm sorry.

**Comment by NathanWolf** [comment]
Sure thing- use `/meditor material restricted`

Then add `ores` to the list.

Note that if you're using the wolf staff you will bypass these restrictions, so make sure to test with a regular wand.

**Comment by ookami0104** [comment]
I'm sorry.
The translator is not working properly.

I have coal, diamonds, gold, iron, copper
I want to disable the ore blocks of
Do you have any samples?

**Comment by NathanWolf** [comment]
Try downloading this file:

https://raw.githubusercontent.com/elBukkit/MagicPlugin/b03ad5b4b7984affb7a6ba2c25825c89c79dc990/Magic/src/examples/elworld/materials.yml

Put it in `plugins/Magic/materials/`

**Comment by ookami0104** [comment]
Thank you very much.
I was able to solve the problem.
Thank you very much for your quick reply.
