### ISSUE TITLE
[Support] Unable to change default wands' path

### ISSUE THREAD

**Issue by Lesanse** [elBukkit/MagicPlugin#988]
Hey there, first of all thanks in advance for your time!

I am a -very- amateur server admin and I tweaked some files of this plugin to change the path a wand travels while leveling up in my server, and which spells can be learnt during those levels.

I set a path of 7 different classes, being the first "level" of the path's name "Prottos".

Thing is, everytime a player acquires a wand from a shop sign, the default wand is always "Beginner" class and not "Prottos".

That means I must manually change that if I want wands to follow the path I designed, which is the one I intend to have as default for every wand. Is there any way to default this new path to all new wands the players might acquire? 

Thanks in advance! :)

**Comment by NathanWolf** [comment]
Sounds like you're doing great so far!

The missing piece is the "class". Wands use a player class to store data, such as the spells they've learned and the path they are on.

So to change the default class, you need to edit the wand's class, which is "mage" - you can edit it like this: `/meditor class mage`

In there you will see `path: beginner`, simply change that to your prottos class.

Hope that helps!

**Comment by Lesanse** [comment]
I believe this has solved the issue! Thanks!
