### ISSUE TITLE
About upgraded with XP on an enchanting table 

### ISSUE THREAD

**Issue by hin6150** [elBukkit/MagicPlugin#99]
I played in 1.9 version. When i put my wand in Enchanting table, there are nothing that i can press button. exactly empty. So i can't upgrade my wand to student. is it error from sever? or am i do something wrong?

PS, i asked admin, he said don't know

**Comment by NathanWolf** [comment]
Unless they have changed configs, you should see a spell shop when you right-click an enchant table with wand in hand.

Wands don't go directly in the enchant table anymore, I did away with that a while ago.

**Comment by hin6150** [comment]
So you mean I should buy some spell at spell shop for upgrade my wand?

**Comment by NathanWolf** [comment]
Yes. The shop GUI should appear when right-clicking an enchant table while holding a wand. If it doesn't, something is broken or misconfigured.

**Comment by hin6150** [comment]
Thanks :D and Thanks for making this fun plugin
