### ISSUE TITLE
Deluxemenus icons

### ISSUE THREAD

**Issue by Desmordss** [elBukkit/MagicPlugin#990]
I want to make a custom store through the deluxemenus plugin, but I can't add an icon. How do I do this?

'minister':
  material: birch_sapling
  nbt_int: CustomModelData:18001
  display_name: 'Minister'
  lore:
    - 'test string'

I tried to make such a setup, but it doesn't work

**Comment by NathanWolf** [comment]
Unless it supports adding items saved from a file, custom NBT tags, or giving items via command you're not going to be able to put magic items in that menul

**Comment by Desmordss** [comment]
Deluxemenus support custom nbt tags

https://www.spigotmc.org/resources/deluxemenus.11734/update?update=285631

**Comment by NathanWolf** [comment]
Can it do sections (compound tags)?

If so, you could try setting `wand.template` to `minister`

**Comment by Desmordss** [comment]
So i need do this?

    nbt_int: '{CustomModelData:18024,template:"wand"}'

not work :(

**Comment by Desmordss** [comment]
FIXED. It was necessary to install the dev build of deluxemenus to display nbt textures of magic
