### ISSUE TITLE
My server player's are unable to use the wand if they are not op

### ISSUE THREAD

**Issue by Devil-darkknight** [elBukkit/MagicPlugin#992]
hello!!! your plugin is op but only server ops are able to use it and members are unable to use it, how to fix it devs

**Comment by NathanWolf** [comment]
Non-ops craft wands. Is that not working?

**Comment by Devil-darkknight** [comment]
Sir, even the normal wand(/wandp) can't be used by normal players(I used
tht command as reference, when I use tht command and give players wands(as
a test) they were unable to use it also even if they crafted a wand they
were unable to use it) what to do sir?

**Comment by NathanWolf** [comment]
Players have no commands.

What about the wand is not working? Swinging to cast? Any errors in your console?

There is nothing in the plugin that prevents players from using wands. What permission plugin do you use?

**Comment by Devil-darkknight** [comment]
Sir, there was no errors in console and it was working fine. Only players
can't use them(sir can I get the discord invite? When I tried to join the
discord using link in spigot it said not safe web) I can explain about this
in discord clearly sir.

Good night sir.

**Comment by NathanWolf** [comment]
You should not be using two different permission systems ... can you remove powerranks?

The discord link should be fixed now, sorry about that.

**Comment by Devil-darkknight** [comment]
Ok sir I can remove the powerranks, thank you for your support sir. I will
check the spigot once again sir.

**Comment by killme** [comment]
I ran into a similar issue where players would be unable to bind or open their own wands, which I fixed by reverting 654320fe92d28abd62b18aad2c6411df4bdcaa66. on my local branch. I am pretty sure this is caused on our end by some hacks that changes the default mode of all permission nodes to false/op however. Though I am not entirely sure why this breaks magic.

**Comment by NathanWolf** [comment]
Hm well that's a shame- do you think I should revert that in general?

It was not a super important change, my goal is to support using permissions for teams but *not* having ops be on those teams by default- doesn't seem possible using "standard" bukkit permissions.
