### ISSUE TITLE
Unable to find customization file for some messages

### ISSUE THREAD

**Issue by Lesanse** [elBukkit/MagicPlugin#995]
Hey there! I'm a newbie at customizing this plugin (or any other, for this matter), and I am failing to find the .yml file that allows me to change some texts of this plugin.

More specifically, the texts I'm being unable to find are those related to spells leveling up. When you, as a player, are checking your spell progression on the enchanting table, or when you manage to get a spell leveled up (I can't recall properly when those texts appear), you get a short text that describes what the next level of the spell is adding to that spell (such as in boon: "now it gives you a jump boost!").

I am unable to find those texts in any .yml config file or in "messages"... 

The main purpose for this is I'm translating the whole plugin (or, at least, the parts of it I'm using) to Spanish :)

Thanks in advance for your time!

**Comment by NathanWolf** [comment]
Well firstly you should try `/mconfig language ES`, there is a builtin translation file already :)

If you find anything missing still, you can use the editor to get all of the messages to edit, such as `/meditor messages spells` to edit all the spell text, including the level-up messages. Or just `/meditor messages` to edit all the text at once.

**Comment by Lesanse** [comment]
Thanks for your quick answer!

I tried configuring to "ES" but the translation to Spanish (at least from a Spaniard point of view, no intent to be rude) is not satisfactory.

I would love to translate the whole thing by myself. I believe it might be a bit too much of a work, so as for now I would like to translate only the most usual things to be read (such as the HUB in the enchanting table, etc).

Still I'd be interested, if considered useful, in traslating the whole plugin into a higher quality Spanish. What would be the easier/most feasible way to do that? :)

PS: Just for context: I have specific paths on my server and changed the names and categories of most spells, but I believe that has nothing to do with the overall language of the plugin, does it? I have changed no effects or properties of how the spells actually work.

**Comment by NathanWolf** [comment]
Using `/meditor messages` is the best way- that'll get you all the default messages as well as the survival configs to edit. It'll also get you any additional examples you add in, if you wanted to translate potter, stars or bending for some reason :)

I completely understand what you mean about the translation, and no offense taken! I honestly should have done a better job asking the people who submitted these which region they are from, as I understand Spanish has a few very distinct dialects.

If you'd like, please take a look here:

https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/main/resources/examples/localizations

There are actually 4 Spanish translations, and I have to admit I do not know the difference between them, other than that they have varying levels of completeness.

If you do translate anything, I would of course _love_ to add it to the plugin so everyone can benefit! 

Or even if you are able to categorize the translations I have in some way that'll be useful to future Spanish-speakers, e.g. Spain vs South America vs Central America or whatever.

**Comment by Lesanse** [comment]
Thanks again for your answer! I revised the Spanish translation and there are some classic "google translate" mistakes on each and every of them. Just FYI, it's not a thing about location or dialects :)

Consecuently, I would rather work on my own version.

I would want to start with the translation, but the option you gave me in using /meditor messages would not work for me, since the computer in which I am going to prepare this translation is not the same in which I play Minecraft -and there is no option whatsoever I can open Minecraft in said computer...-

Given all that, which is the file I should start editing, and where -in which folder- should I put it once I am finished with it? It'd be nice to directly work over the original English file so I can translate directly onto it.

Thanks for your time :)

PS: Also, another question that pops on my mind is the following: I understand I should avoid any signs of customization in the translation file, since I have renamed most of the spells? (not translated but given a different name completely)

If that's the case, how would the translation file and the customized file (let's say messages/spells.yml mainly) interact with each other?

Thanks for your time, given the fact I might be the most amateur code editor ever to exist :')

**Comment by NathanWolf** [comment]
You can use the `meditor` command from the server console, if that helps- it takes you to a web page, there will be a “Download” button on that web page to download the file if you want.

Otherwise, you can look in `plugins/Magic/defaults/messages.defaults.yml` on your server. You can download this file, but it is not editable in-place, you’ll want to put the result in `plugins/Magic/messages.yml`

Customizing this plugin is a little different than most (for various reasons), there isn’t *really* a file I can tell you to edit, but I’m hoping one of those two options works for you.

If you want to share the result I would still appreciate it! Maybe just let me know any sections you think I should replace in my builtin ES translation (I’d love to get rid of Google translate mistakes…).

**Comment by Lesanse** [comment]
It's been working just fine! As I told you however, I am not directly translating things but also customizing to my own server's needs... As such, some spells and their "background" are being reinterpreted...

Your support has been of much use! Thanks for everything :)
